Azure/azure-container-networking

- nmagent/client_test.go
- nmagent/requests.go
the supportedApis path in cns is wrong. PR to fix it
**Notes**:
> fix: correct supportedApis path

- hack/swift/Makefile
- decrease default AKS cluster size (3 -> 2 nodes) (immediate savings of 30%)
- change loadbalancer SKU from default "Standard" (~$0.42/hr) to "Basic" (free, $0/hr)
- change region to public westus2 
- change instance size from default `Standard_DS2_v2` ($0.114/hr) to explicit `Standard_B2s` ($0.042/hr), a decrease of 63%. 
**Notes**:
> Decrease pipeline AKS cluster cost

- debug/windows/npm/README.md
- debug/windows/npm/pod_exec.ps1
- debug/windows/npm/win-debug.ps1
- debug/windows/npm/win-debug.sh
Fixes/Enhancements to windows script:
- Get Pod IPs from all namespaces (previously just from kube-system)
- Log progress and state
- Get extra info:
- pod labels
- network policies
> tool: [WIN-NPM] minor updates to windows script, and new linux script

- npm/pkg/dataplane/dataplane-test-cases_windows_test.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/ipsets/ipset.go
- npm/pkg/dataplane/ipsets/ipset_windows.go
- npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
- npm/pkg/dataplane/ipsets/ipsetmanager_windows_test.go
- npm/pkg/dataplane/testutils/utils_windows.go
When getting endpoints to apply a policy, ignore IPs that have a different pod key in the ipsetmanager versus the endpoint cache (in case the pod controller hasn't updated the dp yet that the IP's pod owner has changed).
> fix: [WIN-NPM] don't apply policy to new pod with same IP as an old pod

- cns/NetworkContainerContract.go
- cns/client/client_test.go
- cns/restserver/api.go
- cns/restserver/api_test.go
During the previous switchover to using the client from the `nmagent` client (as opposed to the `cns/nmagent` client), an assumption was made that "proxied" requests to NMAgent were provided by clients as nested JSON. This assumption was wrong--they are Base64-encoded strings of JSON. Even though they're ultimately similar, they're very different from the perspective of the JSON unmarshaler. Consequently, this restores the nested request body back to a []byte and performs the second-stage decoding manually (similarly to how it was previously done).
Fixes #1694
> Fix inability to unmarshal nmagent request

- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
until issue with curl 1.1.1.1 on byocni nodes is resolved, skipping all pod-to-cidr cilium tests to unblock pipeline
**Notes**:
> skip podtocidr(1.1.1.1:80) tests in cilium connectivity tests

- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Reverts Azure/azure-container-networking#1698
This connectivity test fails out of eastus2 but succeeds elsewhere - this re-enables it and we will run the e2e in another region for now.
> Revert "skip podtocidr(1.1.1.1:80) tests in cilium connectivity tests"

- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/service/main.go
There was insufficient coverage over cases involving different permutations of the "WireserverIP" configuration option. Consequently, there were instances where reasonable values for this option caused CNS to fail to start.
This moves the logic for transforming the CNS configuration into configuration suitable for the NMAgent client into a method off the CNSConfig. It also permits adding coverage over different scenarios that are likely to emerge.
**Notes**:
> Fix failure to start CNS when setting WireserverIP

- cns/kubecontroller/clustersubnetstate/reconciler.go
- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/kubecontroller/nodenetworkconfig/reconciler_test.go
- cns/service/main.go
- crd/client.go
- crd/clustersubnetstate/client.go
- crd/nodenetworkconfig/client.go
The scoped CRD clients did not previously accept a controller-runtime client as an input, and instead constructed one from the kubeconfig. This creats direct (uncached) clients, which is okay for one-offs like during initialization, but not for ongoing high frequency usage like in the Reconcilers.
This change modifies the CRD client constructors to accept a client to wrap, which allows embedding the (cached) client provided by the ctrlruntime Manager. This takes full advantage of the sharedinformer pattern, improves efficiency of the reconcilers, and reduces apiserver load.
**Notes**: I migrated these components away from the Manager's client as part of switching out the scoped clients 😢 that was a mistake, and this is how they …
> fix: cns to use controller runtime (cached) clients in reconcilers

- nmagent/internal/wireserver.go
- nmagent/internal/wireserver_test.go
In cases where clients using a WireserverTransport (namely the NMAgent one) do not wish to provide a body, one must be provided to satisfy quirks of Wireserver. Initially, an empty Go string was thought to be sufficient, but this is not. Wireserver expects an empty JSON string: specifically the 2-byte sequence "".
Furthermore, this logic was only being triggered on cases where a nil body was presented to the WireserverTransport's logic. Given that there are now more linters enforcing the use of `http.NoBody`, this is distinct from `nil` and must be separately checked for (but treated in the same way).
Tests and inline documentation have been updated to reflect this new understanding.
**Notes**:
> Fix incorrect empty body provided to Wireserver

- test/apimodels/cniWindows1903.json
- test/apimodels/cniWindows2004.json
- test/apimodels/cniWindows2022.json
- test/apimodels/cniWindowsDualstack2004.json
We get several s360 items for this, so enabling auto updates on windows aks-engine clusters
> Enable auto updates for windows aks-engine clusters

- .pipelines/pipeline.yaml
We still don't support windows 2004 for aks and aks-e tests are failing very often. While we determine the root cause, in order to allow PRs to go in, and since we'll still run windows 1903 tests, we can disable 2004 tests as a mitigation
A new task was reported to add win 22 tests once we migrate over from aks-e (https://msazure.visualstudio.com/One/_workitems/edit/16667635)
**Notes**:
> remove windows 2004 aks-e tests from pipeline

- cni/network/plugin/main.go
- cni/plugin.go
- cns/restserver/api.go
- cns/service/main.go
- ipam/manager.go
- network/manager.go
- telemetry/telemetrybuffer.go
Moving the lock from InitializeKeyValueStore() function to restore/save functions to improve cni performance on windows.
In Windows CNI We are currently lock access to statefile in the init phase which may cause some CNI performance issue. This PR will move the lock to the exact point when we read/write from/to statefile.
> fix: repair windows cni lock issue

- cns/restserver/api.go
- cns/restserver/api_test.go
CNS was responding with an HTTP status code of "0" from NMAgent. Successes are supposed to be 200. The C-style var block at the beginning of publishNetworkContainer was the reason for this. During refactoring, the location where this status code was set to a successful value of 200 was accidentally removed. Because the var block declared the variable and silently initialized it to 0, the compiler did not flag this bug as it otherwise would have. The status code has been removed from this block and explicitly defined and initialized to a correct value of 200. Subsequent error handling will change this as necessary.
Also, despite consumers depending on this status, there were no tests to verify that the status was set correctly. Tests have been added to reflect this dependency.
**Reason for …
> Fix incorrect HTTP status from publish NC

- hack/manifests/cni-installer-v1.yaml
> Adds reference daemonset for v1 cni installer

- crd/clustersubnetstate/api/v1alpha1/clustersubnetstate.go
- crd/clustersubnetstate/manifests/acn.azure.com_clustersubnetstates.yaml
Update timestamp in ccs crd.
ccs timestamp is controlled by DNC so it belongs to status. Then update it in status.
> Update ClusterSubnetStates crd

- cilium/cilium_helm_values.yaml
L7Proxy is now enabled AKS, setting to true for our test environment.
**Notes**:
> enable l7proxy in cilium configmap

- cns/restserver/api_test.go
- cns/restserver/internalapi.go
- cns/restserver/util.go
fix: repair the NC ID mismatch when get network container.
Fix the mismatch between NC version returned from nmagent and CNS state. Add unit test to gate it.
CNS is onboard with nmagent nc version api 2. NC ID returned from nmagent doesn't include the Swift_ prefix but pure uuid. However, the NC ID in the request and cns state has the Swift_ prefix. This mismatch result in the nc version update failure.
- [ X] adds unit tests
**Notes**:
> Fix the NC ID error when get container

- Makefile
- build/tools/tools.go
conflicting build tag in dependency https://github.com/ryancurrah/gomodguard/blob/main/tools.go#L1 was preventing building the linter
**Notes**:
> update tools build tag due to 3rd party conflict

- cns/restserver/api.go
- cns/restserver/api_test.go
In scenarios where the subnet token does not match (leading to a 401 from NMAgent), CNS returns a 200 for the PublishStatusCode. This is incorrect, and a 401 should be returned instead. This leads clients of CNS to take incorrect action on, what they believe to be, a successful response.
> Fix incorrect 200 for a 401 from NMAgent

- README.md
- docs/npm.md
Fixes #1803.
Also add commands to build NPM Windows and troubleshoot iptables/ipset/HNS.
> docs: [NPM] add windows documentation and update links to MSDocs

- cns/service/main.go
This PR fixes duplicate ip assignment to pods if cns looksup/updates podinfo cache based on pod name and namespace. This PR updates to lookup based on containerid instead if managedendpointstate is set.
**Notes**:
> CNS in-mem cache to use containerid as key if manageendpointstate is enabled

- test/integration/manifests/goldpinger/daemonset.yaml
- test/integration/manifests/goldpinger/deployment.yaml
> upgrade goldpinger version and increase ping/check timeout

- hack/manifests/cni-installer.yaml
- hack/manifests/scaler.yaml
- test/kubemark/aks-e/hollow-node.yaml
https://github.com/kubernetes/k8s.io/issues/4738 
Kubernetes is updating registry address [k8s.gcr.io](http://k8s.gcr.io/) -> [registry.k8s.io](http://registry.k8s.io/) by April 3rd. Please scan your codebase to update references from k8s.gcr.io to registry.k8s.io by April 3rd to remain current
**Notes**:
> Changing gcr repo as per k8s issue 4738

- crd/nodenetworkconfig/client.go
The `SetOwnerRef` method was misleadingly named - it actually calls `ctrlutil.SetControllerReference` and patches, not `ctrlutil.SetOwnerReference` which also exists.
This renames the method to `SetControllerRef` so that it is named what it does. A deprecated stub `SetOwnerRef` which forwards to the new method is left for backwards compatibility.
**Notes**:
> deprecate SetOwnerRef in favor of SetControllerRef

- npm/pkg/dataplane/dataplane-test-cases_windows_test.go
- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/types_linux.go
> fix: [NPM] update endpointcache after remove policy

- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/policies/policymanager_windows.go
1. remove remote endpoint log (superfluous info that dilutes logs)
2. change wording for warning
3. more understandable logs when resetting all ACLs
> log: [NPM-WIN] clean up some logs

- nmagent/requests.go
To enable AZR support, we need to pass two extra params `azID` (uint) and `enableAZR` (boolean) as part of body to NMAgent.
https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/16223444
**Notes**: e2e flow has been tested by creating and deleting NCs with both `enableAZR` set to `true` and `false`
> add azid and enableazr fields to putNC call

- npm/pkg/dataplane/dataplane.go
Not refreshing when not necessary improves NPM efficiency
**Notes**:
> fix: [NPM-WIN] do not refresh endpoints if pod cache is empty

- test/integration/k8s_test.go
- test/integration/label.go
- test/integration/portforward.go
Port forwarding to a Kubernetes pod can be brittle but can be restarted if the appropriate signals are handled. This PR improves the API of the internal port forwarding wrapper `PortForwarder` to allow clients to maintain port forwarding sessions alive.
Example usage:
```go
pfOpts := PortForwardingOpts{
Namespace:     "default",
LabelSelector: "type=goldpinger-pod",
LocalPort:     9090,
DestPort:      8080,
}
pf, _ := NewPortForwarder(restConfig, logger, pfOpts)
if err := pf.Forward(ctx); err != nil {
// errors if initial connection fails
}
go pf.KeepAlive(ctx) // handles connection failures and re-attempts to port forward any pod matching the opts to the same local address
defer pf.Stop()
```
**Notes**:
> Improving port forwarding error handling

- npm/examples/windows/azure-npm-capz.yaml
Update to latest image. Impacts testing of windows nightly builds run on capz (separate repo)
> chore: [WIN-NPM] update mcr image to v1.4.45 for capz testing

- hack/swift/Makefile
> add cilium overlay to hackfile

- npm/examples/windows/azure-npm.yaml
- npm/windows.Dockerfile
Revert .exe change from:
1. https://github.com/Azure/azure-container-networking/pull/1820
2. https://github.com/Azure/azure-container-networking/pull/1838
These changes would break production DaemonSets since the DaemonSet change rolls out async with the image upgrade.
> fix: [WIN-NPM] revert breaking change to .exe filename

- dropgz/build/cniTest.Dockerfile
for parity with release image. 
this was causing test failures, as we [try to deploy these bins](https://github.com/Azure/azure-container-networking/commit/9dc035473b01ea4b72f5c3a3cb21d5a4fbc3d9cd) which are present in the release image but were not being built in the test image.
**Notes**:
> build azure-vnet-telemetry and azure-vnet-ipam in dropgz-test

- cni/network/invoker_cns.go
- cni/network/invoker_cns_test.go
- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_test.go
- cni/network/network_windows.go
Fixing overlay gateway bug that prevented cloud-node-manager-windows from initializing node because it couldn't reach IMDS. An additional VFP rule was implicitly plumbed by HNS to add 169.254.1.1/16 to the exception list. This is most likely based off the RouteConfiguration in the "azure" HNS network.  This additional VFP rule was skipping SNAT for any IP address in this range 169.254.0.0-169.254.255.255. We'll set the first .1 IP of podcidr as the gateway now.
**Notes**:
> fix: Windows CNI Overlay Gateway Bug

- cni/network/invoker_cns.go
- cni/network/invoker_cns_test.go
- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_test.go
- cni/network/network_windows.go
Fixing overlay gateway bug that prevented cloud-node-manager-windows from initializing node because it couldn't reach IMDS. An additional VFP rule was implicitly plumbed by HNS to add 169.254.1.1/16 to the exception list. This is most likely based off the RouteConfiguration in the "azure" HNS network.  This additional VFP rule was skipping SNAT for any IP address in this range 169.254.0.0-169.254.255.255. We'll set the first .1 IP of podcidr as the gateway now.
cherry-picked changes from #1849 to v1.4.35 based branch
**Notes**:
> fix: Windows Overlay Gateway Bug

- cns/service/main.go
- cns/service/metrics.go
Adds a metric for failure to start the controller-runtime manager, which is infinitely retried, but gives us a signal on which to alert on a CNS that is broken for some reason.
**Notes**:
> add metric for tracking failure to start the controller-runtime manager

- npm/examples/windows/azure-npm-capz.yaml
- npm/examples/windows/azure-npm.yaml
- npm/examples/windows/setkubeconfigpath.ps1
Resolve PATH issue correctly. Removing `powershell.exe` is **back-compat** with NPM v1.3.34 (in-prod).
**Notes**:
Don't want to override PATH variable.
```
powershell.exe : The term 'powershell.exe' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:27
+ .\setkubeconfigpath.ps1 ; powershell.exe .\npm.exe start --kubeconfig ...
+                           ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (powershell.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
> fix: [WIN-NPM] back-compat mitigation to PATH issue

- nmagent/requests.go
New variable name makes more sense with respect to the usage
**Notes**:
> change name to AZREnabled

- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/service/main.go
- cns/service/metrics.go
Currently we wait indefinitely for the NNC reconciler to receive an NNC and run the first reconcile before continuing execution (starting the CNS webserver, IPAM pool monitor, etc).
Instead, if the NNC Reconciler does not get an NNC and successfully run a reconcile within 15 minutes, timeout and fail to make it evident that CNS is encountering a fatal error/stuck.
**Notes**:
> timeout after 15 minutes waiting for the NNC reconciler to start

- .github/workflows/golangci.yaml
- cilium/cilium_helm_values.yaml
L7proxy has been disabled in AKS cilium config for GA. Setting L7Proxy to false for ACN pipeline testing.
**Notes**:
> cilium ci: set l7proxy to false

- .github/workflows/golangci.yaml
PRs keep timing out even with 15m timeout (e.g. #1848 and #1879)
**Notes**:
> ci: increase golint timeout to 25m

- crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- go.mod
- go.sum
[Feature: Vnet Scale]: Added the vnet block mode of operation for the NC Type in the NNC
Will be using this mode of operation in the DNC-RC and CNS for CIDR block-based allocations for a Vnet using Prefix on Nic feature of NMAgent
**Notes**: Minor modification of adding a mode of operation.
Design document: [Vnet Scale Scenario](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-networking/sdn-dbansal/azure-container-networking/azure-container-networking-docs/docs/scenarios/vscale/vscaledesign)
> [Feature: Vnet Scale]: Added the vnet block mode of operation for the NC Type in the NNC

- cns/client/client_test.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/service/main.go
This PR enables pprof endpoints to be registered on the multi tenancy path.
**Notes**:
> Adding Pprof register method

- .pipelines/npm/npm-conformance-tests.yaml
Windows Cyclonus pipeline keeps failing with below error:
```
##[error]Artifact Test was not found for build 71469484.
```
**Notes**:
Removing the step that downloads the Test artifact. This artifact isn't needed actually. It only contains the Conformance test binary.
> ci: [WIN-NPM] fix download failures in Cyclonus Pipeline

- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/restserver/homeazmonitor.go
- cns/restserver/homeazmonitor_test.go
validating home az value
change default PopulateHomeAzCacheRetryIntervalSecs value from 15 to 30
**Notes**:
> validating home az value

- cns/cniconflist/generator.go
- cns/cniconflist/generator_linux.go
- cns/cniconflist/generator_linux_test.go
- cns/cniconflist/generator_windows.go
- cns/cniconflist/testdata/fixtures/cilium.conflist
- cns/service/main.go
Today we use dropgz as an initcontainer to bring the cilium conflist to clusters. This PR allows for CNS to write the cilium conflist instead. Dropgz will still be required to install azure-ipam. This feature already exists for the overlay scenario, and it keeps nodes in NotReady state until the network is ready. Now, CNS can write the cilium conflist if we set in the cnsconfig: EnableCNIConflistGeneration as true, specify the conflist scenario to cilium, and set the conflist filepath. 
**Notes**:
Changes were validated in byocni overlay-cilium and byocni pod subnet cilium clusters. The azure-cns deployment was modified so that dropgz only installs azure-ipam, and CNS writes the cilium conflist to etc/cni/net.d.
> CNS writes Cilium Conflist

- test/scale/README.md
- test/scale/connectivity/test-connectivity.sh
- test/scale/install-kwok.sh
- test/scale/run-kwok.sh
- test/scale/templates/kwok-deployment.yaml
- test/scale/templates/real-deployment.yaml
- test/scale/templates/unapplied-networkpolicy.yaml
- test/scale/test-scale.sh
New features:
- Add unapplied NetworkPolicies (don't target Pods)
- Delete Pods
- Delete labels
- Delete NetworkPolicies
**Notes**:
Minor edits:
1. Fix values that are printed out
2. Print out pods to debug
> test: expand KWOK scripts to test deletions and more

- cns/client/client.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
Adding changes that @rbtr suggested in the last PR for CNS dualstack. Also adds two additional unit tests in case we try removing/adding IPs when only some exist in the IPAM. This results in a unsuccessful request/release with error and puts the IPs back where they originally were.
**Notes**:
> CNS ipam and client changes to address comments

- cni/network/network.go
- netio/mocknetio.go
- netlink/mocknetlink.go
- netns/netns.go
- network/api.go
- network/bridge_endpointclient_linux.go
- network/endpoint_linux.go
- network/endpoint_linux_test.go
- network/endpoint_test.go
- network/endpoint_windows.go
- network/manager.go
- network/manager_mock.go
- network/mock_endpointclient.go
- network/network.go
- network/network_linux.go
- network/network_test.go
- network/networkutils/networkutils_linux.go
- network/ovs_endpoint_snatroute_linux.go
- network/ovs_endpointclient_linux.go
- network/snat/snat_linux.go
- network/transparent_endpointclient_linux.go
- network/transparent_vlan_endpoint_snatroute_linux.go
- network/transparent_vlan_endpointclient_linux.go
- network/transparent_vlan_endpointclient_linux_test.go
This PR adds constant mac (aa:aa:aa:aa:aa:aa) for host veth interface. This prevents kernel to allocate unique mac for each host veth interface. Transparent mode already has this change and doing the same for transparent vlan mode here. Also from ubuntu22, we saw mac address getting changed after veth creation and arp entry set to wrong mac due to this. This prevents that if transparent-vlan mode used in ubuntu22 or later.
- Validate netwrok namespace creation and if its same as VM namespace, delete and recreate it
- Check for interface exists after creating vlan interface
- make sure calls are idempotent. even if it fails, retry should succeed
- delete route before adding new route for same ip (only for transparent vlan) …
> Set constant mac for host veth interface in transparent vlan mode

- test/integration/manifests/cns/ciliumconfigmap.yaml
- test/integration/manifests/cns/daemonset.yaml
- test/integration/manifests/cns/overlayconfigmap.yaml
- test/integration/setup_test.go
Implementing changes for CNS to write the cilium conflist in our e2e scenarios. 
**Notes**:
> ci: cns writes cilium conflist for PR tests

- crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
Updates the kubectl output for NNCs to be more immediately useful.
There is an extant bug in the RC which is preventing the "Allocated IPs" from being correctly populated (the value is currently `0` in otherwise correct NNCs). After this change and an update to this dependency over there, this can be fixed to correctly display the number of Allocated IPs, and the kubectl output will look like: 
```
➜  k get nnc
NAME                                ALLOCATED IPS   NC MODE   NC VERSION
aks-nodepool1-39652274-vmss000000   48              dynamic   2
aks-nodepool1-39652274-vmss000001   48              dynamic   2
```
Further information is now available behind the `-o wide` flag, that looks like:
```
➜  k get nnc -o wide
NAME                                REQUESTED IPS …
```
> update nnc printcols for kubectl output

- .pipelines/cni/cilium/cilium-cni-load-test.yaml
- hack/scripts/scale_deployment.sh
- hack/scripts/validate_state.sh
- hack/swift/Makefile
- hack/swift/README.md
- Added the test of restarting the nodes in the CNI load testing pipeline. It scales down the deployment and then restart the nodes without any delay.
- Update the `scale_deployment` script to include different parameters for CNI load testing
**Notes**:
> ci: [CNI] Add restart node in stage in the load test of cni pipeline

- cns/restserver/api.go
- cns/restserver/internalapi.go
- cns/restserver/ipusage.go
- cns/restserver/metrics.go
The IP Usage metrics were not visible for Overlay. 
This change enables the following metrics to be published to prometheus which will then scrape these metrics periodically.
https://msazure.visualstudio.com/One/_workitems/edit/19364564
**Notes**:
> Added IP Usage metrics at Rest server.

- cns/restserver/api.go
DNC requiring to refresh CNS NC associations is not expected to happen too often, but when it does, we need to log all pertinent details. Added the log in CNS should to show refresh detected and initiated by DNC.
**Notes**:
> Add log to happy path

- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
Fixes a bug in CNS where it only generates the CNI conflist if a new NC is discovered and programmed. Instead it should also generate the CNI conflist if the NC is already present in CNS state.
**Notes**:
> fix: generate cni conflist if NCs already exist in state

- cns/restserver/api.go
This PR reverts back a change introduced in #1825, where, during an NC publish, we check if a vnet join has been performed against nmagent and skip the call if so. This change introduced a regression due to nmagent behavior: if nmagent crashes while subscribed to a vnet with no NCs published, it will not re-subscribe once restarted, making the CNS cache invalid and resulting in new NCs published erroring with unauthorized codes. Removing this cache check will make it such that the vnet is always joined before any NC is published.
We should consider reintroducing this check (which greatly minimizes wireserver calls) once we can correctly remove a vnet from the cache when it has no NC.
> CNS - Remove vnet join cache check during NC publish

- pkgerrlint/README.md
- pkgerrlint/cmd/pkgerrlint/internal/run.go
- pkgerrlint/cmd/pkgerrlint/internal/run_test.go
- pkgerrlint/cmd/pkgerrlint/internal/testdata/no_output.go
- pkgerrlint/cmd/pkgerrlint/internal/testdata/no_wrapping.go
- pkgerrlint/cmd/pkgerrlint/internal/testdata/simple.go
- pkgerrlint/cmd/pkgerrlint/main.go
- pkgerrlint/go.mod
- pkgerrlint/go.sum
It was decided by the team that we prefer errors.Wrap over the standard library error wrapping mechanism because pkg/errors provides a more consistent experience by default. This adds a simple linter to detect usages of the standard library error wrapping.
> Add a linter for detecting fmt.Errorf w/ %w

- test/integration/manifests/cilium/cns-write-ovly.yaml
update load test with v1.4.44_hotfix for cns to write conflist
**Notes**:
load test pipeline run against this branch: https://msazure.visualstudio.com/One/_build/results?buildId=72946708&view=results
> ci: use 1.4.44_hotfix image in cilium load test

- cns/restserver/api.go
- cns/restserver/util.go
This PR includes:
Add fixes for cnsclient log to show why sometimes we cannot get NCs
It will log something like:
Failed to get NC "aa" due to "yy"
Failed to get NC "bb" due to "zz"
> Cnsclientlog fix

- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/singletenancy/overlay/overlay-e2e-step-template.yaml
- hack/scripts/validate_state.sh
- hack/swift/Makefile
After restart node stage was added, the PR check to validate pods was getting skipped. 
- Updating the condition in the script to check all namespaces
- Running the check before and after deletion of cilium-test namespace to verify the check works when endpoints change. 
**Notes**:
load test pipeline run: https://msazure.visualstudio.com/One/_build/results?buildId=73145191&view=results
> ci: fix cilium validate state check for PRs

- cns/ipampool/monitor.go
- cns/kubecontroller/nodenetworkconfig/conversion.go
- cns/kubecontroller/nodenetworkconfig/conversion_linux.go
- cns/kubecontroller/nodenetworkconfig/conversion_test.go
- cns/kubecontroller/nodenetworkconfig/conversion_windows.go
- cns/kubecontroller/nodenetworkconfig/reconciler.go
*Introduces VNETBlock NCType in CNS
*Reads CIDR IP blocks from VNETBlock NC and updates secondaryIP config accordingly
VNETScale mode NNC example: 
https://microsoft-my.sharepoint.com/personal/asn_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fasn%5Fmicrosoft%5Fcom%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2FSampleVnetScaleNNC%2Eyaml&parent=%2Fpersonal%2Fasn%5Fmicrosoft%5Fcom%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files&ga=1
This PR introduces support for VNET Scale mode in CNS. The NNC will have CIDR blocks for secondary IPs. Also primaryIP will also be a CIDR block where first IP will be used as PrimaryIP for NC and rest of the IPs will be assigned to secondary IP for pods.
- [*] uses [conventional commit …
> [Vnet Scale - CNS]: Flattening CIDR ranges for Node NNC to a list

- .pipelines/singletenancy/aks-engine/e2e-step-template.yaml
This updates the aks-engine version to @csfmomo 's latest release that removes the port 22 SSH rule from the aks-engine NSGs:
https://github.com/csfmomo/aks-engine/releases/tag/v1.0.9.2
> Remove SSH port 22 rule from aks-engine clusters

- cns/restserver/homeazmonitor.go
- nmagent/client_test.go
**Reason for Change**: If NMA returns 404 for GetHomeAZ API, we should mark CNS' response as `isSupported: false` in this case.
This will only happen for regions that do not support AZs, hence, will not have any AZ info. NMA in this case will return 404.
Fixes https://dev.azure.com/msazure/One/_workitems/edit/23883668
> Initial getHomeAZ 404 changes

- .pipelines/singletenancy/aks-engine/e2e-step-template.yaml
We should have removed 3389 port from AKS Engine PR. Those were getting reported in S360 and are also part of exposed ports.
https://github.com/csfmomo/aks-engine/releases/tag/v1.0.9.3
**Notes**:
> remove udp port 3389

- network/network_windows.go
Removing a redundant route added to Windows VMs for dualstackoverlay
Redundant route being removed:
`netsh interface ipv4 add route "<overlay-subnet-prefix>" "<interface-name>" "<overlay-subnet-gateway>"`
Example:
`netsh interface ipv4 add route "10.244.0.0/16" "vEthernet (Ethernet 2)" "10.244.0.1"`
This route is redundant, because prior to it being added, there is another route added with the **same matching-prefix**:
Route being added before redundant route:
`netsh interface ipv4 add route "10.244.0.0/16" "vEthernet (Ethernet 2)" "0.0.0.0"`
So the second route is rendered useless, and we don't need it
This was confirmed by @princepereira, so removing the redundant route (both for IPV4 and IPV6)
> Remove redundant routes in dualstackoverlay for windows nodes

- test/integration/manifests/cilium/cilium-config.yaml
To enable health check server for the kube-proxy replacement, the kubeProxyReplacementHealthzBindAddr option has to be set (disabled by default). The option accepts the IP address with port for the health check server to serve on.  This change is required for new AKS external lb design where health probe would be sent to this port instead of redirecting to pod. This modifies our pipeline cilium config map
**Notes**:
> [Cilium] [Pipeline] Enable Kubeproxy replacement healthz endpoint

- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
- cni/network/network_windows_test.go
- cns/client/client.go
- network/network.go
- network/network_windows.go
This PR is to fix this issue: https://github.com/Azure/azure-container-networking/issues/1986
Fix has been verified by HNS team, but looking for another issue(incorrect windows CNI conflist file) to be resolved.
**Notes**:
> add v6 port mapping policy to dualstack overlay

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_windows_test.go
Sometimes have UT failure for `TestMultiJobApplyInBackground`.
**Notes**:
> log/test: [WIN-NPM] log when we finish bootup phase & make UT more consistent

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- test/internal/k8sutils/utils.go
- Updating the vm size used for e2e test for cilium
- Improves the pipeline failure due to unavailability of resources(memory ) in case of cilium e2e
**Notes**:
> fix: Updating the vmsize for e2e cilium to avoid resource scarcity

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/load-test-templates/create-cluster-template.yaml
- .pipelines/cni/load-test-templates/pod-deployment-template.yaml
- .pipelines/cni/load-test-templates/restart-node-template.yaml
- .pipelines/cni/load-test-templates/validate-state-template.yaml
- .pipelines/cni/pipeline.yaml
To update the current CNI load testing pipeline to use templates, that can be re used for different cni/os versions.
**Notes**:
> CI:[CNI] Templatise CNI load test pipeline yaml

- dropgz/build/linux.Dockerfile
Updating CNI version in dropgz to CNI v1.5.4, so that the CNI conflist installed with dropgz doesn't break CNI (was using CNI binary 1.5.0 in dropgz, which doesn't support new 'overlay' CNI conflist option, breaking it)
Release [dropgz/v0.0.8](https://github.com/Azure/azure-container-networking/releases/tag/dropgz%2Fv0.0.8) is unusable/unstable, we should not share it with anyone, should I delete the release @rbtr ?
I did not realize I had to change this variable for dropgz to use a new CNI version, that is my bad
I tested this new change, with dropgz both installing the conflist, **and** installing the binary, pod creation worked, and connectivity was good:
[new-dropgz-testing.zip](https://github.com/Azure/azure-container-networking/files/11776736/new-dropgz-testing.zip)
> fix: updating CNI version in dropgz to 1.5.4

- cns/NetworkContainerContract.go
- cns/api.go
- cns/restserver/util.go
Adds `String()` to PodInfo so that logging the interface type works.
Currently, logging with `%[+]v` will insert the interface address in to the string instead of the values of the underlying type:
> ... ipState: {ID:abc IPAddress:123.456.789.0 LastStateTransition:2023-06-15 05:30:57.855233208 +0000 UTC m=+4.301209489 NCID:def **PodInfo:0xc000529ae0** state:Assigned **stateMiddlewareFuncs:[0x164faa0]**}
Note:
> PodInfo:0xc000529ae0
and (impl detail which should be removed)
> stateMiddlewareFuncs:[0x164faa0]
With `String()` implemented on both types, loggers may use `%s` and get correctly formatted and populated output for the underlying types:
> ... ipState: {ID: [abc], NCID: [def], IPAddress: [123.456.789.0], State: [Assigned], LastStateTransition: …
> fix: implement String for logging of PodInfo and IPConfig

- cns/cnireconciler/podinfoprovider.go
- cns/cnireconciler/podinfoprovider_test.go
- cns/restserver/ipam.go
This PR fixes an issue where interfaceID is set to interfaceName instead of containerID and this leads to incorrect CNS reconcilation where CNS key is interfaceName instead of containerID. This is the PR to change CNS running in managed state to recocile based on InterfaceID instead of podname+namespace: https://github.com/Azure/azure-container-networking/pull/1811 
**Notes**:
> [Fix][CNS] InterfaceID should be set to containerID instead of interfaceName if CNS managing state

- cni/client/client.go
- cni/client/const_linux.go
- cni/client/const_windows.go
Sets the working directory when CNS invokes the CNI (only on Windows) so that the CNS reconcile from CNI finds the real CNI statefile and reinitializes the CNS state correctly.
Due to the lack of [CNIRuntimePath set when CNI is running on Windows](https://github.com/Azure/azure-container-networking/blob/390977d5c2128fdd57c39c70a1fdb79035edfb70/platform/os_windows.go#LL27C21-L27C21): when CNS invokes CNI to restore state during initialization on Windows, it looks for the [statefile in the local directory](https://github.com/Azure/azure-container-networking/blob/390977d5c2128fdd57c39c70a1fdb79035edfb70/cni/plugin.go#L170) (`.\azure-vnet.json`) instead of the absolute path at `C:\k\azure-vnet.json`. No statefile exists in the current directory, so the …
> fix: setdir in CNI client

- cns/restserver/internalapi_test.go
- cns/service/main.go
- go.mod
- go.sum
Fix for bug where CNS may incorrectly initialize after a Node reboot
A bug in CNS initialization can lead to an IP being leaked and Assigned to Pods even though it has been deallocated.
- CNS starts to scale down and marks the IP as ToBeDeleted for DNC to deallocate
- the Node reboots / DNC deallocates the IP (in parallel)
- CNS restarts. During CNS initialization, since there are no Pods running, an initialization step is skipped, and the ToBeDeleted IP is incorrectly marked as Available (it is now leaked)
- the leaked IP appears Available. As Pods are started on the Node it is incorrectly Assigned to a Pod
- normal IP pool scaling operations start to fail due to the presence of the leaked IP
**Notes**:
> fix: reconcile initial state from CRD regardless of existing podInfo

- cns/restserver/internalapi.go
- cns/service/main.go
CNS must receive an NC via the NNC to function; it is nonsensical to do anything before the NNC.NC is available. This corrects the initialization to return errors instead of potentially incorrectly initializing state.
**Notes**:
> fix: CNS init must have an NC

- npm/pkg/dataplane/dataplane-test-cases_windows_test.go
- npm/pkg/dataplane/dataplane.go
Prevent a race condition during a narrow window at bootup where we could miss adding a NetworkPolicy to Pods (missed in both `updatePod()` and `AddPolicy()`).
**Notes**:
Race can occur if NetworkPolicy controller applies dataplane while bootup phase is finished.
The race could have logs similar to below:
```
I0621 23:07:54.371058    4184 dataplane.go:471] [DataPlane] Update Policy called for x/base
I0621 23:07:54.371058    4184 dataplane.go:474] [DataPlane] Policy x/base is not found.
I0621 23:07:54.371058    4184 dataplane.go:367] [DataPlane] Add Policy called for x/base
I0621 23:07:54.371058    4184 dataplane.go:292] [DataPlane] [ADD-NETPOL] new batch count: 3
I0621 23:07:54.371058    4184 dataplane.go:295] [DataPlane] …
```
> fix: [WIN-NPM] race during bootup where we may not add one NetPol to a Pod

- test/integration/load/load_test.go
- test/internal/k8sutils/utils.go
- test/internal/k8sutils/utils_create.go
The load test pipeline for CNI is failing if the `load-test` namespace is already created.
Fixes the load test pipeline.
**Notes**:
> fix: [CNI] CNI load test failing due to namespace already created

- aitelemetry/telemetrywrapper.go
- cni/plugin.go
- store/json.go
perf: Performance Improvements of Azure CNI by increasing store Lock timeout for CNI in Windows to 1 minute.
The current value of lock timeout for Azure CNI is 10 second. This value will cause a lot of CNI add call timeout specially on large scale scenarios in Windows. To prevent this add call failure in Windows, we are increasing the value to 1 minutes on Windows to prevent subsequent delete request form Containerd for the failed add request.
**Notes**:
> perf: Store Lock timeout for CNI in Windows is increased to 1 minute.

- network/endpoint_windows.go
Kappie HNS plugin for windows provides metrics for endpoints, but lacks pod info for the metrics. Adding these here will help us map endpoints to pods.
Linux endpoints currently set these properties, but windows is currently not set.
**Notes**:
I have tested this by copying the binary to a windows node and restarting a pod. The new properties show up. I have also replaced the new cni binary with the live version to ensure that there were no errors in the logs.
> update: add pod info to windows endpoint

- test/integration/manifests/noop-deployment-windows.yaml
- test/internal/k8sutils/utils.go
Window cniv1 load-test was failing due to the nanoserver image. Pods were reaching the complete state at various, quick, intervals resulting in a failed availability check. Pipeline logs were missing this interaction.
**Notes**:
PM for pipeline run.
> fix: [CNI] Windows image change for load test

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Adds check to validate CNS pod IP assignment before and after the CNS daemonset is restarted.
**Notes**:
> ci: validate CNS in-memory state after restart

- .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
- .pipelines/pipeline.yaml
- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/singletenancy/aks/e2e-step-template.yaml
- Makefile
- cni/build/windows.Dockerfile
- dropgz/build/cniTest.Dockerfile
- hack/aks/Makefile
- hack/scripts/updatecni.ps1
- test/integration/manifests/cni/cni-installer-v1.yaml
This PR adds creation of aks cluster and replacing the CNI binaries. This is a step to migrate away from aks-engine(deprecated). @jpayne3506  will be adding the datapath to these created clusters.
AKS Engine is deprecated.
**Notes**:
> ci: [CNI] Adding aks cluster creation steps for k8s e2e test

- npm/linux.Dockerfile
- npm/windows.Dockerfile
> fix: disabling CGO for NPM

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Improves the speed for the CNI load test pipeline as we will be using a specific pool to test.
**Notes**:
> ci:[CNI] Update pool name for cni load test pipeline

- nmagent/client.go
- nmagent/client_test.go
- nmagent/requests.go
This change implements the Delete Network API call in the NMAgent client. Adding this method allows for future changes to invoke the Delete Network call on NMAgent after receiving a Delete Network request in DNC.
> Add Delete Network call to NMAgent client

- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
> ci: [Cilium] Add CNS and dropgz version as pipeline params

- cns/kubecontroller/nodenetworkconfig/conversion_linux_test.go
- cns/kubecontroller/nodenetworkconfig/conversion_test.go
- cns/kubecontroller/nodenetworkconfig/conversion_windows.go
- cns/kubecontroller/nodenetworkconfig/conversion_windows_test.go
We need to use .1 address of subnet as GW; skipping 0th and last IP of subnets since they are reserved from HNS POV
**Notes**:
> fix: skip reserved IPs

- network/network_windows.go
- network/network_windows_test.go
When ipv6 is enabled, if the `azure` HNS network is not present, CNI adds some default routes to `vEthernet (Ethernet 2)` before creating the network. On subsequent invocations, CNI recognizes that the network exists, and does not try to add the routes again.
If the `vEthernet (Ethernet 2)` interface is not present for some extraneous reason, adding default routes will continue to fail and thus the `azure` network never gets created, thus making CNI never succeed for any containers.
This PR removes addition of these routes since they are just an optimization, and always letting CNI create the azure network.
> Removing addition of default routes before HNS network creation

- platform/os_windows.go
- platform/os_windows_test.go
**Reason for Change**
Debugging CNI Windows logs is not helpful when we cannot see the entirety of what's output by commands failing. This PR attempts to improve these messages by including both stdout and stderr in the error messages returned.
> Improving error messages in windows command execution

- network/transparent_vlan_endpointclient_linux.go
update gateway IP from `169.254.1.1` to `169.254.2.1` for transparent-vlan as its conflicting with other cni and route addition getting failed since route exists already for `169.254.1.1` ip
**Notes**:
> [Fix] update gw ip to 169.254.2.1 for transparent-vlan as its conflicting with other cni

- cni/network/network.go
- network/endpoint.go
- network/manager.go
- platform/os_linux.go
Removing logs that are not useful and spamming the log file. Also it accounts for cni execution time.
**Notes**:
> chore: Removing CNI logs that are not useful

- cns/configuration/cns_config.json
- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/configuration/testdata/good.json
- cns/service/main.go
-  add EnableAZR flag to make home az goroutine as an opt-in feature
-  change PopulateHomeAzCacheRetryIntervalSecs default to 60
**Notes**:
>  add EnableAZR flag to make home az goroutine as an opt-in feature

- cns/restserver/ipam.go
- cns/service/main.go
> fix: use cached ctrlruntime client in IPAM pool monitor

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- test/integration/manifests/cilium/deployment.yaml
- This PR updates cilium operator arguments for cilium identities to lower the garbage collection interval. 
- Adding a stage in the nightly pipeline to verify that cilium identities are removed once the cilium endpoint is deleted. 
This check will only run for the nightly pipeline and will be skipped in the PR runs. It was previously added to the old version of our nightly pipeline.
**Notes**:
> ci: add cilium identities check to nightly pipeline

- cni/client/client.go
- cns/cnireconciler/version.go
- cns/cnireconciler/version_test.go
The CNS will invoke CNI's `version` command to check CNI version, and use it to determine whether it can be used for reconciling CNS state. This is achieved by a semver comparison >= v1.4.7. However, if the CNI was not tagged with a semantic version, this fails. Since CNI v1.4.7 is quite old, it is probably safe to remove this check entirely and just say "CNS >= v1.4.44 can't be used with CNI <=v1.4.6", but for now we'll just ignore the sem ver check if the parsing fails and assume we can use the command.
**Notes**:
I'm open to just removing the semver check altogether with the caveat that CNS v1.4.44 and above must be used with CNI >= v1.4.7.
> fix: assume invalid semver CNI has the required dump state command

- cns/restserver/ipam.go
We missed acquiring a lock before reading service state in a previous PR. This addresses that.
> CNS - fix locking in AssignDesiredIPConfigs

- Makefile
- hack/aks/Makefile
- hack/aks/README.md
- hack/scripts/k8se2e-tests.sh
- hack/scripts/k8se2e.sh
Allows for users to test cluster network conformance from the command line and give a single command to test network conformance in future CI.
-  [x] relevant PR labels added
**Notes**:
Example commands:
- make -C ./hack/aks/ test-k8se2e CLUSTER=yourClusterName GROUP=resourceGroup OS=windows TYPE=basic
- make -C ./hack/aks/ test-k8se2e CLUSTER=yourClusterName GROUP=resourceGroup
> ci: Add k8s network conformance tests to makefile

- test/integration/datapath/datapath_linux_test.go
- test/integration/datapath/datapath_windows_test.go
Did not match the design of other go tests, slowing down development.
**Notes**:
> refactor: Match CNI go tests

- .pipelines/pipeline.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- test/integration/manifests/cnsconfig/azurecnioverlayconfigmap.yaml
- test/integration/manifests/ip-masq-agent/config-custom.yaml
- test/integration/manifests/ip-masq-agent/config-reconcile.yaml
- test/integration/manifests/ip-masq-agent/ip-masq-agent.yaml
- test/integration/setup_test.go
Add azure cni overlay e2e test to PR pipeline
> test: add azure cni overlay e2e

- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/singletenancy/overlay/overlay-e2e-step-template.yaml
- cni/client/client.go
- cns/cnireconciler/version.go
- cns/cnireconciler/version_test.go
- test/integration/utils_test.go
CNS v1.4.44.4 release candidate
Includes:
- https://github.com/Azure/azure-container-networking/pull/2078 (bug fix)
- https://github.com/Azure/azure-container-networking/pull/2014 (CI fix)
**Notes**:
> Release candidate v1.4.44.4

- .pipelines/pipeline.yaml
`release/*` is a protected branch now. We're going to PR cherry-picks into it. We should auto trigger our PR pipeline on these branches too.
**Notes**:
> chore: add release branches to pr pipeline trigger

- Makefile
- test/integration/load/load_test.go
- test/validate/linux_validate.go
- test/validate/validate.go
- test/validate/windows_validate.go
Removing the predefined interfaces from validate package
**Notes**:
> refactor: [CI-CNI] Removing the predefined interfaces from validate

- cns/NetworkContainerContract.go
- cns/client/client_test.go
- cns/cnireconciler/podinfoprovider.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/service/main.go
Reconciliation after CNS restart is currently not handling dual stack scenarios correctly. There's 2 bugs:
- the information fetched from CNI currently filters out ipv6 addresses.
- reconciliation after restart processes multiple NCs separately, but pod info in CNS (or at least one representation of it) is not able to be patched after first insertion, meaning, a pod will be reconciliated with ipv4 first, and then skip the update with ipv6.
This PR modifies the main reconciliation function such that it takes multiple NCs as input, and processes all IPs for a single pod key (interface or name+namespace, depending on reconcile flow) at the same time, such that both ipv4 and ipv6 can be inserted once as `DesiredIPAddresses`.
> CNS - consider multiple IPs for a pod in reconciliation after restart

- cni/ipam/plugin/main.go
- cni/ipam/pluginv6/main.go
- cni/network/plugin/main.go
This PR is to put back thye config to write to the file instead of only stdout logs
**Notes**:
> put back the config to write logs to the file instead of only stdout logs

- .pipelines/submodules-pipeline.yaml
Enables the use of [comment triggers](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers) for the submodules pipeline. `.pipelines/submodules-pipeline.yaml` was excluded from the triggers and prevented ` /azp run Azure Container Networking PR - submodules ` from being called to run the pipeline.
**Notes**:
> ci: Enable /azp run for submodule pipeline

- cni/log/logger.go
This PR is to get rid of repeated "logger: azure-vnet" name. Instead, it will print the process id, such as : "pid":301
**New logs on Linux:**
```
{"level":"info","ts":"2023-08-11T02:14:30.471Z","msg":"Plugin Info","pid":299160,"name":"azure-vnet","version":"v1.5.9-9-gd589d7df","component":"cni-net"}
2023/08/11 02:14:30 [299160] [net] Restored state
{"level":"info","ts":"2023-08-11T02:14:30.471Z","msg":"Plugin started","pid":299160,"component":"cni-net"}
{"level":"info","ts":"2023-08-11T02:14:30.471Z","msg":"[cni-net] Processing ADD command","pid":299160,"containerId":"0ffde0741e3e96ac0394991ae0fa86f01ffdcb39acdd0877c04843de7a8f7a6d","netNS":"/var/run/netns/cni-039e1fc6-101e-4e19-692d-645048038cb0","ifName":"eth0","args":"K8S_POD_UID=38b85cf6-29ea-43 …
```
> chore: log process id instead of logging name

- cni/ipam/ipam.go
- cni/ipam/plugin/main.go
- cni/ipam/pluginv6/main.go
- cni/log/logger.go
- cni/network/invoker_azure.go
- cni/network/invoker_cns.go
- cni/network/multitenancy.go
- cni/network/network.go
- cni/network/network_windows.go
- cni/network/plugin/main.go
- cni/plugin.go
- cni/telemetry/service/telemetrymain.go
This PR is to change the CNI zap logging component structure. Instead of putting component:cni everywhere, we provide component name globally.
**Example logs in Linux:**
{"level":"info","ts":"2023-08-15T20:44:48.779Z","msg":"Plugin started","pid":3139991,"component":"cni"}
{"level":"info","ts":"2023-08-15T20:44:48.779Z","msg":"[cni-net] Processing ADD command","pid":3139991,"component":"cni","containerId":"9ac1b7e2429d7d2ad36a6b497d6756279fd074d7974910a1c281afeb16e00f6c","netNS":"/var/run/netns/cni-55d04a42-99a4-c2aa-ff40-383dff9d1efb","ifName":"eth0","args":"K8S_POD_NAME=linux-pod2;K8S_POD_INFRA_CONTAINER_ID=9ac1b7e2429d7d2ad36a6b497d6756279fd074d7974910a1c281afeb16e00f6c;K8S_POD_UID=ed43fc0a-e04c-4876-ba1d-be581f99ee39;IgnoreUnknown=1;K8S_POD_NAMESPACE=default","pa …
> zap: change cni component structure

- .pipelines/cni/cilium/nightly-release-test.yml
Fixes Cilium Nightly Pipeline by adding back in the cluster creation and deletion steps. They were removed in #2077 when the cluster creation process was changed for the PR pipeline.
**Notes**:
> fix: Add back cluster create/delete for Cilium Nightly Pipeline

- netlink/ip_linux.go
- netlink/netlink_test.go
* fix: Remove unix.NLM_F_EXCL from Netlink Delete Route api call
unix.NLM_F_EXCL is not expected to set in netlink delete route calls. It's no-op in older kernel and didnt return error. From kernel 5.19+, new flag NLM_F_BULK was defined with same value and serves a purpose in delete route call. This changes breaks azure cni and netlink calls fails in 5.19 kernel and onwards.
The fix is to remove setting unix.NLM_F_EXCL in netlink delete route request.
* fix: Remove unix.NLM_F_EXCL from Netlink Delete Route api call
unix.NLM_F_EXCL is not expected to set in netlink delete route calls. It's no-op in older kernel and didnt return error. From kernel 5.19+, new flag NLM_F_BULK was defined with same value and serves a purpose in delete route call. This changes breaks azure cni and netlink calls …
> fix: Remove NLM_F_EXCL flag from Netlink Delete call (#2150)

- .pipelines/cni/cilium/nightly-release-test.yml
Cilium Nightly Pipeline was not deleting clusters at the end of its run due to mismatched cluster names. 
**Notes**:
Fixed the version input variables for pipeline within ADO. There is an updated policy that auto removes images after 30d that do not match `v*` . Included with that was an initial deletion of all images >30d, leading to the loss of older versions that matched the regex.
> fix: Change cluster name for cilium nightly pipeline

- nmagent/client.go
- nmagent/client_test.go
- nmagent/error.go
This PR makes some minor changes to the NMAgent client package as a part of a larger work item. This commit adds a NotFound method to the error returned by the NMAgent client. It also adds special handling to treat a 400 BadRequest as a NotFound when returned by the DeleteNetwork API call, since this case should be interpreted as a NotFound by the caller.
**Notes**:
> Add NotFound error handling to NMAgent client

- crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
- crd/multitenancy/api/v1alpha1/nodeinfo.go
- crd/multitenancy/api/v1alpha1/podnetwork.go
- crd/multitenancy/api/v1alpha1/podnetworkinstance.go
- crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
- crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
- crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworkinstances.yaml
- crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworks.yaml
Update multitenancy CRDs scope to Cluster
**Notes**:
> update swiftv2 crds scope

- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- .pipelines/templates/create-cluster.yaml
This allows for the Dualstack E2E on the PR pipeline to run if cluster creation succeeds and skip it if it does not.
**Notes**:
> ci: Bypass Dualstack E2E on cluster creation failure

- cns/kubecontroller/multitenantpodnetworkconfig/reconciler.go
- cns/kubecontroller/pod/reconciler.go
- cns/service/main.go
- go.mod
- go.sum
Creates a stub MTPNC reconciler to cause the local ctrlruntime cache to be populated with these objects so that we can interrogate them without making requests against the apiserver.
**Notes**:
Built on/depends on #2162
> Add MTPNC reconciler for cache population in Swift V2

- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
Updates the Total IPs metrics to include the NC Primary IP in the total. Adds a Secondary IPs metric which holds the value that the Total IPs previously held: NC Secondary IPs known to CNS which could be used by Pods.
**Notes**:
> change total IPs and add secondary IP metric

- internal/fs/atomic.go
- internal/fs/atomic_test.go
Instead of moving an existing CNI conflist to <filename>-old immediately, this will copy it to <filename>-old instead. This means we will still generate the new conflist on top of the existing one, but without ever deleting the existing conflist. This will prevent nodes from toggling between Ready->NotReady->Ready when CNS gets restarted (either due to crash or normal rollout).
**Notes**:
not really sure how to write a good test for this since the logic is in `main`, need to think about it some more
> fix: don't delete an existing conflist

- Makefile
due to a change in buildx, we need to explicitly
pull the windows variant of the windows image that we have previously built.
**Notes**:
> fix: add OS=windows to manifest-add args

- .pipelines/pipeline.yaml
Goldpinger was sending nodes into `NodeHasInsufficientMemory`. Resulting in `node.kubernetes.io/memory-pressure:NoSchedule` taints and E2E test failures.
**Notes**:
> ci: Increase vmSize for dualstack overlay

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/load-test-templates/create-cluster-template.yaml
- .pipelines/cni/load-test-templates/pod-deployment-template.yaml
- .pipelines/cni/load-test-templates/restart-node-template.yaml
- .pipelines/cni/load-test-templates/validate-state-template.yaml
- .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/singletenancy/aks/e2e-step-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
- .pipelines/templates/create-cluster.yaml
- .pipelines/templates/delete-cluster.yaml
Moves the PR pipeline and all associated resources to the Build Validations Subscription to alleviate the resource group usage within Azure Network Agent - Test. 
**Notes**:
Added the service connection to the ACN-CNI-Pipeline Variable Group
> ci: Changing Service Connection for PR pipeline

- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/kubecontroller/nodenetworkconfig/reconciler_test.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
There may be occasions where node upgrades may not result in delete and re-create events for an NNC, rather a new set of NCs will be available in the NNC as an update. The current reconcile logic only adds NCs to CNS, so in these cases stale NCs would remain. This PR attempts to ensure there are no stale NCs during NNC reconciles.
> CNS - Ensuring no stale NCs during NNC reconcile

- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
ACN PR pipeline dualstack E2E stage is flaky. When creating the pods the containers take 10s~ to create and the tests take 45s~, leaving very little flexibility on a non-time critical test. 
**Notes**:
There will be a follow on PR to refactor the various job templates to allow for quicker retries of failed E2E steps.
> ci: Increase timeout of datapath tests

- test/integration/manifests/datapath/linux-deployment-ipv6.yaml
- test/integration/manifests/datapath/linux-deployment.yaml
Goldpinger pods in dual stack tests are not able to query apiserver to discover what pod IPs to ping, due to RBAC being incorrectly set up for these deployments.
> fix: serviceAccount must be specified at pod spec level in dual stack goldpinger deployments

- .pipelines/pipeline.yaml
- Makefile
> Publishing our Windows dropgz version in linux dropgz manifest

- .pipelines/cni/load-test-templates/pod-deployment-template.yaml
- .pipelines/cni/load-test-templates/restart-cns-template.yaml
- .pipelines/cni/load-test-templates/restart-node-template.yaml
- .pipelines/cni/load-test-templates/validate-state-template.yaml
- .pipelines/singletenancy/aks/e2e-step-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
- Makefile
- test/integration/load/load_test.go
- test/integration/load/setup_test.go
- test/integration/setup_test.go
- test/internal/kubernetes/utils_create.go
- test/internal/kubernetes/utils_delete.go
- test/validate/validate.go
Refactoring the load test suite in preparation for #2187
- Making `env` variables instead of cmd line flags
- Adding a `CLEANUP` option
- Adding `CNS` installation as an option
> chore: refactor load test suite

- docs/feature/ipammath/0-background.md
- docs/feature/ipammath/1-ipam-math.md
- docs/feature/ipammath/1-watchpods.md
Design docs for redesign of CNS IPAM Pool Monitor to be idempotent and for the view of the world to be derived from a Pod watch instead of the CNI requests.
**Notes**:
> proposal: redesign of CNS IPAM

- cns/NetworkContainerContract.go
- cns/kubecontroller/nodenetworkconfig/conversion.go
- cns/kubecontroller/nodenetworkconfig/conversion_linux.go
- cns/kubecontroller/nodenetworkconfig/conversion_windows.go
- cns/restserver/ipam.go
- crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
Cherry-pick of #2202 and #2193 into the release/v1.4
**Notes**:
> backport "feat: Consume the NCStatus to be able to append subnet is full error to Pod IP reservation failures" to release/v1.4

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
skipping the k8s e2e unsupported service conformance test
Unblocks the PR pipeline
**Notes**:
> fix: skipping the k8s e2e unsupported service conformance test

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
backport "fix: skipping the k8s e2e unsupported service conformance test (#2255)" to release/v1.4
**Notes**:
> backport "fix: skipping the k8s e2e unsupported service conformance test (#2255)" to release/v1.4

- hack/aks/Makefile
Since we occasionally generate long-lived clusters using the hackfile (either intentionally, or leaking them accidentally out of the pipelines), we can at least reduce any ongoing security scan violations by enabling all possible automatic upgrades on these clusters by default.
 
**Notes**:
> fix: set cluster auto-upgrade and node auto-upgrade in the hackfile

- cns/NetworkContainerContract.go
- cns/api.go
- cns/client/client.go
- cns/client/client_test.go
- cns/restserver/ipam.go
- cns/restserver/restserver.go
- cns/service/main.go
In the stateless CNI design two new APIs on CNS side with respect of endpoint state management is needed.
GetEndpoint() is used to return the state of a given endpointId
UpdateEndpoint() is used to update the HNSId and VethName field within the endpoint state. 
**Notes**:
> feat: 🌈 StatelessCNI: Adding getEndpoint and UpdateEndpoint API to CNS

- test/integration/datapath/datapath_linux_test.go
- test/integration/datapath/datapath_windows_test.go
- test/integration/k8s_test.go
- test/integration/load/load_test.go
- test/integration/load/setup_test.go
- test/integration/setup_test.go
- test/internal/kubernetes/utils.go
- test/internal/kubernetes/utils_create.go
- test/internal/kubernetes/utils_delete.go
- test/internal/kubernetes/utils_parse.go
- test/validate/validate.go
`must*` functions should panic, not return `err`
Targeting the `test/internal/kubernetes` package in this PR
> chore: must* functions should panic

- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
Ensures that E2E templates in PR pipeline use `Networking-ContainerNetworking-VMSS` build pool by setting it at the stage level, which is passed to the individual jobs and can be overwritten. This is to prevent using the default build pool that can call old images that no longer exist or are depreciated. 
```
##[warning]An image label with the label Ubuntu16 does not exist.
,##[error]The remote provider was unable to process the request.
```
**Notes**:
> ci: Agent pool default set at stage level

- .pipelines/cni/singletenancy/linux-cniv2-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
- test/integration/manifests/ip-masq-agent/ip-masq-agent.yaml
- test/internal/kubernetes/utils_create.go
Install `ip-masq-agent` in go-code (rather than scripts) and tie it to overlay cns scenarios
> chore: install ip-masq-agent as part of overlay cns scenarios

- npm/azure-npm.yaml
- npm/examples/windows/azure-npm-capz.yaml
- npm/examples/windows/azure-npm.yaml
HostProcess containers have a [change to container mounts](https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#container-mounts) in containerd 1.7.
CAPZ testbed is on containerd 1.7, so current NPM yaml crashes with e.g. `npm.exe not found`.
**Notes**:
> test(capz): [WIN-NPM] support containerd 1.7 filesystem

- Makefile
Added make cmds for stateless cni for swift
**Notes**:
> feat: create stateless cni binary for swift

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/cni/load-test-templates/pod-deployment-template.yaml
- .pipelines/cni/load-test-templates/restart-cns-template.yaml
- .pipelines/cni/load-test-templates/restart-node-template.yaml
- .pipelines/cni/singletenancy/cniv1-template.yaml
- .pipelines/cni/singletenancy/linux-cniv2-template.yaml
- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- .pipelines/templates/log-template.yaml
Fixes #2264 : artifacts having matching names due to calling the same template in separate stages. I.E. HNS restart calling the same suite of templated tests.
**Notes**:
> fix: change artifact naming convention

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/singletenancy/linux-cniv2-template.yaml
- test/internal/kubernetes/utils.go
- test/internal/kubernetes/utils_create.go
Provides CNS image repository parameters to the `make test-load` and `make test-integration` calls.
**Notes**:
> ci: Parameterize CNS image repository

- aitelemetry/telemetrywrapper_test.go
- cni/network/network.go
- cni/network/plugin/main.go
- cni/telemetry/service/telemetrymain.go
- cnm/network/network.go
- cnms/service/networkmonitor.go
- cns/dockerclient/dockerclient.go
- cns/restserver/util.go
- ebtables/ebtables.go
- ipam/manager.go
- ipam/manager_test.go
- iptables/iptables.go
- network/endpoint_windows.go
- network/endpoint_windows_test.go
- network/manager.go
- network/network.go
- network/network_linux.go
- ovsctl/ovsctl.go
- platform/mockexec.go
- platform/os.go
- platform/osInterface.go
- platform/os_linux.go
- platform/os_test.go
- platform/os_windows.go
- platform/os_windows_test.go
- platform/windows/adapter/mellanox/mellanox.go
- telemetry/telemetry.go
- telemetry/telemetry_windows.go
- telemetry/telemetrybuffer.go
- telemetry/telemetrybuffer_test.go
This PR is to migrate platform package logger to zap logger
Remove log from GetLastRebootTime() and log it at caller
**Notes**:
> [CNI] zap logger for platform package

- .pipelines/cni/pipeline.yaml
Adds linux arm64 NPM coverage.
**Notes**:
> ci: Add NPM arm64 to CNI Load Test Pipeline

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Fixes #2280 removal of RBAC on `cilium-overlay-load-test.yaml`
**Notes**:
Located here. https://github.com/Azure/azure-container-networking/commit/f46a4306a30736f9f9d2ea39ab596b9066d8c269#r129933738
> revert: Cilium load test RBAC

- .pipelines/cni/pipeline.yaml
- .pipelines/pipeline.yaml
Having multiple runs on the same commit ID was causing conflicts from cluster creation/deletion. This change makes each run unique by giving it a time stamp of DDHHMM (DayHourMinute). Expected clusterName  `<unique cluster name>-<commitID>-<Timestamp>` | `cilium-over-ebdde6c1-132228`
Adding 7 additional characters at the end of the clusterName resulted in having to change the unique cluster names due to the max character limit being 80. Generally the max length for a cluster name should be 14 characters as 32 characters are reserved by the commit hash + timestamp and prefix/suffix can be up to 18 characters (based on region selection).
ex. `MC_ciliovercnie2e-67b2ede2-132124_ciliovercnie2e-67b2ede2-132124_centraluseuap` 
**Notes**:
> ci: Enable multiple runs with the same commitID

- azure-ipam/const.go
- azure-ipam/ipam.go
- azure-ipam/ipam_test.go
- azure-ipam/ipconfig/ipconfig.go
- cilium/cilium_helm_values.yaml
Adds support in the azure-ipam plugin to use new APIs created for CNS to allow for passing multiple IPs on Add and Delete commands which is needed to create dualstack clusters.
Here's where the new APIs were added.
https://github.com/Azure/azure-container-networking/pull/1773
**Notes**:
> Adding dualstack overlay support to azure-ipam plugin for Cilium

- test/internal/kubernetes/utils.go
- test/internal/kubernetes/utils_delete.go
The windows overlay tests kept hitting:
```
--- FAIL: TestScaleDeployment (0.30s)
load_test.go:141: Scale deployment
panic: could not update deployment win-load-test: Operation cannot be fulfilled on deployments.apps "win-load-test": the object has been modified; please apply your changes to the latest version and try again [recovered]
panic: could not update deployment win-load-test: Operation cannot be fulfilled on deployments.apps "win-load-test": the object has been modified; please apply your changes to the latest version and try again
```
This was most likely because the deployment was not being completely deleted, before each test run
Now we wait for the deployment to be deleted before proceeding
> chore: wait for deployment to completely delete before proceeding

- azure-ipam/ipam.go
In case we use ReleaseIPAddress instead of ReleaseIPs we need to add a second check for async delete.
Was originally a part of https://github.com/Azure/azure-container-networking/pull/2239 but the change was separated out.
**Notes**:
> Adding CNI async delete to old API for cilium

- cni/network/invoker_azure.go
On failure to allocate pool, this PR retries ADD immediately after IPAM state deletion in order to reduce the potential for the CNI to block.
**Notes**:
> fix: retry pool allocation after cleaning IPAM state

- .pipelines/containers/manifest-template.yaml
- .pipelines/pipeline.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
- Makefile
- network/network_linux.go
This PR is the first to migrate our agent pool to a 1ES maintained agent pool. This is primarily to unblock the ACN PR pipeline and will be improved upon. 
Future CI:
- Check for systemd-resolved not tied to ubuntu image version
- Properly assign *auth.json to skopeo commands
- Remove reinstalling dependencies from JIT provisioning script
- Remove all uses of `sudo` where applicable
**Notes**:
> fix: Pipeline agent image update from 18.04 to 22.04 | AzSecPack

- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
- test/internal/kubernetes/utils.go
> fix: Using retryOnConflict to fix v4overlay scale tests failing.

- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
- cni/network/network_windows_test.go
This PR is to fix this issue: https://dev.azure.com/msazure/One/_workitems/edit/25403093/
If no hostIP is provided, then we assume to use ipv4 flag, if hostIP is provided and it's ipv6 address, then we set flag to ipv6 HNS flag.
**Notes**:
> [cni]: dualstack overlay hostIP issue hotfix

- cns/NetworkContainerContract.go
- cns/restserver/util.go
- we need a new containerType as per new NC request type in DNC for the Singularity L1VH APIs for create/delete backend-nic NC, so the goal state to be sent to CNS & used by CNI should have the new containerType for it. Also adding 2 fields required to program a backendNIC to the createNetworkContainerRequest object to send the goal state.
design doc - https://microsoft.sharepoint.com/:w:/t/Aznet/EQqTVNaVUBJDsRbhxwlMFP4BPAqGRM_9-RQiOkoMt7FyxA?e=kYTEJZ
**Notes**:
> add a new container type for l1vh singularity container request

- cni/ipam/ipam.go
- cni/network/network.go
- ipam/azure.go
- ipam/fileIpam.go
- ipam/ipv6Ipam.go
- ipam/manager.go
- ipam/pool.go
- network/transparent_vlan_endpointclient_linux.go
- ovsctl/ovsctl.go
This PR is to migrate zap logger for ACN ipam package
**Notes**:
> [CNI] Migrate zap logger for acn ipam package

- .pipelines/pipeline.yaml
- Makefile
- cni/linux.Dockerfile
- cni/windows.Dockerfile
Up until now, we have released the CNI installer image as a separately versioned component from the CNI releases themselves. This has created a bit of versioning hell, as we struggle to maintain multiple release trains of the CNI (and thus CNI installer) when the CNI and installer version are not correlated. 
This change flips the CNI installer image builder architecture. Previously, `dropgz` pulled in the released CNI tarballs as dependencies and produced a "dropgz-vX" omnibus image which contained uncorrelated CNI versions.
Here, we migrate instead to a CNI Dockerfile which _imports `dropgz` as the dependency_ and is built in lockstep with (at least) azure-vnet builds, and versioned the same as them. Instead of deploying a "dropgz:v0.0.4" with unknown (at least, …
> feat: build cni installer image with cni builds

- crd/multitenancy/api/v1alpha1/podnetwork.go
- crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworks.yaml
Multi-tenancy orchestrator needs to submit Azure Subnet ResourceGUID to PN CRD, in addition to ARM Resource ID.
**Notes**:
> fix: Add SubnetGUID to MT PodNetwork CRD

- cns/configuration/env.go
- cns/configuration/env_test.go
- cns/middlewares/mock/mockSWIFTv2.go
- cns/middlewares/swiftV2.go
- cns/middlewares/swiftV2_test.go
- Renaming NodeCIRDs to InfraVNETCIDRs
- Add route for virtual GW
**Notes**:
> chores: SWIFT v2 routing changes

- cns/restserver/api_test.go
- cns/restserver/internalapi.go
- cns/restserver/util.go
https://github.com/Azure/azure-container-networking/pull/1767 introduced a bug where, if the NC in state does _not_ have the `Swift_` prefix, when we unconditionally add the prefix we become unable to identify it in the NMA responses which don't have it and are stuck:
```json
{"httpStatusCode":"200","networkContainers":[{"networkContainerId":"de043d23-a135-401c-b6a8-1ab6a09f980a","version":"0"}]}
```
and yet
```
[Azure CNS] Failed to get NC de043d23-a135-401c-b6a8-1ab6a09f980a doesn't exist in NMAgent NC version list Skipping GetNCVersionStatus check from NMAgent
```
After investigating, this it seems like nobody knows where or even if we actually have NCs in the wild with the `Swift_` prefix, but it is possible that we do as a legacy artifact, and it could be …
> normalize NCID by stripping Swift prefix

- cni/network/invoker_cns.go
- cni/network/network.go
- netio/mocknetio.go
- netlink/mocknetlink.go
- network/endpoint.go
- network/endpoint_linux.go
- network/endpoint_test.go
- network/endpoint_windows.go
- network/manager.go
- network/secondary_endpoint_client_linux.go
- network/transparent_endpointclient_linux.go
Add a test to validate that endpoint will not be created if SecondaryEndpointClient fails
Passing NIC Type var from CNS response down instead of hardcoding
**Notes**:
> test: validate secondary endpoint client failure

- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
E2E did not have consistent assigning of variables. This led to a bug that affected cilium overlay E2E logging because the commitID variable was never passed to the failure logs. This was not showing as a passed run would skip the logging job. 
**Notes**:
> ci: Move E2E runtime variables from job level to stage

- hack/aks/Makefile
AKS no longer supports 1.24.x and by proxy Ubuntu 18.04. This default allowed for AKS update schedule to eventually deprecate our versions that we were using. 
Now we will consume the default that AKS provides and retain the version that is scheduled for LTS.
Documentation:
[AKS Release Calendar](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)
[AKS Cluster Configuration for 18.04](https://learn.microsoft.com/en-us/azure/aks/cluster-configuration#os-configuration)
**Notes**:
> ci: Update makefile cluster creation

- .pipelines/cni/pipeline.yaml
Standard_NC24r is scheduled for retirement and was not deploying to AKS clusters. 
**Notes**:
> ci: Update RDMA vmSku

- cns/service/main.go
- cns/wireserver/client.go
- cns/wireserver/client_test.go
Previously, the Wireserver Client used a hardcoded IP, which made starting CNS locally impossible. This is because it attempted to make requests to a Wireserver that wasn't there. There is already a configuration for a WireserverIP, with the intention that that be used to redirect those requests to a mock server for local testing.
This makes the host to which those Wireserver requests are directed configurable so that this configuration is respected by the Wireserver client.
No configuration changes are necessary to end users since no configuration has changed.
To use this locally, any mocks that are in use will need to add an endpoint responding to `/machine/plugins?comp=nmagent&getinterfaceinfov1`  responding with XML in the form:
```xml
<Result>
<Interfaces MacAddress="{{mac}}" …
```
> Fix missing Wireserver IP configuration in Wireserver Client

- cns/NetworkContainerContract.go
- cns/NetworkContainerContract_test.go
- cns/networkcontainers/networkcontainers.go
- cns/networkcontainers/networkcontainers_linux.go
- cns/networkcontainers/networkcontainers_windows.go
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/util.go
Validate that the input requests are for valid NCIDs, otherwise don't attempt to process them.
**Notes**:
> fix: validate that NCIDs are well-formed GUIDs

- cns/NetworkContainerContract.go
- cns/NetworkContainerContract_test.go
- cns/networkcontainers/networkcontainers.go
- cns/networkcontainers/networkcontainers_linux.go
- cns/networkcontainers/networkcontainers_windows.go
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/util.go
fix: validate that NCIDs are well-formed GUIDs
backport of #2359
**Notes**:
> fix: validate that NCIDs are well-formed GUIDs (#2359)

- cni/ipam/plugin/main.go
- cni/ipam/pluginv6/main.go
- cni/network/network.go
- cni/network/plugin/main.go
This PR is to fix log rotation issue that is crashed after windows nodes are restarted.
**Notes**:
> fix zap logger rotation issues

- cni/network/network.go
cni should not invoke cns to release ips for muiltitenancy
**Notes**:
> fix: cni should not invoke cns to release ips for muiltitenancy

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Replaces the #2362 fix with a permanent solution that checks the current Cilium agent version and matches it with a supported Cilium CLI version. https://github.com/cilium/cilium-cli#releases
**Notes**:
> fix: Match Cilium CLI to Cilium Agent

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Update to Cilium CLI brought in tests that we do not functionally need or use.
**Notes**:
> ci: Skip cilium encryption tests

- network/endpoint_snatroute_linux.go
- network/networkutils/networkutils_linux.go
- network/transparent_vlan_endpointclient_linux.go
- network/transparent_vlan_endpointclient_linux_test.go
In the transparent vlan endpoint client add endpoint path, detecting the vnet network namespace would previously assume the vlan interface was already inside the namespace. However, this was not always the case (the vlan interface may not exist or may be in the vm namespace). The fix removes any stray vlan interface pertaining to the container in the vm if it exists and also deletes the network namespace if it does not have a valid vlan interface. Then, the code can proceed as though the vnet namespace never existed. Deleting the vnet namespace will not cause existing endpoints to become inaccessible because they must have errored (and been cleaned up) previously to enter this state. 
Additionally, we also explicitly confirm the vlan interface as well as the vnet …
> fix: wait for vnet ns to create and ensure veths are inside namespace instead of assuming

- cni/network/invoker.go
- cni/network/invoker_azure.go
- cni/network/invoker_azure_test.go
- cni/network/invoker_cns.go
- cni/network/invoker_cns_test.go
- cni/network/invoker_mock.go
- cni/network/multitenancy.go
- cni/network/multitenancy_mock.go
- cni/network/multitenancy_test.go
- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_linux_test.go
- cni/network/network_test.go
- cni/network/network_windows.go
- cni/network/network_windows_test.go
- network/endpoint.go
- network/secondary_endpoint_client_linux.go
removing cniTypesCurr.Result dependency in InterfaceInfo
adding scope link for swiftv2 gateway route
**Notes**:
> refactor: remove cniTypesCurr.Result dependency in InterfaceInfo

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/dependabot.yaml
- .github/workflows/crdgen.yaml
- .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
- .github/workflows/cyclonus-netpol-test.yaml
- .github/workflows/golangci.yaml
- azure-ipam/go.mod
- build/tools/go.mod
- cns/linux.Dockerfile
- cns/windows.Dockerfile
- dropgz/build/cniTest_linux.Dockerfile
- dropgz/build/cniTest_windows.Dockerfile
- dropgz/build/linux.Dockerfile
- dropgz/build/windows.Dockerfile
- dropgz/go.mod
- go.mod
- hack/toolbox/Dockerfile.windows
- hack/toolbox/server/Dockerfile.heavy
- hack/toolbox/server/Dockerfile.lite
- npm/linux.Dockerfile
- npm/windows.Dockerfile
- tools/acncli/Dockerfile
- zapai/go.mod
**Notes**:
closes #2243 with unforked branch
> chore: update to go1.21

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
Bypass the cilium connectivity for metric check until the issue https://github.com/cilium/cilium/issues/29213 is resolved in nightly pipeline.
**Notes**:
> ci: bypass metric check for cilium nightly

- .pipelines/cni/cilium/nightly-release-test.yml
Adds:
- commit ID parameter to cilium git checkout. Allowing us to specify the nightly version of cilium we want to test
- extract cluster deletion into its own stage to enable using the pipeline for exclusively cilium cluster creation
**Notes**:
> ci: Improve Cilium nightly pipeline

- .pipelines/pipeline.yaml
- hack/aks/Makefile
- hack/aks/README.md
Added the Vnet Scale Integration Test to the E2E Pipeline and set it up with Kubernetes version 1.28 as the feature is only supported with CNS 1.5x and above which are correlated versions.
N/A
**Notes**:
> ci: Adding the Vnet Scale Integration Tests to the E2E pipeline 

- .pipelines/cni/pipeline.yaml
Follow on from #2372, CNI Load Test pipeline now automatically runs when using these tags:
- dropgz/*
- azure-ipam/*   
- v*
**Notes**:
> ci: CNI Load Test pipeline trigger

- network/network_linux.go
- network/networkutils/networkutils_linux.go
- network/transparent_vlan_endpointclient_linux.go
Pods should not be able to communicate with the wireserver on port 80.
See above.
**Notes**:
- wanted to create a unit test for the iptables command failing but there is no mock interface or way of injecting a mock "iptables" dependency.
- considered placing the code for the vm iptable rule in transparent vlan endpoint client, but this iptable rule only needs to be run once.
- wanted to match the capitalization convention of enabling ipv4 forwarding, but the linter (only now) is giving me warnings about capitalization (not sure why it didn't warn me about the capitalization before).
> fix: block wireserver port 80 traffic in multitenancy

- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
Changed allow all policy for ingress and egress for npm to allow all even with other rules in the network policy and added new test cases to confirm the changes work. 
**Reason for Change**: This change is in alignment with functionality of other network policy tools such as Calico.
**Issue Fixed**: https://portal.microsofticm.com/imp/v3/incidents/incident/442655848/summary
> fix: NPM Changed Allow All Policy for Ingress and Egress

- network/network_linux.go
Ipv6 traffic from within the pod should not be able to reach eth0 on the vm from eth1 in the container. To enforce this, we disable ipv6 on all interfaces in the vm namespace. The vnet namespace has ipv6 forwarding disabled by default so no modification is required on that datapath.
See above.
**Notes**:
- Network utils failure is already tested when we test "enable ipv4 forwarding"
> fix: disable ipv6 on transparent vlan mode network create

- Makefile
- cni/linux.Dockerfile
- cni/network/common.go
- cni/network/network.go
- cni/network/plugin/main.go
- cni/network/stateless/main.go
- cni/windows.Dockerfile
- cnm/network/network.go
- cns/NetworkContainerContract.go
- cns/api.go
- cns/client/client.go
- cns/client/client_test.go
- cns/restserver/ipam.go
- cns/restserver/restserver.go
- cns/service/main.go
- common/plugin.go
- network/endpoint.go
- network/manager.go
- network/manager_mock.go
- telemetry/telemetrybuffer.go
This PR includes all changes related to Stateless CNI in which CNS will manage and maintain the endpoint states.
- There are changes related to CNS to add two new APIs with respect of endpoint state management.
GetEndpoint() is used to return the state of a given endpointId. UpdateEndpoint() is used to update the HNSId and VethName field within the endpoint state.
- The other changes are related to CNI and network package so the ADD/Del calls can be done without the use of statefile on Store package and instead use CNS and aformenetioned APIs.
**Notes**:
[Stateless Azure cni Design Doc- P1.docx](https://github.com/Azure/azure-container-networking/files/13620367/Stateless.Azure.cni.Design.Doc-.P1.docx)
> feat: Dev stateless cni

- cns/healthserver/server.go
- cns/service/main.go
adds a readyz handler to signal CNS readiness, and rearranges the healthz/metrics handlers for consistency
**Notes**:
> feat: enable readyz/healthz endpoints

- cns/service/main.go
App Insights logging should be initialized as early as possible in order to send important CNS start up information to Kusto
Same as #2433 but from main repo branch instead of fork
> CNS - Initialize AI logging as early as possible

- .pipelines/pipeline.yaml
Adds in a cluster delete step for vnetscale e2e and renames the cluster to be under 14 characters to prevent AKS cluster name overflow of 80 characters.
**Notes**:
> ci: Add vnetscale cluster delete

- .github/workflows/stale.yaml
lowers threshold for stale to 2 weeks
lowers threshold for close to 1 week
deletes branches for closed stale PRs
**Notes**:
> update stale workflow

- test/integration/manifests/cns/daemonset-windows.yaml
- test/integration/manifests/cnsconfig/azurecnidualstackoverlaylinuxconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnidualstackoverlaywindowsconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnioverlaylinuxconfigmap.yaml
- test/internal/kubernetes/utils_create.go
Updates the windows CNS daemonset to include the async delete path `/var/run/azure-vnet` in its volume mounts. Without the mount, windows CNS would OOM even if `EnableAsyncPodDelete: false` is read from the configmap. 
Add the appropriate async delete fields to CNS configmaps
**Notes**:
> fix: add windows async delete mounts

- .github/workflows/pipeline.yaml
Adds a workflow check to ensure that merge queues get a pipeline run assigned to them if the CI trigger fails. 
**Notes**:
> ci: Add workflow check for Merge Queue pipeline start on Azure Pipeline 

- .github/workflows/pipeline.yaml
fixes #2460 double queuing of pipeline runs due to agent provisioning time and missing the `notStarted` status in conditional. 
**Notes**:
> fix: check for notStarted

- .pipelines/cni/cilium/nightly-release-test.yml
Adding timestamp for the nightly cilium pipeline.\
**Notes**:
> ci: add date to cilium nightly cluster name

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Adds k8s conformance testing to cilium E2E
**Notes**:
> ci: Add k8s conformance tests to Cilium CI/CD

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Cilium E2E would run if `CONTROL_OS == windows`. Currently Cilium does not support windows and should not run in windows exclusive CNI Release Test Runs.
**Notes**:
> ci: constrain cilium to linux on Release Test Pipeline

- .pipelines/npm/npm-cni-integration-test.yaml
Window NPM testing takes an increased amount of time to complete then linux due to custom changes upstream. https://github.com/kubernetes/kubernetes/compare/master...huntergregory:kubernetes:sleep-before-probing
Fixed taint being left on windows nodes if job timeout occurs.
**Notes**:
> ci: Improve CNI|NPM integration test

- Makefile
`make test-load` does not provide enough context on which tests are being ran when called. 
**Notes**:
> ci: verbose output for make test-load 

- test/integration/load/load_test.go
- test/internal/kubernetes/utils.go
- test/internal/kubernetes/utils_get.go
`TestValidateState()` would allow the test to proceed even if there were no pods scheduled on the cluster causing unnecessary failures within `make test-load` calls. 
**Notes**:
> ci: Improve TestValidateState calls from load package

- test/integration/load/load_test.go
Set a standard time for `TestLoad()` per iteration for each OS type. Setting arbitrary to a default 30 limited the amount of iterations and did not take into account the performance differences between OS.
**Notes**:
> ci: add OS scale timeout

- .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
Windows byocni clusters have kubeproxy turned off by default. Ensuring that kubeproxy is restarted before k8s conformance testing occurs ensures that edge cases do not impact windows testing.  
**Notes**:
> ci: add kubeproxy restart before windows k8s conformance testing

- network/network_linux.go
Earlier command was not setting DNS list but instead it was resolving the IP causing failures in CNI ADD, new change will set the DNS specifically 
**Notes**:
> fix: joining multiple dns server lists

- hack/toolbox/server/Dockerfile.lite
Was getting this:
```
root[toolbox](master) docker build -t acnpublic.azurecr.io/toolbox-lite:v3 -f server/Dockerfile.lite --no-cache .
[+] Building 27.6s (7/8)                                                                                                                                                                                                                                                                                                                                                                                       docker:default
=> [internal] load build definition from Dockerfile.lite …
```
> fix: fixing toolbox-lite dockerfile

- test/e2e/Makefile
- test/e2e/README.md
- test/e2e/framework/types/job.go
- test/e2e/framework/types/jobvalues.go
- test/e2e/framework/types/runner.go
- test/e2e/framework/types/step.go
- test/e2e/framework/types/step_sleep.go
- Steps are reusable
- Steps parameters are saved to the context of the job
- Once written to the job context, the values are immutable
- Cluster resources used in code should be able to be generated to yaml for easy manual repro
- Avoid shell/ps calls wherever possible and use go libraries for typed parameters (avoid capturing error codes/stderr/stdout)
**Notes**:
> ci: E2E Framework [Core types] [1/6]

- cns/imds/client.go
- cns/imds/client_test.go
- cns/imds/testdata/computeMetadata.json
Adds an IMDS client to CNS so it can query IMDS to learn its VM Unique ID
**Notes**:
I double checked the IMDS document and there is nothing I think is sensitive in there, but it would be good for someone else to check it.
> feat: add imds client

- .pipelines/pipeline.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- test/integration/manifests/cilium/v1.14.4/cilium-agent/templates/daemonset.tpl
- test/integration/manifests/cilium/v1.14.4/cilium-operator/templates/deployment.tpl
> Enable Hubble in PR pipeline with additional stage

- test/integration/datapath/datapath_windows_test.go
- test/internal/kubernetes/utils.go
- test/validate/linux_validate.go
- test/validate/utils.go
- test/validate/validate.go
- test/validate/windows_validate.go
- Adds windows CNIv2 state validation
- Moves `cnsCacheStateFileIps()` to `validate.go` as it is OS agnostic
- Adds in reporting for leaked ips that exist on state files when `compareIPs()` fails due to size difference between actual IPs on the cluster and what exists in the state file. Old functionality reported an entire map of IPs from both current IPs and state file IPs. 
- Adds in reporting when `ExecCmdPod()` has a 0 byte response
- Fixes `validateRestartNetwork()` to work in hybrid clusters and only execute on linux nodes
- Moves `RestartKubeProxyService()` to internal `kubernetes` package as it is a wrapper function for `ExecCmdPod()` and does not validate anything
**Notes**:
> ci: Improve Validate package

- cns/api.go
- cns/configuration/configuration.go
- cns/fakes/cnsfake.go
- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
- cns/ipampool/v2/adapter.go
- cns/ipampool/v2/math_test.go
- cns/ipampool/v2/monitor.go
- cns/ipampool/v2/monitor_test.go
- cns/kubecontroller/pod/reconciler.go
- cns/restserver/ipam.go
- cns/service/main.go
- go.mod
- test/integration/manifests/cnsconfig/swiftconfigmap.yaml
v2 IPAM Pool Monitor introduces idempotent scaling math, migrates to an event-driven instead of polling architecture, and leverages the Pod watcher for IP demand instead of using the "free IPs in the pool" to trigger scaling.
Notably this change improves pool scaling performance from O(n) to O(1).
**Notes**: not to be confused with SwiftV2, this is applicable to all dynamic Pod IP Swift scenarios
Design docs for reference: https://github.com/Azure/azure-container-networking/pull/2013
> feat: v2 swift ipampool 

- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
Replacing `make test-integration` with `make test-load` to unify the testing being done on CNIv2 E2E. In doing this goldpinger test are being removed from the PR pipeline with the goal of using them within the CNI Release Test Pipeline.
**Notes**:
> ci: Replace make test-intergration within ACN PR pipeline

- .github/workflows/pipeline.yaml
Output of `az pipeline` commands without the use of `--query-order QueueTimeDesc` was pulling old information on merge queue branches and missing recent runs. This meant that any new runs that were added to the merge queue without the merge commit sha changing were showing up as `completed` within the [ github action ](https://github.com/Azure/azure-container-networking/actions/runs/7788304422/job/21237437223#step:4:77).
Also changed the sleep for the automatically queued runs to be 5 seconds **AND** moved it to be before the checks to ensure that an automated queued run does not get skipped and then manually triggered. 
**Notes**:
For the merge commit sha to change you need:
- a change to master
- merge commits in front of you in …
> fix: az pipeline output within Merqe Queue Check

- cni/azure-windows-multitenancy.conflist
Traffic from the pod to the wireserver on port 80 should not leave the VM.
See above.
**Notes**:
Tested Windows Container on Windows 2022. After rule is added, wgets from the pod to websites such as google.com are still seen leaving the pod destined towards the 12:34... MAC. After the rule is added, traffic is still detected when pinging other pods (confirming the rule does not block pod-pod traffic). Tested routing wireserver requests to the eth0 and apipa eth inside the pod and confirmed that for hyper-v isolation containers, the vfp filter counter increases when requests to the wireserver are made (no traffic on the node is detected going to the wireserver from the pod either). Without the rule, traffic is detected on the node …
> fix: block pod to wireserver port 80 traffic on windows multitenancy

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/pipeline.yaml
- test/integration/manifests/cilium/cilium-config-hubble.yaml
This adds a step in the cilium load test with Hubble enabled. Hubble works with clilium v1.14.4. So necessary changes have been made to accommodate that. 
**Notes**:
> Cilium Load Test with Hubble Enabled.

- cns/imds/client.go
- cns/imds/client_test.go
IMDS client was incorrectly building the URL for the compute json doc by adding the query params into the url path by urlencoding them instead of making them query params. Also, there was no default retry attempts in the client, causing it to retry forever. Instead we'll set the default to three.
**Notes**:
> fix: build imds compute url correctly and give a default retryAttempts

- test/e2e/framework/kubernetes/create-agnhost-statefulset.go
- test/e2e/framework/kubernetes/create-resource.go
- test/e2e/framework/kubernetes/delete-resource.go
- test/e2e/framework/kubernetes/port-forward.go
- test/e2e/framework/types/background_test.go
- test/e2e/framework/types/job.go
- test/e2e/framework/types/jobvalues.go
- test/e2e/framework/types/scenarios_test.go
- test/e2e/scenarios/hubble/azuremonitor/scenario.go
- test/e2e/scenarios/hubble/drop/scenario.go
- test/e2e/scenarios/hubble/flow/scenario.go
Parameter injection for scenarios are now scoped to the scenario, and can inherit from top level job, but don't impede parameters for other subsequent scenarios
See: 
test/e2e/framework/types/scenarios_test.go
in this pr for usage
**Notes**:
> ci: scope scenario parameters instead of whole job

- crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
- crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
PodName field in MTPNC CRD is not used. Make the field optional as a first step. Once the references to the filed are moved from the underlay, remove the field from the CRD in a subsequent PR.
> [refactor] make podname optional

- .pipelines/pipeline.yaml
- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
Replaces kubetest2 to run k8s conformances tests with k8se2e job templates that use exclusively ginkgo. 
**Notes**:
Needs to be backported to support future CI runs
> ci: Replace k8s conformance tests within aks-swift CI

- .github/workflows/pipeline.yaml
pip and keyring have long standing issues that result in flaky logins with `az devops login` 
Moving to login via PAT env var avoids using the above and is a[ 1 of 3 suggested ways to login. ](https://learn.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows)
**Notes**:
> fix: no longer use pip and keyring for az devops login

- .pipelines/cni/singletenancy/cniv1-template.yaml
- .pipelines/singletenancy/aks/e2e-step-template.yaml
- .pipelines/templates/create-cluster.yaml
- hack/aks/Makefile
- test/integration/manifests/cni/cni-installer-v1-windows.yaml
- test/integration/manifests/cns/daemonset-windows.yaml
the 1.5 release train (current master branch) is released to AKS with k8s version 1.28, and should be tested on 1.28. 
**Notes**:
without this version flag, we will currently get an AKS cluster with k8s 1.27, and we used to get 1.26. this should have been set explicitly as soon as we started making release trains to align with the k8s versions.
> fix: test v1.5 train on k8s 1.28

- Makefile
The transparent-vlan on windows and cnm scenarios are not supported and binaries for these scenarios should not be built when making all binaries.
**Notes**:
Specifically, running make all-binaries or make all-binaries-platforms will not generate these binaries
> fix: remove unsupported targets when building all binaries

- cns/configuration/cns_config.json
- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/configuration/testdata/good.json
- cns/restserver/homeazmonitor.go
- cns/service/main.go
Remove EnableAZR config flag from CNS, the config flag is unnecessary.
**Notes**:
> Remove azr enabled from cns

- network/manager.go
In windows, it is possible to successfully create an HNS endpoint and then subsequently fail to write to the CNI statefile. While the CNI call fails, the HNS endpoint is never deleted, causing retries to fail because the HNS endpoint has already been created. As it is not possible to retrieve the existing endpoint on a retried ADD call, we instead opt to delete the HNS endpoint if saving the CNI state fails.
See above.
**Notes**:
The code change affects both the windows and linux scenarios (if saving fails, deleteEndpoint will call the platform specific version for deletion of the endpoint). On windows, tested triggering a save failure and then examining HNS endpoints-- the endpoint is cleaned up which is confirmed in the logs. …
> fix: delete endpoint on cni state save failure

- npm/azure-npm.yaml
Addresses NPM Linux vulnerabilities from security scan by customer.
- Do not use privileged containers
- set securityContext.privileged=false
- Added NET_ADMIN capabilities securityContext.capabilities.add=- NET_ADMIN as netadmin profile is able to view/modify iptables rules without privilege
- Mount container's root filesystem as read only
- set securityContext.readOnlyRootFilesystem=true
- Mounted an emptyDir volume on the mount /tmp instead of writing to the root volume as we need to write for app insights telemetry
> chore: [NPM] Updated NPM to Not Use Privileged containers and to Mount Container's Root Filesystem as Read Only

- .pipelines/networkobservability/e2e.yaml
This pipeline is triggering on every commit due to a missing `trigger: none` field. 
**Notes**:
> ci: add trigger:none to ACN Network Observability E2E pipeline

- .pipelines/cni/cilium/cilium-cni-load-test.yaml
- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
- .pipelines/cni/k8s-e2e/k8s-e2e-step-template.yaml
- .pipelines/cni/load-test-templates/create-cluster-template.yaml
- .pipelines/cni/load-test-templates/pod-deployment-template.yaml
- .pipelines/cni/load-test-templates/restart-node-template.yaml
- .pipelines/cni/load-test-templates/validate-state-template.yaml
- .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
- .pipelines/pipeline.yaml
- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/singletenancy/aks/e2e-step-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/submodules-pipeline.yaml
- .pipelines/templates/create-cluster.yaml
- .pipelines/templates/delete-cluster.yaml
- hack/aks/Makefile
- hack/aks/README.md
- test/internal/k8sutils/utils.go
These CI changes impact all uses of AZP. Needed to be backported to ensure that v1.4 runs are smooth.
Update include:
- Removal of kubetest2 in favor of purely ginkgo
- Moving from ACN Test Sub to Build Validation 
- Using Kubectl installer task instead of manually installing
**Notes**:
> ci: Backport CI dependency changes

- test/internal/kubernetes/utils.go
`MustRestartDaemonset()` did not have safeguards to ensure that `WaitForPodDaemonset()` could capture a restart. This was due to the fact that we need not ensure that a restart had actually occurred within `MustRestartDaemonset()` just that the k8sAPI request was sent and received without errors. The safeguard that was introduced is a short lived check for generation update. This is normally the following response after 200-ing the update request. 
**Notes**:
> ci: Add safeguards to prevent race condition resulting from MustRestartDaemonset()

- cns/client/client_test.go
- cns/cmd/cli/cli.go
- cns/restserver/api_test.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
Removes the IPAM Pool Monitor reference from the HTTPRestService, debug API, and tests. 
It is not a functional requirement and does not get initialized anymore since https://github.com/Azure/azure-container-networking/pull/2422.
**Notes**:
> fix: remove pool monitor from debug api response

- Makefile
* Remove cnm and windows transparent vlan targets when building all binaries
* Remove azure ipam from transparent vlan build
**Notes**:
make all-binaries-platforms succeeds
> fix: backport remove unsupported artifacts

- .pipelines/cni/lsg/kernel-upgrade-template.yaml
- .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
- .pipelines/cni/lsg/pipeline.yaml
- test/internal/kubernetes/utils_create.go
Adding cilium scenario for additional coverage.
Changing from parameter injection when triggering pipeline to variable injection. 
**Notes**:
> ci: Add Cilium to CNI | LSG Integration Pipeline

- test/integration/manifests/cilium/cilium-config-hubble.yaml
- test/integration/manifests/cilium/cilium-nightly-config.yaml
Update the cilium nightly config based on the changes on the master branch. Removal support for `kube-proxy-replacement: strict` : https://github.com/cilium/cilium/blob/main/Documentation/operations/upgrade.rst?plain=1#L448
**Notes**:
> chore: update the cilium nightly config

- iptables/iptables.go
This PR fixes an issue when iptable list cmd delays if reverse dns lookup fails. Adding option `-n` prevents iptable to do reverse dns lookup for ip addresses listed in that chain
**Notes**:
> fix: Prevent iptable list cmd to do reverse dns lookup

- iptables/iptables.go
cherry pick from commit id b8f6db627ae7c80b933226bd8cf3bc3dd199eb86
Cherry pick this PR https://github.com/Azure/azure-container-networking/pull/2682
**Notes**:
> fix: Added -n option in iptables list cmd to prevent reverse dns lookup

- .pipelines/pipeline.yaml
Removing path filter for CI triggered pipeline runs as it exclusively runs for merge queue and tags. This path filter was negatively interacting with the merge queue which required a hack to ensure runs were being triggered. See https://github.com/Azure/azure-container-networking/pull/2460
**Notes**:
> ci: Remove path filter from PR pipeline CI triggers

- .pipelines/pipeline.yaml
We no longer utilize this storage account for AKS engine or Jenkins. 
**Notes**:
> ci: Remove AKS Engine storage account usage

- .pipelines/cni/pipeline.yaml
- .pipelines/npm/npm-cni-integration-test.yaml
- .pipelines/npm/npm-conformance-tests.yaml
Updates test suite being used by NPM to latest to reduce overhead of maintaining forks.
**Notes**:
> ci: Updating k8s test suite for NPM to latest

- Makefile
- cns/api.go
- cns/client/client.go
- cns/client/client_test.go
- cns/restserver/ipam.go
- cns/restserver/restserver.go
- network/endpoint.go
- network/manager.go
The initial Stateless CNI schema needs to change to account for Swift 2.0 scenario 
**Notes**:
> feat: Modifying stateless CNI state to account for swift 2.0 changes.

- telemetry/telemetrybuffer.go
- telemetry/telemetrybuffer_test.go
Prevents leaking of sockets when azure-vnet-telemetry errors and fails to unmarshal mentioned in #2703 (this pr does not fix the unmarshaling error itself)
**Notes**:
The unit test uses time.sleep to ensure the connection populates in the server, and we will be rewriting these tests later anyway with stateless cni.
> fix: close connection on any return from azure-vnet-telemetry

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/templates/cilium-cli.yaml
Creates a template for Cilium CLI install to ensure that all CLI installs are the same.
Provides Cilium 1.14.X a supported CLI version of v0.15.22.
**Notes**:
Changes in Cilium CLI github prompted this change. https://github.com/cilium/cilium-cli?tab=readme-ov-file#releases.
Broken cilium connectivity test when going from v0.16.6 -> v0.16.7 when using Cilium v1.14.9
> ci: create template for cilium cli install

- test/internal/kubernetes/utils.go
Execution cmd fails sometimes due to network issue. Adding a retry with some delay to make sure it gets executed.
Note: Tried with short delay of 250ms but still had the issue. Currently reusing the existing variable for `RetryDelay`
**Notes**:
> ci: adding a retry login on exec cmd on failure

- cns/windows.Dockerfile
- npm/windows.Dockerfile
Latest Windows LTSC2019 image is borked. https://github.com/microsoft/Windows-Containers/issues/493
Pins to previous monthly release, and pins the LTSC2022 image to current working one for good measure.
**Notes**:
> fix: pin Windows images

- crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
- crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
Adds a property to `InterfaceInfo` to tell CNI whether the NIC should be programmed with accelnet enabled or not
**Notes**:
> feat: plumb accelnet bool through interfaceinfo

- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
Skip no-unexpected-packet-drops test cases for ACN PR cilium dualstack e2e -- case is passing in other cilium dualstack scenarios for release pipeline + locally. There are some known issues upstream with this connectivity test case failing. 
**Notes**:
> ci: skip no-unexpected-packet-drops for cilium dualstack e2e

- test/integration/manifests/cilium/v1.13/cilium-operator/templates/deployment.yaml
- test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.yaml
Update Cilium 1.13 and 1.14 templates to include security context for reduced permissions.
Best practice.
**Notes**:
> chore: update cilium-operator security context

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
New test case in latest cilium cil checks for log errors and is failing nightly pipeline. Found that the error reported in the cilium-agent logs recovers on its own, but still causes a failure in this test case. Skipping this check to unblock the pipeline, and will follow up with cilium-cli on this.
```
time=2024-05-30T22:07:56Z level=info msg="Devices changed" module=agent.datapath.devices-controller devices=[]
time="2024-05-30T22:07:57Z" level=info msg="Node addresses updated" device=eth0 node-addresses= subsys=node-address
**time="2024-05-30T22:07:57Z" level=error msg="Unable to write node config header" error="failed to write node configuration file at /var/run/cilium/state/globals/node_config.h: IPv4 direct routing device not found" subsys=datapath-loader** …
```
> ci: cilium-nightly skip test check-log-errors

- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
Nightly pipeline uses a released version of azure-ipam, which does not include recent changes with async delete. Will be releasing a new azure-ipam, but until that is ready we will skip this test 
**Notes**:
> ci: skip async delete for nightly pipeline

- .pipelines/mdnc/azure-cns-cni-1.5.28.yaml
Need an update to CNI version to resolve issue with newer kernels
**Notes**:
> feat: New yaml file for updated CNI and CNS version

- Makefile
exclude ipv6-hp-bpf tags from ACN_VERSION to fix pipeline image tagging 
**Notes**:
> ci: makefile ACN_VERSION exclusions

- Makefile
Editing makefile to add stateless CNI binary to the archives
**Notes**:
> fix: Editing makefile to add stateless CNI binary to the archives

- dropgz/build/linux.Dockerfile
- dropgz/build/windows.Dockerfile
bumping dropGZ to 1.6.0 and adding stateless CNI to Windows
**Notes**:
> feat: bumping dropGZ to 1.6.0 and adding stateless CNI to Windows

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- cns/linux.Dockerfile
- hack/scripts/async-delete-test.sh
- test/integration/manifests/cns/daemonset-linux.yaml
- test/integration/swiftv2/swiftv2_test.go
- test/internal/datapath/datapath_win.go
- test/internal/kubernetes/utils.go
- test/internal/kubernetes/utils_create.go
- test/validate/linux_validate.go
- test/validate/validate.go
- test/validate/windows_validate.go
CNS was moved from `scratch` to `mariner` in [this change](https://github.com/Azure/azure-container-networking/pull/1499/files#diff-505c5d2f3910d5791524e206cc08abca53a8eefac1094baf678cd5d2b5dbf9e0) where we migrated responsibility to CNS to write some iptables rules.
This change moves CNS to the `mariner distroless` base image and adds `iptables`, in an effort to reduce the image size while maintaining the required iptables functionality.
> fix: move CNS to distroless-iptables base image

- cns/service.go
- small refactor to remove redundant check for TLSSettings.TLSPort in CNS
**Notes**:
> [CNS] refactor: remove redundant check for TLSSettings.TLSPort

- test/integration/manifests/cilium/cilium-nightly-config.yaml
Updating `cilium-nightly-config.yaml` to be single point of truth of latest relevant cilium config values. 
https://github.com/cilium/cilium/blob/main/Documentation/operations/upgrade.rst#removed-options
> Deprecated Options
> The unused flag sidecar-istio-proxy-image has been removed.
> The enable-remote-node-identity flag has been deprecated and will be removed in Cilium 1.16. This flag is needed for various features to work correctly and has been enabled by default since Cilium 1.7. There is no benefit in disabling it anymore.
**Notes**:
Ensure that these are removed from appropriate cilium-config(s) when applicable. 
- v1.16 remove `sidecar-istio-proxy-image`
- v1.15 remove `enable-remote-node-identity`
> ci: Remove depreciated values from Cilium nightly config

- .pipelines/pipeline.yaml
- Makefile
- cns/Dockerfile
- cns/middlewares/k8sSwiftV2_windows.go
- cns/middlewares/k8sSwiftV2_windows_test.go
Add default routes k8s windows
In Swiftv2 Windows scenario, we need to set default route on delegatedNIC interface instead of infraNIC interface, so we need to set skpDefaultRoutes to true for infraNIC interface
**Notes**:
> Add default routes k8s windows

- telemetry/telemetrybuffer.go
- telemetry/telemetrybuffer_test.go
If the bufio reader is created in the for loop that handles reads we get unmarshaling errors. Creating a single bufio reader outside of the for loop once the connection is accepted and then repeatedly looping over that single reader fixes this issue.
See above
**Notes**:
> fix: move bufio reader creation out of for loop to fix telemetry unmarshal errors

- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/service/main.go
If an NNC is marked for deletion, CNS should not use it to reinitialize state or ingest any events for it.
**Notes**:
> fix: CNS should ignore NNCs that are being deleted

- cns/NetworkContainerContract.go
Modified the value of DelegatedVMNIC to resolve compatibility issue
**Notes**:
> fix: Modified the value of DelegatedVMNIC to resolve compatibility issue in Version 1.5

- telemetry/telemetrybuffer.go
- telemetry/telemetrybuffer_test.go
* move bufio reader creation out of for loop
if the bufio reader is created in the for loop we get unmarshaling errors
* fix linter issue
* add fixed ut
* fix existing unit test flake due to closing pipe on error
a previous fix ensured the socket closed on error, but this caused an existing ut to nondeterministically fail without the previous fix, the socket wouldn't have been closed on error
* make read inline
Backport telemetry fix to 1.5
Previously azure-vnet-telemetry would output unmarshal errors due to improper handling of socket reads
**Notes**:
> backport: fix: move bufio reader creation out of for loop to fix telemetry unmarshal errors (#2789)

- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/containers/container-template.yaml
- .pipelines/containers/manifest-template.yaml
- .pipelines/pipeline.yaml
- Makefile
- cns/windows.Dockerfile
- npm/windows.Dockerfile
Remove old usage of Azure Container Networking - ACN Public Registry from `release/v1.4` branch
Pins Windows 2019 Dockerfiles for CNS and NPM
Removes building NPM for ws2019
**Notes**:
> ci: [backport] Image related CI/CD

- processlock/processlock.go
Address race issue in 1.6.x
Now it should not matter if cni or k8s makes the directory since they should both have 0755 permissions.
#2818 
**Notes**:
Created nodesubnet/legacy cluster (no cns), checked var/run/azure-vnet directory and it has 0644 permissions.
Replaced cni version with this new one and restarted the node. The var/run/azure-vnet directory now has 0755 permissions after the reboot.
> fix: update azure-vnet directory permissions

- network/endpoint_windows.go
- network/manager.go
Previously did not add hns network id to endpoint struct (only added to endpointInfo), and so when pushing data to cns, we did not have an hns network info id for deletion later.
**Notes**:
> fix: add hns network id to endpoint struct for pushing to cns in stateless

- test/integration/manifests/cilium/v1.13/cilium-config/cilium-config.yaml
- test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset-dualstack.yaml
- test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset.yaml
- test/integration/manifests/cilium/v1.14/cilium-config/cilium-config-dualstack.yaml
- test/integration/manifests/cilium/v1.14/cilium-config/cilium-config-hubble.yaml
- test/integration/manifests/cilium/v1.14/cilium-config/cilium-config.yaml
- systemd-netword-overrides init container was removed in charts for cilium 1.14 since this was fixed upstream
- adding new config value `dnsproxy-enable-transparent-mode: "false"` which is present in 1.13 and 1.14
**Notes**:
> ci: align cilium charts with AKS

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/load-test-templates/restart-node-template.yaml
- .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
- .pipelines/cni/pipeline.yaml
- .pipelines/cni/singletenancy/cniv1-template.yaml
- .pipelines/cni/singletenancy/cniv2-template.yaml
Amplifies the ability for CNI Release Test Pipeline to use different regions for our test matrix. 
As this adjusts `restart-node-template.yaml`, its usages across other pipelines have been updated. 
**Notes**:
> ci: Adjust VM usage for CNI Release Test Pipeline

- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/service/main.go
Backport #2798
If an NNC is marked for deletion, CNS should not use it to reinitialize state or ingest any events for it.
**Notes**:
> fix: CNS should ignore NNCs that are being deleted (#2798)

- network/endpoint.go
- network/endpoint_test.go
- network/endpoint_windows_test.go
- network/hnswrapper/hnsv2wrapperfake.go
- network/manager.go
- network/manager_test.go
- network/network.go
- network/network_test.go
- network/network_windows_test.go
Modifies existing uts to confirm the following:
When we create a network, we add the hns network id to the network{} and EndpointInfo{} structs
When we create an endpoint, we add the hns endpoint id to the endpoint{} and EndpointInfo{} structs
When we create an endpoint, we add the hns network id to the endpoint{} struct from the passed in EndpointInfo{} struct
Also validates that `ContainerID` s for a particular ADD call are all the same and are not equal to the empty string and that the endpoint nic type is populated. An error **will now be returned** if the container ids of all endpoint{} structs are not the same, any of the container ids are the empty string, or the nic type field is not populated. This is only checked on add calls. …
> test: add ut for populating network and endpoint hns id in endpoint and endpoint info structs

- .pipelines/pipeline.yaml
Cleaning up:
- dead code
- non functional code
- erroneous cluster delete jobs
- missing cluster delete jobs 
- 
**Notes**:
> ci: Cleanup ACN PR pipeline yaml

- cns/NetworkContainerContract.go
- cns/api.go
- cns/client/client_test.go
- cns/fakes/imdsclientfake.go
- cns/imds/client_test.go
- cns/imds/testdata/invalidComputeMetadata.json
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/restserver/v2/server_test.go
- cns/service/main.go
Adding a new CNS API to retrieve vmuniqueID of the VM where CNS is running. This uses the existing imdsclient in CNS which already has a method to retrieve vmUniqueID.
This API will invoked by DNC for Swift v2 scenario for ACI/standalone to discover VMUniqueID for the node.
**Notes**:
> feat: Add CNS API to retrieve VMUniqueID from IMDS

- cni/network/network.go
- cni/network/network_test.go
- cns/NetworkContainerContract.go
- cns/NetworkContainerContract_test.go
Validates some fields in requests to the cns, and also validates some fields in the cni args and network config. 
**This PR modifies the behavior of CNS:**
- If the primary interface ip is not a valid ip or cidr, an error will now be raised
- Same if the gateway ip address is not an ip address
**This PR modifies the behavior of CNI:**
- The container id, ifname, and bridge name passed into cni must fully consists of zero or more alphanumeric, dots, dashes, parentheses, or underscores. Otherwise, an error will be raised
**Notes**:
Please confirm there are no existing scenarios in cns where we have a primary interface name or gateway ip field that aren't ips.
> test: validate inputs to acn components

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/singletenancy/cniv1-template.yaml
- .pipelines/cni/singletenancy/cniv2-template.yaml
- .pipelines/pipeline.yaml
Image and Manifest generation has begun to take longer and Clusters are left in `NotReady` for longer than 15 minutes after they are successfully created. Resulting node restarts that occur in the middle of E2E.
RCA: After 15 minutes of being left in `NotReady` status nodes will begin a reboot rollout of the entire cluster.
**Notes**:
> ci: Shift E2E cluster creation

- .pipelines/npm/npm-conformance-tests-latest-release.yaml
- .pipelines/npm/npm-conformance-tests.yaml
- .pipelines/npm/npm-scale-test.yaml
Adds triggers for tags and PR(s). 
This will enable Scale Test and NPM Conformance pipelines to be required for PR(s) that impact `npm/*` and all to be ran when merge to master occurs or a tag is created. 
**Notes**:
> ci: Update triggers for NPM pipelines

- go.mod
- go.sum
hcsshim@v0.12.5 requires a winio version that has `winio.NewOpenFile`. So we need to update the winio version. Before we update hcsshim we should check that this winio update does not cause any regressions. 
**Notes**:
Loss of context for the original reasoning for replace( ) in #961 may introduce some bugs.
> ci: Remove winio from replace( )

- test/scale/connectivity/test-connectivity.sh
- test/scale/test-scale.sh
Runs scheduled for master branch have failed since the `/bin/sh` interpreter does not support double bracket syntax:
```
./test-scale.sh: 62: [[: not found
```
Now we explicitly direct these scripts to use `/bin/bash`.
> ci: [NPM] add bash directive to scale scripts

- cni/network/network_windows.go
- cni/network/network_windows_test.go
Currently if a port mapping is specified in windows, if no host ip is specified, an ipv6 port mapping policy would not be created (only an ipv4 one). This pr makes it so that if no host ip is specified, and dualstack/ipv6 is enabled, we will create two policies, one for ipv6 and one for ipv4. If the host ip is specified, we will create only a single policy based on whether the host ip is ipv4 or ipv6.
Summary:
host port defined with host ip ipv4 (with or without ipv6 enabled) --> ipv4 port mapping policy only
host port defined with host ip ipv6 --> ipv6 port mapping policy only
host port defined without host ip (with ipv6 enabled) --> ipv4 and ipv6 port mapping policy created
host port defined without host ip (without ipv6 enabled) --> ipv4 port mapping policy …
> fix: add ipv6 port policy in addition to ipv4 policy if no host ip and ipv6 enabled

- network/network_windows.go
The PR is to not ignore network exist if network type is transparent to avoid creating a second endpoint
**Notes**:
> Return error if hns network exists for transparent network

- cni/network/network_windows.go
- cni/network/network_windows_test.go
* add ipv6 port policy in addition to ipv4 policy if no host ip and ipv6 enabled
* address feedback
Based on #2852
**Notes**:
> backport: fix: add ipv6 port policy in addition to ipv4 policy if no host ip and ipv6 enabled (#2852)

- .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
- .github/workflows/cyclonus-netpol-test.yaml
- .pipelines/npm/npm-conformance-tests-latest-release.yaml
- .pipelines/npm/npm-conformance-tests.yaml
- .pipelines/npm/npm-scale-test.yaml
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
- test/scale/connectivity/test-connectivity.sh
- test/scale/test-scale.sh
Backporting #2841 and pipeline changes for NPM Cyclonus, Conformance, and Scale Test pipelines.
#2840 
**Notes**:
> [backport] fix/ci: Linux NPM race condition editing "except" CIDR and NPM pipeline fixes

- cni/network/network.go
- cni/network/network_test.go
- cns/NetworkContainerContract.go
- cns/NetworkContainerContract_test.go
* add validation for cni args and cns request values
* address feedback
* simplify regex match
**Notes**:
> backport: test: validate inputs to acn components (#2845)

- aitelemetry/telemetrywrapper_test.go
- cns/dockerclient/dockerclient.go
- ebtables/ebtables.go
- iptables/iptables.go
- network/network_linux.go
- network/network_windows.go
- network/networkutils/networkutils_linux.go
- network/snat/snat_linux.go
- network/transparent_endpointclient_linux.go
- network/transparent_vlan_endpointclient_linux.go
- ovsctl/ovsctl.go
- platform/mockexec.go
- platform/osInterface.go
- platform/os_linux.go
- platform/os_linux_test.go
- platform/os_windows.go
- platform/os_windows_test.go
- telemetry/telemetry_windows.go
Using exec.Command with a desired command has better protection against command injection. In the future we should use this method instead of the existing method.
Also fixes a ut in platform/os_windows_test.go
**Notes**:
Existing behavior should not change in any way (except log statement contents). This method is intended to be used in the future whenever we need to run an os/platform command.
> refactor: create safer command execution method

- test/integration/manifests/cns/daemonset-linux.yaml
- test/integration/manifests/cns/daemonset-windows.yaml
Updates CNS daemonset capabilities to ensure that a race condition does not occur when creating the `/var/run/azure-vnet` directory
Contributes to CI/CD to cover #2818
**Notes**:
> ci: Update CNS daemonset capabilities within E2E

- network/network_windows.go
- network/network_windows_test.go
After windows VM bootup, the transparent networks are not deleted;
To cleanup transparent hns networks, set hnsNetwork Flags as non-persistent so that networks will be gone after nodes get rebooted
**Notes**:
> hotfix: set hcnNetwork flag as non-persistent mode

- cni/network/network.go
- cni/network/network_test.go
CNI always returns endpoint names as xxx-eth**0** that cannot identify if this interface is primary or secondary;
To create reasonable endpoint names, we need to pass non-eth0 as secondary interface names
**Examples of endpoints now:**
ID                 : 9fec3b82-8d49-456b-9590-e380d41197a0
Name               : **841bd4b7-eth1**
Version            : 64424509443
AdditionalParams   : @{SwitchId=7F827C62-F4FB-4BE9-8C33-1BF415650187;
SwitchPortId=9FEC3B82-8D49-456B-9590-E380D41197A0;
VmSwitchNicName=7782EA20-E476-54D6-9A48-95E01CCCDA3B--8CCC5ED3-0EFE-4128-AC3D-44B01F85C813}
Resources          : @{AdditionalParams=; AllocationOrder=2; Allocators=System.Object[]; CompartmentOperationTime=0;
Flags=0; Health=; ID=9209FC4F-6861-4CCD-8A0E-06349DE51834; …
> fix: pass right interface name to generate hns endpoint name as expected

- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
Adds test coverage to validate CNI binary install occurs correctly on all scenarios. Additionally, refreshes current E2E to remove duplicate testing, pull out windows nodepool creation, and leverages existing makefile commands for validation testing.
Contributes to CI/CD to cover #2818 
**Notes**:
> ci: Add node restart to cniv2 E2E

- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Fixes cilium cli cilium-test namespace change - https://github.com/cilium/cilium-cli/pull/2680.
Currently impacts CLI 0.16.14+ |  Cilium v1.15+
**Notes**:
> [fix] ci: Update expected cilium connectivity test namespace

- azure-ipam/Dockerfile
- cni/Dockerfile
- cns/Dockerfile
`servercore` has idle overhead of ~230 MB of memory and a base image size ~2 GB, vs `nanoserver`'s idle overhead of ~90 MB of memory and base image size around 250 MB. Given CNS image pull-time impacts node readiness, VHD space constraints, and recent issues and heightened awareness of memory usage on Windows, migrate to the lighter base image 🙂 
**Notes**:
> chore: move cns from servercore to nanoserver

- azure-ipam/windows.Dockerfile
- cni/windows.Dockerfile
- cns/windows.Dockerfile
servercore has idle overhead of ~230 MB of memory and a base image size ~2 GB, vs nanoserver's idle overhead of ~90 MB of memory and base image size around 250 MB. Given CNS image pull-time impacts node readiness, VHD space constraints, and recent issues and heightened awareness of memory usage on Windows, migrate to the lighter base image 🙂
> backport: chore: move cns from servercore to nanoserver (#2454)

- network/ovs_networkclient_linux_test.go
TestCreateBridge is the only test that fails when running locally on dev machine (permission denied), making it difficult to isolate if a ut failure actually ocurred or not. This mode's behavior is unlikely to change so the test is removed/commented.
**Notes**:
> ci: remove ovs create bridge test

- cni/network/invoker.go
- cni/network/invoker_cns_test.go
- cni/network/multitenancy_test.go
- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
- network/endpoint.go
This PR is to fix dualnic options to avoid overwritting vlanMaps
In the windows dualnic multitenancy case, we receive two interface infos from cns and should create two corresponding networks and endpoints. The first and second endpoints created by hns should have vlan id 1 and vlan id 2, respectively. It is CNI's job to parse the cns input and send a request to hns to create the endpoints. 
However, during testing both endpoints have vlan id 2. This is because the ipamAddConfig's `options` field is unintentionally **shared** between each `EndpointInfo` struct. Modifying the vlan id of one options field in an endpoint info struct inadvertently modifies every other endpoint info struct's options. So, the vlan id reflected during endpoint creation is of the last …
> fix: dualnic options to avoid overwritting vlanMaps

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Fix CNI load tests to run k8s dualstack test cases or datapath test cases
**Notes**:
> fix: k8s load test scenario for dualstack vs datapath

- hack/aks/Makefile
Fixes E2E cluster creation for CNIv1 Linux. 
Changes are already contained within #2939 for 1.4 release train. This only needs to be backported to 1.5.
**Notes**:
> fix: Add --kubernetes-version to linux-cniv1-up cluster creation

- .github/workflows/codeql.yaml
- codeql/addipamconfig-to-exec.ql
- codeql/cni-args-to-exec.ql
- codeql/cns-invoker-to-exec.ql
- codeql/codeql-pack.lock.yml
- codeql/decode-to-exec.ql
- codeql/qlpack.yml
Adds codeql queries specific to the acn repo
**Notes**:
> feat: add custom codeql queries

- cni/log/logger_error.go
- cni/log/logger_test.go
- cni/network/invoker_cns.go
- cni/network/network.go
zap.Error inserts an unwanted field verboseError that contains a stack trace when we don't want it
For example, this is one of the log statements when logging error
```
{"level":"info","ts":"2024-08-06T21:56:57.995Z","caller":"network/network.go:381","msg":"ADD command completed for","pid":10680,"component":"cni-net","pod":"ama-metrics-win-node-2plpb","IPs":null,"error":"Failed to get IP address from CNS: http request failed: Post \"
[http://localhost:10090/network/requestipconfigs\":](http://localhost:10090/network/requestipconfigs/%22:)
dial tcp [::1]:10090: connectex: No connection could be made because the target machine actively refused it.","errorVerbose":"Post \"
[http://localhost:10090/network/requestipconfigs\":](http://localhost:10090/network/requestipconfi …
```
> fix: don't print stack trace of error for certain logs to prevent spam

- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/templates/create-cluster.yaml
- hack/aks/Makefile
- test/integration/manifests/cni/cni-installer-v1-windows.yaml
Backports:
- #2253 to unblock pipelines
- #2564 to restrict v1.4 release train to k8s v1.27. Currently was on 1.29.7. Previous release was on 1.28.9.
- Going from .28 to .29 changed how IPs were stored in CNS. This is causing validate pkg to fail and block PRs.
**Notes**:
> [backport] fix: set cluster auto-upgrade and node auto-upgrade in the hackfile #2253 

- cns/middlewares/standaloneSwiftV2.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/util_test.go
This adds unit tests for PR #2634 for Standalone SwiftV2.
**Notes**: 
- This implementation has some assumptions being made with NC programming on NMAgent that will be addressed in a future PR, once NMagent exposes an API to query for NIC programming.
> [CNS] Add unit tests to Standalone SwiftV2 scenario

- cni/network/network.go
- cni/network/network_test.go
This PR is to add UTs to test findMasterInterface()
**Notes**:
> Add UTs to test findMasterInterface

- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
This PR causes NPM to panic/restart if `applyIPSets()` continues to fail, a symptom of non-retriable errors like those in #2963, an issue which is mitigated by an NPM restart. #2480 was another race condition where this logic could have helped (although #2480 was fixed directly in #2841).
Fixes #2963 with NPM restart
**Notes**:
New panic from the first error to the 100th:
```
E0828 00:46:15.242859       1 dataplane.go:431] [DataPlane] [BACKGROUND] failed to add policies. will retry one policy at a time. err: [DataPlane] [ADD-NETPOL] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset …
```
> fix: [NPM] [Linux] panic if applyIPSets continues to fail

- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
Backport #2964 
Fixes #2963 in release/v1.5 branch
> [backport] fix: [NPM] [Linux] panic if applyIPSets continues to fail

- cns/middlewares/k8sSwiftV2.go
This PR is to disable Swiftv2 Linux and Windows for AccelnetNIC support until they support
**Notes**:
> fix: Ignore accelnetEnable flag to disable swiftv2 Linux&&Windows for AccelentNIC

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_test.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/testutils_linux.go
- npm/pkg/dataplane/ipsets/testutils_windows.go
- npm/pkg/dataplane/policies/policy.go
In Linux, apply IPSets before modifying the IPSet cache when adding CIDR NetPols if the previous apply call failed.
Fix #2977
**Notes**:
Followed steps to reproduce #2977 but now there is no issue due to the new step to apply IPSets here:
`dataplane.go:331] [DataPlane] [ApplyDataPlane] [ADD-NETPOL-CIDR-PRECAUTION] starting to apply ipsets`
Full logs:
```
I0829 20:25:12.654104       1 networkPolicyController.go:225] Network Policy default/repro is not found, may be it is deleted
I0829 20:25:12.654134       1 dataplane.go:569] [DataPlane] Remove Policy called for default/repro
I0829 20:25:12.654209       1 chain-management_linux.go:366] Executing iptables command with args [-w 60 -D AZURE-NPM-INGRESS -j AZURE-NPM-INGRESS-1739478793 …
```
> fix: [NPM] [Linux] race when deleting/readding NetPol with CIDR rules

- network/policy/policy_windows.go
- network/policy/policy_windows_test.go
This PR is to add UTs for CNI windows policy
**Notes**:
> Add UTs for CNI Windows Policy

- cns/restserver/api.go
For AZR scenarios, if NMAgent is restarted, it loses state and does not know what VNETs to subscribe to. As it no longer has VNET state, successive put nc or delete nc calls would fail. We, however, always call join VNET before put nc call. This PR adds such a fdlow for delete AZR nc calls as well.
PS: We don't need this flow for regular NCs, as NMAgent there uses NMA swift module to rehydrate VNETs if state is lost.
**Notes**:
> Add join VNET call for every AZR NC unpublish call

- cns/ipampool/metrics/metrics.go
- cns/ipampool/metrics/observer.go
- cns/ipampool/monitor.go
- cns/ipampool/v2/monitor.go
- cns/service/main.go
- crd/clustersubnetstate/client.go
IPAM metrics that were set by the old IPAM PoolMonitor were not set in the v2 monitor. This breaks the AMA workbooks for subnet usage monitoring on AKS 1.30+ where CNS 1.6 with v2 IPAM is deployed.
The metrics were missing because the v2 PoolMonitor does not use most of that source data anymore - it depends only on Pod count and Batch size, not the full IPAM utilization buckets and previous NNC state that the v1 implementation needed to scale up/down.
This fix creates a "metrics observer" which functionally performs what the IPAM v1 monitor used to do WRT the metrics in a portable closed scope. It is injected into the v2 monitor so that the v2 monitor does not need to be polluted with the data pulls that the v1 monitor needed and can still trigger the metrics …
> fix: add legacy IPAM metrics back to IPAMv2

- test/e2e/framework/kubernetes/port-forward.go
- test/integration/datapath/datapath_linux_test.go
- test/integration/k8s_test.go
- test/integration/networkobservability/hubble_test.go
- test/integration/portforward.go
* do not pass testing logger into goroutine to avoid race
* fix port forwarder
Backports #2959 to resolve data races in cni release test pipeline
**Notes**:
> backport: ci: remove logger field from portforwarder to avoid race with goroutine (#2959)

- .gitignore
- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
#2977 actually could happen for any NetPol. Redoing #2978 to handle all NetPols. This fix forces the data plane to successfully apply IPSets before starting to add a policy if the previous RemovePolicy call failed to apply ipsets. This prevents the chance of NPM removing a policy, flushing all policy IPSets, but failing to delete policy IPSets, then NPM adding the policy back thinking that the policy IPSets are in the kernel with all members (when there are actually no members in the IPSets due to the flush).
Fix #2977 completely
**Notes**:
```
I0910 18:32:18.073907       1 dataplane.go:651] [DataPlane] Update Policy called for default/repro
I0910 18:32:18.074560       1 dataplane.go:575] [DataPlane] Remove Policy called for …
```
> fix: [Linux] [NPM] handle #2977 for netpols without cidrs

- cns/restserver/api.go
Reverts Azure/azure-container-networking#2983
> Revert "Add join VNET call for every AZR NC unpublish call"

- .pipelines/pipeline.yaml
- .pipelines/templates/delete-cluster.yaml
Fixes the delete cluster stage by targeting the different subs. Additionally, amplifies the resource group deletion by targeting the correct region based on the env var.
**Notes**:
Needs to be backported to any release train that has multiple regions or subs in its E2E
> [fix] ci: cluster deletion for swiftv2

- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
Currently windows dualstack k8s E2E testing on 1.30.X clusters is blocked by an HNS error with the loopback adapter. It is currently being investigated, but this should not block other components from being in the correct environment. 
This will need to be reverted once HNS has released a fix. 
This PR is to unblock #2924 
**Notes**:
We do not lose any testing coverage here as:
- Service tests are done for holistically checking that everything is functioning as intended
- Dualstack tests are to reconfirm that TCP and UDP connections work pod-pod, pod-node, pod-world. Our go test(s) cover all 3 [primary scenarios but only with ping and IWR.](https://github.com/Azure/azure-container-networking/blob/ba7af1c03436c04cef74f2f6dc66461002c8 …
> ci: Unblock k8s 1.30 | ACN v1.6 testing

- netlink/netlink_test.go
Linux AddRemoveStaticArp is flaky. It creates the static arp with **no** errors, but when we try to delete it, we get a response that the file is not found. This logs as an error but the pipeline retries 3 times, so this typically goes unnoticed. If the purpose of the deletion is to ensure the arp entry is deleted, this message likely indicates the arp entry is no longer present.
Observed behavior is that the arp entry is added to the arp table, but then is automatically and immediately deleted a fraction of a second later. When using an existing link, or a link that has been up for some time (> 1 second), the arp entry sticks around.
Theory as to why this happens:
1) We create a link
2) We add an arp entry to the link immediately after the link is created
3) The …
> ci: add delay after link creation for test add remove static arp

- cns/restserver/api.go
- cns/restserver/api_test.go
For AZR scenarios, if NMAgent is restarted, it loses state and does not know what VNETs to subscribe to. As it no longer has VNET state, successive put nc or delete nc calls would fail. We, however, always call join VNET before put nc call. This PR adds such a flow for delete AZR nc calls as well.
PS: We don't need this flow for regular NCs, as NMAgent there uses NMA swift module to rehydrate VNETs if state is lost.
**Notes**:
> Add join VNET call for every AZR NC unpublish call with fixed UTs

- .pipelines/pipeline.yaml
- hack/aks/Makefile
Main branch is for release 1.6.x, which is locked to k8s 1.30. Updates the default cluster for E2Es and development to 1.30.
**Notes**:
> fix: update default k8s ver to 1.30

- cns/service/main.go
There is an [if-check for `ChannelMode: Direct` in HTTPRemoteRestService to add the `GetVMUniqueID` handler to it's listener that was not being added](https://github.com/Azure/azure-container-networking/blob/251959ac63e361898baa5089f29a548a120fc044/cns/restserver/restserver.go#L279-L281) because the channel mode was not copied from `cnsconfig` like the rest of the channel modes.
**Notes**:
- validated manually in ACI environment
- it doesn't appear to be trivial to add unit test here because it's in `main()`, any thoughts or suggestions?
> fix: HTTPRemoteRestService config missing Direct ChannelMode

- npm/pkg/dataplane/dataplane_windows.go
As we were booting up npm agent on windows, we saw ~4K endpoints on a node with 16 pods, when there should be a 1:1 endpoint to pod ratio.
Changed logic: When booting up the data plane, instead of getting all remote endpoints, we only get local endpoints which will be the endpoints for the pods in the node.
Testing:
Took a node with 11 non-system pods on it.
Ran windows NPM with new image and saw total of 12 endpoints getting reset vs ~4K that were getting reset originally. 
**Notes**:
> fix: [WIN-NPM] HNS Remote Endpoint Fix

- cns/ipampool/metrics/observer.go
- cns/ipampool/v2/monitor.go
- cns/service/main.go
- crd/clustersubnetstate/client.go
The metrics observer added in #2970 fails fast if a source of metrics is unavailable. This prevents legacy metrics from being collected _at all_ in scenarios like (as occurred) the ClusterSubnetState custom resource definition is not installed in the cluster.
In this change, the observer is made resilient to missing data sources or errors in the data collection, and will make a best-effort attempt to record the metrics even in case of partial data availability.
**Notes**:
> fix: make ipamv2 metrics resilient to missing custom resource definitions

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/codeql.yaml
- .github/workflows/crdgen.yaml
- .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
- .github/workflows/cyclonus-netpol-test.yaml
- .github/workflows/golangci.yaml
- azure-ipam/go.mod
- azure-ipam/linux.Dockerfile
- azure-ipam/windows.Dockerfile
- bpf-prog/ipv6-hp-bpf/go.mod
- bpf-prog/ipv6-hp-bpf/linux.Dockerfile
- build/tools/go.mod
- cni/linux.Dockerfile
- cni/windows.Dockerfile
- cns/linux.Dockerfile
- cns/windows.Dockerfile
- dropgz/build/linux.Dockerfile
- dropgz/build/windows.Dockerfile
- dropgz/go.mod
- go.mod
- hack/toolbox/Dockerfile.windows
- hack/toolbox/server/Dockerfile.heavy
- hack/toolbox/server/Dockerfile.lite
- npm/linux.Dockerfile
- npm/windows.Dockerfile
- tools/acncli/Dockerfile
- zapai/go.mod
> Upgrade to go1.22.7

- cns/service.go
- cns/service/main.go
Fixes missing logs in the `azure-cns.log` file from `main()` because they're using `log` instead of `logger`. `logger` is [initialized in the beginning of `main()`](https://github.com/Azure/azure-container-networking/blob/bee72ee95fc6d2c5c2e7cb91c623f1cdc3331285/cns/service/main.go#L536).
Validated by checking these log lines aren't in Kusto for ago > (7d) when it should be as it's part of CNS startup.
> fix: missing logs in log file

- cns/ipampool/v2/monitor.go
- cns/kubecontroller/pod/reconciler.go
- cns/restserver/internalapi.go
- cns/restserver/ipam.go
- cns/restserver/metrics.go
Improves logging in IPAM pool monitor, Pod watcher, Restserver IPAM methods.
**Notes**:
> chore: improve IPAM logging

- .pipelines/pipeline.yaml
- Makefile
Finishes removing cni-dropgz from CI
**Notes**:
> backport: rip out dropgz

- internal/fs/atomic.go
- internal/fs/atomic_test.go
The atomic fs writer currently opens the tempfile when it is instantiated. This can lead to many tempfiles being created if CNS fails during initiliazation.
This moves the tempfile creation in to the Write() method, so early exits after initialization will not clutter up the host filesystem with empty tempfiles.
**Notes**:
> Update atomic fs writer to delay tempfile creation until Write() is called

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/codeql.yaml
- .github/workflows/crdgen.yaml
- .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
- .github/workflows/cyclonus-netpol-test.yaml
- .github/workflows/golangci.yaml
- azure-ipam/Dockerfile
- azure-ipam/go.mod
- bpf-prog/ipv6-hp-bpf/go.mod
- bpf-prog/ipv6-hp-bpf/linux.Dockerfile
- build/tools/go.mod
- cni/Dockerfile
- cns/Dockerfile
- dropgz/go.mod
- go.mod
- hack/toolbox/Dockerfile.windows
- hack/toolbox/server/Dockerfile.heavy
- hack/toolbox/server/Dockerfile.lite
- npm/linux.Dockerfile
- npm/windows.Dockerfile
- tools/acncli/Dockerfile
- zapai/go.mod
Updates the Go version to v1.23.1 for various improvements, fixes to stdlib, and toolchain upgrades.
**Notes**:
> chore: upgrade go toolchain to 1.23

- .pipelines/singletenancy/azure-cni-overlay-stateless/azure-cni-overlay-stateless-e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- .pipelines/templates/add-windows-nodepool-job.yaml
If a windows nodepool is added to a newly created aks cluster, the aks cluster may be in "Updating" state, causing the job to fail. This PR adds a check to see if the cluster is in updating state and sleeps until the cluster is no longer in the updating state. Also refactors adding windows nodepool into a common template and adds a check if the windows nodepool is already created (so we don't error if the nodepool is already added).
**Notes**:
On detecting updating state, we wait, see line 54:
https://msazure.visualstudio.com/One/_build/results?buildId=105433502&view=logs&j=66af8358-44a8-5a80-90ff-77e03c31665a&t=8f8dc4ee-a8ef-5fc9-ab65-cc330785c488
When not detecting updating state, we proceed: …
> ci: add wait before adding windows nodepool if cluster is in updating state

- cni/network/invoker_mock.go
- cni/network/network_linux.go
- cni/network/network_linux_test.go
- cni/network/network_test.go
- cni/network/network_windows_test.go
- network/endpoint.go
- network/secondary_endpoint_linux_test.go
Adds unit tests to test that endpoint info struct creation is as expected based on args, cns/ipam invoker response, and network configuration for the following scenarios:
- swiftv2 linux ipam response (infra + delegated) -> endpoint info
- swiftv2 windows ipam response (infra + delegated) -> endpoint info
- swiftv1 windows multitenancy dual nic ipam response  (infra + infra) -> endpoint info
- swiftv1 linux multitenancy (infra) ipam response -> endpoint info
Each scenario tests the `Add` method from ipam response until we call an `EndpointCreate`, given args, ipam response, and network configuration and ensure the endpoint info struct generated _exactly matches_ what is expected (so all fields are checked) **except** for the interface name and endpoint id as they …
> test: add uts for cni add function

- test/integration/manifests/cilium/v1.13/cilium-agent/templates/daemonset.yaml
- test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset-dualstack.yaml
- test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset.yaml
- test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset-dualstack.yaml
- test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset.yaml
PodAntiAffinity slows down pod startup in large scale clusters. Removing this from daemonsets for all cilium versions
**Notes**:
> chore: delete podAntiAffinity from cilium daemonsets in test

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/cilium/cilium-scale-test.yaml
- .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
- .pipelines/networkobservability/pipeline.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e.steps.yaml
ACN pipelines used Cilium version tags that didn't include the letter 'v'. This PR updates the pipelines to handle private fork version tags, which include the letter 'v'. This will allow us to set ADO pipeline variables to point to ACN private fork images for Cilium.
Lack of support for ACN Cilium private fork images
**Notes**:
> fix: update pipeline to handle an extra character 'v' in version tag

- crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
In order to communicate the availability zone for ncs from the virtual machine where they are placed, we first need to expand the nnc definition to include the az in its status. Population will be handled in a subsequent PR.
**Notes**:
> Adding availability zone to nnc spec

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
- .pipelines/cni/pipeline.yaml
- .pipelines/networkobservability/pipeline.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/templates/cilium-cli.yaml
- test/integration/manifests/cilium/daemonset.yaml
- test/integration/manifests/cilium/deployment.yaml
- test/integration/manifests/cilium/v1.12/cilium-agent/templates/daemonset.yaml
- test/integration/manifests/cilium/v1.12/cilium-operator/templates/deployment.yaml
- test/integration/manifests/cilium/v1.13/cilium-agent/templates/daemonset.yaml
- test/integration/manifests/cilium/v1.13/cilium-operator/templates/deployment.yaml
- test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset-dualstack.yaml
- test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset.yaml
- test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.yaml
Updates pipeline variables to allow for a matching of release train and cilium version. Cilium version should match the k8s version being used.
This change came about because of https://github.com/Azure/azure-container-networking/pull/3089 changes which bumped cilium version from 1.13.13 -> 1.14.15 which exposed a testing gap.
**Notes**:
> [backport] ci: Update Cilium image usage for release/v1.5

- .pipelines/cni/cilium/cilium-cni-load-test.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- test/integration/manifests/cilium/daemonset.yaml
- test/integration/manifests/cilium/deployment.yaml
Updates pipeline variables to allow for a matching of release train and cilium version. Cilium version should match the k8s version being used.
This change came about because of #3089 changes which bumped cilium version from 1.13.13 -> 1.14.15 which exposed a testing gap.
**Notes**:
> ci: Update Cilium image usage for release/v1.4

- .pipelines/cni/cilium/cilium-scale-test.yaml
- hack/aks/Makefile
use nodepool scale instead of vmss scale since this is the supported way to scale down the nodepool in AKS clusters
**Notes**:
> ci: nodepool scale down for cilium pipeline

- crd/overlayextensionconfig/api/v1alpha1/overlayextensionconfig_types.go
- crd/overlayextensionconfig/manifests/acn.azure.com_overlayextensionconfigs.yaml
We want to make OverlayExtensionConfig `extensionIPRange` field immutable to prevent accidental changes to the field. Network Containers are getting programmed for every IP address in this field's CIDR range, and DNC/DNC-RC will not support updating this field.
**Notes**:
> feat: make OverlayExtensionConfig `ExtensionIPRange` field immutable

- cns/windows.Dockerfile
Reverts Azure/azure-container-networking#2935
CNS Daemonset on AKS does not have a volume mount for powershell, seemingly due to to https://github.com/Azure/AKS/issues/3885, so we need to keep using servercore on v1.4 branch until we add a volume mount to host powershell
> Revert "backport: chore: move cns from servercore to nanoserver (#2454)"

- Makefile
- cni/Dockerfile
- cni/telemetry/service/telemetrymain.go
- cns/service/main.go
- telemetry/aiwrapper.go
- telemetry/aiwrapper_test.go
Updates the cni dockerfile to take in arguments for the ai metadata, similar to the cns dockerfile.
The ai instrumentation key previously was not passed when building the azure vnet telemetry binary when making a *cni image*. The instrumentation key was passed when making the binary with the make file command, however.
Also fixed an error message not logging which hid the above error.
See above
**Notes**:
Tested on podsubnet cluster. No logs were found to be uploaded, and noticed telemetry logs showed an ai handle creation error. However, after applying the cni image with the fix using the cni installer, we started to receive logs. The telemetry logs also no longer produced the error message.
> fix: pass ai metadata to telemetry during cni image build

- .pipelines/singletenancy/aks/aks-e2e.jobs.yaml
- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/singletenancy/azure-cni-overlay-stateless/azure-cni-overlay-stateless-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-job-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.jobs.yaml
- .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e-job-template.yaml
Seeing runs fail due to extended testing times and component detection taking 10 minutes of the default 60. Increasing it to 2 hours can potentially increase run times on failed states, but will allow for enough time for flaky tests to succeed and still have a successful run.
**Notes**:
> ci: standardize E2E job timeout to 2 hours on PR pipeline

- cns/service/main.go
Communicate with the API Server in Proto instead of JSON for improved efficiency. Every little bit counts, and this is basically a free change for us to make.
**Notes**:
> feat: use proto in CNS usage of client-go 

- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
feat: adding stateless CNI support for ACI>
New entry in CNS statefile will be added for a container upon updateEndpoint request if the entry does not already exist. This covers a special case for ACI.
In ACI the CNS path to allocate IP address and send goalstate is different than CNS IPAM for Cilium and azure-cni for AKS. As a result, the endpoint entry for statefile is not getting create upon IP allocation and this fix will create the whole entry when CNI send updateEndpoint API request to CNS.
**Notes**:
> feat: adding stateless CNI support for ACI

- cni/azure-windows-swift-overlay-dualstack.conflist
- cni/azure-windows-swift-overlay.conflist
- cni/azure-windows-swift.conflist
- cns/hnsclient/hnsclient_windows.go
- cns/service/main.go
- network/network_windows.go
- network/network_windows_test.go
This PR is to simplify windows l2bridge mode and remove l2tunnel mode from the system.
**Notes**:
> Remove l2bridge checker on windows and l2tunnel mode

- .pipelines/cni/pipeline.yaml
- .pipelines/containers/container-template.steps.yaml
- .pipelines/containers/container-template.yaml
- .pipelines/containers/manifest-template.steps.yaml
- .pipelines/containers/manifest-template.yaml
- .pipelines/npm/npm-cni-integration-test.yaml
- .pipelines/npm/npm-conformance-tests-latest-release.yaml
- .pipelines/npm/npm-conformance-tests.yaml
- .pipelines/npm/npm-cyc-win-tests-latest-release.yaml
- .pipelines/npm/npm-scale-test.yaml
- .pipelines/pipeline.yaml
- .pipelines/run-pipeline.yaml
- Makefile
- azure-ipam/Dockerfile
- cni/Dockerfile
- cns/Dockerfile
- npm/windows.Dockerfile
Windows HPC are special.
They explicitly [do not run in a `chroot`](https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#container-mounts:~:text=There%20will%20be%20no%20chroot%20equivalent) or similar execution sandbox, and their [filesystem is a merged view](https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#container-mounts) of the hostfs and their shipped containerfs. This means that we don't need to ship a filesystem: we recently moved from `servercore` to `nanoserver` and observed that the lack of `pwsh.exe` in `nanoserver` is manageable (in containerd 1.7+, automatically, and in 1.6, by tweaking the container `PATH`). We can go further and remove the rest of …
> feat: Windows HPC base image

- .pipelines/singletenancy/aks-swift/aks-swift-e2e.steps.yaml
- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
- .pipelines/singletenancy/aks/aks-e2e.steps.yaml
- .pipelines/singletenancy/aks/e2e-step-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e.steps.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e.steps.yaml
- .pipelines/templates/cilium-cli.steps.yaml
- .pipelines/templates/cilium-cli.yaml
- .pipelines/templates/cilium-tests.yaml
Certain PR pipeline steps did not capture bash error codes correctly or overwrote them with successive calls. 
In fixing this I also captured a missed input for the `cilium-test.yaml` template that also required fixes.
**Notes**:
Instead of adding set -e everywhere we can also split out deleting namespaces, assigning variables, ect. 
Exit codes get overwritten when any command is ran after a test i.e `make test-validate-state | go test ...`
> ci: Add exit code capture for PR pipeline

- cns/configuration/cns_config.json
- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/configuration/testdata/good.json
- cns/service.go
- cns/service/main.go
- cns/service_test.go
- server/tls/tlscertificate_retriever.go
A configuration change is required in CNS to be able to specify the optional config of minimum TLS version support desired for TLS handshake
**Notes**:
> expose MinTLSVersion config for TLS handshake

- cns/middlewares/k8sSwiftV2.go
- cns/middlewares/k8sSwiftV2_linux.go
- cns/middlewares/k8sSwiftV2_windows.go
- cns/middlewares/k8sSwiftV2_windows_test.go
This PR is to fix one issue in swiftv2 Windows scenario:
When a pod is created, the default route is added on infra vnet:
root@swiftv2-pod-3:/# ip route
default via 10.244.2.1 dev eth0 metric 1
It leads to ping a VM IP in the same VNET that cannot work.
There are two issues::
1.CNS does not provide the default route to CNI;
2.CNI should only add the default route to secondary interface customer vnet; on Swiftv2 scenario, skipDefaultRoutes is set to true for infraNIC interface and false for a secondary interface; so if !info.skipDefaultRoutes, then add default route.
Add dummy default route and pass to CNI as a workaround;
After this fix after a pod creation is done, the route table shows:
**root@swiftv2-pod-1:/# ip route
default via 10.241.0.1 dev eth1** …
> Fix: Add default route on delegatedNIC interface

- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-job-template.yaml
backports #3124 to v1.5 release train
**Notes**:
> [backport] ci: standardize E2E job timeout to 2 hours on PR pipeline (#3124)

- .pipelines/pipeline.yaml
- .pipelines/templates/delete-cluster.yaml
Backports changes to clean up pipeline. See commits for more details.
**Notes**:
> [backport] ci: PR pipeline yaml cleanup 

- hack/aks/Makefile
fix: Add--kubernetes-version to linux-cniv1-up cluster creation
backports #2952 to v1.5 release train. Already exists in v1.4.
**Notes**:
> [backport] fix: Add --kubernetes-version to linux-cniv1-up cluster creation (#2952)

- cni/network/network_windows_test.go
Adds testing coverage to test if network policies passed in from the networking configuration make their way into the proper NetworkPolicies field and EndpointPolicies field of the endpoint info struct. Also tests to ensure that each endpoint info struct has a distinct network policies and endpoint policies slice, separate from other endpoint infos.
**Notes**:
> test: add create endpoint info policy test

- cns/service/main.go
- platform/os_linux.go
- platform/os_windows.go
- platform/os_windows_test.go
- test/validate/validate.go
PowerShell is heavy (+30mb of memory footprint per invocation). We don't need to use it to interact with the Windows Registry (or ServiceManager) - the Go stdlib has good native bindings that should use instead.
**Notes**:
This functionality was introduced in #1306. In #2315, it was changed to conditionally set the reg key value only if the HNS path exists. Why? It seems simpler and harmless to always try to set the reg key, so that's what I have done. Unclear if this is problematic - cc @ZetaoZhuang 
Supersedes and closes #2974 and #2961 (and #2949)
> fix: remove PowerShell from Windows registry interactions

- Makefile
- cni/linux.Dockerfile
- cni/telemetry/service/telemetrymain.go
- cni/windows.Dockerfile
- cns/service/main.go
- telemetry/aiwrapper_test.go
Backports #3095 
Updates Linux dockerfile since in v1.5 the dockerfile is split per OS
**Notes**:
> backport: fix: pass ai metadata to telemetry during cni image build (#3095)

- cni/azure-windows-multitenancy.conflist
- cni/azure-windows-swift-overlay-dualstack.conflist
- cni/azure-windows-swift-overlay.conflist
- cni/azure-windows-swift.conflist
- cni/azure-windows.conflist
This PR is to cleanup windows cni config file to remove bridgeName fields
**Notes**:
> Remove bridgeName field from CNI windows conflist files

- cns/service/main.go
Reverts Azure/azure-container-networking#3131
might be causing a problem for swift v2
> Revert "feat: use proto in CNS usage of client-go "

- .pipelines/pipeline.yaml
- .pipelines/run-pipeline.yaml
Current iteration of swiftv2 E2E coverage is satisfied in other pipelines. Disable until next iteration.
**Notes**:
> ci: disable swiftv2 E2E

- cns/configuration/cns_config.json
- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/configuration/testdata/good.json
- cns/logger/constants.go
- cns/metric/configsnapshot.go
- cns/metric/configsnapshot_test.go
- cns/service/main.go
Inspired by @ramiro-gamarra's PR to emit config snapshots at an interval, we should do the same for CNS for a consistent view for both components.
**Notes**:
> [CNS] add config snapshot event metrics at an interval

- cns/service/main.go
This PR is to use CNS zap logger lib instead of general log lib;
it's because some logs are not stored in the cns log file
**Notes**:
> use cns logger lib

- npm/pkg/dataplane/policies/policymanager_test.go
Had this failure running Windows unit tests:
```
--- FAIL: TestBootup (0.00s)
policymanager_test.go:118: 
Error Trace:	D:/a/_work/1/s/npm/pkg/dataplane/policies/policymanager_test.go:118
Error:      	Not equal: 
expected: "iptables-nft"
actual  : "iptables"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-iptables-nft
+iptables
Test:       	TestBootup
```
> test: [NPM] fix windows unit test for policymanager

- network/endpoint.go
- network/endpoint_linux.go
- network/manager.go
- network/ovs_endpoint_snatroute_linux.go
- network/snat/snat_linux.go
- network/snat/snat_linux_test.go
- network/transparent_vlan_endpoint_snatroute_linux.go
- network/transparent_vlan_endpointclient_linux.go
- network/transparent_vlan_endpointclient_linux_test.go
If the interface is not found when querying for it in AllowHostToNC or vice versa, the error is ignored, leading to a potential panic if we try to access the interface (which would be nil). This PR checks the error and returns it if it is not found, avoiding the panic. Additionally, if there is a failure in deleting one of the interfaces for an endpoint, this PR will still attempt to clean up associated snat interface (previously an error during the cleanup process would cause the snat endpoint not to be cleaned up).
**Notes**:
Green run: https://msazure.visualstudio.com/One/_build/results?buildId=109439035&view=results
> fix: return error on interface not found and always clean up snat ep

- .pipelines/templates/cilium-cli.yaml
Hardcodes CLI version for v1.13 agent to v0.14.8.
**Notes**:
Old txt file `stable-v0.14.txt` was removed from main with https://github.com/cilium/cilium-cli/pull/2869 .
> fix: hardcode CLI for 1.13 agent

- cni/network/invoker_azure.go
- network/manager.go
This PR removes saving to the azure cni statefile from the AddExternalInterface and CreateNetwork methods since we only want to commit to the statefile once we create the endpoint. Saving the state will save all in-memory state including all networks, external interfaces, and endpoints, so it's unecessary to call save state after each update-- we only need to call it once at the end (which is when the endpoint is created).
We also backport https://github.com/Azure/azure-container-networking/pull/2309/files here
Previously, if we wrote the external interface to the state, and then crashed before we wrote the corresponding network, the subsequent DEL call would not clean up the ips (since azure cni does not see the network in the azure cni state file, …
> fix: save cni state only during endpoint creation or deletion

- .github/workflows/codeql.yaml
> disable custom codeql because something is broken

- crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
- crd/multitenancy/api/v1alpha1/podnetworkinstance.go
- crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
- crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworkinstances.yaml
As part of adding default deny so pods can't communicate with one another when network policies are not present, this pr is part 1 which updates the pni crd and mtpnc crd with adding a default deny acl bool field.
**Test**:
Confirmed when default deny is not added as a field or is added as a field and set to false, mtpnc displays Default Deny ACL : false as shown below
Confirmed when default deny is added as a field and set to true, mtpnc displays Default Deny ACL : true as shown below
**Notes**:
> [NPM Lite] Added DefaultDeny in PNI + MTPNC CRD's

- npm/cmd/start.go
Missing telemetry in case of a few potential errors during NPM bootup.
Fixes #3145 
**Notes**:
`metrics.SendErrorLog()` doesn't work as intended in these three places since telemetry is not initialized until later:
https://github.com/Azure/azure-container-networking/blob/bbe5cb9d1216cea6a57364f90714a352193ea2f3/npm/cmd/start.go#L239-L240
https://github.com/Azure/azure-container-networking/blob/bbe5cb9d1216cea6a57364f90714a352193ea2f3/npm/cmd/start.go#L184-L186
https://github.com/Azure/azure-container-networking/blob/bbe5cb9d1216cea6a57364f90714a352193ea2f3/npm/cmd/start.go#L193-L195
> log: [NPM] init telemetry before dataplane

- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/service/main.go
IPAMv2 can handle update events even when the update is made from CNS itself, like patching
the spec for more IPs. This solves the problem of missed updates when a watch is re-established
and an NNC has been updated in both its spec and status. IPAMv2 is idempotent and will not
fall into a feedback loop where after CNS patches the NNC for more IPs its NNC reconciler still
sees IPs needed so it requests more IPs again, which triggers the reconciler again to request
more IPs, and so on ...
Fixes #3278 
**Notes**:
The first commit is the basic implementation. The 2nd commit does some more refactoring. I am fine to take just the first commit if you all don't like the refactoring attempt.
> fix: let NNCResonciler process update events with different generations when IPAMv2 is enabled

- .github/workflows/codeql.yaml
- codeql/acn-addipamconfig.ql
- codeql/acn-cni-args.ql
- codeql/acn-cns-invoker.ql
- codeql/acn-decode.ql
- codeql/lib/ACN.qll
A new version of the codeql bundle (2.20.0) caused existing queries to break.
Should address the compilation issue and re-enable custom codeql queries.
**Notes**:
> fix: modify codeql query to use DataFlow instead of DataFlow2 library

- .golangci.yml
Most developers agree that magic numbers are problematic. However, the gomnd linter lacks finesse to understand when magic numbers aren't magic at all. Examining the context of where the number is used is often enough to deem it non-magical.
Consider some common magic numbers flagged by gomnd: 0644, 8080. Without any additional context, it's fairly likely these are a file mode and a port number, respectively. It's even more obvious when presented with the context:
```go
f, err := os.OpenFile("notes.txt", os.O_RDWR|os.O_CREATE, 0644)
```
The linter would flag this, even though it's completely obvious what 0644 is. The remediations for the linter's flag creates categorically worse code. The most common learned behavior for developers facing this linter is to simply constantize everything it …
> Remove gomnd from Golang CI

- crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
fix: Updating the AvailabilityZone field in the NNC to be an int value as the return from NMA is an int value
N/A
**Notes**:
> fix: Updating the AvailabilityZone field in the NNC to be an int value as the return from NMA is an int value

- npm/cmd/start.go
- npm/metrics/ai-utils.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
> fix: [NPM] close telemetry handler before crashing

- aitelemetry/telemetrywrapper.go
When CNS (and NPM after #3333) crash, they block on a call to close the app insights client so that queued logs are sent. This relies on a channel which might not close until much after the timeout which NPM/CNS specify. The ApplicationInsights-Go repo recommends having a timer of our own for the maximum time we want to wait for app insights to close.
This PR changes CNS and NPM so that they wait at most 30 seconds.
Related to #3299.
**Notes**:
> fix(log): time waiting for appinsights to close was unbounded

- cns/NetworkContainerContract.go
- common/config.go
as part of default deny work, updated network container contract to add DefaultDenyACL field. For background, cns will send cni the Default Deny acl's, if the default deny bool is set to true, which cni will use to create hns policies
**Notes**:
> [NPM Lite] Default Deny - Updating Network Container Contract

- aitelemetry/telemetrywrapper.go
- npm/cmd/start.go
- npm/metrics/ai-utils.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
- npm/pkg/dataplane/policies/policymanager_test.go
Backporting https://github.com/Azure/azure-container-networking/pull/3161, https://github.com/Azure/azure-container-networking/pull/3316, https://github.com/Azure/azure-container-networking/pull/3333, and https://github.com/Azure/azure-container-networking/pull/3337 for v1.5.41 release of NPM.
**Notes**:
> [backport] [NPM] Backport NPM Changes for v1.5.41

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
- .pipelines/networkobservability/pipeline.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium/cilium-e2e.steps.yaml
- .pipelines/templates/cilium-tests.yaml
check-log-errors sometimes catches on transient errors and fails the entire connectivity test suite
this test case is skipped in other pipelines, adding skip to ACN until issue is resolved
opened a GH issue in cilium - https://github.com/cilium/cilium/issues/36992
**Notes**:
> ci: skip check-log-errors in cilium connectivity

- cns/service/main.go
- platform/os_windows.go
**Reason for Change**: Add timeout to HNS service restart so that CNS will fail out instead of hang during init if it gets stuck. 
**Notes**:
> fix: prevent CNS hanging on HNS restart

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium/cilium-e2e.steps.yaml
- .pipelines/templates/cilium-tests.yaml
- test/integration/manifests/cilium/cilium-nightly-config.yaml
- test/integration/manifests/cilium/v1.13/cilium-operator/templates/deployment.yaml
- test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.yaml
- test/integration/manifests/cilium/v1.16/cilium-operator/templates/deployment.yaml
Enable CiliumEndpointSlice (CES) in Cilium clusters for testing prior to release. Enable CES in Cilium Operator only for version 1.13-1.16, and on the entire cluster from v1.17 / Nightly Pipeline. Adding list CRDs to pipelines for debugging.
> chore: enable CiliumEndpointSlice in testing

- test/integration/manifests/datapath/linux-deployment-ipv6.yaml
- test/integration/manifests/datapath/linux-deployment.yaml
- test/integration/manifests/datapath/windows-deployment.yaml
Attempts to fix this issue in our pipelines: https://msazure.visualstudio.com/One/_build/results?buildId=113599589&view=logs&j=b1429627-982b-5d7c-f874-2297f1590463&t=f4ed6e9d-3ea8-54bd-90c0-ce2d41a370dc
It looks like there is a possibility that one node becomes unbalanced (ex: both metrics pods, gateway keepers etc. all land on the same node), and so new pods are scheduled all on the other node to balance resources. This PR increases the number of replicas such that it is more likely that at least two pods land on each node (which is a hard requirement in the test). It also adds a topology constraint to encourage pods to distribute themselves on the nodes.
**Notes**:
Successful runs: …
> ci: increase goldpinger replicas from 4 to 8 and add topology constraints

- hack/aks/Makefile
- test/integration/manifests/datapath/linux-deployment-ipv6.yaml
- test/integration/manifests/datapath/linux-deployment.yaml
- test/integration/manifests/datapath/windows-deployment.yaml
Backport https://github.com/Azure/azure-container-networking/pull/3376
Cherry picking the two commits in that PR to 1.5 branch
Also enables LTS support for k8 version 1.28 during cluster creation
**Notes**:
> backport: ci: increase goldpinger replicas from 4 to 8 and add topology constraints

- aitelemetry/api.go
- aitelemetry/telemetrywrapper.go
- cns/logger/cnslogger.go
Send log levels to AI so that, for example: log.Error() shows up as SeverityLevelError in AI.
**Notes**:
> feat: add levels to CNS AI logs

- network/manager_test.go
Unit test for #3254
**Notes**:
> test: add ut to ensure store unaffected during add external interface

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Skipping cilium connectivity test no-unexpected-packet-drops in release tests 
**Notes**:
> ci: skip no-unexpected-packet-drops in release tests

- cns/kubecontroller/nodenetworkconfig/metrics.go
- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/restserver/internalapi.go
- cns/restserver/metrics.go
Exposes a metric for known NNC and NCs in the NNC reconciler and sync host NC loop.
**Notes**:
> feat: add metrics for count of known NNC and NCs

- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- hack/aks/Makefile
Backports #3011 as 1.29 clusters are also impacted by this issue.
**Notes**:
> [backport] ci: Unblock k8s 1.30 | ACN v1.6 testing (#3011)

- cns/client/client_test.go
- cns/fakes/iptablesfake.go
- cns/restserver/api_test.go
- cns/restserver/internalapi_linux.go
- cns/restserver/internalapi_linux_test.go
- cns/restserver/internalapi_windows.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/restserver/v2/server_test.go
- cns/service/main.go
In the vnet scale scenario, we use the node's ip as the primary ip instead of an ip from the pod's subnet (what happens in pod subnet mode). In cilium, we add snat rules from the cns, and base our snat on the primary ip + subnet. However, the primary ip is now the node ip, meaning we only snat packets from the node's primary ip w/ the pod subnet cidr. It should be that we also snat packets from the pod subnet's network/cidr. This change modifies the cns to grab any secondary ip from the pod subnet, combine it with the pod subnet cidr, and create an iptable rule for the pod subnet. The cidr is for the whole subnet space (applies to all static ip blocks allocated).
See above
**Notes**:
Manually tested cilium w/ updated cns and …
> fix: add iptables rules for dns in vnet scale cilium case

- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
> ci: skip restart and validation test in dualstack windows

- cns/client/client_test.go
- cns/fakes/iptablesfake.go
- cns/restserver/api_test.go
- cns/restserver/internalapi_linux.go
- cns/restserver/internalapi_linux_test.go
- cns/restserver/internalapi_windows.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/restserver/v2/server_test.go
- cns/service/main.go
Forward port of https://github.com/Azure/azure-container-networking/pull/3400
**Notes**:
> forwardport: fix: add iptables rules for dns in vnet scale cilium case

- cns/logger/cnslogger.go
- cns/logger/constants.go
- cns/logger/log.go
- cns/metric/heartbeat.go
- cns/service/main.go
Adds AKS apiserver FQDN to CNS log metadata so that logs can be aggregated by Cluster.
**Notes**:
> feat: add apiserver FQDN to CNS log metadata

- .pipelines/pipeline.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
- Makefile
- hack/aks/Makefile
- hack/scripts/wait-cluster-update.sh
Splits dualstack and overlay E2E testing stages into stages dedicated to each operating system.
Dualstack E2E --> Dualstack Windows E2E and Dualstack Linux E2E
Overlay E2E --> Overlay Windows E2E and Overlay Linux E2E
Increases load test timeout from 30m to 40m due to timeouts (even though it seemed like the test was progressing)
Dualstack and Overlay E2E stages take the longest to run in the pipeline and are the most likely to fail. These stages will fail faster if run in parallel.
**Notes**:
Green run: https://msazure.visualstudio.com/One/_build/results?buildId=115530896&view=results
> ci: split dualstack and overlay e2e tests by operating system

- cni/log/logger_windows.go
- cns/logger/cnslogger_windows.go
- zapetw/core_windows.go
Fixes a bug in the zapetw core where the extra `fields` added by calling `With` were not referenced when producing the log output.
There was a private `fields` slice in the Core struct, but it is not referenced anywhere. When a new Core is created in `With`, the `fields` were copied over...but still not _used_.
Now, instead, these fields are added to the Encoder. In the `With` call, the Core is copied and the Encoder cloned, then new fields are added to the clone. This ensures that the new Fields in a derived logger/core do not propogate back _up_ to the root logger...and also that they are used in producing the log output.
Also includes some minor refactoring to fix naming and improve contracts.
> fix: zapetw core With fields

- .pipelines/cni/load-test-templates/create-cluster-template.yaml
- .pipelines/cni/pipeline.yaml
- .pipelines/cni/singletenancy/cniv1-template.yaml
- .pipelines/pipeline.yaml
- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/singletenancy/aks/e2e-job-template.yaml
- .pipelines/templates/create-cluster.yaml
- hack/aks/Makefile
- hack/aks/README.md
Fix inconsistent creation of windows and linux clusters, now all use OS makefile variable
Adding a windows nodepool waits for cluster to be in succeeded state instead of immediately failing
**Notes**:
Release: https://msazure.visualstudio.com/One/_build/results?buildId=115700355&view=results
PR: https://msazure.visualstudio.com/One/_build/results?buildId=115758111&view=results
> ci: unify windows and linux cluster creation methods

- test/integration/manifests/cilium/daemonset.yaml
- test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset-dualstack.yaml
- test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset.yaml
AppArmor annotations are deprecated in kubernetes 1.30+, moving cilium 1.16 chart away from annotations and using security context for AppArmorProfile instead.
**Notes**:
> chore: use AppArmorProfile for cilium 1.16

- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/templates/delete-cluster.yaml
- .pipelines/templates/k8s-yaml-test.yaml
Regular k8s updates are causing warnings with our maintained daemonsets and deployments for using, soon to be, outdated config values and fields. Currently adding this to nightly pipeline as to not block PR(s), but still capture these warnings.
**Notes**:
> ci: add k8s yaml deprecation check to nightly

- npm/pkg/dataplane/ipsets/ipsetmanager_windows_test.go
Previously `TestFailureOnCreation` in `npm/pkg/dataplane/ipsets/ipsetmanager_windows_test.go` could flake: https://msazure.visualstudio.com/One/_build/results?buildId=112594849&view=logs&j=1e95c5bf-f785-5c1d-a4c1-33b038e882fb&t=4058cacc-5989-52ae-5341-5beff346fc28 since the contents of a set have no defined order. This PR changes the test validation behavior to copy the cache object, sort the values, and then replace the copy's values with the sorted values before comparing the copy (sorted) to the expected.
**Notes**:
This PR is made so this PR won't flake https://github.com/Azure/azure-container-networking/pull/3156
> test: sort npm set policy values before validation

- .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
[Cyclonus extended](https://github.com/Azure/azure-container-networking/actions/runs/13125530079) has been broken.
**Notes**:
Fixed by changing the Kind setup step to the one in the other cyclonus github action.
> ci(cyclonus extended): [NPM] fix broken GH action

- .pipelines/npm/npm-conformance-tests.yaml
- npm/profiles/v2-background.yaml
- npm/profiles/v2-place-first.yaml
Use Policy Assistant (essentially Cyclonus) to test traffic to LoadBalancer and NodePort services. Previous tests only tested ClusterIP services.
Also updates NPM profiles:
- disable placefirst for "background" profile
- enable background for "placefirst" profile
**Notes**:
Uses this policy assistant change: https://github.com/kubernetes-sigs/network-policy-api/pull/287
> ci: [NPM] conformance test for loadbalancer and nodeport services

- npm/linux.Dockerfile
Updated NPM Linux dockerfile to manually run `apt-get install` to get latest versions of Ubuntu packages (libc-bin, libc6, and libtasn1-6) to resolve the following Ubuntu CVEs in NPM's base image. 
Once the base image is updated to fixes we can remove this manually installation.
`libc-bin CVE-2025-0395`
`libc6 CVE-2025-0395`
`libtasn1-6 CVE-2024-12133`
**Trivy scan of NPM on current v1.5 release:** 
```
mcr.microsoft.com/containernetworking/azure-npm:v1.5.42 (ubuntu 20.04)
======================================================================
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 0, CRITICAL: 0)
┌────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────────┬───────────────────────────────────────────────────────────┐
│  Library …
```
> fix: [NPM] [CVEs] Update NPM Linux Dockerfile to Fix Ubuntu Vulnerabilities

- .pipelines/templates/run-unit-tests.yaml
- .pipelines/templates/unit-tests.stages.yaml
When the go tests are split up, only the status of the last command run determines the status of the entire step/task. Any previous steps, even if they exited with a failure, won't cause the task to visibly fail. By combining all tests together in one command, if this single command fails (due to any of the tests failing), the step/task will visibly fail on the pipeline.
See above
**Notes**:
**Will fail in the pipeline until npm windows tests are fixed (this is expected, as previously those tests were silently failing).**
When those npm changes are merged in, I will rebase this PR against master to resolve the errors.
Will be backported to `release/v1.5`
> ci: combine go tests such that any test failure will report a failure for the entire task

- cns/NetworkContainerContract.go
- cns/api.go
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/restserver.go
- cns/types/codes.go
- nmagent/responses.go
Expose GET NC list API in CNS client. DNC will call this endpoint to fetch the list of NCs programmed on the node.
In the backend, CNS calls NMAgent's _http://%s/machine/plugins/?comp=nmagent&type=NetworkManagement/interfaces/api-version/%s_ endpoint
> Expose GET NC list API in CNS client

- .golangci.yml
fix check-shadowing not allowed
Backports #3432
**Notes**:
> backport: ci: fix check-shadowing not allowed (#3432)

- cns/logger/log.go
- cns/logger/v2/config.go
- cns/logger/v2/config_linux.go
- cns/logger/v2/config_test.go
- cns/logger/v2/config_windows.go
- cns/logger/v2/cores/ai.go
- cns/logger/v2/cores/ai_test.go
- cns/logger/v2/cores/etw_windows.go
- cns/logger/v2/cores/file.go
- cns/logger/v2/cores/file_test.go
- cns/logger/v2/cores/stdout.go
- cns/logger/v2/logger.go
- cns/logger/v2/logger_linux.go
- cns/logger/v2/logger_windows.go
- go.mod
- go.sum
- internal/time/duration.go
- internal/time/duration_test.go
Adds v2 logger package for CNS. [1/2]
The v2 logger is built with zap and offers structured logging, derived contexts, multiple output targets and formats including stdout, files, ETW, and AppInsights.
The logger constructor is opinionated and will initialize targets and formats fully based on what is supported per-platform. The logger is intended to be used directly.
This pt. 1 change is strictly the addition of the v2 logger package machinery.
> feat: cns logger v2 [1/2]

- npm/linux.Dockerfile
Updates NPM Linux dockerfile to manually run `apt-get install` to get latest versions of Ubuntu package `libgnutls30 `to resolve `CVE-2024-12243` an Ubuntu CVE in NPM's base image.
**Trivy scan of NPM on current v1.5 release (v1.5.43):**
```
mcr.microsoft.com/containernetworking/azure-npm:v1.5.43 (ubuntu 20.04)
======================================================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
┌─────────────┬────────────────┬──────────┬────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────┐
│   Library   │ Vulnerability  │ Severity │ Status │ Installed Version  │   Fixed Version    │                         Title                          │ …
```
> fix: [NPM] [CVEs] Update NPM Linux Dockerfile to Fix Ubuntu CVE-2024-12243 

- .pipelines/templates/run-unit-tests.yaml
* add set ex to ci
* add race and timeout args
* remove race check
Backport #3156
**Notes**:
> backport: ci: combine go tests such that any test failure will report a failure for the entire task (#3156)

- cni/network/invoker_cns_test.go
This PR is to add multiple IB NICs Unit test
**Notes**:
> [Swiftv2 L1VH]Add multiple IB NICs UT

- cns/service/main.go
- platform/os_windows.go
don't restart HNS when setting SDNRemoteArpMacAddress (or at all, it's fragile).
reverts behavior changed in https://github.com/Azure/azure-container-networking/pull/3343 (timeout and retry if HNS is not responding) and https://github.com/Azure/azure-container-networking/pull/2993 (restart HNS after the regkey is set unconditionally)
> fix: don't restart HNS if the ARP regkey is not changed

- .pipelines/mdnc/azure-cns-cni-1.4.39.1.yaml
- .pipelines/mdnc/azure-cns-cni-1.5.28.yaml
- .pipelines/mdnc/azure-cns-cni-1.5.4.yaml
- .pipelines/mdnc/azure-cns-cni.yaml
- cns/azure-cns.yaml
- hack/manifests/cni-installer.yaml
- hack/toolbox/manifests/agents.yaml
- hack/toolbox/manifests/daemonset.yaml
- hack/toolbox/manifests/master.yaml
- test/integration/manifests/cilium/cns-write-ovly.yaml
- test/integration/manifests/cns/daemonset-linux.yaml
- test/scale/templates/kwok-node.yaml
- tools/acncli/deployment/manager_swift.yaml
Replaces the beta.kubernetes.io/os with kubernetes.io/os to fix the cilium nightly pipeline from failing
**Notes**:
> ci: remove beta kubernetes os selector

- test/integration/manifests/cnsconfig/azurecnidualstackoverlaylinuxconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnidualstackoverlaywindowsconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnioverlaylinuxconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnioverlaywindowsconfigmap.yaml
- test/integration/manifests/cnsconfig/azurestatelesscnioverlaywindowsconfigmap.yaml
- test/integration/manifests/cnsconfig/ciliumconfigmap.yaml
- test/integration/manifests/cnsconfig/ciliumnodesubnetconfigmap.yaml
- test/integration/manifests/cnsconfig/overlayconfigmap.yaml
- test/integration/manifests/cnsconfig/swiftwindowsconfigmap.yaml
Adds EnableIPAMv2 to all CNS configs as it is default enabled for 1.30+.
**Notes**:
> fix: set EnableIPAMv2 to true for current release train

- netlink/mocknetlink.go
- network/transparent_vlan_endpointclient_linux.go
- network/transparent_vlan_endpointclient_linux_test.go
Previously, `DeleteEndpointsImpl` would return an error if it failed to remove routes, skipping any further clean up logic. This could lead to the vnet veth device not being deleted (The vnet veth device is one end of the container's veth pair, the other resides in either the container if it was successfully moved, or still in the vnet ns if it was not moved). On subsequent adds, an error would pop up mentioning the pair already exists.
The PR ensures both pieces of logic always run, even if there is an error (which is logged). Unit tests have been added to verify the correct code paths are hit and there don't seem to be other methods in the delete flow that have this problem for this scenario.
**Notes**:
Tested on a multitenancy …
> fix: modify cleanup path to always delete link

- platform/os_windows.go
- platform/os_windows_test.go
#3498 reverted two functional changes to the CNS init HNS interaction:
1) always restart HNS after attempting to set the regkey
2) retry restarting HNS if it hangs
It turns out that HNS hangs are common enough that they notably impact CNS on Windows becoming ready and are preventing that revert from passing tests and rolling out. Thus, it is not safe for CNS to block on HNS restarting - if it hangs, CNS never becomes ready, meaning the Node never becomes Ready.
This is a retake on (2) while keeping (1) reverted - we will _only_ try to restart HNS if the regkey is **not already set**. But when we do try to restart it, we will retry this instead of hanging forever.
> fix: carefully retry restarting HNS if it hangs

- platform/os_windows.go
#3529 refactored the HNS restart such that the stop/start could be retried - this adds a deadline to fail and cause that retry, and changes the retry strategy to exponential backoff instead of constant
> fix: backoff retry and timeouts in HNS restart 

- hack/aks/Makefile
https://azure.microsoft.com/en-us/updates?id=azure-basic-load-balancer-will-be-retired-on-30-september-2025-upgrade-to-standard-load-balancer
**Notes**:
> chore: remove basic lb due to deprecation on 250930

- test/integration/lrp/lrp_fqdn_test.go
- test/integration/lrp/lrp_test.go
- test/integration/manifests/cilium/lrp/fqdn-cnp.yaml
- test/internal/datapath/datapath_win.go
- test/internal/kubernetes/utils.go
- test/internal/kubernetes/utils_create.go
- test/internal/kubernetes/utils_delete.go
- test/internal/kubernetes/utils_parse.go
- test/validate/linux_validate.go
- test/validate/validate.go
- test/validate/windows_validate.go
Adds a test to validate functionality of a cilium local redirect policy when a cilium network policy is applied-- for example, confirms whether certain dns requests are redirected and increment a metric when they are allowed in the network policy (and confirms that they don't increment the counter when not allowed). Updates necessary utility methods and creates a function that issues an exec on pod command but does _not_ retry on failure.
N/A
**Notes**:
Example run: https://msazure.visualstudio.com/One/_build/results?buildId=119685764&view=logs&j=a725b465-af6c-5b16-2e20-4e0bf1d0563e&t=d9595ca1-827d-5105-2385-c679bcc42718
Nightly: https://msazure.visualstudio.com/One/_build/results?buildId=119489437&view=results
ACN PR run (no …
> ci: add fqdn with cilium local redirect policy test

- hack/aks/Makefile
https://azure.microsoft.com/en-us/updates?id=azure-basic-load-balancer-will-be-retired-on-30-september-2025-upgrade-to-standard-load-balancer
**Notes**:
> chore: remove basic lb due to deprecation on 250930 (v1.4)

- cns/healthserver/healthz.go
- cns/healthserver/healthz_test.go
already doing the strip prefix https://github.com/tyler-lloyd/azure-container-networking/blob/40b6c443d62321ee61c134bf6573ed2de9813d50/cns/healthserver/server.go#L15
so doing it inside check builder is redunant and causes the /healthz endpoint to return a 404
**Notes**:
> fix: do not return a StripPrefix handler when building checker

- .pipelines/templates/run-unit-tests.yaml
- Makefile
The current pr pipeline does not check if a PR drastically decreases the code coverage of the repository, nor does it publish code coverage results to the code coverage tab in ADO. This PR enables publishing code coverage and should mark the build as a failure if the code coverage decreases by a significant amount (> 0.25% I believe) compared to the master branch. Merges code coverage between windows and linux oses.
See above
**Notes**:
> ci: add code coverage publishing and check to pipeline

- hack/aks/Makefile
https://azure.microsoft.com/en-us/updates?id=azure-basic-load-balancer-will-be-retired-on-30-september-2025-upgrade-to-standard-load-balancer
**Notes**:
> chore: remove basic lb due to deprecation on 250930 (v1.5)

- .pipelines/pipeline.yaml
- hack/aks/Makefile
Adds cilium podsubnet vnet scale to the pipeline for e2e testing of cns and related components. Also updates the makefile to explicitly include pod allocation mode static block for targets that are intended to use vnet scale mode. Currently there seem to be makefile targets that are meant to create vnet scale clusters but upon creation and examination of their nncs, the mode only mentions 
```
kubernetes.azure.com/podnetwork-subnet=podnet
kubernetes.azure.com/podnetwork-type=vnet
```
We expect 
```
kubernetes.azure.com/podnetwork-subnet=podnet
kubernetes.azure.com/podnetwork-type=vnetblock
```
**Notes**:
Will fail until relevant backend changes go in for creating vnet scale clusters with network plugin none
Done: …
> ci: add vnet scale cilium pipeline stage

- .pipelines/cni/load-test-templates/create-cluster-template.yaml
- .pipelines/templates/create-cluster.jobs.yaml
- .pipelines/templates/create-cluster.yaml
- hack/aks/Makefile
Enables testing of various Kubernetes versions against master. 
**Notes**:
Does not impact functionality of PR or Releases.
Using variable `${K8S_VERSION}`
ACN PR - https://msazure.visualstudio.com/One/_build/results?buildId=120416666&view=logs&j=b7272be1-c4e1-5606-108c-57e47d6749ec&t=24d1cf9e-6a2a-5c4b-89db-514da0326b17&l=77
CNI Release Test - https://msazure.visualstudio.com/One/_build/results?buildId=120417599&view=logs&j=5880768e-a1e2-5440-d89b-0c014d2bdd3f&t=36f18d29-ef7e-52ae-b9f6-f2d795e40dd6&l=74
> ci: Allow manual overwrite of k8s version in CI/CD

- test/integration/manifests/cnsconfig/azurecnidualstackoverlaylinuxconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnidualstackoverlaywindowsconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnioverlaylinuxconfigmap.yaml
- test/integration/manifests/cnsconfig/azurecnioverlaywindowsconfigmap.yaml
- test/integration/manifests/cnsconfig/azurestatelesscnioverlaywindowsconfigmap.yaml
- test/integration/manifests/cnsconfig/ciliumconfigmap.yaml
- test/integration/manifests/cnsconfig/ciliumnodesubnetconfigmap.yaml
- test/integration/manifests/cnsconfig/overlayconfigmap.yaml
- test/integration/manifests/cnsconfig/swiftlinuxconfigmap.yaml
- test/integration/manifests/cnsconfig/swiftwindowsconfigmap.yaml
Adding in fields that have 0 impact to current E2E as they default to false or are not used. 
**Notes**:
Will sort and organize bottom block to match default managed aks offering after #3502 has merged.
> ci: Populate missing fields in CNS configmap

- iptables/iptables.go
- iptables/iptables_test.go
It was speculated that even though the iptables command returns with no errors, it was possible that the iptables rule was never created. This change aims to validate the rule was created and will error out the cni plugin if the rule specified in append or insert was not found (using a -C check).
Validated against transparent vlan and pipeline with no error: https://msazure.visualstudio.com/One/_build/results?buildId=121810862&view=results
See above.
**Notes**:
> fix: validate iptable rule exists after calling insert or append iptable rule

- hack/aks/Makefile
Reverts Azure/azure-container-networking#3607 as https://github.com/Azure/azure-cli/issues/31345 has been resolved with https://github.com/Azure/azure-cli-extensions/pull/8703
> Revert "ci: set aks preview to 14.0.0b3"

- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/templates/log-check-template.yaml
Adds an additional level of alerting for breaking changes occurring in upstream cilium.
**Notes**:
> ci: Add check for cilium error logs to cilium nightly pipeline

- platform/os_windows.go
- platform/os_windows_test.go
backport of HNS restart fixes #3529, #3540
> backport: retry restarting HNS (#3529, #3540)

- cni/Dockerfile
- cns/Dockerfile
- cns/configuration/configuration.go
- cns/healthserver/healthz.go
- cns/healthserver/healthz_test.go
- cns/service/main.go
We only really need an ongoing connection to k8s if we are in dynamic podsubnet mode. Overlay and vnetblock are static and do not need it after initialization, so we shouldn't consider loss of apiserver connectivity a restartable failure in those scenarios.
> fix: only ping k8s for healthz in podsubnet

- .pipelines/npm/npm-conformance-tests.yaml
- .pipelines/npm/npm-scale-test.yaml
- npm/azure-npm.yaml
- npm/examples/azure-npm-lite.yaml
Removes the `hostUsers: false` setting in the NPM daemonset. Reverts from changes https://github.com/Azure/azure-container-networking/pull/2589
Also adds a public-ip and service tag to NPM scale and conformance tests to comply with SFI rules (failing with `RequestDisallowedByPolicy` otherwise).
From https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/#limitations 
When using a user namespace for the pod, it is disallowed to use other host namespaces. In particular, if you set `hostUsers: false` then you are not allowed to set any of:
```
hostNetwork: true
hostIPC: true
hostPID: true
```
**Notes**:
> revert: [NPM] Remove hostUsers Configuration

- hack/aks/Makefile
Preempts future PR(s) of making certain release trains hardcoded into LTS usage. Defaults into LTS when we want to specify it, but allows us to build non-LTS clusters on older release trains.
**Notes**:
PR is generated for `release/v1.5` to show working POC.
> ci: future proof for LTS clusters

- hack/aks/Makefile
> [backport] ci: future proof for LTS clusters (#3620)

- hack/aks/Makefile
- test/integration/manifests/cilium/v1.13/cilium-operator/templates/deployment.yaml
- test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.yaml
- test/integration/manifests/cilium/v1.16/cilium-operator/templates/deployment.yaml
update operator tolerations to match AKS charts
small makefile fix in overlay-cilium-up
**Notes**:
> chore: update tolerations in cilium operator manifests, makefile fix

- hack/aks/Makefile
Forwardports #3620 
**Notes**:
> [forwardport] ci: future proof for LTS clusters (#3620)

- cns/hnsclient/hnsclient_windows.go
revert the apipa endpoint gw change  to .1  to resolve the nc to host connection issue in Linux contianer. This does not impact the initial change for changing the apipa network gw and loop adapter defualt gw from .1 to .2 on host.
**Notes**:
This fix already been verified by updating the legacy runner cns with this fix for both windows and linux containers.
> change apipa endpoint gateway back to .1

- hack/aks/Makefile
Cannot reassign make variable values. Leverage `LTS` as a "boolean" value and set `LTS_ARGS` appropriately for cluster creation.
**Notes**:
> [ci] fix: make variable assignment

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
- .pipelines/templates/cilium-mtu-check.yaml
- .pipelines/templates/cilium-tests.yaml
- hack/manifests/nginx.yaml
- hack/scripts/cilium-mtu-validation.sh
compare pod eth0 mtu with node eth0 mtu and verify same value
**Notes**:
> ci: mtu check for cilium e2e

- npm/linux.Dockerfile
Reverts manual package installations made to the NPM Linux dockerfile in: https://github.com/Azure/azure-container-networking/pull/3439 and https://github.com/Azure/azure-container-networking/pull/3461. These changes were made as NPM base image (Ubuntu) did not have the updated packages installed which lead to CVEs on the base image. Ubuntu has since been patched to have the CVEs resolved so there is no need to manually install the packages at a specific version.
Trivy scan of NPM linux with changes to dockerfile:
```
acnpublic.azurecr.io/azure-npm:v1.5.49Test2 (ubuntu 20.04)
==========================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
**Notes**:
> revert: [NPM] [CVEs] Revert Manual NPM Linux Dockerfile Package Installations

- .pipelines/build/manifests.jobs.yaml
- .pipelines/build/publish-manifest.steps.yaml
Outputs a tarball containing the complete manifest for our corresponding components. This alleviates additional scripting and tool usage in following release CI/CD.
**Notes**:
> ci: output manifest tarball with Oras

- .pipelines/build/dockerfiles/cns.Dockerfile
- .pipelines/build/dockerfiles/cns.Dockerfile.tmpl
- cns/Dockerfile
- cns/Dockerfile.tmpl
- cns/azure-cns-windows.yaml
- test/integration/manifests/cns/daemonset-windows.yaml
As of [AKS 1.30](https://github.com/Azure/AKS/releases/tag/2024-06-09), service account tokens refresh every ~1 hour when OIDC is enabled. They were previously valid for a year.
[This `setkubeconfigpath.ps1` script](https://github.com/Azure/azure-container-networking/blob/47b243c42fd16119a96ab6d06eb602ac2ce40e7d/npm/examples/windows/setkubeconfigpath.ps1) was at some point necessary on Windows to create a valid kubeconfig for CNS (and NPM and others), but based on my testing we don't need it today. It copies the token from the token file to create a custom kubeconfig from a template at startup and then we pass CNS _that_ file via `--kubeconfig`. 
The script runs at startup and never re-runs, so the token that exists at Pod start is the token CNS will try to use …
> fix: let Windows CNS use the InClusterConfig

- cns/service/main.go
- cns/service/metrics.go
Instead of crashing after 10 retries to initialize the CNS state, this change retries until it succeeds and increments a metric if it doesn't to count NNC init failures. Also adds a positive-signal metric "hasNNCInitialized" to signal that this process has completed succesfully.
> feat: add metric for NNC init failures

- hack/aks/Makefile
Added virtual tags to all public ips. This change updates the previously added service tags ([in this PR](https://github.com/Azure/azure-container-networking/pull/3277)) to virtual tags since the public ips in these scenarios don't use NSGs, NSPs, or ACLs.
**Testing**:
Tested changes in a couple of pipelines:
[Cilium Nightly Pipeline](https://msazure.visualstudio.com/One/_build/results?buildId=127725784&view=results)
Seems like all runs of this pipeline are currently failing but cluster creation (the main concern here) is happening successfully
[CNI Release Test](https://msazure.visualstudio.com/One/_build/results?buildId=127803066&view=results)
A few scenarios are failing across all pipelines because of region capacity I believe. The remaining regions look okay for …
> [Service Tags] ci: Update ACN to use Virtual Tags

- .pipelines/build/dockerfiles/azure-ip-masq-merger.Dockerfile
- .pipelines/build/ob-prepare.steps.yaml
- .pipelines/build/scripts/azure-ip-masq-merger.sh
- .pipelines/pipeline.yaml
- .pipelines/run-pipeline.yaml
- azure-ip-masq-merger/Dockerfile
- azure-ip-masq-merger/README.md
Adds building the azure ip masq merger to the signed and unsigned binaries pipelines. Merge once #3737 has merged in.
**Notes**:
ACN PR Run Before Rebase: https://msazure.visualstudio.com/One/_build/results?buildId=127562678&view=results
ACN PR Run Latest: https://msazure.visualstudio.com/One/_build/results?buildId=127597027&view=results
ACN Official Build Signed: https://dev.azure.com/msazure/One/_build/results?buildId=127600651&view=results
> ci: add azure ip masq merger to pipeline

- hack/aks/Makefile
Backporting SFI service and virtual tags to release/v1.5 to address failures mentioned [here](https://teams.microsoft.com/l/message/19:db3193bfd6c84f1eba2d5a6981e4e611@thread.skype/1748388381530?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1eb27b57-8ace-4f0e-a9a9-e6db4e9829b7&parentMessageId=1748388381530&teamName=ContainerNetworking&channelName=Pipelines&createdTime=1748388381530)
> [Service Tags] ci: Backport service/virtual tag updates to release/v1.5

- .github/CODEOWNERS
- .pipelines/templates/run-unit-tests.yaml
- Makefile
Updates codeowners and adds uts for these go modules to the pr pipeline, combining code coverage as necessary. Previously, azure ipam and azure ip masq merger uts weren't included in make test-all because they were in different modules from the root module. Running make workspace before running the coverage allows us to include these numbers in the overall code coverage.
See above.
**Notes**:
> ci: add azure ipam and azure ip masq merger uts to pipeline

- crd/multitenancy/api/v1alpha1/nodeinfo.go
- crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
It was discovered that HomeAZ was incorrectly placed in the Status portion of NodeInfo, rather than the Spec, where it should be placed. This is because information in Spec is provided by CNS, while information in the Status is provided by DNC. As CNS is the entity that is initially aware of the HomeAZ of some node, the correct place for this to be communicated is in the Spec. Comments have also been updated to reflect the ownership of these fields, so as to not cause the same confusion to future contributors.
> Move HomeAZ to NodeInfo Spec

- npm/linux.Dockerfile
Resolves `CVE-2025-6020` present in the current `v1.6.26` version. Forward port of https://github.com/Azure/azure-container-networking/pull/3763.
```
mcr.microsoft.com/containernetworking/azure-npm:v1.6.26 (ubuntu 24.04)
======================================================================
Total: 4 (UNKNOWN: 0, LOW: 0, MEDIUM: 4, HIGH: 0, CRITICAL: 0)
┌────────────────────┬───────────────┬──────────┬────────┬───────────────────┬──────────────────┬───────────────────────────────────────────┐
│      Library       │ Vulnerability │ Severity │ Status │ Installed Version │  Fixed Version   │                   Title                   │
├────────────────────┼───────────────┼──────────┼────────┼───────────────────┼──────────────────┼───────────────────────────────────────── …
```
> [Forwardport] [NPM] [CVE] Resolve CVE-2025-6020

- .pipelines/run-pipeline.yaml
- .pipelines/templates/run-unit-tests.stages.yaml
- Removes the file copy of the coverage-all.out file from the run unit tests stage.
- Adds the image build steps to the regular pipeline execution.
There is an error on the file copy because the cover-all.out is not generated by the Official or Unofficial builds. Removing the copy should fix this.
The images aren't currently built during general pipeline execution. This will allow us to make sure that we are able to build images when changes are submitted.
**Notes**:
> ci: Remove File Copy and Add Image Build Stage to Regular Build

- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/testutils_linux.go
- npm/util/const.go
Updates iptables to `legacy` fix crashloopbackoffs in `CBL-Mariner/Linux` nodepools.
NPM's Ubuntu base image was recently updated to `24.04` from `20.04` as the older version was EOL (see: https://github.com/Azure/azure-container-networking/pull/3743). There was a behavioral change between the 2 Ubuntu versions that required NPM to specify `legacy` for its Iptables. 
`Error: failed to create dataplane with error Operation [BootupDataplane] failed with error code [999], full cmd [], full error failed to reset policy dataplane: Operation [BootupPolicyManager] failed with error code [999], full cmd [], full error failed to bootup policy manager: failed to detect iptables version: unable to locate which iptables version kube proxy is using` …
> [NPM] fix: Update Iptables to Legacy

- .pipelines/templates/run-unit-tests.yaml
> [backport] #3791 ci: only check for code coverage at merge, not release

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/cilium/nightly-release-test.yml
- .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
- .pipelines/networkobservability/pipeline.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
- .pipelines/templates/cilium-connectivity-tests.yaml
- .pipelines/templates/cilium-tests.yaml
> ci: cleanup Cilium cli and connectivity test usage

- network/secondary_endpoint_client_linux.go
- network/secondary_endpoint_linux_test.go
* fix: dhcp error message to include kubelet err msg
* Update network/secondary_endpoint_client_linux.go
**Notes**:
> [backport] perf: dhcp err msg  in network swiftv2 code path (#3793)

- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/testutils_linux.go
- npm/util/const.go
Forwardport the bug fix made in https://github.com/Azure/azure-container-networking/pull/3782 to master branch.
Updates iptables to `legacy` fix crashloopbackoffs in `CBL-Mariner/Linux` nodepools.
NPM's Ubuntu base image was recently updated to `24.04` from `20.04` as the older version was EOL (see: https://github.com/Azure/azure-container-networking/pull/3743). There was a behavioral change between the 2 Ubuntu versions that required NPM to specify `legacy` for its Iptables. 
`Error: failed to create dataplane with error Operation [BootupDataplane] failed with error code [999], full cmd [], full error failed to reset policy dataplane: Operation [BootupPolicyManager] failed with error code [999], full cmd [], full error failed to bootup policy …
> [Forwardport] [NPM] fix: Update Iptables to Legacy (#3782)

- .pipelines/build/generate-manifest.steps.yaml
- .pipelines/build/image.steps.yaml
- .pipelines/build/images.jobs.yaml
- .pipelines/build/ob-prepare.steps.yaml
- .pipelines/run-pipeline.yaml
The ADO build pipeline is currently blocked with a reference to a "acn-devops" repo which is not refenced in the main pipeline file (in the ADO repository).
This PR reverts this reference. It also implements a fix for a building all the images in the OneBranch ADO pipeline.
No GitHub issue associated to this PR.
**Notes**:
> ci: Unblocking ADO build pipeline

- .pipelines/cni/pipeline.yaml
```
ERROR: (Windows2019NotSupportedWithOrchestratorVersion) Cannot create Windows2019 node pools with the current Kubernetes version "1.33.1" because Windows2019 was deprecated after Kubernetes version "1.33.0". Please create Windows2022 node pools instead.
Code: Windows2019NotSupportedWithOrchestratorVersion
Message: Cannot create Windows2019 node pools with the current Kubernetes version "1.33.1" because Windows2019 was deprecated after Kubernetes version "1.33.0". Please create Windows2022 node pools instead.
```
not supported with latest pipeline k8s, removing cluster create/test from pipeline
**Notes**:
> ci: remove windows2019 from release test pipeline

- .github/dependabot.yaml
Removes deprecated `reviewers` field and add `release/v1.6` label to relevant Dependabot PRs
**Notes**:
> chore: add label and remove reviewers

- .github/CODEOWNERS
- .pipelines/build/dockerfiles/azure-iptables-monitor.Dockerfile
- .pipelines/build/ob-prepare.steps.yaml
- .pipelines/build/scripts/azure-iptables-monitor.sh
- .pipelines/pipeline.yaml
- .pipelines/run-pipeline.yaml
- azure-iptables-monitor/Dockerfile
Adds image publishing for azure iptables monitor to ACN Official Build pipeline and ACN PR pipeline
Merge after #3779
**Notes**:
ACN PR: https://msazure.visualstudio.com/One/_build/results?buildId=129848847&view=results
ACN Build Pipeline: https://dev.azure.com/msazure/One/_build/results?buildId=129816140&view=results
ACN Unofficial Build: https://msazure.visualstudio.com/One/_build/results?buildId=129854515&view=results
which feeds into ACN Buddy Image Release: https://dev.azure.com/msazure/One/_build/results?buildId=129977665&view=results
After rebase:
ACN PR: https://msazure.visualstudio.com/One/_build/results?buildId=132175501&view=results
ACN Unofficial Build: https://msazure.visualstudio.com/One/_build/results?buildId=13217580 …
> ci: add azure iptables monitor pipeline

- .pipelines/npm/npm-conformance-tests-latest-release.yaml
- .pipelines/npm/npm-conformance-tests.yaml
Removes the NPM Windows 2022 tests from the NPM conformance test pipeline runs. 
Recently the NPM conformance tests have experienced a `[TIMEDOUT]` error for the Windows 2022 tests. This is causing NPM-related PRs to be delayed due to flaky/inconsistent pipeline runs. We do not need to verify NPM Windows scenarios in the conformance test as we aren't supporting Windows or planning to ever cut a new release. This change streamlines the NPM conformance test runs to test NPM Linux which is the only supported NPM version outside of NPM-Lite which runs different tests to validate.
**Notes**:
> chore: Remove NPM Windows 2022 Tests from the NPM Conformance Tests

- .pipelines/build/scripts/azure-ip-masq-merger.sh
- .pipelines/build/scripts/azure-ipam.sh
- .pipelines/build/scripts/cni.sh
- .pipelines/build/scripts/cns.sh
- .pipelines/build/scripts/dropgz.sh
- .pipelines/build/scripts/ipv6-hp-bpf.sh
- .pipelines/build/scripts/npm.sh
- Makefile
- azure-ip-masq-merger/Dockerfile
- azure-ipam/Dockerfile
- bpf-prog/ipv6-hp-bpf/linux.Dockerfile
- cni/Dockerfile
- cni/Dockerfile.tmpl
- cns/Dockerfile
- cns/Dockerfile.tmpl
- npm/linux.Dockerfile
- npm/windows.Dockerfile
In a distroless environment we lose the need for debug symbols to be present on binaries. Debug symbol removal from binaries generally saves 20%-35% of HDD space.
For comparison linux/amd64 bins
CNS 91MB v 63MB
CNI 82MB v 56MB
IPAM 49MB v 34MB
NPM 66MB v 45MB
ipv6-hp-bpf 8MB v 5.3MB
azure-ip-masq-merger 20MB v 13MB
**Notes**:
Want to move to leveraging our make commands for binary generation. This is a placeholder until that effort can be picked up.
> feat: Remove symbols from all binaries

- .pipelines/singletenancy/aks-swift/e2e.stages.yaml
- .pipelines/singletenancy/aks/e2e.stages.yaml
- .pipelines/singletenancy/azure-cni-overlay-stateless/azure-cni-overlay-stateless-e2e.stages.yaml
- .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e.stages.yaml
- .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.stages.yaml
- .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e.stages.yaml
- .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.stages.yaml
- .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.stages.yaml
- .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e.stages.yaml
Upstream validation changes now capture for these fields
**Notes**:
> ci: remove stage level pool field, isCustom, from e2e job templates

- aitelemetry/telemetrywrapper.go
- aitelemetry/telemetrywrapper_linux.go
- aitelemetry/telemetrywrapper_windows.go
- cns/configuration/configuration.go
- cns/logger/cnslogger.go
- cns/logger/log.go
- cns/logger/v2/config.go
- cns/logger/v2/cores/ai.go
- cns/logger/v2/cores/etw_windows.go
- cns/logger/v2/cores/file.go
- cns/logger/v2/cores/stdout.go
- cns/logger/v2/fields.go
- cns/logger/v2/logger.go
- cns/logger/v2/logger_linux.go
- cns/logger/v2/logger_windows.go
- cns/logger/v2/shim.go
- cns/service/main.go
backport loggerv2 to 1.6 release
> backport: feat: cns logger v2 [2/2] (#3438)

- npm/linux.Dockerfile
Resolves `CVE-2025-40909` in the `perl-base` library in NPM base Ubuntu image.
`v1.6.32 (Current NPM Image):`
```
mcr.microsoft.com/containernetworking/azure-npm:v1.6.32 (ubuntu 24.04)
======================================================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
┌───────────┬────────────────┬──────────┬────────┬─────────────────────┬─────────────────────┬────────────────────────────────────────────────────────────┐
│  Library  │ Vulnerability  │ Severity │ Status │  Installed Version  │    Fixed Version    │                           Title                            │
├───────────┼────────────────┼──────────┼────────┼─────────────────────┼─────────────────────┼──────────────────────────────────────────────────── …
```
> [NPM] [Vulnerability] Resolve CVE-2025-40909 in perl-base Library

- npm/linux.Dockerfile
Reverts manual package installations made to the NPM Linux dockerfile for `libsystemd0, libudev1, libpam-modules, libpam-modules-bin, libpam-runtime, libpam0g`. These changes were made as NPM base image (Ubuntu) did not have the updated packages installed which lead to CVEs on the base image. Ubuntu has since been patched to have the CVEs resolved so there is no need to manually install the packages at a specific version.
**Notes**:
> revert: Revert Manual NPM Linux Dockerfile Package Installations (libsystemd0, libudev1, libpam-modules, libpam-modules-bin, libpam-runtime, libpam0g)

- npm/linux.Dockerfile
Reverts manual package installations made to the NPM Linux dockerfile for perl-base `5.38.2-3.2ubuntu0.2` made here https://github.com/Azure/azure-container-networking/pull/3922. These changes were made as NPM base image (Ubuntu) did not have the updated packages installed which lead to CVEs on the base image. Ubuntu has since been patched to have the CVEs resolved so there is no need to manually install the packages at a specific version.
Trivy:
```
isaiah@CPC-isaia-1HIMP:~/AzureRepo/azure-container-networking$  trivy --scanners vuln image  --ignore-unfixed -f table  acnpublic.azurecr.io/azure-npm:pertBaseRemoved
2025-08-13T18:21:05Z    INFO    [vuln] Vulnerability scanning is enabled
2025-08-13T18:21:08Z    INFO    Detected OS     family="ubuntu" version="24.04" …
```
> revert: Revert Manual NPM Linux Dockerfile perl-base Package Installation

- crd/overlayextensionconfig/api/v1alpha1/overlayextensionconfig_types.go
- crd/overlayextensionconfig/manifests/acn.azure.com_overlayextensionconfigs.yaml
feat: Add App Gateway Subnet ID as a field to the Overlay Extension Config CRD
N/A
**Notes**:
> feat: Add App Gateway Subnet ID as a field to the Overlay Extension Config CRD

- Makefile
- azure-iptables-monitor/Dockerfile
- bpf-prog/azure-block-iptables/cmd/azure-block-iptables/main.go
- bpf-prog/azure-block-iptables/cmd/azure-block-iptables/main_test.go
- bpf-prog/azure-block-iptables/pkg/bpfprogram/interface.go
- bpf-prog/azure-block-iptables/pkg/bpfprogram/program.go
- cni/Dockerfile
- cns/Dockerfile
This PR incorporates the azure-block-iptables binary into the azure-iptables-monitor image. We originally were planning to deploy this binary as a systemd service through AgentBaker. However, @paulgmiller pointed out a limitation of doing so, which meant that we'd be forced to do node rotations when enabling/disabling eBPF host routing.
To avoid node rotations, we are now planning to install the iptables rule blocking from an init container in the CNS daemonset. Once the init container runs, it installs the LSM BPF program to block iptables rule installation, and additionally pins the link to the filesystem. This means that even after the init container finishes, iptables rules can't be installed in the host network namespace, unless explicitly allowed by our …
> feat: include iptables block binary in iptables monitor image

- cns/fakes/iptablesfake.go
- cns/restserver/internalapi_linux.go
- cns/restserver/internalapi_linux_test.go
- cns/restserver/internalapi_windows.go
- cns/restserver/restserver.go
Contains same changes as #3930 but without the behavioral change of snat to node ip
Deletes iptables legacy jump to swift postrouting rule **before** adding nftables rules because:
If we delete before:
If iptables maps to iptables nftables, we should already have nftables rules programmed on the node because cns 1.7.1 has fully rolled out, so deleting first should not cause any connectivity blip.
If iptables somehow maps to iptables legacy, we have a blip and then write the rule immediately after
If we delete afterwards:
If iptables maps to iptables nftables, we write the rules and delete the legacy jump after as expected
If iptables somehow maps to iptables legacy, we would add the rules and then delete the jump we just added, breaking the node until the cns …
> feat: remove jump to swift-postrouting in iptables legacy as rules already exist in iptables nftables

- .pipelines/templates/run-unit-tests.stages.yaml
We introduced bpf code as part of the iptables block binary, that relies on code generation. We updated run-unit-tests.yaml, which is used by the UT runs on the PR pipeline, to have the extra code generation steps.  But the signed binary release uses run-unit-tests.stages.yaml, which wasn't updated. This PR adds the code generation to that file as well.
**Notes**:
> fix: add code generation to run-unit-tests.stages

- .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
- .pipelines/cni/pipeline.yaml
- .pipelines/cni/singletenancy/cniv2-template.yaml
- .pipelines/npm/npm-cni-integration-test.yaml
- test/integration/manifests/cilium/v1.17/cilium-config/cilium-config.yaml
Allows for bumping the cns version in the release pipeline byo clusters to test upgrades to the next version. CNS patch test is already in place for cilium scenarios, this PR extends it to the CNIv2 scenarios.
Requires setting upgradeScenario: true in pipeline trigger and updating the following variables:
- `TEST_CNS_VERSION`: set to current cns patch
- `CNS_IMAGE_REPO`: set the repo for current cns image
- `UPGRADE_CNS_VERSION`: set to upgrade cns patch
- `UPGRADE_CNS_IMAGE_REPO`: set the repo for upgrade image
Continuation of #3678 
**Notes**:
> ci: cns patch testing in release pipeline

- cns/fakes/iptablesfake.go
- cns/restserver/internalapi_linux.go
- cns/restserver/internalapi_linux_test.go
Changes the ip CNS-added IPTables rules SNAT to from the primary ip to node ip for **linux** podsubnet scenarios (both azure and cilium cases). CNI-added iptables rules are not modified and windows behavior remains the same (will be modified in a future PR).
**Notes**:
Tested:
- Podsubnet linux upgrade from 1.7.3 --> this version --> downgrade to 1.7.3 and dns snat is as expected
- Podsubnet linux cilium ugprade from 1.7.3 --> this version --> downgrade to 1.7.3 and dns snat is as expected
> feat: snat azure dns traffic to node ip in cns linux

- azure-ipam/ipam.go
- azure-ipam/ipam_test.go
- azure-ipam/ipconfig/ipconfig.go
- cns/NetworkContainerContract.go
- cns/kubecontroller/nodenetworkconfig/conversion.go
- cns/kubecontroller/nodenetworkconfig/conversion_linux.go
- cns/kubecontroller/nodenetworkconfig/conversion_test.go
- cns/kubecontroller/nodenetworkconfig/conversion_windows.go
- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/kubecontroller/nodenetworkconfig/reconciler_test.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_linux.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/util.go
- cns/service/main.go
Current Problem: 
VNET currently limits scaling to 64K IP addresses per VNET due to per-IP route mappings. To support larger AKS clusters, the platform is introducing per-prefix (CIDR) route mapping, allowing a single mapping to represent multiple IPs (e.g., /24 enables 256 IPs per mapping). This enables scaling up to 16 million IPs per VNET without impacting the underlying platform.
Change needed:
Prefix on NIC v4 is supported in Swiftv1, but Swiftv1 does not support IPv6. This change upgrades Prefix on NIC v4 functionality to Swiftv2 and introduces IPv6 support in Swiftv2.
Changes
This PR has changes specific to Prefix on NICv6
CNS
--Consuming PrimaryIPv6, GatewayIPv6, MacAddress (DelegatedNIC) from NNC CRD because of dualstack NC
--IP allocation: Assign IPs of …
> Prefix on nicv6 support

- .pipelines/cni/cilium/nightly-release-test.yml
unblock operator image build by setting GOEXPERIMENT arg to boringcrypto
**Notes**:
> fix: cilium nightly pipeline set boringcrypto arg in build
