Azure/azure-container-networking

- cni/network/network.go
Bounds check the ContainerID before using it.
Fixes #58
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> cni: Bounds check the ContainerID before using it

- cni/ipam/ipam.go
- cni/network/network.go
- cni/plugin.go
- ipam/api.go
- ipam/manager.go
- ipam/pool.go
Adds ability to add a generic identifier to each address request. This identifier is associated and persisted with the allocated address. IPAM client can later use the same identifier to request the same address.
This ensures state integrity if the client misbehaves or crashes after an address request succeeds but before the client had a chance to persist its state. Successive calls by the client will not leak addresses as long as it uses the same identifier.
The generic identifier can be set to any string as the client sees fit. This change also updates the CNI IPAM plugin to pass the endpoint ID as the identifier, allowing us to later track which IP address was assigned to which container endpoint.
> Store an identifier in address records to track address requests

- cnm/ipam/ipam.go
- cnm/ipam/ipam_test.go
- ipam/pool.go
Added reservation id support in IPAM to enable user to tag an ID against IP Address. This will be helpful when IP request transaction is committed in IPAM but the user didn't receive IP Address due to some reason. The user can avail the same address by issuing request address again with the same reservation id
> Added reservation support in IPAM

- cnm/ipam/api.go
- cnm/ipam/ipam.go
- cnm/ipam/ipam_test.go
- ipam/manager.go
- ipam/pool.go
The option field allows the user to release the address by specifying reservation id alone. The id to address mapping will be handled by ReleaseAddress function.
> Added options in release address to support release address with id

- log/logger.go
- log/logger_linux.go
- log/logger_test.go
- log/logger_windows.go
- log/stdapi.go
Rotates log files when they reach the size limit, keeps the last n files.
> Add support for log file rotation

- cnm/ipam/api.go
- cnm/ipam/ipam.go
- cnm/ipam/ipam_test.go
Made Ipam API path, request and response structures as public so that Ipamclient can make use of those structures and variables without duplicating it. Ipam client can import Ipam package and access those structures and path.
> Exposed IPAM API path and structures as public

- cns/ipamclient/ipamclient.go
- cns/ipamclient/ipamclient_linux.go
- cns/ipamclient/ipamclient_windows.go
- cns/restserver/restserver.go
- cns/routes/routes_linux.go
Modified CNS to support ipamclient for both Linux and windows. In Linux ipamclient connects to server via unix domain socket and in windows via tcp socket. Tested the functionality of cns in both Linux and windows.
> Added support for Ipamclient in Linux in CNS

- CHANGELOG.md
I believe the author likely meant "idempotent" not "omnipotent".
> Change word choice on CHANGELOG

- cnm/plugin.go
- cns/api.go
- cns/dockerclient/api.go
- cns/dockerclient/dockerclient.go
- cns/restserver/restserver.go
- cns/service/main.go
This PR contains support for allowing outbound connectivity from containers by enabling SNAT and by specifying bridge mode from CNS instead of default tunnel mode. The azure-vnet and ipam plugin will also be started as part of CNS
> Outbound connectivity from containers

- cni/network/network.go
- ipam/pool.go
- netlink/link.go
- network/endpoint.go
This fix makes sure that there is no ip address leak even if delete endpoint(removing veth pair and resources) fails. It assumes container namespace would have been removed already and will invoke ipam release call to release ip address and other resources
> CNI should invoke ipam release call even if delete endpoint fails

- telemetry/telemetry.go
Added logging for HTTP 400 error. This error can be ignored as it won't affect CNI functionality. This will get resolved when telemetry is activated
> Added logging for HTTP 400 error

- network/endpoint.go
- network/endpoint_linux.go
- network/endpoint_windows.go
**What this PR does / why we need it:**
1. Enable outboundNAT for Windows containers.
2. Handle consecutive ADD calls for the same container. 
3. Handle attach endpoint for workload containers.
Related issue: [https://github.com/kubernetes/kubernetes/issues/57253](url)
> Enable outboundNAT for Windows containers.

- telemetry/telemetry.go
- telemetry/telemetry_linux.go
- telemetry/telemetry_windows.go
This PR contains minimal support for windows telemetry so that we can track number of VMS running CNI. Still, some work pending(retrieving system/os details) to be done for windows telemetry
```release-note
```
> VSTS#1748724 Minimal Support for Windows Telemetry

- cni/ipam/ipam.go
This PR removes setting reservation id by default in CNI. Because this is conflicting with the support added for reboot scenario in this PR #98 
```release-note
```
> removed reservation id inclusion from CNI

- cni/plugin.go
- cnm/plugin/main.go
- cns/service/main.go
- common/utils.go
- ipam/manager.go
- ipam/pool.go
- network/manager.go
- network/network_linux.go
- platform/os_linux.go
- platform/os_windows.go
- telemetry/telemetry.go
This PR supports recreating the network that exists before reboot. The CNM will read the state and recreate network if necessary.
**Which issue this PR fixes** #
The issue is that docker remembers the network after reboot but CNM doesn't. This PR will fix that inconsistency and will recreate the network after reboot.
This PR also fixes a bug in reservation id.
If an ip is reserved, it will be marked use by default and the cannot be used with docker run --ip. This PR fixes this issue so that address won't be marked use at the time of reservation.
```release-note
```
> Added support for cnm reboot scenario

- cns/api.go
- cns/dnccontract.go
Renaming NetworkContainerOrchestratorInfo to OrchestratorInfo and modifying its contents to be more generic.
> Renaming and modifying NetworkContainerOrchestratorInfo

- cns/dnccontract.go
- cns/restserver/api.go
- cns/restserver/restserver.go
- cns/restserver/restserver_test.go
This PR adds GetNetworkContainerByContext api which retrieves network configuration based on orchestrator context. In case of kuberenetes, the context includes podname and podnamespace.
Also Added corresponding unit tests to validate the basic functionality
```release-note
```
> Added GetNetworkContainerByContext Api

- client/cnsclient/cnsclient.go
- cni/network/network.go
- cni/plugin.go
- cns/restserver/api.go
- cns/service/main.go
- common/config.go
This PR adds support for CNI to query and get network config based on podname and namespace. Also added an option in cns to not to start cnm by default.
```release-note
```
> CNI gets networkconfig from CNS 

- cns/dnccontract.go
- cns/restserver/restserver.go
Based on the network container type, it will call netagent networkcontainer.exe otherwise it saves the state and exits 
```release-note
```
> check for network container type

- cni/network/plugin/main.go
- telemetry/telemetry.go
This PR adds a CniSucceeded flag as part of the telemetry report set to HostNetAgent.
> Adding CniSucceeded flag to report whether CNI had been run successfully.

- cns/restserver/restserver.go
Adding this to resolve invalid orchestrator type error when sending WebApps request.
> Adding check for WebApps orchestrator type.

- cns/dnccontract.go
- cns/restserver/restserver.go
Renaming VnetAddressSpace to CnetAddressSpace since all traffic shod be sent to loopback adapter not just Vnet space.
> Renaming VnetAddressSpace to CnetAddressSpace

- cni/network/network.go
- network/api.go
- network/endpoint_linux.go
Generate VethName based on podname and namespace in CNI. The function will generate hash of the key provided and return first 11 characters of hash. The key is "podname.podnamespace" in CNI.  
```release-note
```
> Generate VethName based on podname and namespace in CNI

- cni/network/network.go
This PR adds kubernetes pod's namespace to dns suffix on Windows platform so that service name can be resolved by kube-dns.
> add k8s pod namespace to dns suffix

- cns/dockerclient/dockerclient.go
- cns/imdsclient/imdsclient.go
- cns/ipamclient/ipamclient.go
- telemetry/telemetry.go
Closing response bodies to prevent socket exhaustion.
> Closing response bodies to prevent socket exhaustion.

- cni/cni.go
- cni/ipam/ipam.go
- cni/network/network.go
- cni/network/plugin/main.go
- cni/plugin.go
- network/endpoint.go
- network/endpoint_linux.go
- network/endpoint_windows.go
CNI spec has added a new method : GET which allows the runtime / orchestrator to query the current state of the container networking configuration. This change adds the implementation for the GET method in azure-vnet plugin. The supported version changes to 0.4.0 to support GET API.
This PR fixes #148
> azure-vnet: Implement GET command

- cnm/plugin/main.go
- cns/service/main.go
- docs/cnm.md
Adds support for --ipam-query-url command line switch. Without this is not possible to specify IPAM server URL from command line.
> Added support for --ipam-query-url command line switch

- telemetry/telemetry_linux.go
Use /etc/os-release instead of /etc/issue as a source for the osInfo because /etc/issue contains completely different lines depending on the linux distributive and fails on the CoreOS.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #108 
Split PRs as required
```release-note
Fixed the osinfo source.
```
> Fixed the #108 issue.

- scripts/install-cni-plugin.sh
Fix typo for clean execution for CNI install script, changed *.conf to *.conflist
```release-note
```
> Fix typo in CNI install script

- ipam/manager.go
- log/logger.go
- log/logger_linux.go
- log/logger_windows.go
- network/manager.go
- platform/os_linux.go
- platform/os_windows.go
- store/json.go
This PR fixed the issue raised in acs-engine #3121 . It converts both reboot and file modification time to UTC .
```release-note
```
> Convert time to UTC

- cns/routes/routes_test.go
On a linux machine, the go test fails for cns/routes because `cmd` is not found:
```
$ go test github.com/Azure/azure-container-networking/cns/routes
2018/06/08 01:54:56 Test: PutMissingRoutes
2018/06/08 01:54:56 [Azure CNS] Adding missing route: [/C route ADD 159.254.169.254 MASK 255.255.255.255 0.0.0.0 METRIC 12]
2018/06/08 01:54:56 [Azure CNS] Failed to execute add route: [/C route ADD 159.254.169.254 MASK 255.255.255.255 0.0.0.0 METRIC 12]
exec: "cmd": executable file not found in $PATH
2018/06/08 01:54:56 [Azure CNS] Deleting route: [/C route DELETE 159.254.169.254 MASK 255.255.255.255 0.0.0.0 METRIC 12]
2018/06/08 01:54:56 [Azure CNS] Failed to execute delete route: [/C route DELETE 159.254.169.254 MASK 255.255.255.255 0.0.0.0 METRIC 12]
exec: …
```
> mark routes_test as windows build

- log/logger.go
- log/stdapi.go
This should prevent issues when multiple threads are using the same logger instance.
> Locking loggers in case of multi-threaded apps.

- cni/network/network.go
This PR fixes the CNI plugin crash when error returned in some cases. The issue was raised in acs-engine #176 
```release-note
```
> Fix for the github acsengine issue #176

- cns/ipamclient/ipamclient.go
- cns/ipamclient/ipamclient_test.go
The `ipamclient_test.go` was using undefined variables.
```
$ go test github.com/Azure/azure-container-networking/cns/ipamclient
./ipamclient_test.go:30: undefined: getAddressSpacesPath
./ipamclient_test.go:31: undefined: requestPoolPath
./ipamclient_test.go:32: undefined: reserveAddrPath
./ipamclient_test.go:33: undefined: releaseAddrPath
./ipamclient_test.go:34: undefined: getPoolInfoPath
FAIL    github.com/Azure/azure-container-networking/cns/ipamclient [build failed]
```
This is addressed with the first commit of this PR 8123f3bbc91597cff121956012d42d7ca48a2712
Also, `ipamclient.go` had a nil pointer dereference on non-200 results code responses.
```
$ go test github.com/Azure/azure-container-networking/cns/ipamclient
2018/06/08 04:21:25 …
```
> fix ipamclient failures

- network/network_windows.go
This is a workaround for windows CNI, where the platform need some delay before cni starts creating endpoint on a newly created network.
The second change is to remove the networkAdapterName
The next change is to use the latest compile with latest CNI
This workaround is needed only for 1803 & below
```release-note
```
> Add workaround for windows network creation

- cni/plugin.go
Fixes https://github.com/Azure/azure-container-networking/issues/178
```release-note
```
> Fix to use latest cni for building

- cns/restserver/restserver.go
Adding check to prevent AzureNetworkContainer.exe from running if nc exists and the version has not changed.
> Adding check to prevent duplicate Network Container creation

- Makefile
- cni/network/network.go
- cni/network/plugin/main.go
- npm/Dockerfile
- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/iptm/iptm.go
- npm/iptm/iptm_test.go
- npm/namespace.go
- npm/namespace_test.go
- npm/npm.go
- npm/nwpolicy.go
- npm/nwpolicy_test.go
- npm/parse.go
- npm/plugin/main.go
- npm/pod.go
- npm/pod_test.go
- npm/util/const.go
- npm/util/util.go
- platform/os_linux.go
- platform/os_windows.go
- telemetry/telemetry.go
- telemetry/telemetry_linux.go
- telemetry/telemetry_test.go
- telemetry/telemetry_windows.go
This PR adds Azure Network Policy Manager, a.k.a, azure-npm, to Azure CNI.
Azure-npm is a Microsoft Azure's fault-tolerant and scalable implementation of [Kubernetes Network Policy plugin](https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/).
Azure-npm supports all [network policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) specified by current version of Kubernetes, and will continue to support future versions.
Azure-npm only supports [Kubernetes v1.8](https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/) or later, as it requires NetworkPolicy API v1beta1.
> Add Azure-npm to provide k8s network policy support

- Dockerfile.build
This PR updates build image to fetch all dependencies required to build Azure-npm in a docker container.
> update build image

- Makefile
This PR enforces GNU make to build Azure-npm only for Linux platform.
> only build npm for Linux

- Dockerfile.build
- Makefile
- build/build-all-containerized.sh
This PR enables containerized build to build images.
> Make all images

- Makefile
- build/build-all-containerized.sh
This PR removes stale container while in the build process.
Previously there will be a stale container for failed Jenkins build. This will prevent next build from happening. This PR removes stale container while in the build process.
> Smooth build process

- network/endpoint.go
- network/endpoint_linux.go
- network/endpoint_windows.go
- network/manager.go
This PR fixes leaking IPs if netns is empty. In that case, endpointID is returned empty and call to ipam resource cleanup is not happening
```release-note
```
> Generating EndpointID should not rely on netns in Linux

- network/endpoint_windows.go
This PR handles the "" string case. This change can prevent "endpoint not found" error and prevent ip exhaustion.
> Fix ConstructEndpointID

- cni/network/network.go
This PR fixes the unparseable error returned by Azure CNI (#195 ). Azure CNI should write result to stdout only in successful case
```release-note
```
> Fix for unparseable error returned by Azure CNI

- cns/NetworkContainerContract.go
- cns/restserver/restserver.go
Add ClearContainer as network container type and
ServiceFabric as orchestrator type.
This is needed for Service Fabric
> Add new networkcontainer and orchestrator types

- cni/network/network_windows.go
- network/endpoint_windows.go
1. Return error if hotadd fails so that all resources will be cleaned up.
2. If endpoint not found on second add call, return error
```release-note
```
> Fixed windows CNI issues

- cni/network/plugin/main.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
Moving dnc specific material out.
> Moving dnc specific material out.

- cni/azure-linux-multitenancy.conflist
- cni/network/mutlitenancy.go
- network/epcommon/endpoint_common_linux.go
Block apipa address going via snat bridge
```release-note
```
> Block apipa address 

- telemetry/telemetry.go
- telemetry/telemetry_windows.go
Removing CNI specific logging from generic SendReport function.
> Removing CNI specific logging from generic SendReport function.

- cni/plugin.go
- netlink/ip.go
- netlink/link.go
- netlink/netlink.go
- netlink/netlink_test.go
- netlink/netlink_windows.go
- netlink/protocol.go
- netlink/socket.go
- network/endpoint_linux.go
- network/endpoint_windows.go
- network/epcommon/endpoint_common_windows.go
- network/namespace_linux.go
- network/network_linux.go
- network/network_windows.go
- store/json.go
- store/store.go
Signed-off-by: John Howard <jhoward@microsoft.com>
Fixes https://github.com/Azure/azure-container-networking/issues/242
- First, the store timeout is woefully low. Bumped to 20 seconds from 2 seconds.
This appears to fix https://github.com/Azure/azure-container-networking/issues/242#issuecomment-422701838
IMO, as only test code calls it non-blocked, why even have a block parameter to Lock()?
IMO also, why a timeout at all? They're always fraught with error and machine timing.
- Presence of a key should be checked using `raw, ok := hvs.data[key]`, not the current nil checked
- ErrKeyNotFound should be returned if the store file does not exist. It shouldn't ignore that error.
- Actually now reports if a timeout occurred correctly, along with non-block lock attempt when already locked.
- …
> Store fixes; Windows compile

- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
- network/network_windows.go
This PR removes HNSNetwork's DNS suffix in Windows. Previously, the HNSNetwork's DNS suffix gets overwritten by newly created HNSEndpoint's DNS suffix. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #245
> Remove HNSNetwork's DNS suffix in Windows

- .circleci/config.yml
- npm/iptm/iptm.go
- npm/namespace_test.go
- npm/nwpolicy_test.go
- npm/pod_test.go
This PR:
1. Changes the order of Azure-NPM for applying network policies from FIFO to LIFO.
As per @neumanndaniel suggested, kubernetes administrators/network operators usually apply a deny-all policy then whitelist certain traffic. Without this PR to achieve this, one would have to whitelist all traffic first then apply the deny-all policy. 
2. Adds Azure-NPM to CircleCI config for CI/CD.
**Which issue this PR fixes**: 
Fixes #217
This is a change of behavior, not a bug fix.
> LIFO order for network policies

- cni/azure-windows.conflist
- cni/netconfig.go
- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
Rebase of https://github.com/Azure/azure-container-networking/pull/253
Azure CNI doesn’t program any port mappings. Its not supported in Azure CNI.
Earlier it worked because the port mapping was programmed through NAT network which was added by accident.
> Adding PortMapping support to Azure cni for Windows (Rebase).

- cni/cni.go
- cni/ipam/ipam.go
- cni/netconfig.go
- cni/network/mutlitenancy.go
- cni/network/network.go
- cni/network/plugin/main.go
- cns/service/main.go
- network/api.go
- network/endpoint.go
- network/endpoint_linux.go
- network/endpoint_windows.go
- network/manager.go
This PR adds capability in Azure CNI to update network config for a running container. We only supports updating routes for now in multitenancy mode. It does not require clients to delete and recreate containers to apply new config.
> Implement CNI update for Azure CNI

- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
- network/endpoint_windows.go
- network/manager.go
- network/network.go
- network/network_linux.go
- network/network_windows.go
- network/policy/policy.go
- network/policy/policy_windows.go
This change allows containers from different vnets to reside in a VM that belongs to a completely different infra-vnet. The isolation is achieved using vlan.
Multitenancy and snatonhost can be enabled using flags in azure conflist file. When multitenancy is enabled, CNI depends on CNS to get the goal state for the network container which includes the allocated IP.
> Implement multitenancy for windows

- cni/azure-windows-multitenancy.conflist
- network/endpoint_windows.go
- network/network_windows.go
- network/policy/policy.go
- network/policy/policy_windows.go
Handle the OutBoundNAT policy with a dedicated logic as a part of policies' serialization
> Fix Endpoint policy regression

- cns/networkcontainers/networkcontainers.go
- telemetry/telemetry.go
- telemetry/telemetrybuffer.go
- telemetry/telemetrybuffer_linux.go
- telemetry/telemetrybuffer_windows.go
> Adding telemetry buffer.

- netlink/link.go
- netlink/netlink_test.go
- netlink/protocol.go
- network/bridge_endpointclient_linux.go
This PR fixes the issues where sometimes packet is getting routed to host instead of pod. Setting static arp entry will prevent vm getting arp responses from host
```release-note
```
> Adding/Remove static arp entry for pod IP in VM 

- cnm/ipam/ipam.go
- cnm/network/network.go
- cnm/plugin.go
- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient.go
- cns/dockerclient/dockerclient.go
- cns/restserver/api.go
- cns/restserver/restserver.go
- cns/routes/routes_windows.go
- cns/service.go
- cns/service/main.go
- common/config.go
- log/logger.go
- log/stdapi.go
- platform/os_linux.go
- platform/os_windows.go
- telemetry/cnstelemetry.go
- telemetry/telemetry.go
- telemetry/telemetrybuffer.go
Adding telemetry capabilities for CNS.
> Cns telemetry

- ipam/manager.go
- network/manager.go
- platform/os_linux.go
- platform/os_windows.go
Sometimes issue is seen after reboot when the network config state is not
cleaned up. This change detects reboot and cleans up the network config state.
> Detect reboot for windows and cleanup network config

- cni/plugin.go
- ipam/manager.go
- network/manager.go
- platform/os_windows.go
- store/json.go
- store/json_test.go
- store/store.go
After detecting reboot, old networks need to be deleted along with
lock files left behind on the VM.
> Cleanup old networks and lock files after detecting reboot

- store/json.go
When many pods are scheduled simultaneously, locking the store times out.
This is expected as each process needs exclusive lock while modifying the lock file.
In doing so, the lock file timestamp is changed. Update to this timestamp indicate
process(es) are actively using CNI plugin. The lock retry count is reset if the process
detects this change. As a result, timeout will only happen if the process cannot lock the
store while it remain unchanged for the duration of the timeout.
> Reset lock retry count if lock file timestamp changes

- platform/os_windows.go
Using systeminfo to get boot time is causing a delay.
Using wmic os get lastbootuptime instead which is much faster
> Change the implementation of Get boot time

- cni/network/plugin/main.go
- cni/telemetry/service/telemetrymain.go
- telemetry/telemetry_test.go
- telemetry/telemetrybuffer.go
1. fix for closing telemetry socket in cni
2. fix for closing telemetry socket in telemetry server when read fails to close connection socket
```release-note
```
> Close telemetry socket when its done

- cni/azure-windows.conflist
- cni/netconfig.go
- cni/network/network.go
- cni/network/network_windows.go
Co-authored-by: James Sturtevant <jstur@microsoft.com>
Adds dns [capability](https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md) for custom DNS, which is [only used on Windows](https://github.com/kubernetes/kubernetes/blob/7dbe426b2426458f02339e28d1cc102efdb6eda1/pkg/kubelet/dockershim/network/cni/cni.go#L104).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: https://github.com/kubernetes/kubernetes/issues/74541
```release-note
Add DNS capability for custom DNS on Windows
```
> Add dns capabilities to allow for custom dns in Windows

- telemetry/cnstelemetry.go
- telemetry/telemetry_test.go
- telemetry/telemetrybuffer.go
This PR fixes code coverage issue seen by #296 . The PR contains UT for server side closing connection first instead of client.
```release-note
```
> Added UT in telemetry code to fix code coverage

- cns/networkcontainers/networkcontainers_windows.go
We are locking the loopback adapter operations in this PR. In cases where simultaneous create/update/delete network container calls are processed, only 1 goroutine may execute the loopback adapter binary since the kernel cannot handle multiple loopback adapter operation calls at the same time.
> Locking loop-back adapter operations.

- npm/npm.go
- npm/plugin/main.go
- npm/util/util.go
On Azure-NPM restart events, the networkpolicies are delivered to Azure-NPM in a random order. This will result in undefined iptables behavior.
**Which issue this PR fixes** : fixes #313
> Handle failover scenarios

- cni/network/plugin/main.go
- cns/service/main.go
- common/config.go
- log/logger.go
- telemetry/cnstelemetry.go
- telemetry/telemetry.go
- telemetry/telemetrybuffer.go
- Instead of running telemetry buffer (server) on goroutine, we will spawn a separate process.
- Adding an option to disable telemetry when starting CNS (-telemetry=false)
> CNS to start telemetry process and connect to it

- cni/network/network.go
Cutting out Routes and DNS from EventMessage because it is cause HostNetAgent crash. This is a temporary/quick resolution to prevent NetAgent crash.
> Cutting out Routes and DNS from EventMessage

- cns/restserver/restserver.go
- platform/os_linux.go
- platform/os_windows.go
SDNRemoteArpMacAddress is the registry key for the remote mac address.
This is needed in case of multitenancy to get arp response from within VM.
This is achieved by setting In-VM arp responder that always responds with
a fake mac address.
```release-note
```
> Set SDNRemoteArpMacAddress regKey for windows multitenancy

- cni/network/network.go
- cnm/network/network.go
- network/endpoint.go
- network/endpoint_windows.go
CNM attaches endpoint separately as a part of Join request. This
change avoids the hot attach endpoint operation from CNM create
endpoint. CNI still performs hot attach endpoint as a part of create
endpoint.
```release-note
```
> Skip HotAttachEp from CNM createEndpoint

- cns/api.go
- cns/restserver/restserver.go
Create get, set and remove functions for service network state
operations. This acquires the service lock inside the functions.
```release-note
```
> Create functions for service network state

- telemetry/telemetrybuffer.go
Lowering telemetry buffer (maxy payload) size to 4096.)
> Lowering telemetry buffer (maxy payload) size to 4096.)

- npm/iptm/iptm.go
- npm/util/const.go
1. ip6table cmd support
2. wiat falg with timeout
This PR adds following support:
1. ip6tables command support without changing function signature
2. Wait flag with timeout parameter
3. Added few more constants to support specific iptable rules
```release-note
```
> Added more features in iptm package

- npm/iptm/iptm.go
This PR changes iptable indefinite wait lock to wait with default timeout as 60 seconds
```release-note
```
> Added iptable default wait lock timeout to 60 seconds

- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
Instead of basing HnsNetwork name on vlan, it's now created from subnet + prefix.
This is a temporary workaround until we can add/update HnsNetwork with multiple subnets.
e.g. azure-vlan1 -> azure-vlan1-172-28-1-0_24
> Divide hns network

- cns/hnsclient/hnsclient_windows.go
- platform/os_windows.go
Moving some Hns const variables so windows can compile.
> Moving some Hns const variables.

- network/network.go
- network/network_linux.go
This PR fixes cni issue with ubuntu 18 on addressing dns issues.
This fix enables resolving vmname from agent nodes
```release-note
```
> Set dns domain on azure0 interface for ubuntu version >= 17

- test/e2e/kubernetes/cniLinux18.json
Added ubuntu18 AKS config for doing e2e test in ubuntu 18
```release-note
```
> Added ubuntu18 AKS config for e2e test in ubuntu 18

- cni/network/network.go
- cni/network/network_windows.go
NetNs is an optional argument for deleting the network container.
If not specified, CNI logs the error and proceeds with deleting the
network container. In case of windows multitenancy, pod name
and pod namespace are required and it will return an appropriate
error.
> Delete container even if NetNs is not specified

- Makefile
- cni/telemetry/Dockerfile
- cni/telemetry/service/telemetrymain.go
- log/logger.go
- log/logger_test.go
- log/stdapi.go
- npm/Dockerfile
- npm/azure-npm.yaml
- npm/ipsm/ipsm.go
- npm/iptm/iptm.go
- npm/namespace.go
- npm/namespace_test.go
- npm/npm.go
- npm/nwpolicy.go
- npm/nwpolicy_test.go
- npm/parse.go
- npm/plugin/main.go
- npm/pod.go
- npm/pod_test.go
- npm/util/const.go
- telemetry/cnstelemetry.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
- telemetry/telemetrybuffer.go
This PR contains:
1. Changing the telemetrybuffer to message queue model. This is because in previous model, a burst of logs will be dropped since the previous buffer only holds up to 4KB. Now, the buffer holds up to 1MB and will send 4KB every 30 seconds in a FIFO order. The payload sent to host is crafted in a round-robin manner so that every component(DNC/CNI/CNS/NPM) will get its chance to send.
2. Enabling Azure-NPM telemetry.
Requires a new release after this PR is merged.
`NONE`
> change telemetry to message queue and add npm

- cns/NetworkContainerContract.go
- cns/restserver/restserver.go
Change basically adds a flag to indicate whether Host to NC Communication is needed or not. If yes, CNI will do the needful, otherswise regular workflow will be executed.
> CNS Changes to support Host to NC Communication 

- .circleci/config.yml
- cns/networkcontainers/networkcontainers.go
- We only want to return an error when CNI prints the Error struct to stdout. If the Error struct doesn't exist then the operation is considered successful.
- Updating Circle CI to use Golang v1.12.6
**Test**
Azure Batch has tested and confirmed that this resolved their problem with unmarshal errors affecting attach network API.
> Return Correct Invoke CNI Error

- network/endpoint_linux.go
This PR will fix issue referred in #356, #280 
```release-note
```
> Fix for CNM issue

- cni/telemetry/Dockerfile
- npm/Dockerfile
This PR updates base image for Azure-NPM and Azure-vnet-telemetry to Ubuntu 19.10.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
This version of Ubuntu fixes a [bzip2 vulnerability](https://lists.ubuntu.com/archives/ubuntu-security-announce/2019-June/004983.html).
None
```
None
```
> Update base image for Azure-NPM and Azure-vnet-telemetry

- cni/network/network.go
Variable err is overwritten in CNI functions - ADD, DEL, GET and UPDATE.
This causes the functions to return nil error even though there is
a valid error. This changes fixes the bug and returns the correct
error from CNI functions.
> Fix bug for returned error from CNI

- cns/api.go
- cns/restserver/api.go
- cns/restserver/restserver.go
- cns/restserver/restserver_test.go
Exposed a new API to get number of CPU Cores on a Node. This will be used by DNC eventually to enforce per node NIC limit which is dependent on number of cores.
DNC before allocating a NIC, will get query a node for number of cores and see if the limit ha already been achieved,
> Exposed a new API to get number of CPU Cores on a Node

- cns/service/main.go
- common/config.go
CNM starts by default when CNS starts. This change prevents CNM
from starting by default. stopcnm commandline option can be used
to start CNM if needed.
```release-note
```
> CNS: Do not start CNM by default

- log/logger.go
- log/logger_test.go
Each cni request starts a new process, but they share same log file. When multi cni requests received at same time, it is difficult to distinguish logs for each request, add pid to logs will help to better troubleshooting  issue.
Fixes #354
> Add pid to log

- cni/network/network.go
- cni/network/plugin/main.go
- common/utils.go
- network/manager.go
- telemetry/telemetry.go
This PR fixes CNI locktimeout issue in linux. If there are multiple cni calls at same time, then all process will try to start telemetry process and eventually endup in undesirable state( cni plugin hangs at telemetry write and lock not released). For this, moved starting telemetry service inside lock code. Fix for #372 
Also moved log setup out of newplugin function to main code.
```release-note
```
> Fix for CNI lock timedout issue.

- cns/NetworkContainerContract.go
- cns/restserver/api.go
- cns/restserver/restserver.go
- cns/restserver/restserver_test.go
Changes:
1. Add string for COW container type.
2. Removed string for Clear Container container type.
3. Misc formatting fixes - shown as per VS code.
> Remove/Add ClearContainer/COW Container type support

- network/ovs_endpointclient_linux.go
- network/ovsinfravnet/infravnet.go
- ovsctl/ovsctl.go
Addressing security concerns in Linux Multi tenancy. This PR does following:
1. Prevent ovs bridge broadcasting packets to all container interfaces by modifying it to forward to particular port.
2. Allow packets to go through only it comes from right source IP. (IP Spoofing)
```release-note
```
> Addressing security concerns in Linux Multitenancy

- npm/translatePolicy.go
- npm/translatePolicy_test.go
Create default drop entries only when the corresponding policy type exists.
> Fix default drop entries

- .codecov/codecov.yml
- .gitignore
- .pipelines/Dockerfile
- .pipelines/pipeline.yml
- Makefile
- README.md
- network/network_linux.go
- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/iptm/iptm.go
- npm/iptm/iptm_test.go
- npm/namespace_test.go
- npm/nwpolicy_test.go
- npm/translatePolicy_test.go
Fixing npm tests and reporting for clean signal on azure pipelines
```release-note
NONE
```
> NPM test fixes + Azure Pipelines

- npm/translatePolicy_test.go
Adding a test to verify that allow policies will take precedence over deny policies
> Adding a Test to verify Allow Precedence over Deny

- Makefile
Fixing full image name to push to MCR
> Fixing full image name to push to MCR

- Makefile
- cns/networkcontainers/networkcontainers.go
- cns/networkcontainers/networkcontainers_linux.go
- cns/networkcontainers/networkcontainers_windows.go
Loopback adapter creation operation comprises of two operations - createInterface and setWeakHostOnInterface. These operations take place inside the lock. If there are simultaneous requests, it interleaves these calls causing every loopback adapter creation to absorb the delay due to interleaving. createInterface can take time in seconds (typically 2 to 7 seconds based on the tests) while setWeakHostOnInterface finishes very quickly ( less than a second ). This change calls setWeakHostOnInterface within the same lock if createInterface succeeds. The tests show this improves the loopback adapter creation times for simultaneous requests.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
> Optimize call flow to complete loopback adapter creation

- npm/iptm/iptm.go
- npm/namespace.go
- npm/npm.go
- npm/util/const.go
Previously there might be left over states for old Azure-NPM instances. This PR clears any left over states in iptables created by old Azure-NPM instances.
```release-note
N/A
```
> clear stale states on creation

- npm/azure-npm.yaml
Update npm yaml to version v1.0.28
> Update npm yaml to version v1.0.28

- cns/restserver/restserver.go
In case of WebApps the NC goal state gets saved with CNS if the loopback adapter creation is successful. This change fixes the bug where the goal state wasn't getting saved because the condition for WebApps containerType would run into default case and error out.
```release-note
```
> Fix saveNCGoalState bug for WebApps containerType

- aitelemetry/api.go
- aitelemetry/telemetrywrapper.go
- aitelemetry/telemetrywrapper_test.go
1. Add fields for enabling metrics and logs from application
2. made logging configurable
```release-note
```
> addressed concerns discussed during brownbag session

- Makefile
- cns/NetworkContainerContract.go
- cns/nmagentclient/nmagentclient.go
- cns/restserver/api.go
- cns/restserver/restserver.go
- cns/restserver/restserver_test.go
- cns/service/main.go
- common/config.go
- common/utils.go
Expose 2 APIs to publish and unpublish network containers from CNS.
a.	PublishNetworkContainer
b.	UnpublishNetworkContainer
DNC calls CNS to publish and unpublish the network containers.
```release-note
```
> Publish/Unpublish Network Containers via CNS

- cns/networkcontainers/networkcontainers_windows.go
AzureNetworkContainer.exe is in the same location as azure-cns.exe but
if CNS is invoked from a process which is in a different working directory,
os.stat called in CNS points to the directory of parent process. This change
fixes the logic to point to the correct working directory.
```release-note
```
> Fix the logic to detect AzureNetworkContainer.exe

- cns/NetworkContainerContract.go
- cns/restserver/restserver.go
Currently DNC can register a node multiple times using different NodeIDs, this fix will make node registration unique.
> Unique Node Registration

- cns/restserver/restserver.go
Join vnet before publishing NC. This is required as nmagent may be
restarted which causes the NC publishing to fail.
```release-note
```
> Join vnet as a part of NC publish

- npm/azure-npm.yaml
- npm/iptm/iptm.go
- npm/npm.go
- npm/plugin/main.go
- npm/translatePolicy.go
- npm/translatePolicy_test.go
- give precedence to drop rules (over allow)
- remove telemetry buffer from NPM (removed sidecar as well)
- write logs to stdout (and file) so that we may see logs using 'kubectl logs...'
- remove kube-system chain
- add drop entries in corresponding chain for specific policies (i.e. non ALLOW-ALL* entries)
> Fix NPM Regression & Remove TelemetryBuffer Sidecar

- cnm/plugin/main.go
- cns/service/main.go
- common/config.go
Command line parameter support to override store file path. 
Verification : In progress.
> Store file override via command line path.

- cni/azure-windows-multitenancy.conflist
enableExactMatchForPodName  flag is missing in the multitenancy config
for windows. This changes adds this missing flag in the config.
```release-note
```
> Add enableExactMatchForPodName flag in windows multitenancy config

- npm/npm.go
- npm/pod.go
- npm/translatePolicy.go
- npm/translatePolicy_test.go
Create namespace set if it doesn't exist. This fixes reboot bug where entries don't get added after failing to append non-existing namespace to all-namespaces.
When NPM reboots, namespace details do not always sync before policies and pods do. In those cases the namespace will need to be added before we proceed with add/update pod/networkpolicy workflow.
replaces https://github.com/Azure/azure-container-networking/pull/461
> Prevent Namespace Race

- npm/translatePolicy.go
- npm/translatePolicy_test.go
NPM was not treating {} rules as external so the rules get routed to all-namespaces instead.
fixes* #465 
*Partially fixes via allow external but ordering needs to be fixed
i.e.
Behaviour depends in the order these policies applied.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: dns
namespace: test
spec:
podSelector: {}
egress:
- to:
- namespaceSelector: {}
ports:
- protocol: UDP
port: 53
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
name: allow-test-egress
namespace: test
spec:
podSelector:
matchLabels:
app: test
egress:
- {}
---
> Allow External for Empty Ingress/Egress Rules

- npm/iptm/iptm.go
- npm/translatePolicy.go
- npm/translatePolicy_test.go
Union between multiple network policies was broken because current implementation only scopes per policy. This PR will prepend all ipt entries except for chain jumps to prioritize the union of allows.
fixes #465 along with https://github.com/Azure/azure-container-networking/pull/466
> Merge Multiple Network Policies

- npm/testpolicies/allow-all-from-app-backend.yaml
- npm/testpolicies/allow-all-ns-to-frontend.yaml
- npm/testpolicies/allow-all-to-app-frontend.yaml
- npm/testpolicies/allow-app-backend-to-app-frontend-port-8000.yaml
- npm/testpolicies/allow-app-frontend-tcp-port-or-udp-port-53.yaml
- npm/testpolicies/allow-backend-to-frontend.yaml
- npm/testpolicies/allow-internal-and-external.yaml
- npm/testpolicies/allow-multiple-labels-to-multiple-labels.yaml
- npm/testpolicies/allow-ns-dev-and-app-backend-to-app-frontend.yaml
- npm/testpolicies/allow-ns-dev-to-app-frontend.yaml
- npm/testpolicies/allow-ns-test-namespace-to-frontend.yaml
- npm/testpolicies/complex-policy.yaml
- npm/testpolicies/deny-all-from-app-backend.yaml
- npm/testpolicies/deny-all-from-ns-unsafe.yaml
- npm/testpolicies/deny-all-policy.yaml
- npm/testpolicies/deny-all-to-app-frontend.yaml
- npm/testpolicies/test-allow-all-to-k0-and-k1-and-app-frontend.yaml
- npm/translatePolicy_test.go
Removes policies as structs, and instead loads from yaml for easier testing of scenarios on live clusters.
```release-note
```
> Azure NPM UT Test Refactor

- cni/netconfig.go
- cni/network/network.go
- iptables/iptables.go
- platform/os_linux.go
- platform/os_windows.go
Added config option for disabling iptable lock. By default, iptable lock is enabled. If users want to disable iptable lock, they have to set disableIPTableLock field to true in conflist.
```release-note
```
> Added config option for disabling iptable lock

- Makefile
- cns/Dockerfile
This is just for testing purposes; (runners)
```release-note
```
> Add build and publish image capabilities for cns

- .pipelines/e2e-job-template.yaml
- .pipelines/e2e-step-template.yaml
- test/e2e/kubernetes/cniLinux1604.json
- test/e2e/kubernetes/cniLinux1804.json
- test/e2e/kubernetes/cniWindows1809.json
- test/e2e/kubernetes/cniWindows1903.json
> Use prebuilt artifacts in E2E

- Makefile
- aitelemetry/api.go
- aitelemetry/telemetrywrapper.go
- aitelemetry/telemetrywrapper_test.go
- cni/network/network.go
- cni/network/plugin/main.go
- cni/telemetry/service/telemetrymain.go
- common/utils.go
- telemetry/aiwrapper.go
- telemetry/azure-vnet-telemetry.config
- telemetry/constants.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
- telemetry/telemetrybuffer.go
This PR adds AI telemetry support for CNI via telemetry service. The CNI will send telemetry data to telemetry service and telemetry service in turn will send data to AppInsight.
```release-note
```
> AppInsightTelemetry support for CNI

- aitelemetry/telemetrywrapper.go
Added resourcegroup as default dimension in AI metrics. Resource group, subid and vmname can uniquely identify a VM else VMID uniquely identifies a VM.
```release-note
```
> Added resourcegroup and vmid as default dimension in AI metrics

- cni/netconfig.go
- cni/network/network.go
- network/network.go
- network/network_linux.go
Adds an option to not enable Hairpin on the host interface. 
Setting hairpin on the host interface creates a problem when the upstream network devices have STP enabled. This prevents the CNI to be used on bare-metal hosts.
Note:
1. The default behavior of CNI is left as-is. Only a optional parameter is added for scenarios where enabling hairpin on host doesn't work.
2. Hairpin will still be enabled on all the virtual interfaces, so a pod will still be able to connect itself via its ServiceIP.
```release-note
```
> Config option to not enable hairpin on host interface

- Makefile
- npm/Dockerfile
- npm/namespace_test.go
- npm/npm.go
- npm/nwpolicy_test.go
- npm/plugin/main.go
- npm/pod_test.go
Adding AppInsights metrics for NPM. Pod count, namespace count, and network policy count will be reported on a 30 min heartbeat/interval.
> Adding AI metrics for NPM

- cns/configuration/configuration.go
- cns/service/main.go
This is the fix for setting default config values. Passed object as pointer instead of value
```release-note
```
> Fix for setting default config values

- cns/Dockerfile
- npm/npm.go
- Let npm loop 30 min (1 heartbeat interval) for AI telemetry handle.
- Update ca-certs for CNS image so it may send AI telemetry.
> Limit NPM AI Telemetry Handle Retrievals

- cns/cnsclient/cnsclient.go
Fix logging for cnsclient package. otherwise the program will crash if it uses cnsclient apis
```release-note
```
> Fix logging for cnsclient package

- aitelemetry/telemetrywrapper_test.go
- cni/ipam/plugin/main.go
- cni/network/plugin/main.go
- cni/telemetry/service/telemetrymain.go
- cnm/plugin/main.go
- cns/logger/log.go
- cns/service/main.go
- log/logger.go
- log/logger_test.go
- log/stdapi.go
- npm/plugin/main.go
log.SetTarget creates the log file under log directory using golang os package. Whenever code sets the log directory, it needed to call SetTarget to create the actual log file under that directory. In the recent logger changes, InitLogger by default set the log directory to the current folder. This created the log file in the current folder. The code then set the log directory to a different location without a subsequent call to log.SetTarget. This resulted into the logger to not find the actual log file in the set log directory.
This fix updates the logger InitLogger function to accept the log directory to create the file in correct log directory. To avoid having such issue, this fix also combines the function calls to set log directory and set target into a single function. This …
> Fix CNS regression due to logger change

- cns/configuration/configuration.go
- cns/networkcontainers/networkcontainers_windows.go
- common/utils.go
> Fix the code used to get the working directory

- cns/logger/heartbeat.go
- cns/service/main.go
> Separated cns heartbeat to separate thread.

- npm/util/util.go
- npm/util/util_test.go
The value of minor was incorrectly assumed to be e.g. 14.8-hotfix.20191113 instead of 14+
Fixes #494
> NPM Version Validation

- npm/azure-npm.yaml
copy kube-proxy tolerations NPM may run on customer tainted nodes
> Update NPM Tolerations

- .pipelines/Dockerfile
- .pipelines/e2e-job-template.yaml
- .pipelines/e2e-step-template.yaml
- .pipelines/pipeline.yaml
- Makefile
- test/e2e/kubernetes/cniLinux1604.json
- test/e2e/kubernetes/cniLinux1804.json
- test/e2e/kubernetes/cniWindows1809.json
- test/e2e/kubernetes/cniWindows1903.json
Builds and pushes NPM, then uses that image in AKS-Engine E2E tests
```release-note
```
> Test NPM in E2E

- aitelemetry/api.go
- aitelemetry/telemetrywrapper.go
- aitelemetry/telemetrywrapper_test.go
- cns/configuration/cns_config.json
- cns/configuration/configuration.go
- cns/logger/constants.go
- cns/logger/log.go
- cns/restserver/restserver.go
- cns/service/main.go
> Add AI Events and CNS NC Snapshots.

- .pipelines/e2e-step-template.yaml
- .pipelines/pipeline.yaml
- cns/Dockerfile
- npm/Dockerfile
Base image ubuntu:19.10 contains vulns across lubudev1, libss2, libgcrypt20. Add step in Dockerfile to upgrade all packages at image build time.
Upgrade will bump package version from installed to candidate.
https://launchpad.net/ubuntu/+source/libgcrypt20/1.8.4-5ubuntu2.1
```
apt-cache policy libudev1   
libudev1:
Installed: 242-7ubuntu3
Candidate: 242-7ubuntu3.7
Version table:
242-7ubuntu3.7 500
500 http://archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
242-7ubuntu3.6 500
500 http://security.ubuntu.com/ubuntu eoan-security/main amd64 Packages
*** 242-7ubuntu3 500
500 …
```
> Upgrade packages at image build time

- cni/network/network_windows.go
Added endpoint checking logic before calling consecutiveAdd. If endpoint is attached, return directly without calling consecutiveAdd. 
When endpoint is attached, it means ADD has been done successfully previously. No consecutiveAdd is needed. 
fixes #367
> Fix unnecessary consecutiveAdd for windows

- npm/azure-npm.yaml
Update npm image version to use the latest v1.0.33
> Update npm image version to use the latest v1.0.33

- cni/azure-linux.conflist
This PR fixes the issue of duplicate packets being sent from UDP and TCP load balancers on a kubernetes cluster using CNI. The change was to add DisableHairpinOnHostInterface:true to the conflist.
fixes #525
> Fixing duplicate UDP/TCP packets being sent from load balancer

- network/monitor_windows.go
Fixing the windows test build. Did this by rewriting the empty funciton for monitor_windows.go
> Fixing windows test failure

- cns/restserver/restserver.go
As DNC makes the call to CNS to publish NC, CNS logs the incoming request.
This prints the auth token. This change removes the auth token from getting
into the logs.
```release-note
```
> Avoid printing the auth token in CNS log

- cnms/cnmspackage/api.go
- cnms/cnmspackage/monitor2rules_linux.go
- cnms/service/networkmonitor.go
- cnms/service/networkmonitor_test.go
This PR adds telemetry capabilities to network monitoring of Eb rules.
It reports discrepancies to telemetry pipeline which can be viewed in jarvis.
**Testing**
To see the test logs go to this jarvis [link](https://jarvis-west.dc.ad.msft.net/E85E6F5A)
Adaptation of [this](https://github.com/tamilmani1989/azure-container-networking/tree/netmon_telemetry) branch
> Adding telemetry to network monitor

- cnms/Dockerfile
- network/monitor_linux.go
This PR updates network monitor to add ipv6 dnat rule to its monitoring list. Also fixes arp reply rule for primary ip
```release-note
```
> Network monitor to honor ipv6 changes (dnat rule)

- .pipelines/e2e-job-template.yaml
- ipam/ipv6Ipam.go
- ipam/ipv6Ipam_test.go
- ipam/manager_ipv6Ipam_test.go
Don't reserve gateway address in IPv6 IPAM
```release-note
```
> IPv6 don't reserve gateway address

- npm/namespace.go
- npm/namespace_test.go
- npm/npm.go
- npm/nwpolicy.go
- npm/nwpolicy_test.go
- npm/pod.go
- npm/pod_test.go
Update operations should've been locked to prevent a race between other operations.
e.g.
namespace updates
>npm deletes namespace
network policy updates
>npm deletes network policy
>npm adds network policy (fails because namespace was not created yet)
...
>npm add namespace
> Lock update operations to prevent race in between updates.

- .pipelines/e2e-job-template.yaml
- .pipelines/e2e-step-template.yaml
- .pipelines/pipeline.yaml
- test/e2e/kubernetes/cniLinux1604.json
- test/e2e/kubernetes/cniLinux1804.json
- test/e2e/kubernetes/cniWindows1809.json
- test/e2e/kubernetes/cniWindows1903.json
> Change pipeline storage account ID to Build ID

- cns/NetworkContainerContract.go
- cns/hnsclient/hnsclient_linux.go
- cns/hnsclient/hnsclient_windows.go
- cns/restserver/restserver.go
This PR consumes endpoint policies targeting APIPA endpoints. In the future, we are extending policies to requested by the orchestrator in a extensible way from the Create Network Container Request. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #533 
Tested the successful creation of the HostNCApipaEndpoint with the additional policies requested. 
```release-note
```
> Consume ACL for APIPA Endpoint from CreateNC Req

- npm/iptm/iptm.go
- npm/nwpolicy.go
- Removing old npm chains (past baking period) which were causing errors on uninit
- Add merged policies to processed network policy map
- Add/delete raw policies to raw network policy map
- Check if network policy has changed before updating
> Fix NPM Bugs

- npm/nwpolicy.go
Revising add and update network policy logic in npm
- removing redundant delete from update network policy func
- use processed and raw network policy maps accordingly
> Revising add and update network policy logic in npm

- npm/nwpolicy.go
- npm/pod.go
- check both processed and raw network policy maps when updating
- when pods get updated, only add the entries back if pod is not in completed or failed state since we're assuming that they will release their IPs
**Which issue this PR fixes**:
fixes #428
> Check Processed NP Map & Add Update Pod Conditions

- cns/NetworkContainerContract.go
- cns/hnsclient/hnsclient_windows.go
> Update action to block and increase priority for allow

- npm/iptm/iptm.go
- npm/nwpolicy.go
- npm/parsePolicy.go
Fix a bug that created a random egress entry when deleting from ingress-centric policy group. Also removing check that prevented adding multiple identical entries in order to prevent deletion of once policy to affect another.
> Fix Merged Network Policy Deletions

- cni/network/plugin/main.go
- go.sum
- telemetry/aiwrapper.go
Empty CNI telemetry logs were being sent and cluttering jarvis. This PR disallows empty messages being sent.
https://msazure.visualstudio.com/One/_workitems/edit/7041879
@tamilmani1989 , I tried adding a function in that defer call we were talking about yesterday, but it broke the connectivity of new pods. Opted for this simpler fix of just checking the error and event message for empty instead.
> Fix cni logs

- npm/azure-npm.yaml
- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/namespace.go
- npm/npm.go
- npm/nwpolicy.go
- npm/nwpolicy_test.go
- npm/pod.go
- npm/testpolicies/named-port.yaml
- npm/translatePolicy.go
- npm/translatePolicy_test.go
- npm/util/const.go
Adding support for named ports in NPM
**Which issue this PR fixes**:
fixes #550 
**Notes for reviewer**
ipset ip+port hash solution
~$ sudo ipset list **azure-npm-671120875**
Name: azure-npm-671120875
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 152
References: 1
Number of entries: 1
Members:
**10.240.0.21,tcp:80**
~$ sudo ipset list **azure-npm-420423296**
Name: azure-npm-420423296
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 472
References: 4
Number of entries: 2
Members:
**10.240.0.21**
10.240.0.66
match-set **azure-npm-420423296** dst match-set azure-npm-1519775445 dst match-set **azure-npm-671120875 dst,dst** _/* …
> Named Ports Support

- npm/nwpolicy.go
Making a fix to prevent NPM from deleting ipsets on delete network policy operation.
> Don't Delete Ipsets in DeleteNetworkPolicy

- npm/namespace.go
- npm/pod.go
Ignore non-actionable namespace and pod updates.
> Ignore Non-Actionable Updates

- .pipelines/pipeline.yaml
- Makefile
- codecov.yml
Fix the broken integration with coverage report upload
```release-note
```
> Add codecov.yml

- common/listener.go
If CNS Client happen to use a library which checks for the content type before decoding the response ( ex: Python -aiohttp, then reading the response will always fail. 
We are defaulting to "Content-Type: text/plain; charset=utf-8"
As the response is always JSON ended. The fix basically always add the Content-Type header as  "application/json; charset=UTF-8"
> Explicitly add content type header.

- telemetry/telemetry_test.go
Fix race in telemetry test code
```release-note
```
> Fix race in telemetry test code

- npm/npm.go
- npm/parsePolicy_test.go
- npm/pod.go
- npm/pod_test.go
Pods with the same labels and ip were being deleted from their respective ipsets multiple times causing inadvertent deletions.
fixes #562
> Prevent multiple deletions of pods

- cni/network/plugin/main.go
- telemetry/constants.go
This PR is to remove the CNIExecutionTimeMs metric from CNI because cni is using too much metrics data and this isn't a very informative metric and is causing lots of data usage from the Application Insights resources for our telemetry.
@Tamilmani I tested the changes on an aks-engine cluster and the add and del metrics are unchanged, meaning the add and del metrics still show up in the metrics table in jarvis when adding and deleting pods
> Removing execution time metric

- network/bridge_networkclient_linux.go
- network/epcommon/endpoint_common.go
- network/ovs_networkclient_linux.go
- network/ovssnat/ovssnat.go
Disable RA for interfaces created by CNI to address potential security issues.
```release-note
```
> Disable RA for interfaces created by CNI

- npm/iptm/iptm.go
Move AZURE-NPM chain under KUBE-SERVICES chain; Move default allow CONNECTED/RELATED entry to the end of AZURE-NPM chain.
**Which issue this PR fixes**: 
fixes #569
> Re-order NPM IpTable Chains/Rules

- test/e2e/kubernetes/cniWindows1809.json
- test/e2e/kubernetes/cniWindows1903.json
Set test vm image tag to be latest to keep up to date.
```release-note
```
> Set Windows 1903 e2e apimodel to latest 

- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/namespace.go
- npm/npm.go
- npm/nwpolicy.go
- npm/nwpolicy_test.go
- npm/pod.go
- npm/testpolicies/complex-policy.yaml
- npm/translatePolicy.go
- npm/translatePolicy_test.go
- npm/util/const.go
Ipset is an extension for iptable to store and look up ip blocks in an efficient hash way. Move ip cidr related rule to ipset will improve npm performance.
It fixes perf issue when large amount of ip cidr rule got applied.
Examples of ipset and iptables rules with this change.
```release-note
```
> Move Cidr translation from iptable to ipset.

- npm/Dockerfile
Lock Azure NPM image to Ubuntu 18 rather than Ubuntu 20, which fixes:
https://lists.ubuntu.com/archives/ubuntu-security-announce/2020-June/005466.html
Also is more in line with current AKS schedule:
https://aka.ms/aks/Ubuntu1804
```release-note
```
> Fix NPM image libgnutls vulnerability

- build/build-all-containerized.sh
- build/build-all.sh
If you run `./build/build-all.sh` or `./build/build-all-containerized.sh`, it will fail:
```none
command-line-arguments
go build -v -o output/_/cni/azure-vnet-ipam.exe -ldflags "-X main.version=v1.0.12-rc3-8-g009ebee-dirty -s -w" cni/ipam/plugin/*.go
github.com/Azure/azure-container-networking/cni/ipam
command-line-arguments
cp cni/azure-.conflist output/_/cni/10-azure.conflist
cp: cannot stat 'cni/azure-.conflist': No such file or directory
Makefile:246: recipe for target 'cni-archive' failed
make: *** [cni-archive] Error 1
Makefile:169: recipe for target 'all-containerized' failed
make: *** [all-containerized] Error 2
```
This fixes it and will show proper usage instead.
> Adding parameter validation to build scripts

- Makefile
- cni/ipam/ipam_test.go
- ipam/ipv6Ipam_test.go
- ipam/manager_ipv6Ipam_test.go
- ipam/pool_test.go
- network/endpoint_test.go
- network/manager_test.go
- network/network_test.go
- testutils/netapi_mock.go
1. Add ipam/pool_test.go
2. Add network/*test.go
3. Using ginkgo test ipv6ipam
> Improving and adding CNI unit tests 

- npm/ipsm/ipsm.go
- npm/iptm/iptm.go
- npm/namespace.go
- npm/nwpolicy.go
- npm/pod.go
- npm/translatePolicy.go
Update NPM logs to use Logf statements instead of Printf as those are less CPU intensive. Also fixed few logs to avoid printing the old NetworkPolicy objects as that could potentially impact specially for large networkPolicy object. There are log lines when each rule is processed which can be used for debugging.
> Update NPM logs to use Logf instead of Printf

- npm/nwpolicy.go
- npm/nwpolicy_test.go
fix: repair 0.0.0.0/0 cidr which ipset not support
Ipset doesn't support 0.0.0.0/0 cidr. A general approach is convert it to 1.0.0.0/1 and 128.0.0.0/1
- fix: Bug Fixes 🐞
> Add logic to deal with 0.0.0.0/0 which ipset not support.

- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
Ipset deletion condition check existed in DeleteSet function and got removed from previous PR
https://github.com/Azure/azure-container-networking/pull/582/files#diff-8b67ee9376710a903cde1eac00f06c6aL214
This check is still needed when DeleteFromSet got called. When one pod replica got deleted but there are still other pod replica exsit, we should not delete the whole ipset.
Ipset deletion condition check.
- [* ] adds unit tests
> fix: move ipset deletion condition check from DeleteSet to DeleteFromSet.

- go.mod
- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/npm.go
- npm/nwpolicy.go
- npm/pod.go
- npm/pod_test.go
Cache the PodIp which is added in the ipset so that it gets cleaned up deterministically as Pod DeleteEvent callback is asynchronous.
In case Pod DeleteEvent is received after ip has been reassigning to another POD deployed in the same namespace, then there wont be any ipset change.
> Changes for caching pod ip

- npm/testpolicies/allow-backend-to-frontend-with-missing-port.yaml
- npm/translatePolicy.go
- npm/translatePolicy_test.go
fix: add nil pointer checker when reading port value to avoid panic.
When generating network policy, customer could forget to fill in port value. No port value will result in panic due to nil pointer. Add check to avoid it. 
fix: Bug Fixes 🐞
> Add nil pointer checker when reading port value to avoid panic.

- npm/nwpolicy.go
- npm/translatePolicy.go
fix: update NPM logs to use Logf statements instead of Printf as those are less CPU intensive.
We have merged a change which use Logf to replace Printf, this one is a followup for the rest of Printf introduced by other merging PR.
> Update NPM logs to use Logf instead of Printf.

- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
Adding an IPConfig to CNS IPAM could overwrite an existing IPConfig state. Now blocks the scenario AddIPConfig changing state from Allocated to any other state
- [ x] adds unit tests
**Notes**:
> Add CNS IPAM check to not change state

- cni/network/network.go
- network/policy/policy_windows.go
For HnsV2 we will only add outbound nat policy for single tenant scenario or if enableSnatForDns is true.
**Notes**:
> Fix NATing on *COW (HnsV2) Scenarios

- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient_test.go
- cns/restserver/ipam.go
Updated the SecondaryIpConfigs to only add the IPSubnet state in NetworkContainerRequest. SecondaryIPStatus (Its state and associated pod orchastrationContext is not persisted and is maintained in memory)
Fixes AB#7716387
> Update SecondaryIpConfigs in NetworkContainerRequest contract

- network/epcommon/endpoint_common.go
Incase if user disables ipv6 kernel setting, then accept_ra file would not exist and sysctl cmd would fail. This PR addresses that scenario
**Notes**:
> Added check to find accept_ra file exists

- Makefile
- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient_test.go
- cns/cnsclient/httpapi/client.go
- cns/logger/log.go
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/const.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/restserver/util.go
Added implementation for CreateOrUpdateNetworkContainerInternal. This will be called by the CNS requestController and it will handle SecondaryIpConfigs update which will add state for new Secondary ips and delete the state for any delta.
> Implement CreateOrUpdateNetworkContainerInternal API. 

- .pipelines/Dockerfile
- .pipelines/pipeline.yaml
- Makefile
Use ubuntu 16.04 for build image and upgrade various packages for failing tests
**Notes**:
> Pipeline update

- .pipelines/pipeline.yaml
> Prepare artifacts stage

- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
fix: an inconsistency set type creation introduced by AddToSet function.
NPM created 3 types of ipset. AddToSet will check whether set exist before adding entries. However, previous NPM logic only create 1 type of set in AddToSet function which introduced inconsistency between set type.
Simplify logic to create set only when set is not exist for add to set logic.
Fix the inconsistency between set type.
fix: Bug Fixes 🐞X
> Simplify AddToSet logic and fix an inconsistency set type creation.

- cns/cnsclient/apiclient.go
- cns/cnsclient/httpapi/client.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller_test.go
- cns/restserver/api_test.go
- cns/restserver/const.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/util.go
Implement Init/Reconcile NC state to save NC configuration and save in memory state for Pods which are already allocated with NC's secondary ips.
> Implement ReconcileNCState

- Makefile
- cns/aks.Dockerfile
This PR adds a dockerfile for cns. It is an improvement of the previous dockerfile in terms of best practices of containers.
Mainly, the container only has the binary, and builds the binary as part of the dockerfile, instead of how it was doing it before of copying in a pre-built binary into the dockerfile.
Also this new dockerfile only pulls in the necessary dependencies, wheras the old dockerfile brought many unused dependencies into the image.
I'm thinking we can keep both for now, and eventually remove the old one, as well as update the runner yamls to use the new container.
> Dockerfile for cns container

- cns/azure-cns.yaml
This is just a dummy fix to update the example cns yaml we have in our repro which mirrors the aks rp.
The yaml doesn't actually do anything other than stand as a reference.
> CNS yaml update to reflect aks rp helm chart

- npm/ipsm/ipsm_test.go
- npm/util/const.go
test: kernel status checking in unit test for TestDeleteFromList. 
Previous unit test only check whether error happens when calling DeleteFromList. Add logic to check whether the kernel status match what we expect.
If it works properly, then more kernel status checking will be added in unit test. 
> Add kernel status checking in unit test for TestDeleteFromList.

- cni/network/network.go
- cni/plugin.go
- cni/plugin_linux.go
- cni/plugin_windows.go
- cnm/network/network.go
- cnms/service/networkmonitor.go
- ipam/manager.go
- network/manager.go
- network/manager_test.go
uptime -s returns different values due to clock drift and cni need not rehydrate based on reboot time.
#639 
**Notes**:
> CNI not to rehydrate based on reboot time

- cns/requestcontroller/kubecontroller/crdtranslator.go
- cns/requestcontroller/kubecontroller/crdtranslator_test.go
Fix: add gateway IP address to NC request from CRD status
**Notes**:
Updated unit test to reflect desired behavior and changed `CRDStatusToNCRequest` to pass that test
> Add gateway to NCRequest in CRD Translator

- cns/cnsclient/cnsclient_test.go
- cns/restserver/const.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/util.go
Update CNS/CNI contract to also pass GatewayIP and DnsServers for SecondaryIpConfigs.
> Cns change cni interfacefor secondary ips

- cns/requestcontroller/kubecontroller/crdtranslator_test.go
- nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
feat: include subnet address space in CRD
BREAKING CHANGE: removes `Netmask` from NNC Status because it is now redundant
Adds subnet address space to CRD status
**Notes**:
> feat: include subnet address space in CRD

- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient_test.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller_test.go
- cns/requestcontroller/kubecontroller/crdtranslator.go
- cns/requestcontroller/kubecontroller/crdtranslator_test.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/restserver/util.go
Removed PrefixLength from SecondaryIPConfig struct. We dont need to populate /32 in this struct. When CNI request for SecondaryIPconfig, then add Subnet range prefix length it the IP CIDR format.
> cns_removePrefixLengthFromSecondaryIpconfig

- cns/cnsclient/cnsclient.go
- cns/cnsclient/cnsclient_test.go
- cns/restserver/ipam.go
- cns/restserver/util.go
IPAM delete in CNS was not passing pod info, therefore ID in state was never found
**Notes**:
> fix: pass podinfo to CNS delete

- cns/requestcontroller/kubecontroller/crdrequestcontroller_test.go
- cns/requestcontroller/kubecontroller/crdtranslator.go
- cns/requestcontroller/kubecontroller/crdtranslator_test.go
- cns/restserver/ipam.go
- cns/restserver/util.go
Persist the prefix length of PrimaryIPConfiguration from SubnetAddressRange. Note, since SecondaryIPs are also allocated form same range, no need to persist the length with every secondary ip. That will be populated from primaryIP while passing info to CNI
> Add prefixlength from SubnetAddressRange

- npm/ipsm/ipsm_test.go
fix: flaky unit test.
Ipset deletion unit test was flaky at deletion path. It is caused by ipset which didn't get cleaned up when previous tests end. Add deletion and validation to make sure unit test is not flaky anymore.
test: Testing 💚
> Add list deletion and validation in unit test.

- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient_test.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/util.go
Added more details for podIpInfo in response to CNI GetIpConfigRequest. 
Still working on pulling HostIP details
> Added more details for podIpInfo in response to CNI GetIpConfigRequest

- cns/api.go
- cns/cnsclient/apiclient.go
- cns/cnsclient/cnsclient_test.go
- cns/cnsclient/httpapi/client.go
- cns/fakes/cnsfake.go
- cns/fakes/requestcontrollerfake.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/ipampoolmonitor/ipampoolmonitor_test.go
- cns/requestcontroller/kubecontroller/crdreconciler.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller_test.go
- cns/restserver/api_test.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/ipampoolmonitor.go
- cns/restserver/restserver.go
- cns/restserver/util.go
- cns/service/main.go
Lay the groundwork for the monitor that will make calls to CNS and RequestController to adjust CNS pool size
**Notes**:
> CNS Pool Monitor - Init and basic resize logic

- npm/util/const.go
fix: variable name
NMAgent is using npm package. A change in NPM package const variable blocked build. Change variable name back to unblock build.
NMAgent is using npm package. A change in NPM package const variable blocked build. Change variable name back to unblock build.
Build blocking.
build: Build 🏭
> Change variable name from IP6tables back to Ip6tables.

- cns/api.go
- cns/cnsclient/apiclient.go
- cns/cnsclient/cnsclient_test.go
- cns/cnsclient/httpapi/client.go
- cns/fakes/cnsfake.go
- cns/fakes/ipampoolmonitorfake.go
- cns/fakes/requestcontrollerfake.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/ipampoolmonitor/ipampoolmonitor_test.go
- cns/logger/log.go
- cns/requestcontroller/kubecontroller/crdreconciler.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller_test.go
- cns/restserver/api_test.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/service/main.go
Integrates the IPAM Pool Monitor with existing request controller and CNS.
DO NOT MERGE BEFORE https://github.com/Azure/azure-container-networking/pull/667, this PR is continually rebased off that one.
**Notes**:
> CNS Scaling Integration (3/3)

- cns/requestcontroller/kubecontroller/crdrequestcontroller.go
Fixes an issue where if the CRD is nil, then don't pass to IPAM pool monitor
**Notes**:
> CNS CRD nullref fix

- cni/network/plugin/main.go
We have seen cases where our CNI is getting called for COMMAND with commands other ADD/DEL.
CHECK is only supported for 0.4.0 and above, and current logging gives an impression CNI DID nothing for ADD/DEL calls.
> Add logging to record CNI_COMMAND value

- .pipelines/e2e-job-template.yaml
- .pipelines/pipeline.yaml
Moving the e2e's to a different stage instead of inside the build and UT's
**Notes**:
> Move E2E's to separate stage

- .pipelines/e2e-step-template.yaml
We want to stop skipping the restart test in aks-engine e2e test suite. [code](https://github.com/Azure/aks-engine/blob/c670571cd42c68ecddca9a9379a5a1d3b0cd6a69/test/e2e/kubernetes/kubernetes_test.go#L812)
Can do this by setting `DEBUG_CRASHING_PODS=true` in pipeline
> test: stop skipping aks-engine restart test

- test/e2e/kubernetes/cniWindows1809.json
- test/e2e/kubernetes/cniWindows1903.json
A test was being skipped due to our config files listing agent nodes as availability sets instead of vmss's.
This test  which makes sure containers come back up correctly after a restart was being skipped because our config files had the agent nodes as availability sets instead of vmss.
https://github.com/Azure/aks-engine/blob/c670571cd42c68ecddca9a9379a5a1d3b0cd6a69/test/e2e/kubernetes/kubernetes_test.go#L2238
> test:  stop skipping windows test

- cns/restserver/internalapi.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/service/main.go
Adds the pending release from the CRD to CNS on start
**Notes**:
> Add PendingRelease to CNS on start

- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_windows.go
A recent change made the operation as no-op.
> [Windows] Keep the network state cleanup behavior unchanged 

- cni/network/network.go
azure-vnet-ipam should not called for multitenancy path.
> Disable vnet ipam for multitenancy

- docs/cni.md
Doc on how to find cni version
> chore: adding cni doc on how to find version

- docs/cni.md
Tweak wording to include update scenario
> chore: tweaked wording on install cni doc

- cni/network/invoker_cns.go
- cns/NetworkContainerContract.go
- cns/restserver/util.go
- network/bridge_networkclient_linux.go
- network/manager.go
In swift mode the route for host to pod on other host needs to go via the default gateway, so we add a route to the bridge for the pod subnet to use the host default gateway
**Notes**:
> fix: Pass host gateway to CNI in swift mode

- cns/NetworkContainerContract.go
- cns/api.go
- cns/fakes/cnsfake.go
- cns/fakes/imdsclientfake.go
- cns/imdsclient/api.go
- cns/imdsclient/imdsclient.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/requestcontroller/kubecontroller/crdtranslator.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/util.go
*Add pending program status for IPs in CNS.
*Add logic structure of how to update program status.
feat: 
Add logic structure for CNS udpate NC secondary IP to pending program before available
Pending program is a status to track that IP is available in NC but not in NMAgent side yet. IP is available when NMAgent is also ready. 
Prevent CNS allocate pending program IP to pod.
> Add pending program status for IPs in CNS.

- cns/NetworkContainerContract.go
- cns/requestcontroller/kubecontroller/crdrequestcontroller_test.go
- cns/requestcontroller/kubecontroller/crdtranslator.go
- cns/requestcontroller/kubecontroller/crdtranslator_test.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam_test.go
- cns/restserver/util.go
feat: Add NC version in SecondaryIPConfig structure.
When CNS reconcile, it needs NC version to determine whether an IP should be stay in pending programming or available.
> Add nc version in SecondaryIPConfig stucture.

- .pipelines/e2e-job-template.yaml
- .pipelines/e2e-step-template.yaml
- cni/network/invoker.go
- cni/network/invoker_azure.go
- cni/network/invoker_cns.go
- cni/network/network.go
All add calls and delete calls should be via the invoker interface, this fix is to change DelegateDel's to invoker.Delete, which is required in swift mode
**Notes**:
> fix: Add missing CNI invoker delete calls

- cni/azure-linux.conflist
Azure CNI has been working in bridge mode for single tenancy till date. In bridge mode, a L2 bridge is created, commonly named as "azure0", which acts as a master for the eth0 interface of VM. This bridge gets programmed with the Ip addrs, DNS name servers and other properties from eth0. When a Pod is created, veth pairs for these Pod will have one interface in Pod name space and other one in the pair is attached to L2 bridge. Pod to Pod communication intra-VM occurs through this L2 bridge. Inter-VM Pod-Pod communication requires the packet to come out of bridge, routed to the default gateway assigned in the ip route tables and gets delivered to the destination VM by fabric.
In Transparent mode Azure CNI, there is no L2 bridge and eth0 is not touched by Azure CNI. When a Pod is created, …
> Azure CNI transparent mode as default

- cns/NetworkContainerContract.go
- cns/cnsclient/cli.go
- cns/cnsclient/cnsclient.go
- cns/cnsclient/cnsclient_test.go
- cns/restserver/internalapi.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/restserver.go
- cns/restserver/util.go
- cns/service/main.go
- common/config.go
Adds a debug API to get IP addresses, options include "Available", "Allocated", and "All".
Usage example:
```bash
$ k exec -it azure-cns-z74hd -- /usr/local/bin/azure-cns -cmd get -darg All
{10.0.0.39 Allocated}
{10.0.0.40 Allocated}
{10.0.0.41 Available}
{10.0.0.42 Allocated}
{10.0.0.43 Available}
{10.0.0.44 Available}
...
$ k exec -it azure-cns-z74hd -- /usr/local/bin/azure-cns -cmd get -darg Allocated
{10.0.0.39 Allocated}
{10.0.0.40 Allocated}
{10.0.0.42 Allocated}
{10.0.0.45 Allocated}
{10.0.0.46 Allocated}
{10.0.0.48 Allocated}
{10.0.0.50 Allocated}
...
$ k exec -it azure-cns-z74hd -- /usr/local/bin/azure-cns -cmd get -darg Available
{10.0.0.41 Available}
{10.0.0.43 Available}
{10.0.0.44 Available}
{10.0.0.47 Available}
{10.0.0.49 Available} …
```
> Adds debug commands to CNS binary with debug API

- cns/NetworkContainerContract.go
- cns/restserver/internalapi.go
Remove GetNCVersionURLFmt from NodeInfoResponse api contract
This change removes GetNCVersionURLFmt from the NodeInfoResponse which CNS gets
as a part of SyncNodeStatus in case of managed mode. This data is available with CNS and
should not be needed from DNC.
**Notes**:
> Remove GetNCVersionURLFmt from NodeInfo contract

- npm/ipsm/ipsm_test.go
fix: flaky ipset unit test.
Unit test is flaky since it can be influenced by other ipsets exist in the system. If there are ipsets got referenced from kernel, flush or destroy won't delete it but return error. TestDestroy validation should changed to validate whether the testing ipset got deleted or not.
Flaky unit test.
test: Testing 💚
> Fix flaky ipset unit test

- cni/network/network_windows.go
- network/policy/policy_windows.go
In order to support VIPs for container Port Mappings, we should
use PortMappingPolicySetting type from HNSv2 instead of the old
NatPolicy from HNSv1.
Kubernetes e2e test: [sig-scheduling] SchedulerPredicates [Serial] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [Conformance] fails on Windows Server 2004 ( as shown here: https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-master-2004-containerd-serial-slow ). The reason for this failure is that setting hostIP for port mappings are not supported with Azure-CNI. This PR uses allows setting of VIP by using the PortMappingPolicySetting type instead of NatPolicy.
**Notes**:
As suggested by @erfrimod , instead of converting From HNSv1 NatPolicy to …
> fix: Use PortMappingPolicySetting

- cni/azure-windows.conflist
Removed default ACLs from the CONF file, so as to not interfere with orchestrator logic.
> Remove default ACLs

- cns/fakes/cnsfake.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/ipampoolmonitor/ipampoolmonitor_test.go
Fix a race condition in IPAM Pool Monitor during Scale down. It currently overwrites the NotInUse list during incremental deletes
Fixed a bug in IPAM Pool monitor
**Notes**:
> CNS: Fix IPAM scaler down to handle incremental decrease

- network/endpoint_windows.go
Need to handle cases where a CNI delete is invoked on a non-existing HNS endpoint
https://github.com/Azure/azure-container-networking/issues/715
**Notes**:
> Handling "endpoint not found" in hns delete

- go.mod
- ipam/azure.go
- ipam/pool.go
We had an incident where it seems like nmagent returned an empty list of ip address.
Improve logging so we know next time
**Notes**:
> log what ips we got and make defer pickup when no ips are found

- acncli/deployment/manager.yaml
- cni/network/invoker_cns.go
- iptables/iptables.go
- network/bridge_networkclient_linux.go
- network/epcommon/endpoint_common.go
- network/manager.go
- network/network_linux.go
Fixed an issue for adding routes to the external interface, in transparent and bridge mode, as well as the snat rules
**Notes**:
> refactor: Move CNI bridge/transparent routes to common

- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/npm.go
- npm/pod.go
- npm/pod_test.go
- npm/translatePolicy.go
- npm/translatePolicy_test.go
- npm/util/const.go
NPM creates IPsets for the following today:
- NameSpace
- Label
- LabelKey:Value
- NamedPorts
- CIDR blocks
Namespace and namespace labels are getting a `ns-` prefix helping NPM to distinguish between PodLabels and NameSpaceLabels. But there are several instances where the IPSet names for Labels and NamedPorts are surfacing. This occurs when a podLabel `http:test` and a namedPort `http` is created. An example can be seen in #733 . NPM hashes `http` from label and creates a IpSet with this hash, then when it is adding namedPort `http` it would hash to the same value and it logs this below error.
>Stderr: [exit status 1, ipset v6.34: Syntax error: Elem separator in <IP_ADDR>,<PORT_NUM>, but settype hash:net supports none.]
Using ":" as prefix delimiter as k8s does not …
> [NPM] 🐞 {fix} error creating IPsets when same string for ports and labels is used

- npm/ipsm/ipsm.go
- npm/iptm/iptm.go
- npm/metrics/ai-utils.go
- npm/npm.go
fix: Change function name from SendErrorMetric to SendErrorLogandMetric
Change to a better name to reflect what SendErrorLogandMetric function will do.
> Change AI log and metrics sending function name in NPM.

- cns/configuration/cns_config.json
- cns/configuration/configuration.go
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/service/main.go
This PR adds a configuration option for wireserver ip, helpful in cases where we are not in a live environment and need to use mocks for nmagent. It also adds a check in the publish container endpoint to possibly extract the wireserver endpoint from the incoming request; given that the rest of the payload contains urls used to communicate to wireserver, it follows that we should try to use that instead of the internal cns configuration.
**Notes**:
> Configurable wireserver endpoint

- cns/restserver/util.go
This change prevents the subnet auth token getting saved in the CNS state file.
**Notes**:
> Prevent storing auth token in CNS state file

- .pipelines/e2e-step-template.yaml
- .pipelines/pipeline.yaml
- Makefile
Hardcoded image registries makes retargeting difficult, these were still hardcoded.
**Notes**:
> chore: Update pipeline yaml, replace hardcoded registries to env's

- network/endpoint_linux.go
- network/transparent_endpointclient_linux.go
1. updated routes
2. added static arp entry in container namespace for virtual gw ip
**Notes**:
> [hotfix] Fix latency in transparent mode

- cns/api.go
- cns/fakes/cnsfake.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/util.go
Improvement: Ensure pending programming IPs will be released first when scale down.
When scale down, we want to ensure pending programming IPs can be released before available IPs to improve performance. Pending programming IPs need to check programmed NC version before available. Release pending programming IPs will save one step.
Improve performance. 
- [X ] uses [conventional commit messages](https://www.conventionalcommits.org/)
perf: Performance Improvements 🚀
- [X ] includes documentation
> Ensure pending programming IPs will be released before available IPs when scale down.

- cns/service/main.go
> CNS changed blocking channel send to non-blocking

- cns/Dockerfile
fix: repair docker build failure for previous CNS ubuntu version
Previous 19.10 ubuntu image has issue with apt-get update. Official support for 19.10 also stopped. Updated to official version of 20.04
https://hub.docker.com/_/ubuntu/?tab=tags&page=1&ordering=last_updated
docker build failure for ubuntu 19.10 image.
None.
build: Build 🏭
chore: Maintenance 🔧
> Update CNS ubuntu version to 20.04

- npm/pod.go
- npm/pod_test.go
This fix involves ignoring any Add, Update or Delete Pod events for Hostnetwork Pods.
> [NPM] Ignoring hostnetwork pods from being added into Ipsets

- npm/pod.go
- npm/pod_test.go
* Ignoring hostnetwork pods from being added into Ipsets
* generalizing the check on hostnetwork pod
* Adding tests for add, update and delete hostnetwork pods
> [1.2.2_hotfix] [NPM] Ignoring hostnetwork pods from being added into Ipsets (#776)

- npm/namespace.go
- npm/namespace_test.go
- npm/util/util.go
NPM currently deletes all the ipsets when an existing namespace is updated. This fix selectively deletes or adds only the changed labels for an existing Namespace.
> [NPM] Supporting Namespace label updates

- network/transparent_endpointclient_linux.go
…pace is deleted
The issue is that in transparent mode cni generates the veth pair names based on pod name and namespace. In this case, a new container with the same pod name and namespace called CNI ADD before the old container with the same pod name and namespace call  CNI DEL. Due to this, when the old container issued CNI DEL, it deleted the veth host interface, in turn deleting the eth0(other veth) of the new container.
**Notes**:
> Fix for deleting hostvethpair in transparent mode

- cns/restserver/api_test.go
- cns/restserver/internalapi_test.go
- cns/restserver/restserver.go
- cns/restserver/util.go
- cns/service/main.go
- store/json.go
- store/store.go
- testutils/store_mock.go
This change removes unreadable state file ( azure-cns.json ) while starting the CNS service
**Notes**:
> fix: Remove unreadable CNS state file upon CNS service start

- cns/restserver/util.go
Remove overriding host verson when IP already exist to avoid programming IPs become available after CNS restarts and restore from previous state.
fix: repair a bug when CNS restarts.
When nmagent nc version api is not ready, host version should always be -1 which indicate CNS can't verify nc version from nmagent side. 
No IP can be assigned since nmagent is not ready.
However, found CNS will assign IPs when restarts and restore from preivous states when nmagent is not ready. It's due to host version override. 
Removing unnecessary override of host verson.
fix: Bug Fixes 🐞
**Notes**:
Related logs
```
2021/02/05 17:45:33 [7] [Azure CNS]  Restored state, &{Location: NetworkType: OrchestratorType:KubernetesCRD NodeID: Initialized:false …
```
> Remove overriding host verson when IP already exist.

- npm/npm.go
- npm/pod.go
For HostNetwork pods on v1.2.2hotfix, we are seeing lots of logs messages for dummy PodUpdate events. This is causing logs to be overwritten fast.
> [NPM] Fixing log noise and removing GetClusterState

- npm/npm.go
- npm/pod.go
* Fixing log noise for hotnet pods
* Removing GetClusterState usage
**Notes**:
> [NPM][master] Fixing log noise and removing GetClusterState (#784)

- npm/iptm/iptm.go
- npm/iptm/iptm_test.go
- npm/npm.go
- npm/pod.go
- npm/util/const.go
Today, NPM is in a configure and forget state for adding AZURE-NPM chain in FORWARD iptable chain. This change will include running a go routine to periodically (every 5 mins) check the order of AZURE-NPM chain in FORWARD. We can later extend this go routine to check other chains too.
> [NPM] Periodic Reconciliation of NPM Chain ordering in FORWARD table

- .pipelines/Dockerfile
- .pipelines/npm/npm-conformance-tests.yaml
> Add NPM Conformance Test Pipeline

- cns/azure-cns.yaml
- tools/acncli/deployment/manager_swift.yaml
> updated cns version and created cni installer for swift

- cns/ipampoolmonitor/ipampoolmonitor.go
> Remove Log noise from ipam pool monitor

- log/logger.go
Log rotation does not respect configured target, causing it to always only log to file after initial rotation. This breaks stdout logging if enabled, once the first rotation takes place.
**Notes**:
> Log rotation does not respect configured target

- cns/requestcontroller/kubecontroller/crdtranslator.go
- cns/restserver/internalapi.go
Just making logger package consistent for cns aks swift scenario logging.
The command line flag was being honored, I just didnt' realize there were leftover logs on disk from previous containres 
The pipeline shows a failure with goldpinger tests but I ran the same tests with the same CNS dirty version on an underlay in our runners sub and they passed so pretty sure the pipeline one is a flake
CONFIRMED : it was a flake, this same exact build passed the tests
https://msazure.visualstudio.com/One/_build/results?buildId=39844247&view=logs&j=c4e47b90-07e0-53db-2983-8e94a4f7f491&t=c4e47b90-07e0-53db-2983-8e94a4f7f491
> chore: consolidating logger package for cns aks swift scenario code

- cni/network/invoker_cns.go
Adding a new rule in POSTROUTING table to accept pod traffic going to internet
Chain POSTROUTING (policy ACCEPT 37 packets, 2743 bytes)
pkts bytes target     prot opt in     out     source               destination
0     0 ACCEPT     all  --  *      *       10.241.0.0/16        0.0.0.0/0            destination IP range ! 168.63.129.16-168.63.129.16
> [CNI] Bypassing POSTROUTING table for Swift POD traffic

- npm/namespace.go
- npm/namespace_test.go
- npm/npm.go
- npm/nwpolicy.go
- npm/pod.go
- npm/pod_test.go
- npm/util/const.go
- npm/util/util.go
- npm/util/util_test.go
Reverts Azure/azure-container-networking#780
This change caused regression in confromance tests, so reverting PodCache
> Revert "[NPM] Caching Pod information to compare against desired state"

- network/policy/policy_windows.go
Current code is incorrectly checking against EndpointPolicyType.
**Notes**:
> fix: ACLPolicy check for hnsv2

- cns/NetworkContainerContract.go
- cns/api.go
- cns/cnsclient/cli.go
- cns/cnsclient/cnsclient.go
- cns/cnsclient/cnsclient_test.go
- cns/restserver/ipam.go
The GetIPAddressesMatchingStates now returns IPConfigurationStatus
type, which also includes PodInfo along with IP address and state
**Notes**:
>  CNS_Fixing debug API

- .pipelines/npm/npm-conformance-tests.yaml
- npm/http/server/server_test.go
- npm/namespace.go
- npm/namespace_test.go
- npm/npm.go
- npm/nwpolicy.go
- npm/nwpolicy_test.go
- npm/pod.go
- npm/pod_test.go
- npm/util/const.go
- npm/util/util.go
> [NPM] Decoupling resource cache maps from NSmap

- cns/restserver/internalapi.go
- cns/restserver/ipam.go
fix: Change version comparison from string to int and as well as the following 3 improvements.
1. Add more log in SyncHostNCVersion.
2. Remove unnecessary check for MarkIpsAsAvailable.
3. Auto formatting.
Logs are not sufficient enough to debug. 
After these logs got added, it will unsure whether host version got updated.
In another word, after log got added, we are clear whether select sentence after channel got executed porperly.
> Change version comparison from string to int and add more log in SyncHostNCVersion.

- cns/logger/log.go
- cns/nmagentclient/nmagentclient.go
- cns/restserver/ipam.go
- log/logger.go
fix: repair 3 logs.
3 not-readable logs as following
```
// Should use body info instead of its address
Response body is [123 34 104 116 116 112 83 116 97 116 117 115 67 111 100 101 34 58 34 50 48 48 34 44 34 110 101 116 119 111 114 107 67 111 110 116 97 105 110 101 114 115 34 58 91 93 125]
// Should expose pod info for debugging
SetIPConfigAsAvailable failed to release, no allocation found for pod
// Should use decoded message
[azure-cns] Received *cns.IPConfigRequest &{DesiredIPAddress: OrchestratorContext:[123 34 80 111 100 78 97 109 101 34 58 34 109 101 116 114 105 99 115 45 115 101 114 118 101 114 45 53 56 102 100 99 56 55 53 100 53 45 104 57 109 107 107 34 44 34 80 111 100 78 97 109 101 115 112 97 99 101 34 58 34 107 117 98 101 45 115 121 115 116 101 109 34 …
```
> Fix log which let log to show more readable info.

- npm/nwpolicy.go
Right now, network policy cache is updated even if there are errors below, this PR will make sure that cache is not updated if error occurs
> [NPM] pushing Netpol cache update below errors

- npm/nwpolicy.go
because of this error, none of the valid network policies are being applied.
This error is caused by non-removal of some benign namespaces
> [NPM] Remove non-fatal error which is causing early bail out

- cns/NetworkContainerContract.go
- cns/cnsclient/cli.go
- cns/cnsclient/cnsclient.go
- cns/cnsclient/cnsclient_test.go
- cns/restserver/ipam.go
- cns/restserver/restserver.go
feat: This API exposes one of the Httpservice struct field to 
display map of OrchestratorContext->PodIpID (UUID) and 
includes debug command getPodContexts for CLI use-case.
> CNS Debug API to expose PodIpIdByOrchrestratorContext

- codecov.yml
- npm/ipsm/ipsm_test.go
- npm/util/errors/errors.go
Subset of https://github.com/Azure/azure-container-networking/pull/830, used to classify NPM IPSet errors
**Notes**:
> [NPM] Add NPM Error structs

- nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
Adding a max ip count to the CRD scaler
> feature: max ip limit for NodeNetworkConfig

- cns/NetworkContainerContract.go
- cns/api.go
- cns/cnsclient/cli.go
- cns/cnsclient/cnsclient.go
- cns/cnsclient/cnsclient_test.go
- cns/fakes/ipampoolmonitorfake.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/restserver/ipam.go
- cns/restserver/restserver.go
Feat:  [CNS] Debug API to expose In-Memory Data HTTPRestService 
This commit has following changes - 
1. Removed AllocatedIPCount field from HTTPRestService struct in restserver.go as it is not used in project.
2. Added debug command getInMemory and API to expose fields-HTTPRestService and 2 fields from IPAMPoolMonitor.
3. Added Test function to test the new debug api response.
**Reason for Change**: Helping in debug commands for CNS service.
**Notes**: Please review and suggest the naming of the command, handler and end point.
> [CNS] Debug - Expose In-memory data from HTTPRestService

- go.mod
- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/nameSpaceController.go
- npm/npm.go
- npm/podController.go
- npm/podController_test.go
- npm/util/const.go
- npm/util/util.go
Today, during a resource event handling, NPM will return immediately if it encounters an error and local NPM cache will not be updated. This results in leaked ipset/iptables state in kernel which will never be cleaned up since the local NPM cache is not aware of it. 
Solution:
Build cache after each successful operation. Return on first error.
This PR, incorporates the above logic, NPM now keeps updating the local cache after every successful operation. NPM also ignores the notexists errors in Delete set operations.
Logging is updated to use klog instead of using acn/log.
if the Cached Pod IP changes, now NPM will delete the existing cached pod and adds a new pod.
CleanUpDeletedPod will now only require the key of the pod which needs to be deleted.
> [NPM] better error handling and cache building

- npm/nameSpaceController.go
- npm/nameSpaceController_test.go
- npm/networkPolicyController.go
- npm/networkPolicyController_test.go
- npm/npm_test.go
- npm/podController.go
- npm/podController_test.go
Current code does not enqueue a key of DeletedFinalStateUnknown object on deletion event, which may cause leak of applied states (e.g., ipset, iptables) and keep an item in a local cache (e.g., podMap, nsMap, nsMap).
This PR is to properly clean up applied states (e.g., ipset, iptables, and local cache (e.g., podMap, nsMap, nsMap) in case of DeletedFinalStateUnknown object on deletion event in each controller.
**Notes**:
> [NPM] fix management of DeletedFinalStateUnknown object on deletion event in each controller

- npm/ipsm/ipsm.go
- npm/nameSpaceController.go
- npm/podController.go
The shared NsMap local cache is incorrectly managed between nameSpaceController and PodController. So, if the podController first reconciles the event and adds the npm-namespace object into NsMap, nameSpaceController missed the chance to call AddToList function since the npm-namespace object exists in our NsMap cache.
In this PR, podController adds the npm-namespace object into NsMap only after successfully completing ipset operations for namespace of the pod if the npm-namespace object does not exist in NsMap cache.
#865
**Notes**:
> [NPM] fix incorrect NsMap local cache management between nameSpaceController and PodController

- cni/network/invoker_cns.go
- cni/network/network.go
- cns/cnsclient/cli.go
- cns/cnsclient/cnsclient.go
- cns/cnsclient/cnsclient_test.go
No timeout specified in CNI, so when CNS is locked and won't respond, this issue gets propagated down to CNI being locked waiting for a response from CNS.
**Notes**:
> [CNI] Specify CNSClient HTTPClient timeout 

- nodenetworkconfig/manifests/doc.go
**Reason for Change**: 
We want to include the NodeNetworkConfig CRD in a dependent project - this change allows go mod to include the manifests directory when we `go mod vendor` so that we can use it as the canonical source for the CRD installation.
> make the CRD yaml vendor-able

- cni/network/invoker.go
- cni/network/invoker_azure.go
- cni/network/invoker_cns.go
- cni/network/network.go
- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient.go
- cns/cnsclient/cnsclient_test.go
New CNI log line:
New CNS log line:
https://github.com/Azure/azure-container-networking/issues/885
**Notes**:
> [CNI] Update CNI to pass IP address on delete

- Makefile
- nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
- nodenetworkconfig/manifests/embed.go
- nodenetworkconfig/manifests/embed_test.go
Adds custom status and printer columns for NNC kubectl output 
Adds convenience method for accessing the embedded NNC CRD definition
**Notes**:
> feat: add more status fields to the nodenetworkconfig: status, allocated IPs, subnets, NCs

- cns/hnsclient/hnsclient_windows.go
> remove deleting network adapter when no endpoints

- Makefile
- cni/client/client.go
- cni/client/client_integration_test.go
- cni/client/client_unit_test.go
- go.mod
- go.sum
- test/utils/utils.go
- vendor/github.com/hashicorp/go-version/CHANGELOG.md
- vendor/github.com/hashicorp/go-version/LICENSE
- vendor/github.com/hashicorp/go-version/README.md
- vendor/github.com/hashicorp/go-version/constraint.go
- vendor/github.com/hashicorp/go-version/go.mod
- vendor/github.com/hashicorp/go-version/version.go
- vendor/github.com/hashicorp/go-version/version_collection.go
- vendor/modules.txt
CNS can be aware of the CNI version it's calling
**Notes**:
> [CNI] Parse CNI version in CNI client

- cni/network/plugin/main.go
- cni/telemetry/service/telemetrymain.go
- cnms/service/networkmonitor.go
- cns/logger/heartbeat.go
- cns/logger/log.go
- cns/service/main.go
- log/logger.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
- telemetry/telemetrybuffer.go
Removing telemetry processed on HostNetAgent
**Notes**:
> chore: Deprecating HostNetAgent Processed Telemetry

- .github/workflows/repo-hygiene.yaml
- Makefile
- README.md
> fix: lint changes vs the default branch only

- ebtables/ebtables.go
- network/ovs_endpoint_snatroute_linux.go
- network/ovssnat/ovssnat.go
added drop rule for arp request for snat bridge ip
**Notes**:
> Drop arp request for snatbridge apipa range

- Makefile
- cni/client/client_integration_test.go
- cni/network/network.go
- cni/network/network_test.go
- cns/api.go
- ipam/manager.go
- network/manager.go
- store/json.go
- store/store.go
When reconciling with CNI, it may be the case that CNI state hasn't been created yet. Don't block consumers of that state when empty.
**Notes**:
> fix: [CNI] handle getting endpoints when state file is empty

- platform/os_linux.go
- platform/os_windows.go
- store/json.go
- store/json_test.go
> updated lock directory for store package in Linux

- .github/workflows/cyclonus-netpol-test.yaml
- npm/azure-npm.yaml
- test/cyclonus/install-cyclonus.yaml
- test/cyclonus/test-cyclonus.sh
- test/kind/kind.yaml
> ci: bump Cyclonus version

- cni/network/network.go
- cnm/plugin/main.go
- cnms/service/networkmonitor.go
- cns/service/main.go
- network/bridge_endpointclient_linux.go
- network/endpoint.go
- network/endpoint_linux.go
- network/epcommon/endpoint_common.go
- network/manager.go
- network/network_linux.go
- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/networkPolicyController.go
- npm/networkPolicyController_test.go
- npm/npm.go
- npm/translatePolicy.go
- npm/translatePolicy_test.go
- platform/os_test.go
- telemetry/telemetry_linux.go
- telemetry/telemetrybuffer.go
- tools/acncli/cmd/logs.go
A batch of cosmetic/non-functional changes to fix existing syntactic/style issues discovered by the linter.
**Notes**:
> chore: appease the linter, pt 1 of ?

- npm/translatePolicy.go
- npm/translatePolicy_test.go
TestAllowMultiplePodSelectors has a flake UT result due to ordering of ipset name in the comment. This PR fixes it
> [NPM] [bug] Adding sort in iptable comment for deterministic behavior in Flake UT

- cni/network/network.go
- cni/network/plugin/main.go
- cni/plugin.go
- store/json.go
> removed lock for version command

- cni/network/network.go
- cni/network/plugin/main.go
- cni/plugin.go
- store/json.go
Reverts Azure/azure-container-networking#929
> Revert "removed lock for version command"

- platform/os_linux.go
- store/json_test.go
> [CNI Linux] update lockdir to /var/run/azure-vnet

- cns/cnireconciler/podinfoprovider_test.go
- cns/cnireconciler/statefile.go
- cns/cnireconciler/statefile_test.go
- cns/service/main.go
> write empty json object to empty cni statefile if exists

- cns/azure-cns.yaml
- test/integration/manifests/cns/daemonset.yaml
> chore: update cns daemonset specs with new mounts

- Makefile
- cns/cnireconciler/version.go
- cns/cnireconciler/version_test.go
bump required version of CNI to 1.4.7 for CNI reconcile
**Notes**:
> fix: bump minimum cni to 1.4.7 for reconcile flow

- test/integration/manifests/cns/configmap.yaml
- test/integration/manifests/cns/daemonset.yaml
removes extra cns-config configmap definition in integration test specs
**Notes**:
> fix: remove extra definition of cns-config in test/integration

- npm/translatePolicy.go
translatePolicy function returns duplicated ipsets for namedPort if duplicated ipsets exist, which causes unnecessary call in network policy controller. While the duplicated ipset is filtered in network policy controller, it is the best to avoid the call.
**Notes**:
> [NPM] Remove duplicate namedports in slices to avoid unnecessary CreateSet calls in network policy controller

- cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler.go
- cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler_test.go
- cns/restserver/internalapi.go
- cns/restserver/util.go
- crds/multitenantnetworkcontainer/api/v1alpha1/multitenantnetworkcontainer_types.go
- crds/multitenantnetworkcontainer/manifests/networking.azure.com_multitenantnetworkcontainers.yaml
fix: pass in orchestrator context when querying NC and add more logs
**Notes**:
> [CNS] fix: pass in orchestrator context when querying NC and add more logs

- .golangci.yml
Noticed some things didn't get caught by linters that we had in the config that should have caught them...
Corrects the golangci-lint config format so that the wanted linters are enabled.
**Notes**:
> fix: correct golangci format to enable listed linters

- npm/npm.go
- npm/plugin/main.go
This PR is to print running NPM version in stdout which can help diagnose errors or know tested version (e.g., which version is used for testing).
In addition, this PR replace log with klog for better stdout format in npm.go and main.go
**Notes**:
> [NPM] Print running NPM version in stdout.

- cns/fakes/requestcontrollerfake.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/ipampoolmonitor/ipampoolmonitor_test.go
- cns/restserver/util.go
Finishes and closes https://github.com/Azure/azure-container-networking/pull/962.
> There is a current bug in IPAM pool monitor where if a scale up happens right after scale down then we were accidently deleting the IpsNotInUse list in case Scale up Requested count is same as Total current ip count in CNS.
> 
> As a result DNC was not honoring the scale down as well not allocating new IPs because the existing secondary ip count matches the updated requested count.
**Notes**:
> fix: hysteresis in ipampool during rapid pool scaling

- platform/os_windows.go
Improve performance of boot time query on Windows, it is also a solution for https://github.com/Azure/azure-container-networking/issues/955.
This is refresh of https://github.com/Azure/azure-container-networking/pull/529, the idea comes from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/util_windows.go#L119.
Please note there will be possible one second deviation of result in new implementation, for example the output:
Old:   2021-08-09 00:52:28
New: 2021-08-09 00:52:27(the actual value is 2021-08-09 00:52:27.3958047)
Fixes #955
> fix: Improve boot time query on Windows

- cni/cni.go
- cni/network/plugin/main.go
Remove lock for version command. Noticed azure cni VERSION cmd was called getting more frequently and each call takes a lock file and returning the supported versions. No need for lock to be acquired for returning version. Also few logs are added as part of this call which overrides actual ADD/DEL logs. This PR also remove logs added by version command. 
**Notes**:
> Remove lock for version command

- .golangci.yml
- cns/NetworkContainerContract.go
- cns/api.go
- cns/cnsclient/cli.go
- cns/cnsclient/cnsclient.go
- cns/filter/ipam.go
- cns/filter/ipam_test.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/util.go
- Adds a custom type for IPConfigState to enforce compile-time type safety, 
- Extracts the filters for IPConfigState, simplifies and tests them
**Notes**:
> typed IPConfigState and lazy reusable filters

- cns/api.go
- cns/cnsclient/apiclient.go
- cns/cnsclient/cnsclient_test.go
- cns/cnsclient/httpapi/client.go
- cns/fakes/cnsfake.go
- cns/fakes/ipampoolmonitorfake.go
- cns/fakes/requestcontrollerfake.go
- cns/ipampoolmonitor/ipampoolmonitor.go
- cns/ipampoolmonitor/ipampoolmonitor_test.go
- cns/restserver/internalapi.go
- cns/singletenantcontroller/kubecontroller/crdreconciler.go
- cns/singletenantcontroller/kubecontroller/crdrequestcontroller.go
- cns/singletenantcontroller/kubecontroller/crdrequestcontroller_test.go
- cns/singletenantcontroller/kubecontroller/crdtranslator.go
- cns/singletenantcontroller/kubecontroller/crdtranslator_test.go
- cns/singletenantcontroller/kubecontroller/directcrdclient.go
- cns/singletenantcontroller/kubecontroller/kubeclientinterface.go
- cns/singletenantcontroller/requestcontrollerinterface.go
removes unnecessary "nnc" rename from some "...nnc/api/v1alpha" imports, since it is already unambiguous 
**Notes**:
> chore: remove rename from nnc/v1alpha import

- ipam/ipv6Ipam.go
kubelet registers nodename as lowercase and Azure VMSS sets host name as Capital letters as it scales.  This makes sure we use the correct nodename by lowercasing it.
Reference issue explaining the restriction: https://github.com/kubernetes/kubernetes/issues/71140#issuecomment-439464431
https://github.com/Azure/aks-engine/issues/4623
**Notes**:
> Lowercase ipv6 ipam to name make sure go-client finds the node

- cni/network/invoker_cns.go
- iptables/iptables.go
Let Pods query IMDS when CNS is doing the IPAM (when IPs come from secondary IPs of NC)
**Notes**:
> [Swift] Add snat rule to host IP for IMDS for CNS IPAM

- .pipelines/pipeline.yaml
- Makefile
We need to build an ARM64 version of CNI too now.
Validation on an ARM64 machine:
```
azureuser@test-vm:~$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           Cavium
Model:               2
Model name:          ThunderX2 99xx
Stepping:            0x1
BogoMIPS:            400.00
NUMA node0 CPU(s):   0-31
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
azureuser@test-vm:~$ sudo ./azure-vnet
v1.4.11
```
And when I try running an amd64`cni binary on an arm64 machine, it fails
```
azureuser@test-vm:~$ sudo amd64/azure-vnet
amd64/azure-vnet: 3: …
```
> Adding a build stage for arm64 cni

- cns/NetworkContainerContract.go
- cns/cnsclient/cnsclient.go
- cns/restserver/ipam.go
- cns/restserver/restserver.go
> simplify debug api handlers

- cns/client/client.go
- cns/client/client_test.go
- Making an http client interface
- Testify - TestNew
- Testify - existing cases
- TestNew more cases
- buildRoutes tests
- GetNetworkConfiguration tests
- CreateHostNCApipaEndpoint tests
- DeleteHostNCApipaEndpoint tests
- RequestIPAddress tests improvements
- ReleaseIPAddress tests improvements
- GetIPAddressesMatchingStates tests improvements
- GetPodOrchestratorContext tests improvements
- GetHTTPServiceData tests improvements
> Client http refactor & testing

- cni/network/invoker_azure.go
- cni/network/invoker_azure_test.go
* include add tests
* test delete
* gci
**Notes**:
> test: add tests for CNI Azure invoker (cherry-pick#1010)

- cni/network/multitenancy.go
- cni/network/network.go
> Address comments of utcoverage PR

- netio/mocknetio.go
- netio/netio.go
- netlink/link.go
- netlink/mocknetlink.go
- netlink/netlink_test.go
- netlink/netlink_windows.go
- netlink/netlinkinterface.go
- network/bridge_endpointclient_linux.go
- network/bridge_networkclient_linux.go
- network/endpoint.go
- network/endpoint_linux.go
- network/endpoint_windows.go
- network/epcommon/endpoint_common.go
- network/manager.go
- network/network_linux.go
- network/ovs_endpointclient_linux.go
- network/ovsinfravnet/infravnet.go
- network/ovssnat/ovssnat.go
- network/transparent_endpoint_linux_test.go
- network/transparent_endpointclient_linux.go
> Set MTU for veths based on VM interface

- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/metrics/ipsets.go
Current logic of destroy IPSets flushes and destroy each ipset individually, this results in some ipsets being deleted before their references have been wiped out. This PR will now flush all the Ipsets and then will delete all the ipsets making sure the references are removed while deleting,
> [NPM] Modifying destroy ipsets logic

- network/policy/policy.go
- network/policy/policy_windows.go
- network/policy/policy_windows_test.go
Fixes #1002
Allow the cni plugin to marshall and apply L4WFPProxyPolicy
to Windows endpoints.
Tested on Kubernetes v1.19 with AKS-engine and docker runtime
Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>
**Notes**:
> feat: Adds support for HNS L4WFPProxyPolicy

- .github/workflows/cyclonus-netpol-test.yaml
- .pipelines/npm/npm-conformance-tests.yaml
- .pipelines/pipeline.yaml
- .pipelines/singletenancy/aks-engine/e2e-step-template.yaml
- Makefile
- cns/Dockerfile
- npm/Dockerfile
This adds arm64 docker images for Azure CNS and Azure NPM.
Uses docker buildx to do this, which makes it possible for the clients to pull which arch image they need at runtime dynically, and keep the same tag for both amd64 and arm64. Read more about it here
https://wiki.onap.org/display/DW/Building+a+Platform-Agnostic+Container+Image
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
> Arm64 docker

- Makefile
Fixes the order of the makefile's GOOS and GOARCH setting, if you're just running this on a windows host for example it's necessary, but like we were before with `make all-binaries-platforms` it wasn't necessary/failing, just if only on windows
> chore: moving order of GOOS and GOARCh env sets in makefile

- cni/network/multitenancy.go
- cni/network/network.go
1. not passing correct nma url
2. overwriting result variable in handleconsecutive add call
**Notes**:
> Fix cni multitenancy issues due to code redesign

- npm/npm.go
- npm/pkg/controlplane/controllers/v1/networkPolicyController.go
- npm/pkg/controlplane/controllers/v1/networkPolicyController_test.go
- npm/pkg/controlplane/controllers/v1/parsePolicy.go
- npm/pkg/controlplane/controllers/v1/parsePolicy_test.go
- npm/pkg/controlplane/controllers/v1/parseSelector.go
- npm/pkg/controlplane/controllers/v1/parseSelector_test.go
- npm/pkg/controlplane/controllers/v1/translatePolicy.go
- npm/pkg/controlplane/controllers/v1/translatePolicy_test.go
- npm/pkg/dataplane/policies/policy_windows.go
Moving all v1 controllers and helper files into their new location. Also fixing a couple of issues in windows policy from master
> [NPM] Moving v1 netpol controller into its new location

- .pipelines/pipeline.yaml
- .pipelines/singletenancy/aks-engine/e2e-job-template.yaml
- .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
- .pipelines/windows-image.yaml
- Makefile
- log/logger_windows.go
- npm/Dockerfile.windows
- windows.ps1
For building windows based images
**Notes**:
> ci: add windows build pool 

- vendor/github.com/Microsoft/hcsshim/hcn/hcnpolicy.go
This PR is to change one field in SetPolicySetting from Type to PolicyType to unblock all our testing and images until we have a official HNS build
type SetPolicySetting struct {
Id         string
Name       string
PolicyType SetPolicyType
Values     string
}
> fix: [NPM] Fixing a bug in vendor files until we get an official build

- npm/pkg/controlplane/controllers/v1/podController.go
- npm/pkg/controlplane/controllers/v1/podController_test.go
- npm/util/util.go
- npm/util/util_test.go
PodController in NPM removes ipset information as soon as Pod's status becomes “Terminating”. 
So, even though terminated Pod has some activities (e.g., sending traffic to other pods to notify something) during "Terminating" status, NPM does not allow this connection from the Pod.
Thus, NPM needs to delay cleanup process until Pod completes graceful shutdown.
Plus : started trying parallel UTs.
Fixes #1066
**Notes**:
Only updated podController in v1 now.
> feat: [NPM] Support graceful shutdown in pod

- npm/pkg/controlplane/controllers/v1/podController.go
- npm/pkg/controlplane/controllers/v2/podController_test.go
- npm/pkg/controlplane/controllers/v2/podcontroller.go
- npm/util/util.go
- npm/util/util_test.go
PodController in NPM removes ipset information as soon as Pod's status becomes “Terminating”.
So, even though terminated Pod has some activities (e.g., sending traffic to other pods to notify something) during "Terminating" status, NPM does not allow this connection from the Pod.
Thus, NPM needs to delay cleanup process until Pod completes graceful shutdown.
Fixes #1066
**Notes**:
Previous PR for v1 - feat: [NPM] Support graceful shutdown in pod #1083
> feat: [NPM] Support pod grace period for v2 

- npm/pkg/controlplane/translation/doc.go
- npm/pkg/controlplane/translation/parseSelector.go
- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
This PR includes
1. Add comments of translation packages.
2. Refactor parseSelector.go before egress translation logic to better understand parseSelector code and significantly simplify codes and reduce multiple computations in translatePolicy.go
**Notes**:
You can find the generic ingress translation PR (https://github.com/Azure/azure-container-networking/pull/1055)
Will delete unused codes add UTs for parseSelector.go in a next PR.
Will follow egress translation PR.
> refactor: [NPM] parsing label selector for general translation logic

- npm/pkg/controlplane/translation/parseSelector.go
- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
- npm/pkg/dataplane/policies/policy.go
This PR is to support egress and generalizes translation for egress and ingress.
**Notes**:
1. [NPM] General translation logic for linux and windows #1055
2. refactor: [NPM] parsing label selector for general translation logic #1077
3. refactor: [NPM] General translation logic (mainly clean-up codes and correct bugs) #1105
As @huntergregory summarized, next PR will deal with below lists.
1. switching to `PeerList` instead of `SrcList` and `DstList` like you suggested
2. deciding what to do for pod selector structs
> refactor: [NPM] General translation logic for egress and ingress

- npm/config/config.go
- npm/iptm/iptm.go
- npm/iptm/iptm_test.go
- npm/npm.go
- npm/npm_v1_test.go
- npm/pkg/controlplane/controllers/v1/controllers_v1_test.go
- npm/pkg/controlplane/controllers/v1/networkPolicyController.go
- npm/pkg/controlplane/controllers/v1/networkPolicyController_test.go
- npm/util/const.go
Fix #1088 
In the iptables nat table, under certain conditions, KUBE-SERVICES will mark a packet sent to an LB service before DNAT to a pod's IP. Then, in iptables filter table the KUBE-FORWARD table will accept packets with this mark before the packet reaches AZURE-NPM chain.
As a result, we might not get a chance to drop packets that we should.
As it is now, NPM comes after KUBE-FORWARD.
```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
pkts bytes target     prot opt in     out     source               destination         
17386 1819K KUBE-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding rules */
17129 1806K KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */ …
```
> fix: [NPM] reposition iptables jump to AZURE-NPM chain

- test/integration/manifests/goldpinger/daemonset.yaml
- test/integration/manifests/goldpinger/deployment.yaml
While we wait for bloomberg to cut a new goldpinger release, I have updated the e2e with an image with [my change that only pings ready pods.](https://github.com/bloomberg/goldpinger/pull/107)
**Notes**:
> use goldpinger image which supports IPv6 and only pings ready pods

- npm/pkg/controlplane/controllers/v1/nameSpaceController.go
- npm/pkg/controlplane/controllers/v2/namespacecontroller.go
To avoid using heavy deepEqual to compare label and be consistent with other controller codes.
**Notes**:
Test two functions and their results.
```go
package testing
import (
"reflect"
"testing"
k8slabels "k8s.io/apimachinery/pkg/labels"
)
func BenchmarkLabelEqual(b *testing.B) {
labelA := map[string]string{
"project": "myproject",
"role":    "frontend",
}
labelB := map[string]string{
"project": "myproject",
"role":    "frontend",
}
for i := 0; i < b.N; i++ {
k8slabels.Equals(labelA, labelB)
}
}
func BenchmarkLabelDeepEqual(b *testing.B) {
labelA := map[string]string{
"project": "myproject",
"role":    "frontend",
}
labelB := map[string]string{
"project": "myproject",
"role":    "frontend",
}
for i := 0; i < b.N; i++ { …
```
> perf: [NPM] Use Equal function for label comparison instead of using reflect.DeepEqual in namespaceController

- cni/network/multitenancy.go
- cni/network/plugin/main.go
- cnm/plugin.go
- cns/client/client_test.go
- cns/configuration/configuration.go
- cns/networkcontainers/networkcontainers.go
- common/utils.go
- ipam/fileIpam.go
- log/logger_test.go
- npm/cmd/debug_test.go
- npm/http/server/server_test.go
- npm/pkg/controlplane/controllers/v1/translatePolicy_test.go
- npm/pkg/dataplane/debug/converter.go
- npm/pkg/dataplane/parse/parser.go
- platform/os_linux.go
- processlock/filelock_test.go
- server/tls/tlscertificate_retriever_linux.go
- server/tls/tlscertificate_retriever_linux_test.go
- server/tls/tlscertificate_retriever_windows.go
- server/tls/tlscertificate_retriever_windows_test.go
- store/json.go
- telemetry/telemetrybuffer.go
- test/integration/portforward.go
- tools/acncli/installer/conflist.go
- tools/acncli/installer/utils.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). Since this project has been upgraded to Go 1.17 in #1042, this PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
**Notes**:
> refactor: move from io/ioutil to io and os packages

- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/policy_linux.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/pkg/dataplane/policies/policymanager_linux.go
- npm/pkg/dataplane/policies/policymanager_linux_test.go
- npm/pkg/dataplane/policies/policymanager_windows.go
- npm/pkg/dataplane/policies/testutils_linux.go
Features:
- Cleans up dead policy chains in the background.
- Removes and adds all chains when the number of policies becomes 0.
> feat: [NPM] Clean up iptables chains in Linux v2

- npm/pkg/controlplane/controllers/v1/networkPolicyController.go
- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
- npm/pkg/dataplane/dataplane.go
To handle special IPBlock (0.0.0.0/0) and de-duplicated elements in except in translation logic.
**Notes**:
Instead of using `nomatch`, a better data structure to indicate whether `cidr` or `except` is needed for generic data planes.
Will improve it in next PR with revising data structure.
In addition, 0.0.0.0/0 handling was not decided yet in windows dataplane since windows does not support `nomatch` for `cidr` yet. 
Related previous PR:
1. [NPM] General translation logic for linux and windows #1055
2. refactor: [NPM] parsing label selector for general translation logic #1077
3. refactor: [NPM] General translation logic (mainly clean-up codes and correct bugs) #1105
4. refactor: [NPM] General translation logic for egress and …
> refacto: [NPM] Handle 0.0.0.0/0 ipblock and de-duplicated elements in except field

- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/metrics/ipsets.go
- npm/metrics/ipsets_test.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
- npm/pkg/dataplane/ipsets/testutils_linux.go
Logic for resetting IPSets in Linux:
- get current npm IPSets: 
- run `ipset list --name` (which returns just the set names per line) and grep for "azure-npm-"
- create a restore file which flushes all these sets and then deletes all of them
- see the code for detailed description of the error handling logic and Prometheus metrics logic
Update for Prometheus `ResetIPSetEntries`: 
- removes all sets from the Prometheus metric for IPSet entries
> feat: [NPM] Reset ipsets & update a Prometheus function ResetIPSetEntries (previously just used for UTs)

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_test.go
- npm/pkg/dataplane/ioutil/restore_linux.go
- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/pkg/dataplane/policies/policymanager_linux_test.go
- npm/pkg/dataplane/policies/policymanager_test.go
- npm/pkg/dataplane/policies/testutils.go
- npm/pkg/dataplane/policies/testutils_linux.go
- test/integration/npm/main.go
Linux DP wasn't working for integration tests before this PR. Now it does. 
It will fail conformance tests though due to the first problem in the TODOs below.
TODO in followup PR: 
- fix problem: accept rules for iptables ingress chains jump to EGRESS instead of jumping to ALLOW-INGRESS-MARK chain
- uncomment reboot code for Linux Policy Manager (reset and initialize Azure chains when we have 0 network policies)
- call reconcile for policy manager within DP
- getting the chain line number will return the first digit of the line number, not the whole number. So we might think position 15 is ok when we need position 1.
Linux Policy Manager fixes (in _chain-management_linux.go_):
1. make the jump from FORWARD chain to AZURE-NPM chain the first rule in the FORWARD chain
2. Don't throw an …
> fix: [NPM] Testing Changes and updates to Linux Policy Manager

- npm/azure-npm.yaml
- npm/cmd/start.go
- npm/config/config.go
- npm/npm.go
Update codes to enable v2 NPM (e.g., network policy v2, and etc)
**Notes**:
> feat: [NPM] Update feature toggles and corresponding codes for enabling V2 NPM test

- cni/client/client.go
- cns/cnireconciler/statefile.go
- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/restserver/util.go
- cns/service/main.go
- common/config.go
- platform/os_linux.go
- platform/os_windows.go
- store/json.go
- store/mockstore.go
- store/store.go
- testutils/store_mock.go
In order to get cns to work as a host process pod on windows for AKS, these changes are necessary
> Cns windows aks

- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
When scaling up, we should account for the IPs we have requested when we calculate our free. But when scaling down, we should only account for the IPs that we _have_ when calculating free.
**Notes**:
> fix ipampool scaling - only release IPs we have

- .hooks/pre-push
- Makefile
Installs a pre-push git hook that runs lint and only allows pushing when lint is clean.
**Notes**:
> lint pre-push hook

- cns/NetworkContainerContract.go
- cns/ipampool/monitor.go
- cns/ipampool/monitor_test.go
- cns/restserver/internalapi.go
- cns/restserver/ipam_test.go
**Reason for Change**: 
Plurals are never made with apostrophes
**Notes**:
> fix IPs typos in CNS code and comments

- crd/nodenetworkconfig/client.go
Adds SetOwnerRef to nnc client which sets the NNC ownership to the given object
> feat: nnc client sets ownerref

- .github/workflows/cyclonus-netpol-test.yaml
- npm/azure-npm.yaml
- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_test.go
- npm/pkg/dataplane/ioutil/restore_linux.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
- npm/pkg/dataplane/policies/policy.go
- npm/pkg/dataplane/policies/policy_linux.go
- npm/pkg/dataplane/policies/policy_windows.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/pkg/dataplane/policies/policymanager_linux.go
- npm/pkg/dataplane/policies/policymanager_linux_test.go
- npm/pkg/dataplane/policies/policymanager_test.go
- npm/pkg/dataplane/policies/testutils.go
- npm/pkg/dataplane/policies/testutils_linux.go
- npm/util/errors/errors.go
After running conformance test, fix finding issues.
1. Had a bug where we were jumping to AZURE-NPM-EGRESS chain instead. We need to jump to this other chain since the ingress allow mark will prevent us from returning to ingress chain again after a no-op pass through egress chain.
2. Observed multiple restarting NPM. Checked log and there is nil pointer errors in `NPMSimpleError`.
- For the second error, we need to UT to catch this `nil` error.  
- Need to resolve lint warning.
3. Fix case-sensitivity on protocol value
- need to remove dependency later 
- need better management with `unspecified` and `Any`
4. Fix problem of trying to destroy sets in use by a kernel component
- previously when running `ipset restore`, we would try to destroy sets before deleting any …
> fix: [NPM] V2 NPM (with only linux data plane) bug fix after first run

- cns/NetworkContainerContract.go
- cns/api.go
- cns/client/client.go
- cns/client/client_test.go
- cns/cmd/cli/cli.go
- cns/fakes/cnsfake.go
- cns/fakes/monitor.go
- cns/fakes/requestcontrollerfake.go
- cns/filter/ipam.go
- cns/filter/ipam_test.go
- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
- cns/ipampool/monitor_test.go
- cns/metric/pool.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/restserver/metrics.go
- cns/restserver/restserver.go
- cns/restserver/util.go
- cns/service/main.go
- cns/singletenantcontroller/metrics.go
- cns/singletenantcontroller/reconciler.go
- cns/types/ipconfig.go
- Standardize the language for the CNS IP pool:
- "Allocated": all IPs that CNS has been allocated by DNC.
- "Assigned": the IPs that CNS has assigned to specific Pods.
- "Unassigned": allocated - assigned.
- Defines additional data types for modelling IP pool information:
- `ipPoolState`: is the live view of the IP pool; IPs allocated, assigned, requested, available, pendingProgramming, pendingRelease, unavailable, notInUse.
- `metaState`: holds pool metadata: the batch size, max size, and min/max free.
- adds helper methods to build this state from a single query of the CNS pool singleton instead of several locking calls.
- Upcast all the numerics in the pool Monitor to int64 to stop converting and comparing back and forth between int/int64
- Update the IPAM …
> Update IPAM pool monitor's pool state logic and language

- .github/workflows/cyclonus-netpol-test.yaml
All profile cyclonus logs are emitted same name resulting in overwritten results. Adding the profile suffix to differentiate logs. 
**Notes**:
> fix: [CI] adding profile name to logs

- cns/restserver/api.go
- cns/restserver/api_test.go
Due to wrong regex the hostip is extracted out wrong resulting in 400 badrequest from NMAgent
https://regex101.com/r/pkrHQv/1 
https://github.com/Azure/azure-container-networking/blob/4a4370b0be7c4c7b0293275cd30a470b54a125bf/cns/restserver/api.go#L1085
below is a log snippet, the host ip should be just the IP and not "168.63.129.16/machine/plugins/?comp=nmagent&type=NetworkManagement" regex is not parsing.
[Azure-CNS] Storing ncGetVersionURL for NC ID 53347415-65c7-47af-b13d-31ed8acd1272:  HOST IP 168.63.129.16/machine/plugins/?comp=nmagent&type=NetworkManagement , join net url http://168.63.129.16/machine/plugins/?comp=nmagent&type=NetworkManagement/joinedVirtualNetworks/4941a21f-1a8d-4d0f-8256-cc6e73a8cd22/api-version/1, urlfmt, …
> fix: [CNS] fixing a regex to extract hostip in getncversion req

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_linux.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/pkg/dataplane/policies/policymanager_windows.go
- test/integration/npm/main.go
Adding support to reset all existing NPM ACL policies on all endpoints in windows DP.
**Notes**:
> feat: [NPM] adding windows ACL Policy reset support

- cns/service/main.go
- crd/nodenetworkconfig/Makefile
- crd/nodenetworkconfig/api/v1alpha/zz_generated.deepcopy.go
- crd/nodenetworkconfig/client.go
- crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
- hack/swift/Makefile
Updates the patch methods in the NNC client to use server-side apply.
**Notes**:
> fix: use server-side applies in nnc client

- .pipelines/npm/npm-conformance-tests.yaml
Does shared work in single jobs, then runs the actual testing for each NPM profile in parallel.
Shared work:
- setting up the environment
- making conformance binaries
- creating a shared Azure Resource Group
Work done for each profile:
- creating an AKS cluster
- installing NPM with the given profile
- running conformance and publishing results and logs
> test: [NPM] conformance tests for multiple profiles

- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/testutils_linux.go
Delete the old jump to azure chain (without ctstate new) so that we can destroy azure chain on reset. 
Prior to this fix, deploying v2 after v1 caused a CrashLoopBackOff.
> fix: [NPM] v2 backwards compatibility

- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
Estimated 50-75% improvement in latency from experiments. Previously used regex and now use strings to parse ipset save files. 
Hoping to reduce memory usage as well by not using regex.
> perf: [NPM] cut latency in half for v2 applyIPSets

- npm/cmd/start.go
- npm/pkg/dataplane/dataplane_test.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/pkg/dataplane/policies/policymanager_test.go
- npm/pkg/dataplane/policies/policymanager_windows_test.go
- npm/pkg/dataplane/policies/testutils_windows.go
- test/integration/npm/main.go
- Fix build errors from #1150 in dataplane_windows.go and in dataplane_test.go for Windows.
- Rename `Mode` to `PolicyMode` for the dataplane config.
This PR doesn't try to fix UT errors for Windows that existed before #1150.
> fix: [NPM] fix Windows build errors

- cns/service/main.go
Instead of watching all NNCs (and Nodes and Pods) and filtering on the client-side, we should modify the Manager's cache to only Watch objects with the appropriate fields set which match our Node. This filtering happens server-side as part of the WatchList initialization and should effectively scope CNS's apiserver traffic to its own Node's objects instead of letting it scale with Node and Pod count.
**Notes**:
> Server-side filtering for NodeNetworkConfig, Node, and Pod objects

- npm/iptm/iptm.go
- npm/iptm/iptm_test.go
- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/chain-management_linux_test.go
This PR fixes a bug around getting the iptables line number of the jump from FORWARD chain to AZURE-NPM. The code would take the first digit of the line number, so if the line number were 12, then the code would think the line number is 1.
Updated in both v1 and v2. 
v2 throws errors if the grep output is unexpected, whereas v1 won't. This way, we don't modify the error-throwing behavior of v1.
> fix: [NPM] detect multi-digit numbers when getting iptables line number

- cni/network/network.go
- cni/network/plugin/main.go
- telemetry/telemetry.go
This PR logs critical cni events to AI resource which would help for debugging as logs getting rotated in some cases.
**Notes**:
> chore: Log CNI events to kusto for debugging

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/policies/policy_windows.go
According to the newly found info in VFP, the src and dst port mapping we used earlier are wrong. So correcting the logic as per below mapping:
// HNS has confusing Local and Remote address defintions
// For Traffic Direction INGRESS
// 		LocalAddresses  = Source Sets
// 		RemoteAddresses = Destination Sets
//      LocalPorts      = Destination Ports
//      RemotePorts     = Source Ports
// For Traffic Direction EGRESS
// 		LocalAddresses  = Source Sets
// 		RemoteAddresses = Destination Sets
//      LocalPorts      = Source Ports
//      RemotePorts     = Destination Ports
// If we use IPs in ACLs, then INGRESS mapping is same, but EGRESS mapping will change to below
// For Traffic Direction INGRESS
// 		LocalAddresses  = Source IPs
// 		RemoteAddresses = …
> fix: [NPM] Windows Dataplane logic fix for src and dst ports

- cns/azure-cns.yaml
- cns/service/main.go
- cns/singletenantcontroller/reconciler.go
- crd/nodenetworkconfig/client.go
- test/integration/manifests/cns/clusterrole.yaml
Fixes potential race condition where, since NNCs are named using the Node name:
- a Node named X could be deleted, 
- its NNC might not (yet) be garbage collected, 
- CNS starting on a new Node _also_ named X might fetch that stale NNC and assign IPs from it.
this could result in IP leaks/pod connectivity disruptions when the stale NNC eventually gets GC'd and the new one for that node is created.
**Notes**:
> match on Node controller ref in NNC event predicate

- npm/pkg/controlplane/controllers/v2/namespaceController.go
- npm/pkg/controlplane/controllers/v2/podController.go
- npm/pkg/dataplane/policies/chain-management_linux.go
> fix: [NPM] reduce log noise for reconcile periodic task

- cns/NetworkContainerContract.go
- cns/service/main.go
Signed-off-by: Evan Baker <rbtr@users.noreply.github>.
**Notes**:
> fix initialize from kube pods flow

- cns/NetworkContainerContract.go
- cns/nmagent/client.go
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/util.go
- common/utils.go
> guard against unstructured url forwarding in CNS API's

- cni/client/client_common_test.go
- cni/client/client_integration_test.go
- cni/client/client_unit_test.go
- cni/network/network.go
- cni/network/network_linux.go
- cni/network/network_linux_test.go
- cni/network/network_test.go
- cni/network/network_windows.go
- cni/network/network_windows_test.go
- cni/plugin.go
- cnm/network/network.go
- network/api.go
- network/endpoint.go
- network/endpoint_linux.go
- network/endpoint_windows.go
- network/endpoint_windows_test.go
- network/hnswrapper/hnsv2wrapper.go
- network/hnswrapper/hnsv2wrapperfake.go
- network/hnswrapper/hnsv2wrapperinterface.go
- network/manager.go
- network/manager_mock.go
- network/network.go
- network/network_test.go
- network/network_windows_test.go
- network/transparent_endpoint_linux_test.go
Today in Azure CNI in windows multitenancy, we depend on the NC state to exist in CNS in order for host endpoint cleanup to work. But, if the NC state got deleted from CNS before the CNI DEL command was invoked, the CNI DEL will fail since the CNS state doesn't exist. This PR allows the CNI DEL command to use only the CNI state instead of relying on CNS.
**Notes**:
> feat: don't use CNS for CNI DEL command in windows multitenancy

- npm/http/api/api.go
- npm/http/server/server.go
- npm/metrics/ipsets.go
- npm/metrics/namespaces.go
- npm/metrics/namespaces_test.go
- npm/metrics/pods.go
- npm/metrics/pods_test.go
- npm/metrics/policies.go
- npm/metrics/policies_test.go
- npm/metrics/prometheus-metrics.go
- npm/metrics/prometheus-values.go
- npm/metrics/prometheus_metrics_test.go
- npm/metrics/prometheus_test.go
- npm/metrics/timer.go
- npm/pkg/controlplane/controllers/v1/nameSpaceController.go
- npm/pkg/controlplane/controllers/v1/nameSpaceController_test.go
- npm/pkg/controlplane/controllers/v1/networkPolicyController.go
- npm/pkg/controlplane/controllers/v1/networkPolicyController_test.go
- npm/pkg/controlplane/controllers/v1/parsePolicy.go
- npm/pkg/controlplane/controllers/v1/podController.go
- npm/pkg/controlplane/controllers/v1/podController_test.go
- npm/pkg/controlplane/controllers/v2/namespaceController.go
- npm/pkg/controlplane/controllers/v2/namespaceController_test.go
- npm/pkg/controlplane/controllers/v2/networkPolicyController.go
- npm/pkg/controlplane/controllers/v2/networkPolicyController_test.go
- npm/pkg/controlplane/controllers/v2/podController.go
- npm/pkg/controlplane/controllers/v2/podController_test.go
This PR adds controller exec time metrics for pods/namespaces/policies. Metric labels are "operation" (create/update/delete) and "error" ("true" or "false").
Completed UTs:
- apply time metrics
- v1 controllers
TODO:
- UTs for v2 controllers
> feat: [NPM] perf metrics for pod/ns/policy CRUD

- npm/cmd/start.go
- npm/iptm/iptm.go
- npm/metrics/ai-utils.go
- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/util/const.go
- npm/util/ioutil/restore.go
This PR does the following:
- Sends a log when NPM starts up (allows us to see if a version reached a customer since we can look for that log)
- Sends a heartbeat log which runs in iptables/policy manager periodic tasks. It includes the number of policies in the cluster
- Sends error logs in the v2 dataplane, which previously sent nothing
> feat: [NPM] send more AI logs

- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
- cns/ipampool/monitor_test.go
- test/integration/setup_test.go
> Include PendingRelease when calculating IP pool for scale-down 

- cns/ipampool/monitor.go
- cns/restserver/internalapi.go
- cns/restserver/ipam.go
- cns/restserver/ipam_test.go
- cns/service/main.go
- cns/singletenantcontroller/reconciler.go
> Don't send NNC to Pool Monitor before Reconciler starts

- .github/workflows/cyclonus-netpol-test.yaml
- .pipelines/windows-image.yaml
- Makefile
- docs/npm.md
- windows.ps1
> update cyclonus workflow

- npm/http/server/server.go
- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/policy.go
- npm/pkg/dataplane/policies/policy_linux.go
- npm/pkg/dataplane/policies/policymanager_linux.go
- npm/pkg/dataplane/policies/policymanager_linux_test.go
- npm/pkg/dataplane/policies/testutils_linux.go
Changes:
- disable the CLI for v2
- update some comments
- polish linux policy manager
- increase the max try count to 2 for iptables-restore
- fix the exit code that we ignore when deleting jumps to policy chains (now we ignore when the rule doesn't exist
> fix: [NPM] disable v2 CLI & polish linux policy manager

- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/util.go
- cns/restserver/util_test.go
Allow CNS to register the node if no NCs are present
Livesite issue 13242071
**Validation**
#unitTests and,
When NCs are not present, CNS **allows** re-registration of node:
When NCs **are** present, CNS **denies** re-registration of node:
> Allow cns to register node if no NCs are present

- crd/multitenantnetworkcontainer/Makefile
- crd/multitenantnetworkcontainer/manifests/networking.azure.com_multitenantnetworkcontainers.yaml
Fix the controller-gen args used in multitenantnetworkcontainer makefile and update the generated version to 0.7.0
**Notes**:
> fix: update controller-gen args for multitenantnetworkcontainer crd

- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
> Subnet labels

- npm/ipsm/ipsm.go
- npm/ipsm/ipsm_test.go
- npm/pkg/controlplane/controllers/v1/networkPolicyController.go
Lock ipsm while adding a netpol so that ipsets referenced by iptables rules can't be destroyed before the iptables rule are added.
> fix: [NPM] eliminate chance of ipset race between pod delete and netpol create

- npm/cmd/root.go
- npm/deploy/manifests/controller/azure-npm.yaml
- npm/deploy/manifests/daemon/azure-npm.yaml
- npm/pkg/dataplane/ipsets/ipsetmanager_windows_test.go
- npm/pkg/dataplane/policies/policy_windows.go
Applying changes based on HNS behavior.
**Notes**:
> Windows test branch for validating backport

- .gitignore
- npm/Dockerfile
- npm/cmd/root.go
- npm/cmd/start.go
- npm/deploy/kustomize/overlays/controller/deployment.yaml
- npm/deploy/kustomize/overlays/daemon/deployment.yaml
- npm/pkg/transport/errors.go
- npm/pkg/transport/events_client.go
- npm/pkg/transport/events_server.go
- npm/pkg/transport/tls.go
- npm/scripts/generate_certs.sh
- npm/scripts/san.cnf
This change adds the generation of the Server cert and CA cert to the docker image. These certs are available to both the client and the server side to establish a secure gRPC connection between client & server.
Changes include,
- Adding tls helper functions to transport package
- Generate script to generate the TLS certificates
- Dockerfile (Linux) updated to run the generate script at build time.
TODOs,
- Create a generate script for Windows.
**Notes**:
> [NPM] Generate TLS certificates during docker build and bake into image for gRPC secure channels

- .pipelines/npm/npm-conformance-tests.yaml
Grab non-truncated NPM logs and introduce stress test option to test matrix. 
- NPM logs are tailed and written to file in the background. Conformance exit codes are returned properly.
- Stress testing runs multiple conformance (currently 3) in the background, waits for these processes to finish, and exits with the first failed tests code or 0 if all pass.
- Only adds a profile for v2 stress testing.
- All conformance runs are written to file and published.
> test: [NPM] Stress Testing & Fix Conformance Logs

- cni/network/invoker_mock.go
- cni/network/network.go
- cni/network/network_test.go
- cni/network/plugin/main.go
2. cni to return retriable error for transient errors
This PR addresses CNI to return retriable error for transient errors so that cri would retry on error. This will prevent ipleaks in case if cni cannot connect to cns or cni cannot remove endpoint due to transient error
**Notes**:
> [CNI] Return retriable error for transient errors

- cni/network/network.go
Fixes a regression since [CNI 1.4.13](https://github.com/Azure/azure-container-networking/compare/v1.4.12...v1.4.13#diff-a2f1c51b6e94c2d11383e394bdae9391a1cdef8e6b6ff24210e4ff04f7692f5eL596) where the IPTables chains were set in the opts map, then that opts map was thrown away and an empty opts map was used in the function that execs IPTables with the contents of the opts map.
**Notes**:
> pass the populated IPTables opts instead of overwriting with empty map

- network/endpoint_windows.go
Windows CNI to ignore removenamespaceendpoint error. sometimes cri removes namespace before cni get to removenamespaceendpoint api and thus its failing with namespace not found error and hns endpoint and ip is getting leaked. this change will ignore error from that api and proceed with hns endpoint deletion and ip release
**Notes**:
> Windows CNI to ignore removenamespaceendpoint error

- network/endpoint_windows.go
Using the different HLIP prefix.
> changing the HLIP address used in apipa endpoint

- cns/NetworkContainerContract.go
During CNS initialization, we crash out if we see a Pod with the same IP. However, if there are Pods that have not yet been assigned an IP, they will have the same empty string `""` for that field, triggering this error case.
This ignores pods without IPs during the state initialization.
**Notes**:
> ignore pods that have not been assigned an IP during CNS initialization

- aitelemetry/telemetrywrapper.go
> add hostname and version in the correct field in ai logs

- .github/workflows/crdgen.yaml
Adds a PR check requiring that the CRDs have been regenerated and that the YAMLs are up to date with the Go definitions.
**Notes**:
> add blocking crd gen ci step

- npm/cmd/start.go
- npm/cmd/start_daemon.go
- npm/cmd/start_server.go
- npm/metrics/ai-utils.go
Currently in SOV clouds,  AI telemetry is not initialized. This PR will not let NPM crash on this error. 
**Notes**:
> test: [NPM] Removing fail on AITelemetry error

- cni/network/network.go
CNI delete should not throw error if network not found, This can happen if vm rebooted with pod in running state. After reboot, CRI will call CNI DEL and CNI ADD to create it again. During CNI DEL, network would not be present and cni delete throws errors and prevents pod from getting created. In this PR, when cni gets network not found, there is no point in calling ipam and it should swallow error and return nil.
**Notes**:
> CNI Delete to ignore network not found error

- npm/http/server/server.go
- npm/http/server/server_test.go
- npm/pkg/dataplane/debug/converter_test.go
- npm/pkg/dataplane/debug/trafficanalyzer_test.go
%w directive is not allowed in fmt.Errorf, go1.18 caught this
**Notes**:
> npm: fix error wrapping with go 1.18

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/crdgen.yaml
- .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
- .github/workflows/cyclonus-netpol-test.yaml
- .pipelines/Dockerfile
- Dockerfile.build
- build/tools/go.mod
- cns/Dockerfile
- cns/windows.Dockerfile
- go.mod
- hack/toolbox/Dockerfile.windows
- npm/Dockerfile
- tools/acncli/Dockerfile
> update to go1.18

- crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
> add Overlay mode to NodeNetworkConfig CRD

- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/service/main.go
- Moves metrics to the CNS service port (from previously a dedicated metrics port).
- Adds healthz handler to the root mux.
- Adds pprof handlers to the root mux conditionally based on a new `debug` config opt.
Closes #1294 (because I can't push to it)
**Notes**:
> move metrics to service port, add healthz, pprof 

- cns/singletenantcontroller/conversion.go
- cns/singletenantcontroller/conversion_test.go
RC can write the PrimaryIP in CIDR Notation (as it will in Overlay). This lets CNS parse CIDR PrimaryIPs.
**Notes**:
> support CIDR notation in the NC PrimaryIP

- .github/CODEOWNERS
- .github/workflows/golangci.yaml
The intention of CODEOWNERS is not to set up gatekeepers, but to expedite reviews by automatically assigning someone with domain knowledge when the PR is opened.
**Notes**:
> drop go1.17 from golangci-lint and update codeowners

- cns/ipampool/monitor.go
After init, the PoolMonitor writes the Spec, so it has the target state locally and should not let the NNC updates it receives overwrite that local state.
**Notes**:
> Don't overwrite Spec in IPAM PoolMonitor from NNC again after initialization

- network/hnswrapper/hnsv2wrapperfake.go
- network/network_windows.go
- network/network_windows_test.go
>  Skip network creation if network already exists in HNS

- crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
- crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
> move mode to NC and add type

- npm/pkg/dataplane/ipsets/dirtycache.go
- npm/pkg/dataplane/ipsets/dirtycache_linux.go
- npm/pkg/dataplane/ipsets/dirtycache_linux_test.go
- npm/pkg/dataplane/ipsets/dirtycache_test.go
- npm/pkg/dataplane/ipsets/dirtycache_windows.go
- npm/pkg/dataplane/ipsets/dirtycache_windows_test.go
- npm/pkg/dataplane/ipsets/ipset.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
- npm/pkg/dataplane/ipsets/ipsetmanager_test.go
- npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
- npm/pkg/dataplane/ipsets/testutils_linux.go
dramatically improves apply time for medium to large scale.
Previously, we would parse through an ipset save file for every batch dataplane operation. We can forego that by maintaining member diff for our ipset dirty cache.
New dirty cache adds robustness to all combinations of create/add/del/destroy calls. Windows doesn't need to maintain member diff by nature of HNS.
> perf: [NPM] make apply ipsets faster

- npm/pkg/controlplane/controllers/v2/podController.go
- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/policymanager_linux.go
- remove error messages for non-error (unable to delete deprecated jump to AZURE-NPM)
- fix log that printed a pointer instead of the ipset
> fix: [NPM] clean up logs

- npm/pkg/controlplane/translation/translatePolicy_test.go
Added additional ingress tests
**Notes**:
> test: added additional ingress tests

- hack/toolbox/manifests/Dockerfile.heavy
- hack/toolbox/server/Dockerfile.heavy
> update missed docker image pull

- .pipelines/containers/container-template.yaml
- .pipelines/containers/manifest-template.yaml
- .pipelines/pipeline.yaml
- .pipelines/windows-image.yaml
- Makefile
> build multiplat manifests with buildah

- hack/manifests/busybox-ds.yaml
- hack/manifests/busybox.yaml
- hack/manifests/kubectl.yaml
- hack/manifests/scaler.yaml
- hack/manifests/sshd.yaml
- kubectl pod for cx controlplane access from underlay
- hostnet busybox daemonset and deployments
- pause anti-affinity deployment for scaling nodes when autoscaler is enabled
- sshd deployment
**Notes**:
> hack pods for debugging

- cns/singletenantcontroller/conversion.go
- cns/singletenantcontroller/conversion_test.go
We don't need to reserve a gateway IP, so we can claim the full, inclusive span of the subnet
**Notes**:
> include 0th address when parsing overlay cidrs

- cns/NetworkContainerContract.go
- cns/restserver/api.go
OrchestratorContext cannot always be unmarshalled due to different orchestrator types, so updating CNS logging to exclude it
**Notes**:
> Fix CNS logging

- npm/pkg/controlplane/goalstateprocessor/goalstateprocessor.go
- npm/pkg/controlplane/goalstateprocessor/goalstateprocessor_test.go
- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
- npm/pkg/dataplane/dataplane_test.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/dpshim/dpshim_test.go
- npm/pkg/dataplane/ipsets/ipset.go
- npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
- npm/pkg/dataplane/policies/policy.go
- npm/pkg/dataplane/policies/policy_linux.go
- npm/pkg/dataplane/policies/policy_windows.go
- npm/pkg/dataplane/policies/policymanager_linux_test.go
- npm/pkg/dataplane/policies/policymanager_test.go
- npm/pkg/dataplane/policies/policymanager_windows.go
- npm/pkg/dataplane/policies/policymanager_windows_test.go
- npm/pkg/dataplane/policies/testutils.go
- test/integration/npm/main.go
- 1st commit: remove Name field from NPMNetworkPolicy because we should be using PolicyKey field instead
- Windows Dataplane was using the wrong field in some scenarios
- 2nd commit: move PolicyID field in ACLPolicy to NPMNetworkPolicy since it's the same for all ACLs in a netpol
> fix/refactor: [NPM] eliminate struct fields to prevent errors & reduce memory

- cns/service/main.go
- cns/singletenantcontroller/reconciler.go
> Fix CNS Reconciling and AssignmentMode handling for AKS Swift

- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/ipsets/ipset.go
- npm/pkg/dataplane/ipsets/ipset_test.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
- npm/pkg/dataplane/policies/policy.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/pkg/dataplane/policies/policymanager_windows.go
- npm/util/const.go
Used to never apply policies to endpoints if the policy selector involved a list set. Two changes to enable this:
1. fix calculation getting IPs in the intersection of pod selector IPSets
2. separate out member IPSets of list IPSets in the pod selector
Other change: fail the dataplane if a non "azure" network is specified or if IPPolicyMode is used, which is unimplemented.
> fix: [NPM] fix windows intersection of IPs

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_windows.go
Any of the three controllers can call `dp.ApplyDataPlane()` at any time, so we have to be careful of this situation: 
- `AddPolicy` is called
- an existing pod satisfies a policy's selector
- `ApplyDataPlane()` is called after the selector IPSets are created, but before the network policy is applied
When applying ipsets to the kernel in Windows, we need to add/remove policies from pod endpoints based on whether the pod now satisfies or no longer satisfies a policy's selector. This change makes sure we don't try to add a policy that is "pending" (about to be added to the kernel) in `dp.updatePod()`
Once the pending policy is applied, then existing code already applies the policy to all necessary endpoints.
> fix: [NPM] windows-specific controller race leads to policy doesn't exist error while policy is pending

- cni/network/invoker_azure.go
- ipam/api.go
- ipam/pool.go
- store/json.go
- Fixed some items in this PR: https://github.com/Azure/azure-container-networking/pull/1392
- Fixed some linting issues
- Remove unused error messages, renamed
**Notes**:
> return early if CNI state exist and add some style fixes

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
- npm/pkg/dataplane/policies/policy.go
- npm/pkg/dataplane/policies/policymanager_windows.go
- npm/pkg/dataplane/types.go
- npm/pkg/dataplane/types_linux.go
- npm/pkg/dataplane/types_windows.go
- maintain the netpol references of endpoints so we can delete netpols off the endpoint if needed
- don't need to update an endpoint if a pod update is called for a stale (deleted) pod
- garbage collect the endpoint cache
> fix: [NPM] manage policies on pod endpoints

- npm/pkg/dataplane/ipsets/ipset.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/ipsetmanager_test.go
- npm/util/util.go
> fix: NPM ipv6/CIDR validation

- cns/NetworkContainerContract.go
- cns/service/main.go
replace NumCPU with NumCores, so that it can be correctly decode in dnc side.
wrong request field name, should use NumCores instead of NumCPU
**Notes**:
> fix: replace NumCPU with NumCores

- cns/configuration/cns_config.json
- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/service.go
- cns/service/main.go
- common/listener.go
- go.mod
- go.sum
- keyvault/certrefresher.go
- keyvault/certrefresher_test.go
- server/tls/tlscertificate_retriever.go
This PR adds a `CertRefresher` construct, which allows background pull of new certificates from KeyVault. We use this construct to provide a `tls.Certificate` in a dynamic manner to an HTTP server that uses a `tls.Config`.
**Notes**:
> Adding TLS cert refreshing from KeyVault

- cni/network/invoker_cns.go
- cni/network/invoker_cns_test.go
> add tcp dns snat in swift scenario

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/ipsets/ipset.go
- npm/pkg/dataplane/ipsets/ipset_test.go
- npm/pkg/dataplane/ipsets/ipsetmanager.go
- npm/pkg/dataplane/ipsets/ipsetmanager_test.go
- npm/util/const.go
Previous bug: all traffic is incorrectly allowed if a network policy has a namespace selector for a key (or key:value pair) and none of the namespaces have the given key (or key:value).
In HNS, an ACL conditioned on a list (nested ipset) will apply to any IP if the list has no members. This is contrary to Linux `ipset` behavior, where a match on an empty list will never match any IP.
> fix: [NPM-WIN] add an empty set to lists in Windows

- npm/pkg/dataplane/policies/policymanager_windows.go
Scenario:
- policy applies to pod A
- pod A is deleted
- policy is deleted
- netpol controller currently keeps trying/failing to delete the policy because pod A's endpoint is not found
- pod B comes up, and the deleted policy applies to pod B, so incorrect ACLs may be applied on pod B
This PR also cleans up some logs that were slightly confusing to read
> fix: [NPM-WIN] deleted policy may sometimes be applied to a pod

- npm/pkg/controlplane/controllers/v2/namespaceController.go
- npm/pkg/controlplane/controllers/v2/networkPolicyController.go
- npm/pkg/controlplane/controllers/v2/podController.go
- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/policies/policy.go
- npm/pkg/dataplane/policies/policymanager.go
Windows HNS doesn't support SCTP
> fix: [NPM-WIN] validate sctp

- Makefile
- aitelemetry/api.go
- aitelemetry/telemetrywrapper.go
- cni/network/network.go
- cni/network/plugin/main.go
- cni/telemetry/service/telemetrymain.go
- cns/service/main.go
- common/config.go
- network/endpoint.go
- network/endpoint_windows.go
- network/manager.go
- telemetry/aiwrapper.go
- telemetry/telemetry.go
- telemetry/telemetrybuffer.go
…vice for windows multitenancy will be started from cns.
This PR removes azure-vnet-telemetry binary from windows multitenancy package. Instead, added option in cns to start telemetry service which will receive events from CNI. For windows multitenancy scenario, customer needs to start cns with this option "-ts". eg: ./azure-cns.exe -ts
**Notes**:
> Remove azure-vnet-telemetry for windows multitenancy

- npm/cmd/start.go
Currently if the ConfigMap has `EnableV2NPM: false` we always run v1 NPM, which uses Linux functions.
> fix: [NPM-WIN] never use v1 on windows

- hack/swift/Makefile
> add byo swift cluster to hack makefile

- hack/swift/Makefile
> Fix net-up target in hack Makefile

- cns/restserver/internalapi.go
- cns/restserver/ipam.go
- cns/restserver/metrics.go
> fix latency metrics that should be recorded in Seconds

- azure-ipam/azilium.conflist
- dropgz/build/cni.Dockerfile
> add cilium and azure-ipam to dropgz image

- cns/NetworkContainerContract.go
- cns/configuration/configuration.go
- cns/restserver/api_test.go
- cns/restserver/internalapi.go
- cns/restserver/restserver.go
- cns/restserver/util.go
- cns/service/main.go
- cns/singletenantcontroller/conversion.go
- cns/types/codes.go
- common/config.go
Draft PR for programming iptables snat rules in CNS, which is a part of delegated IPAM.
> Program IPTables SNAT rules in CNS

- cns/ipampool/monitor.go
- cns/ipampool/monitor_test.go
The pool scaling math incorrectly handled a batch size of 1, this fixes that (and codifies the odd-batch behavior) without changing the existing base case behavior.
**Notes**:
> Update poolmonitor to support batch size of 1

- Makefile
> Add make target for delegated ipam

- cns/configuration/configuration.go
- cns/configuration/configuration_test.go
- cns/configuration/testdata/good.json
- cns/ipampool/monitor.go
- cns/ipampool/monitor_test.go
- cns/kubecontroller/clustersubnetstate/reconciler.go
- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/service/main.go
Watch the ClusterSubnetState CRDs for Subnet Exhausted states, push those to the IPAM Pool Monitor to trigger a batch override to 1, releasing all extra IPs and scaling one IP at a time.
**Notes**:
> Watch ClusterSubnetState and drive subnet exhaustion batch changes

- network/bridge_endpointclient_linux.go
- network/endpoint_windows.go
- network/endpoint_windows_test.go
- network/hnsendpoint_mock_windows.go
- network/hnswrapper/hnsv1wrapper.go
- network/hnswrapper/hnsv1wrapperwithtimeout.go
- network/hnswrapper/hnsv2wrapper.go
- network/network_windows.go
- network/network_windows_test.go
- network/ovs_networkclient_linux.go
- network/ovsinfravnet/infravnet_linux.go
- network/transparent_endpointclient_linux.go
Gofumpt network package
N/A
**Notes**:
> style: Go fumpt entire network package

- hack/manifests/cni-installer.yaml
> add cni installer manifest to hack dir

- .github/workflows/codeql.yaml
- .github/workflows/crdgen.yaml
- .github/workflows/golangci.yaml
**Reason for Change**: Moving a PR from "Draft" to "Ready for Review" should run the configured PR Workflows. Other states are defaults that need to be specified now.
**Notes**:
> run workflows when PR promoted out of draft

- npm/pkg/controlplane/controllers/v2/networkPolicyController.go
- npm/pkg/controlplane/translation/translatePolicy.go
- npm/pkg/controlplane/translation/translatePolicy_test.go
negative matches are not supported in windows
> fix: [NPM-WIN] validation to prevent cidr except in windows

- npm/iptm/iptm.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
- npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
- npm/pkg/dataplane/ipsets/testutils_linux.go
- npm/pkg/dataplane/policies/chain-management_linux.go
- npm/pkg/dataplane/policies/chain-management_linux_test.go
- npm/pkg/dataplane/policies/policymanager_linux.go
- npm/util/const.go
- npm/util/ioutil/current-azure-chains.go
- npm/util/ioutil/grep.go
- npm/util/ioutil/restore.go
Sometimes at high scale, the Linux *ipset* utility will leak reference counts for ipsets e.g. there will be no iptables rules or lists referencing an ipset, yet it will have a positive reference count. As a result, some lingering ipsets can't be deleted when NPM boots up. 
In NPM "v1", we ignore these in-use-by-kernel errors. Now we do the same in "v2" to prevent a CrashLoopBackOff when this kernel leak happens.
> scale: [NPM] ignore leaked ipset references

- hack/manifests/cni-installer.yaml
> remove cns bits from cni installer hackfile

- cns/client/client.go
These were forgotten during a previous effort to add endpoints to the
CNS client. Consequently, those endpoints don't actually work unless
these paths are present here.
**Notes**:
> Add missing client paths to CNS Client

- cns/ipampool/monitor.go
- cns/kubecontroller/nodenetworkconfig/reconciler.go
**Reason for Change**: Due to superficial usage of the NC in the IPAM Pool Monitor, it was considered un-started until it received an NNC with an NC. This change fixes that and considers the reconciler and monitor started as soon as an NNC is ready, whether or not the NC is ready also.
**Notes**:
> Accept NNC with no NC as valid and consider pool monitor and reconciler started

- network/network_linux.go
- network/transparent_vlan_endpointclient_linux.go
- network/transparent_vlan_endpointclient_linux_test.go
Packets sent from a network container to another network container on the same VM and same VNET will now leave the VM, have NSG rules applied, and then return to the VM in the transparent vlan (formerly native) mode. Previously, they would be routed in the VNET namespace, never leaving the VM.
N/A
**Notes**:
Disables rp filter to enable asymmetric routing.
> feat: Enable same VM same VNET packet tunneling to host for Transparent Vlan

- cns/NetworkContainerContract.go
Used by Azure-IPAM. This helps the CNS state management PR pass the dropgz build test.
> feat : Add ifname to ipconfigrequest

- cns/configuration/env.go
- cns/kubecontroller/nodenetworkconfig/conversion_test.go
- cns/kubecontroller/nodenetworkconfig/reconciler.go
- cns/kubecontroller/nodenetworkconfig/reconciler_test.go
- cns/service/main.go
CNS shouldn't `CreateOrUpdateNCInternal` a NC that was created for a different Node IP. If the Node IPs don't match, DNC-RC will eventually clean it up, so it is not valid for use.
> feat: compare node IP with NNCs node IP

- .pipelines/npm/npm-conformance-tests.yaml
> chore: Update k8s verion for NPM conformance tests

- zapai/encoder.go
extend fieldStringer to support zap ErrorType and BoolType, so zap.Error and zap.Bool fields can be better map to strings while constructing TraceTelemetry
**Notes**:
> feat: extend fieldStringer to support zap ErrorType and BoolType

- npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
Remove marshalling log line. A third of logs are this line and the operation is instantaneous.
> chore: [NPM-WIN] reduce logs by a third

- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
- test/integration/setup_test.go
> Add services conformance tests to ciliume2e

- cns/kubecontroller/nodenetworkconfig/reconciler.go
> fix level of no valid NC log in reconciler

- Makefile
The target make all-binaries does not currently include building azure-ipam.
Including azure-ipam in the build so that it's available to use in the release pipeline when releasing dropgz.
**Notes**:
> Update Makefile to build all binaries

- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
copy the set's map to avoid issues
> fix: [WIN-NPM] concurrent map iteration and write for ipset selector reference

- npm/pkg/dataplane/dataplane.go
- npm/pkg/dataplane/dataplane_windows.go
- npm/pkg/dataplane/policies/policymanager.go
- npm/pkg/dataplane/policies/policymanager_linux_test.go
- npm/pkg/dataplane/policies/policymanager_test.go
- npm/pkg/dataplane/policies/policymanager_windows.go
- npm/pkg/dataplane/policies/policymanager_windows_test.go
When removing a policy during updatePod(), the policy should not be removed from the cache. This would cause the policy to not be found when deleting the policy.
This PR also fixes the prometheus ACL metric for windows.
> fix: [WIN-NPM] don't remove policy from cache when updating pod

- test/cyclonus/test-cyclonus-windows.sh
test case 60 always failed because it had a namedport. It was the only test case with the label 'update-policy'
> test: [WIN-NPM] ignore a test case with an unsupported namedport

- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
The NC primary IP is not an assignable IP and should not be used by CNS when calculating the IPAM pool scale math. This moves the Primary IP count to a separate metric so that it is not artificially inflating the Total IP count that CNS thinks it has available to assign.
**Notes**:
> Move primary IP count to separate metric to not affect the IPAM math

- .pipelines/npm/npm-cyc-win-tests-latest-release.yaml
> pipeline: New Cyclonus NPM windows only pipeline

- azure-ipam/ipam.go
- azure-ipam/ipconfig/ipconfig.go
…ture
This PR fixes azure-ipam support for aks swift overlay cluster. In AKS swift overlay mode, empty gatewayIP is getting passed from cns to azure-ipam and which is expected. Cilium/Azure CNI really doesn't use this gatewayip. So its better to skip parsing this gatewayIP and passing to Azure CNI 
**Notes**:
> Remove parsing GatewayIP and passing down to CNI

- .pipelines/npm/npm-conformance-tests-latest-release.yaml
- .pipelines/npm/npm-conformance-tests.yaml
> Pipelines: Failfast on an error

- .pipelines/npm/npm-cyc-win-tests-latest-release.yaml
- Makefile
> fix: [NPM] cyclonus latest pipeline cleanup issue

- dropgz/README.md
- dropgz/pkg/embed/payload.go
This is a fix for the cyclic dependency in the dropgz deploy subcommand. The deploy command is trying to write a file that is already being executed by some other program.
This change renames the current dest as old one ( deleting the old dest if it exists) and then try to write the new content to the dest.
**Notes**:
Tested the change locally by trying to use the `deploy` cmd for a file that was running continuously in the background.
> fix: file busy error while deploying through dropgz

- crd/clustersubnetstate/api/v1alpha1/clustersubnetstate.go
- crd/clustersubnetstate/manifests/acn.azure.com_clustersubnetstates.yaml
Evan Baker <rbtr@users.noreply.github.com>
- Updates the JSON annotations to be lowercase for consistency with the rest of Kubernetes
- Fixes the printercolumns to refer to real fields so that we get values in the `kubectl` output
**Notes**:
> Fix ClusterSubnetState JSON annotations and kubectl printcolumns

- Makefile
> add git configuration target to Makefile for Codespaces

- cns/NetworkContainerContract.go
- cns/client/client.go
- cns/client/client_test.go
- cns/client/error.go
These are the final two endpoints that DNC uses without going through the CNS client. Adding these makes it possible to use the CNS client exclusively in DNC.
**Notes**:
> Add two more CNS endpoints to the CNS client

- cni/network/invoker_cns.go
Use 169.254.1.1 gw for cni in overlay mode, tested in standalone aksdev cluster
CreateNetwork fails in windows cni overlay mode because the GW is nil
**Notes**:
> fix: Add 169.254.1.1 GW for Windows CNI Overlay Mode

- cni/network/network_windows.go
- cni/network/network_windows_test.go
The issue is that right now with an IP "172.168.1.1/24" networkName "azure" and multitenancy id "1", we expect the function to return "azure-vlan1-172.168.1-0_24" but instead it returns "azure-vlan1-172.168.1-1_24"
This PR is fixing the issue by parsing the CIDR correctly.
> fix: fixing the CIDR format of getNetworkName() on Windows

- cns/ipampool/metrics.go
- cns/ipampool/monitor.go
- cns/service/main.go
Removes extra local fields to simplify the code for exhausted subnet state handling, and builds a compound CRD Scheme for a shared ctrl runtime manager.
**Notes**:
> Optimize subnet exhaustion handling

- .pipelines/pipeline.yaml
Windows container build fails due to timeout frequently at current limit of 60m. Doubles to attempt to mitigate and increase the pipeline pass percentage.
**Notes**:
> Increase windows container build timeout to 120m

- .pipelines/pipeline.yaml
Disable dual stack e2e tests as its currently not supported by AKS
**Notes**:
> Disabling dual stack e2e tests

- .pipelines/pipeline.yaml
- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
adding additional testing to swift cluster for HostPort conformance
**Notes**:
> Add HostPort conformance test to swifte2e

- cns/restserver/internalapi.go
- cns/restserver/metrics.go
- emits a metric for total NC sync (attempt) count, labelled by success/failure
- improves the sync method to consider the scenario where not all of the NCs that CNS knows about are present in the NMA response an error, and return an error indicating this after processing the NCs that are present in the response.
**Notes**:
> Emit a metric in CNS for NC Sync count by status

- cns/client/client.go
- cns/client/client_test.go
Added two API in CNS client:
`GetAllNCsFromCns()`
`PostAllNCsToCns()`
> Add two API in CNS client for GET and POST all NCs

- docs/feature/subnet-scarcity/phase-2/2-scalingmath.md
- docs/feature/subnet-scarcity/phase-2/3-subnetscaler.md
- docs/feature/subnet-scarcity/proposal.md
Adds migration of the Scaler from the NNC to the ClusterSubnet CRD to Phase 2 of Subnet Scarcity.
Also clarifies the pool scaling feature to indicate that CNS will account for the NC Primary IPs when calculating its request.
**Notes**:
> add scaler migration to subnet scarcity phase 2

- .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
- .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Retry cilium connectivity tests 3 times on failure, since this test has been flaking recently.
PR also changes naming of clusters in the deletion/cleanup stage (name has been changed to avoid resource overlap in submodules/main pipeline)
**Notes**:
> add retry attempts for cilium connectivity test

- .pipelines/npm/npm-conformance-tests-latest-release.yaml
- .pipelines/npm/npm-conformance-tests.yaml
- .pipelines/npm/npm-cyc-win-tests-latest-release.yaml
- AKSWindows2022Preview flag is removed since Windows Server 22 is now GA'ed.
- k8s version does not need to be specified and can prevent cluster from creating if the version goes out of service.
**Notes**:
> [NPM][Windows] remove Windows22 preview flag and k8s version

- cns/NetworkContainerContract.go
- cns/client/client_test.go
- cns/fakes/nmagentclientfake.go
- cns/nmagent/client.go
- cns/restserver/api.go
- cns/restserver/api_test.go
- cns/restserver/internalapi.go
- cns/restserver/internalapi_test.go
- cns/restserver/restserver.go
- cns/restserver/restserver_test.go
- cns/restserver/util.go
- cns/service/main.go
- nmagent/client.go
- nmagent/client_test.go
- nmagent/nmagent_test.go
- nmagent/requests.go
- nmagent/requests_test.go
- nmagent/responses.go
The NMAgent client used previously in CNS is older, and a duplication of the one added in `nmagent/`. In order to maintain one nmagent client and prevent duplication / wasted effort, this changes CNS to use the "official" client instead.
**Notes**:
> Replace the NMAgent client in CNS with the one from the nmagent package

- hack/swift/Makefile
- hack/swift/README.md
> add cilium cluster to hackfile

- telemetry/telemetry.go
- telemetry/telemetrybuffer.go
CNI blocks when sending failure report because CNS exits and is not receiving.
Unblocking channel with select/default clause.
**Notes**:
> fix: unblock channel for cni

- cns/configuration/configuration.go
- cns/logger/cnslogger.go
- cns/logger/log.go
- cns/service/main.go
Allows the user of CNS to specify an appinsights instrumentation key in config so we can split out the telemetry backends to address some of our scale issues.
**Notes**:
no unit tests since there are already no unit tests for the cnslogger and this is a trivial change to grab a string from config and pass it to the Init function
> feat: allow the user to pass an aikey in config

- .pipelines/npm/npm-conformance-tests.yaml
- test/cyclonus/test-cyclonus-windows.sh
- test/cyclonus/test-cyclonus.sh
Previously, a timed-out cyclonus run may be considered green.
Additionally, this PR:
- prints NPM pod state (e.g. restart count) and captures any previous pod logs
- prevents chance of collisions for test resource groups names
> test: [NPM] fail cyclonus if unfinished
