Azure/azure-container-networking

cni/network/network.go, cni/network/plugin/main.go, common/utils.go, ipam/azure.go, telemetry/telemetry.go, telemetry/telemetry_linux.go, telemetry/telemetry_test.go, telemetry/telemetry_windows.go
This PR contains 
- support for telemetry in Linux
- CNI will send its telemetry report to HostNetAgent
- Can predict the number of VMs running Azure CNI, system information and other details
- Will send errormessage if CNI encounters any
=> VSTS#1728451 Added telemetry support for CNI Linux

.github/PULL_REQUEST_TEMPLATE.md
Creates a template for sending Pull Requests.
=> Checkin template for pull requests

docs/cnm.md
Misc updates to the CNM plugin docs, as example was not working for me
=> Update CNM plugin docs

Makefile
This PR adds azure-cns as part of azure-container-networking build and this will enable releasing cns along with cnm and cni.
```release-note
```
=> Added azure-cns as part of azuure-container-networking build

cns/common/utils.go
Forget to add a file in previous PR #101 which contains common functions used by CNS
```release-note
```
=> Util functions for CNS use

cnm/plugin/main.go, cns/api.go, cns/imdsclient/api.go, cns/imdsclient/imdsclient.go, cns/ipamclient/ipamclient_test.go, cns/networkcontainers/networkcontainers.go, cns/networkcontainers/networkcontainers_linux.go, cns/networkcontainers/networkcontainers_windows.go, cns/restserver/api.go, cns/restserver/restserver.go, cns/restserver/restserver_test.go, cns/service.go, cns/service/main.go, common/config.go, common/utils.go, log/logger.go, log/stdapi.go
This PR adds
1. APIs in CNS to support multi-tenancy.
2. Support to specify custom log directory.
3. Ability for CNS to listen on a specific URL based on input parameters.
=> Add APIs in CNS to support multitenancy

telemetry/telemetry.go
=> Added CniSucceeded flag in telemetry.go

cns/api.go
Adding NetworkContainerOrchestratorInfo to CreateNetworkContainerRequest.
=> Adding NetworkContainerOrchestratorInfo field to CreateNetworkContainerRequest.

cns/dnccontract.go
This PR modifies orchestrator and containertype names to more reasonable one
```release-note
```
=> Modified orchestrator and containertype names in dnccontract

cns/restserver/restserver.go
This PR gets orchestrator context and saves to CNS state so that network configuration can be queried based on orchestration context
```release-note
```
=> Modified networkcontainercreate request to save podinfo

cns/dnccontract.go
Adding these constants to describe MultiTenancyInfo ID.
=> Adding encap types.

cns/dnccontract.go
Removing 'ID' suffix from EncapType.
=> Modifying encap types.

Dockerfile.build
moved golang version to 1.10 to unblock windows build
```release-note
```
=> moved golang version to 1.10 

cni/network/network_windows.go
Fix the debug message
```release-note
```
=> Fix error message to include endpoint, container id

Makefile
This PR creates separate package for cni that supports multitenancy
=> Create package for cni that supports multitenancy

cni/azure-windows-multitenancy.conflist
Added windows multitenancy conflist
=> added windows multitenancy conflist

store/json.go
This PR addresses wait timeout for acquiring a lock before the next retry. 
```release-note
```
=> Fixed wait timeout issue for getting file lock

Makefile, cni/network/plugin/main.go, telemetry/telemetry.go
This PR sets up Jenkins for Azure-npm for CI/CD.
=> Setup Jenkins for Azure-npm

Makefile
This PR archives Azure-npm image in Makefile.
=> archive npm image

Dockerfile.build, Makefile, build/build-all-containerized.sh
This PR enables containerized build to build images.
Already tested & merged to dev in PR #204.
=> build image inside build container

cni/network/network.go, cni/network/plugin/main.go, cni/plugin.go, common/utils.go, npm/npm.go, platform/os_linux.go, platform/os_windows.go, telemetry/telemetry.go, telemetry/telemetry_linux.go, telemetry/telemetry_test.go
Adding telemetry report functionality for DNC.
=> Adding telemetry report functions for DNC.

network/ovs_endpointclient_linux.go, network/ovs_networkclient_linux.go
…r 10.0.0.10
Added support for blocking private IP space via snat bridge except for dns ip 10.0.0.10
```release-note
```
=> Added support for blocking private IP space via snat bridge

network/bridge_endpointclient_linux.go, network/endpoint_linux.go
…This fixes pod connecting to itself via service IP
Enabled hairpin on host veth interface to allow pod connecting to itself via service IP
Fixes #189 
```release-note
```
=> Fix for Pod Connecting to itself via ServiceIP

README.md
=> Add CI/report badges to main README

telemetry/telemetry.go
Replacing go log with cns log.
=> Replacing go log with cns log.

scripts/Invoke-wincni.ps1
Adding powershell script to call cni.
=> Adding powershell script to call cni.

Makefile, cni/network/network.go, cni/network/plugin/main.go, cni/telemetry/service/telemetrymain.go, common/utils.go, network/manager.go, npm/npm.go, platform/os_linux.go, platform/os_windows.go, telemetry/cnstelemetry.go, telemetry/main/telemetrymain.go, telemetry/telemetry.go, telemetry/telemetry_linux.go, telemetry/telemetry_test.go, telemetry/telemetry_windows.go, telemetry/telemetrybuffer.go, telemetry/telemetrybuffer_linux.go, telemetry/telemetrybuffer_windows.go
Added support for reporting telemetry from Azure CNI. This features gives statistics about CNI like how many nodes running CNI, how many failures in ADD/DEL calls. Apart from this, it also reports useful messages. 
```release-note
```
=> Added support for reporting telemetry from Azure CNI

cns/service/main.go, log/logger.go
We're temporarily disabling CNS telemetry until we add to changes to spawn the telemetry buffer as a detached process.
```release-note
```
=> Disabling CNS telemetry.

test/e2e/kubernetes/cniLinux.json, test/e2e/kubernetes/cniWindows.json
This PR makes the e2e test files version agnostic. Also using RFC 4627 format.
=> Update E2E files to make them version agnostic

README.md, docs/README.md, docs/npm.md, npm/azure-npm.yaml
This PR adds azure-npm documentation and azure-npm.yaml.
=> Add azure-npm documentation

network/network.go
=> Check for null ref before deleting network

test/e2e/kubernetes/cniWindows.json
This files fixes the e2e test for Windows.
=> Update windows e2e json

telemetry/telemetry.go
Adding new fields in DNCReport.
=> Adding new fields in DNCReport.

cns/NetworkContainerContract.go, cns/restserver/api.go, cns/restserver/restserver.go, cns/restserver/restserver_test.go
=> Support JobObject as a valid network container type

telemetry/telemetry.go
=> Adding container type field.

test/e2e/kubernetes/cniLinux.json, test/e2e/kubernetes/cniLinux18.json, test/e2e/kubernetes/cniWindows.json
=> remove ochestratorRelease patch version in e2e

npm/ipsm/ipsm_test.go, npm/iptm/iptm_test.go, npm/namespace_test.go, npm/nwpolicy_test.go
**What this PR does / why we need it**: Test were failing, but CI was passing
```release-note
NONE
```
=> Report NPM exit codes during tests

Makefile
Create and push images to ACR instead of dockerhub
=> Create and push images to ACR instead of dockerhub

.pipelines/pipeline.yaml
=> Fix AZP artifact names

npm/azure-npm.yaml
Pull azure-vnet-telemetry image from MCR
=> Pull azure-vnet-telemetry image from MCR

aitelemetry/api.go, aitelemetry/telemetrywrapper.go
Updated package path since its case sensitive. 
```release-note
```
=> Updated package path since its case sensitive

cni/ipam/plugin/main.go, cni/network/plugin/main.go
This PR fixes compilation error as result of previous PR(Remove orphan lockfile)
```release-note
```
=> fixed compilation issue

cns/service/main.go
added back telemetry cmdline option in cns to make sure not breaking the existing call to cns
```release-note
```
=> added back telemetry cmdline option

cns/logger/log.go, cns/restserver/restserver.go
updated logger for request and response
```release-note
```
=> updated cns logger for request and response

cns/logger/log.go
fixed request and response function to send logs to AI
```release-note
```
=> fixed request and response function to send logs to AI

cnm/network/network_test.go, ipam/fileIpam_test.go
=> Update CNM test to delete endpoint 

cni/network/network.go, cni/network/plugin/main.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #436 
```release-note
```
=> Fix ACN issue 436 for surfacing CNI errors to kubelet.

cni/azure-linux.conflist, cni/netconfig.go, cni/network/network.go, ebtables/ebtables.go, network/bridge_endpointclient_linux.go, network/endpoint.go
Added EB rules for ip addresses in the conflist. These rules route these ip addresses via the host for linux.
=> Added EB rule for ip addresses in conflist for linux

npm/Dockerfile
=> Update NPM base image to 20.04

cni/azure-linux.conflist
Enable hairpin on VM Nic by default. This will address for LB scenarios where VM acts as proxy or router.
```release-note
```
=> Enable hairpin on VM Nic by default

npm/azure-npm.yaml
Update azure-npm.yaml file to use the latest npm version.
**Which issue this PR fixes** : 
Fix azure-npm version update.
```release-note
```
=> Update to latest image version for azure-npm.yaml file.

.pipelines/Dockerfile
Updating pipeline image with necessary libs and bumping up base image version to 20.04LTS
=> Update Pipeline Image

cns/NetworkContainerContract.go, cns/cnsclient/apiclient.go, cns/cnsclient/httpapi/client.go, cns/requestcontroller/kubecontroller/crdreconciler.go, cns/requestcontroller/kubecontroller/crdrequestcontroller_test.go
API template and skeleton implementation to unblock Neha
=> CNS Client API interface and skeleton implementation

Makefile, cns/restserver/api_test.go
Enable restserver tests, commented faulty tests for now
Failed tests will be fixed as part of VSO: https://msazure.visualstudio.com/One/_workitems/edit/7720083
=> Enable restserver tests, commented faulty tests for now

cns/cnsclient/cnsclient_test.go
=> CNS Client Test Fix

cns/restserver/internalapi.go, cns/service/main.go
Add Truncated Lines from Previous Rebase
**Notes**:
=> Add Truncated Lines from Previous Rebase

cns/service/main.go
Pool monitor was undeclared and causing runtime exceptions
**Notes**:
=> Fix undeclared pool monitor

npm/Dockerfile
Setting base image to focal removes vulnerabilities
https://quay.io/repository/matmerr/azure-npm/manifest/sha256:7cc3a7d1e7a97cc933fde2c04f1e034efe7076d880bdec8dfa2872aacfd816a3?tab=vulnerabilities
**Notes**:
=> Update NPM Dockerfile

Makefile, cni/azure-linux-swift.conflist
Need to generate a CNI tarball with a swift conflist, where the CNI mode is `azure-cns`
**Notes**:
=> feat: Produce Azure CNI Swift tarball

nodenetworkconfig/api/v1alpha/nodenetworkconfig.go, nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
=> NodeNetworkconfig: Updated json name to avoid spaces in the IP definition

.pipelines/e2e-step-template.yaml, cns/azure-cns.yaml
=> update cns tag in yaml

cns/azure-cns.yaml
Update CNS tag to 1.2.0
**Notes**:
=> Update cns yaml

network/endpoint_linux.go, network/transparent_endpointclient_linux.go
=> [master] latency fix for transparent mode

network/network_linux.go
=> fix for configuring multiple dns server on azure0 interface

.pipelines/npm/npm-conformance-tests.yaml, .pipelines/singletenancy/aks-engine/e2e-step-template.yaml, Makefile
Enable debugging symbols while still persisting compiler optimization
**Notes**:
=> [build] Enable debug symbols in bins

.pipelines/npm/npm-conformance-tests.yaml, .pipelines/singletenancy/aks-engine/e2e-step-template.yaml, Makefile, npm/iptm/helper.go, npm/iptm/helper_test.go, npm/iptm/iptm.go
Right now all the basic chain and rules are hard to comprehend with redundant code. Cleaning that up
=> [NPM] Consolidating default chains and rules for easier readability

npm/plugin/main.go
Reducing resync time to 15 mins
=> [NPM] Reducing resync time to 15 mins

cns/api.go, cns/cnsclient/cli.go, cns/ipampoolmonitor/ipampoolmonitor.go, cns/restserver/ipam.go, cns/restserver/ipam_test.go
Handle Error handling in IPAMPoolMonitor to update the cached spec only if CRD Update is successful otherwise keep retrying
=> Cns fixipampoolmonitor errorhandling

npm/plugin/main.go
=> [perf] NPM only writes to stdout instead of file

.pipelines/pipeline.yaml
=> [ci] Remove Windows 1809 E2E definition

npm/iptm/helper.go, npm/iptm/iptm.go, npm/namespace.go, npm/nwpolicy.go, npm/pod.go, npm/util/const.go
This PR includes:
1. A new chain where NPM will remove the added MARKs and will ACCEPT packets
2. Bailing out when error occurs
=> [NPM] Clearing NPM MARKs on packets before accepting them

.pipelines/npm/npm-conformance-tests.yaml, npm/ipsm/ipsm.go, npm/ipsm/ipsm_test.go, npm/namespace_test.go, npm/pod.go, npm/util/const.go
Bail early on ipset errors
**Notes**:
=> [fix] IPset fail if set doesn't exist when attempting to add to list

npm/nameSpaceController_test.go, npm/npm.go, npm/npm_test.go, npm/podController_test.go
After adding two controller and resolving conflicts through web editor, it left some dangling imports resulting in failures.
=> Fixing a regression with integration of two controllers

.pipelines/singletenancy/aks-swift/e2e-step-template.yaml
Removing artifact directories that had the logs, after published of course
=> Cleanup artifacts dir

npm/azure-npm.yaml
=> NPM: Update NPM limits

Makefile
We need statically linked binaries
**Notes**:
=> [CNI] Disable cgo when building ACN artifacts

Makefile
Only building linux binaries
**Notes**:
=> chore: remove hardcoded envs from makefile

cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler.go, cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler_test.go, cns/service/main.go
fix: set correct orchestratorType and orchestratorContext
**Notes**:
=> fix: set correct orchestratorType and orchestratorContext

cns/service/main.go
Tidy up the use of rootCtx so that it's only used directly in `main()` and pass child contexts to other functions.
**Notes**:
=> fix: only use rootCtx in main()

npm/npm.go
Due to this bug, reconcile loop is dying after one 5 minute loop and not continuing.
=> [NPM] [Bug] Fixing the looping issue in backup and reconcile chains

cns/cnireconciler/statefile.go
=> fix: add addtl log context when CNS mutates CNI statefile

cns/azure-cns.yaml, test/integration/manifests/cns/daemonset.yaml
=> fix: mount cni bin dir

tools/acncli/deployment/manager.yaml, tools/acncli/deployment/manager_swift.yaml
=> updated cni manager to latest versions

cni/network/network.go
=> fix: return nil instead of earlier err when we complete

cns/azure-cns.yaml
=> update cns.yaml to version 1.4.7

tools/acncli/deployment/manager_swift.yaml
=> Update azure-cni-manager to 1.4.7

.github/workflows/cyclonus-netpol-test.yaml, test/cyclonus/install-cyclonus.yaml
Increasing verbosity from info to debug will be useful when unexpected test results come after running cyclonus test. 
Also update sed matching to avoid updating cyclonus-netpol-test.yaml file when npm image 
version in the azure-npm.yaml is changed.
**Notes**:
=> chore:  [NPM]  Update scripts for cyclonous test

cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler_test.go
fixes a broken UT in the multitenant CRD operator that was introduced in #960 
=> fix: broken multitenant crd unit test

Makefile, build/tools/go.mod, build/tools/tools.go
raises golangci-lint timeout from 1m to 10m and adds gofumpt to tools for convenience 
**Notes**:
=> update to tools and Makefile

cns/cnsclient/httpapi/client.go, cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler.go, cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler_test.go
=> fix: repair error code dismatch in multitenantnetworkcontainer controller

cns/api.go, cns/cnsclient/apiclient.go, cns/cnsclient/cnsclient_test.go, cns/cnsclient/httpapi/client.go, cns/fakes/cnsfake.go, cns/fakes/ipampoolmonitorfake.go, cns/ipampoolmonitor/ipampoolmonitor.go, cns/multitenantcontroller/mockclients/Makefile, cns/multitenantcontroller/mockclients/cnsclient.go, cns/restserver/api_test.go, cns/restserver/internalapi.go, cns/restserver/internalapi_test.go, cns/restserver/ipam_test.go, cns/singletenantcontroller/kubecontroller/crdreconciler.go, cns/singletenantcontroller/kubecontroller/crdrequestcontroller_test.go
=> chore: cleanups in ipampoolmonitor

aitelemetry/api.go, aitelemetry/telemetrywrapper.go, aitelemetry/telemetrywrapper_test.go
Add flush func for ai telemetry wrapper so services may force the current queue to be sent.
**Notes**:
=> chore: Add Flush for AITelemetryWrapper

network/network_linux.go
Today for multitenancy on Ubuntu 18, we assume systemd-resolved is running, query the dns servers on eth0 and move them to azure0 when we create the bridge. The problem for privatecluster is that they are using ubuntu 18 but disabling systemd-resolved. So instead of assuming it is running for Ubuntu 18, we should instead check the service status, and if it is not running, don't copy the dns servers from eth0 to azure0 (basically just do what we do for ubuntu 16 today).
**Notes**:
=> fix: Check if systemd-resolved is running before copying dns servers

cns/NetworkContainerContract.go, cns/cnireconciler/podinfoprovider.go, cns/cnireconciler/podinfoprovider_test.go, cns/singletenantcontroller/kubecontroller/crdrequestcontroller.go
=> feat: crash cns when dupe ips are found during reconcile

npm/npm.go, telemetry/telemetry.go
Remove dead codes in NPM-related metrics from telemetry and NPM
**Notes**:
=> [NPM] chore: NPM telemetry cleanup

telemetry/metadata_test.json, telemetry/telemetry.go, telemetry/telemetry_linux.go, telemetry/telemetry_test.go, telemetry/telemetry_windows.go, telemetry/telemetrybuffer.go
Remove dead codes and corresponding UTs from telemetry package.
**Notes**:
=> chore: Remove dead codes from telemetry packages. 

.golangci.yml
lint on variables shadowing imparts and protected keywords.
**Notes**:
=> feat: add shadow linting

cni/network/invoker_azure.go, cni/network/invoker_azure_test.go
add's UT's to the azure vnet ipam invocation process
**Notes**:
=> test: add tests for CNI Azure invoker

telemetry/aiwrapper_test.go, telemetry/telemetry.go, telemetry/telemetry_test.go, telemetry/telemetrybuffer_test.go
Refactor UTs to cleanup UTs and increase UT coverages in telemetry package
**Notes**:
=> chore: Refactor UTs in telemetry packages

Makefile, cns/configuration/configuration.go, cns/configuration/configuration_test.go, cns/configuration/testdata/bad.txt, cns/configuration/testdata/good.json, cns/hnsclient/hnsclient_linux_test.go, cns/service/main.go
Up UT % in CNS by testing config behavior and HNS Linux stub (0 -> 85% and 0 -> 100%)
**Notes**:
=> test cns config and hns linux stub

telemetry/metadata_test.json, telemetry/telemetry.go, telemetry/telemetry_linux.go, telemetry/telemetry_test.go, telemetry/telemetry_windows.go, telemetry/telemetrybuffer.go
=> Remove dead codes from telemetry package (Cherry-pickup#1004)

telemetry/aiwrapper_test.go, telemetry/telemetry.go, telemetry/telemetry_test.go, telemetry/telemetrybuffer_test.go
* Refactor UTs to cleanup UTs and increase UT coverages
* User assert for consistency
* Applied comments and resolve lint error
* Delete unnecessary license header
**Notes**:
=> chore: Refactor UTs in telemetry packages (cherry-pick#1011)

cni/network/network.go, cnm/network/network.go, cnm/network/network_test.go, cnms/service/networkmonitor.go, netlink/ip.go, netlink/link.go, netlink/mocknetlink.go, netlink/netlink.go, netlink/netlink_linux.go, netlink/netlink_test.go, netlink/netlink_windows.go, network/bridge_endpointclient_linux.go, network/bridge_networkclient_linux.go, network/endpoint.go, network/endpoint_linux.go, network/endpoint_test.go, network/endpoint_windows.go, network/epcommon/endpoint_common.go, network/manager.go, network/netlinkinterface/netlinkinterface.go, network/network_linux.go, network/ovs_endpoint_infraroute_linux.go, network/ovs_endpoint_snatroute_linux.go, network/ovs_endpointclient_linux.go, network/ovsinfravnet/infravnet.go, network/ovssnat/ovssnat.go, network/ovssnat/ovssnat_test.go, network/transparent_endpointclient_linux.go, npm/translatePolicy_test.go
* Initial pass at Netlink interface
* changing some netlink and epc
* Resolcing all dependencies on netlink package
* first pass at adding a netlinkinterface
* windows working now
* feat: update cns client (#992)
* fix debug commands
* fix: update cns client
* add ctx to debug calls
* repackage cns client
* add ctx to all methods and preinit all route urls
* down-scope cns client interface and move to consumer packages
* no unkeyed struct literals …
=> Netlink package interfacing and adding a fake (cherry-pick#996)

network/endpoint_linux.go, network/network_linux.go, network/ovs_endpoint_snatroute_linux.go, network/ovs_endpointclient_linux.go, network/ovs_networkclient_linux.go, network/ovs_networkclient_linux_test.go, network/ovsinfravnet/infravnet.go, network/ovssnat/ovssnat.go, network/ovssnat/ovssnat_test.go, ovsctl/ovsctl.go, ovsctl/ovsctl_mock.go
* Added ovsctl mock
* Changed iptables and ovsctl to use interface instead of concrete
classes
* Added tests for ovs_networkclient_linux.go
* Fix linter issues
Co-authored-by: Shriroop <shrjo@microsoft.com>
**Notes**:
=> Add UT coverage ovs_network_client (cherry-pick#1008)

crd/multitenantnetworkcontainer/api/v1alpha1/multitenantnetworkcontainer_types.go, crd/multitenantnetworkcontainer/manifests/networking.azure.com_multitenantnetworkcontainers.yaml
sync MultiTenantNetworkContainer properties from aks rp
**Notes**:
=> chore: add reservationSet property to MultiTenantNetworkContainer

Makefile, npm/pkg/dataplane/policies/policy_windows.go
Policy Managed Linux missed a windows code change causing windows NPM build failure. Fixing it.
=> [NPM] Fixing a windows NPM build issue

cns/configuration/configuration.go, cns/configuration/configuration_test.go, cns/service/main.go
=> fix: use correct duration for pool refresh

npm/pkg/dataplane/ipsets/ipset.go, npm/pkg/dataplane/policies/policy.go, npm/pkg/dataplane/policies/policy_windows.go, npm/pkg/dataplane/policies/policymanager.go, npm/pkg/dataplane/policies/policymanager_linux.go
Few changes (use better functions, update comments and remove todo for better maintenance.
**Notes**:
=> refactor: [NPM] Minor fixes (does not change functionality, but for better maintenance)

cns/azure-cns-windows.yaml, tools/acncli/deployment/manager_swift.yaml
`azure-cns-windows.yaml` to deploy the azure-cns docker container from #1043
=> Azure cns yaml

npm/Dockerfile.windows
=> chore: Update npm windows to dockerfile servercore base

Makefile
Makes the hook install optional because windows+linux using the repo at the same time is broken.
**Notes**:
=> make hook install optional

.github/dependabot.yml
=> chore: create dependabot.yaml

.github/dependabot.yml
=> chore: remove dependabot vendor

cns/NetworkContainerContract.go, cns/api.go, cns/client/client.go, cns/client/client_test.go, cns/fakes/cnsfake.go, cns/fakes/requestcontrollerfake.go, cns/filter/ipam.go, cns/filter/ipam_test.go, cns/ipampool/monitor.go, cns/restserver/internalapi_test.go, cns/restserver/ipam.go, cns/restserver/ipam_test.go, cns/restserver/metrics.go, cns/restserver/util.go
=> feat: shim in a metric for ipconfigstatus state transition durations

npm/examples/windows/azure-npm.yaml
Fixing the toggle name in windows files
**Notes**:
=> fix: [NPM] enable v2 toggle name in windows

test/kubemark/aks-e/README.md, test/kubemark/aks-e/azure-npm-with-kubemark.yaml, test/kubemark/aks-e/configure-hollowNode-on-external-cluster.sh, test/kubemark/aks-e/deployments/deploy1.yaml, test/kubemark/aks-e/deployments/deploy10.yaml, test/kubemark/aks-e/deployments/deploy2.yaml, test/kubemark/aks-e/deployments/deploy3.yaml, test/kubemark/aks-e/deployments/deploy4.yaml, test/kubemark/aks-e/deployments/deploy5.yaml, test/kubemark/aks-e/deployments/deploy6.yaml, test/kubemark/aks-e/deployments/deploy7.yaml, test/kubemark/aks-e/deployments/deploy8.yaml, test/kubemark/aks-e/deployments/deploy9.yaml, test/kubemark/aks-e/hollow-node.yaml, test/kubemark/aks-e/hollownodes.sh, test/kubemark/aks-e/npm.sh, test/kubemark/aks-e/pods.sh
This PR has all scripts and documents to run future NPM scale perf experiment.
Please check `README.md` in the PR.
You may find further information on `acndocs` in `NPM/kubemark`
**Notes**:
=> test: [NPM] This PR has all scripts and documents to run kubemark for future NPM scale perf experiment

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, Makefile
adds trimmed down (go+git+k8s) config for codespaces 
**Notes**:
=> add devcontainer for codespaces

.pipelines/npm/npm-conformance-tests.yaml
Conformance pipeline is failing because the NpmLogs artifact for 2nd matric run complains. Fixing that. 
**Notes**:
=> fix: [NPM] fix conformance pipeline NPM Logs name

npm/iptm/iptm.go, npm/testpolicies/allow-all-ns-to-frontend.yaml, npm/testpolicies/deny-all-from-app-backend.yaml
testpolicy names used to conflict with each other
=> fix: [NPM] remove print statement in v1 and update testpolicy names

.pipelines/singletenancy/aks-engine/e2e-dualstack-job-template.yaml
This PR updates dualstack e2e cluster rgname to "kubernetes-dual-xx" so that cleanup pipeline can remove dangling clusters starts with kubernetes 
**Notes**:
=> update dualstack rgname to "kubernetes-dual-xx"

.github/workflows/cyclonus-netpol-test.yaml, npm/cmd/start.go, npm/config/config.go, npm/examples/windows/azure-npm.yaml, npm/profiles/v2-apply-on-need.yaml
Toggle options: Apply All and Apply On Need. only affects v2.
Adds a Cyclonus test for v2-apply-on-need.
=> feat: toggle for ipset mode plus profile for v2-apply-on-need

.github/workflows/codeql-analysis.yml
=> Adds CodeQL action

.github/workflows/stale.yaml
=> update stale parameters and include PR messages

cns/restserver/ipam.go, cns/restserver/metrics.go
We want to know when we're getting lots of failures. Instrumenting from prometheus for aks case so expose errror codes int he two most frequent calls it gets from cni. 
Issue not made. 
**Notes**:
=> get return codes for ipconfig at least

build/tools/go.mod, build/tools/go.sum
=> update gofumpt tool

.github/workflows/cyclonus-netpol-test.yaml
=> specify docker as container builder

.pipelines/Dockerfile, Dockerfile.build, Dockerfile.cnm, Makefile, cni/telemetry/Dockerfile, cns/Dockerfile, cns/windows.Dockerfile, hack/toolbox/Dockerfile.windows, hack/toolbox/manifests/Dockerfile.heavy, hack/toolbox/server/Dockerfile.heavy, hack/toolbox/server/Dockerfile.lite, npm/Dockerfile, npm/Dockerfile.windows, tools/acncli/Dockerfile
Only Docker assumes you want to pull from DockerHub, everyone else should be told which registry to pull the image from.
**Notes**:
=> use fully-qualified image names in all Dockerfiles

npm/cmd/start.go, npm/cmd/start_daemon.go, npm/cmd/start_server.go, npm/config/config.go, npm/iptm/iptm.go, npm/metrics/ai-utils.go, npm/pkg/dataplane/dataplane.go, npm/util/const.go
include NPM v1/v2 in telemetry and fix heartbeat log (wasn't sending)
=> feat: [NPM] include NPM v1/v2 in telemetry and fix heartbeat log

.pipelines/pipeline.yaml
Putting back Swift pipeline stage
**Notes**:
=> test: adding back Swift e2e pipeline

crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
=> Updates to the CRD Manifests.

.github/workflows/golangci.yaml
=> update golangci-lint action

.github/CODEOWNERS
=> test codeowners

.pipelines/pipeline.yaml
=> fix: [tests] temporarily disable Windows Dualstack e2e

cns/service/main.go
Set remote ARP MAC address when CNS is running in CRD mode
Unblocks AKS-Swift on windows along with #1076 
**Notes**:
=> feat: Set remote ARP MAC address when CNS is running in CRD mode

Makefile, cni/azure-windows-swift.conflist
Modify Makefile to build CNI archive for Windows AKS Swift and add the corresponding conflist
**Notes**:
=> build: Enable Windows AKS Swift Release

cni/azure-linux-swift-overlay.conflist, cni/azure-windows-swift-overlay.conflist, cni/netconfig.go, cni/network/invoker_azure_test.go, cni/network/invoker_cns.go, cni/network/network.go, cni/network/network_test.go, cni/network/network_windows.go, cni/util/const.go
=> Return if execution mode is v4OnlyOverlay

cns/nmagent/client.go
=> return an error for non http 200 response from nmagent

npm/util/util_test.go
This should increase coverage of util.go by 26.4%.
=> test: add tests for npm/util

.gitignore, Makefile, go.work, go.work.sum
=> remove workspace and add helpers to set it up

.pipelines/Dockerfile, Dockerfile.build, Dockerfile.cnm, cni/telemetry/Dockerfile, cns/Dockerfile, cns/windows.Dockerfile, hack/toolbox/Dockerfile.windows, hack/toolbox/manifests/Dockerfile.heavy, hack/toolbox/server/Dockerfile.heavy, hack/toolbox/server/Dockerfile.lite, npm/Dockerfile, npm/Dockerfile.windows, tools/acncli/Dockerfile
DockerHub will start rate-limiting us and fetching deps from the internet will be blocked internally shortly. Getting ahead of that by migrating to MCR.
**Notes**:
=> pull images from mcr

cns/configuration/configuration.go, cns/configuration/configuration_test.go, cns/service/main.go
This reverts commit 5ec6a3f2a8d3ca02f8c02716e6024f7f67ea765f.
**Notes**:
=> Revert "move metrics to service port, add healthz, pprof  (#1318)"

Makefile
=> build overlay cni tgz

cns/doc/examples/metrics/README.md, cns/doc/examples/metrics/grafana.json, cns/doc/examples/metrics/grafana.yaml, cns/doc/examples/metrics/podMonitor.yaml, cns/doc/examples/metrics/scrape_config.yaml
=> CNS Prometheus and Grafana examples

cni/azure-linux-multitenancy.conflist, cni/azure-windows-multitenancy.conflist
Fix the CNI conflist of multitenancy and add the correct ipam type
**Notes**:
=> Fix the CNI conflist of multitenancy and add the correct ipam type

.pipelines/singletenancy/aks-swift/e2e-job-template.yaml
Use default build pool for AKS-Swift
**Notes**:
=> build: Use default build pool for AKS-Swift

.github/dependabot.yaml
=> Add build/tools to dependabot tracking

.pipelines/containers/container-template.yaml, .pipelines/containers/manifest-template.yaml, Makefile
images should be in the artifact payload for release
**Notes**:
=> save image tarballs as pipeline artifacts

.pipelines/singletenancy/aks-engine/e2e-step-template.yaml
Picking up AKS-E w/ [these changes](https://github.com/jaer-tsun/aks-engine/pull/1)
**Notes**:
=> ci: bump AKS-E to v1.0.5

.pipelines/singletenancy/aks-engine/e2e-step-template.yaml
=> Adding the delete rg task

cni/network/invoker_cns.go, cni/network/invoker_cns_test.go
Fixes CNI ADD command for Overlay scenario
=> fix: set hostsubnetprefix for overlay

.github/dependabot.yaml
Configures dependabot to update our GH Actions workflows and our Dockerfiles
**Notes**:
=> add docker and github actions to dependabot config

cni/network/invoker_azure.go
style: the true condition of cniStateExists has already been checked above.
**Notes**:
=> style: remove code smell

npm/azure-npm.yaml
=> Update image in azure-npm.yaml

npm/pkg/dataplane/dataplane_windows.go
=> NPM: Delete log for public preview

npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
Moving some logs for Windows NPM
=> [NPM] moving some logs around for windows

.pipelines/pipeline.yaml
=> fix: temp bypass of broken win2022 e2e

azure-ipam/logger/logger.go, azure-ipam/main.go
=> Cilium Integration fixes 

cns/ipampool/monitor.go
=> log full pool state on change and every 30s

cns/ipampool/monitor_test.go
=> add test to purge pendingRelease IPs in ipampoolmonitor

cns/kubecontroller/nodenetworkconfig/conversion.go, cns/kubecontroller/nodenetworkconfig/conversion_test.go, cns/kubecontroller/nodenetworkconfig/metrics.go, cns/kubecontroller/nodenetworkconfig/reconciler.go, cns/kubecontroller/nodenetworkconfig/reconciler_test.go, cns/kubecontroller/nodenetworkconfig/scopedclient.go, cns/service/main.go
=> move singletenantcontroller to nested kubecontroller package and rename

.pipelines/singletenancy/aks-swift/e2e-step-template.yaml, hack/swift/Makefile, test/integration/manifests/cns/daemonset.yaml, test/integration/setup_test.go
=> Update swift e2e to use CNS ds with CNI installer

Makefile
=> exclude tags for go submodules when building repo version

cns/kubecontroller/nodenetworkconfig/reconciler.go
=> move reconciler-started log in to the once

test/integration/manifests/cns/daemonset.yaml
CNS 1.4.29 does not include updates for iptable rules, changing to 1.4.32
**Notes**:
=> Update CNS version in test daemonset

.pipelines/singletenancy/aks-swift/e2e-step-template.yaml
=> Add conformance tests to swifte2e

.github/dependabot.yaml
=> add azure-ipam to dependabot tracking

.pipelines/containers/container-template.yaml, .pipelines/pipeline.yaml
=> build arm64 images on an arm64 pool

.pipelines/containers/container-template-windows.yaml, Makefile
=> fix: Remove retry from Windows pipelines

.pipelines/containers/container-template-windows.yaml, Makefile
=> fix: Remove powershell sub command while building windows images

.pipelines/npm/npm-cyc-win-tests-latest-release.yaml
=> test: [NPM] rename resource group for win cyc latest to prevent cleanup

.pipelines/npm/npm-cyc-win-tests-latest-release.yaml
hns debugger will capture logs/traces
=> test: [NPM] deploy hns-debugger in latest cyc pipeline

dropgz/build/cni.Dockerfile
=> fix: removing cert container from cniInstaller

cns/NetworkContainerContract.go, cns/restserver/api.go, cns/restserver/api_test.go, cns/restserver/restserver.go, cns/restserver/util.go
Added API on CNS:
- If received  "GET": Return all NCs in CNS's state file to DNC in order to check if NC refresh is needed
- If received "POST": Store all the NCs (from the request body that client sent) into CNS's state file
Added test for the two handler above.
=> NC refresh optimization

cns/client/client.go
This path was missed in a prior iteration, but is necessary for the client to function properly. Without it, the route cannot be found and thus the request cannot be created.
**Notes**:
=> Add path to CNS client for DeleteNC

.pipelines/pipeline.yaml
Updates the pipeline triggers to:
- Only build on PRs to master
- excluding PRs which only change `docs/*`
- Don't rebuild for commits on master
- Build tags on master
- excluding tags under `zapai/`, `azure-ipam/`, or `dropgz`
**Notes**:
=> update pipeline triggers

.devcontainer/devcontainer.json
=> Update default extensions and settings for codespace vscode

hack/swift/Makefile
build overlay clusters
**Notes**:
=> add overlay-up target to hackfile

dropgz/build/cni.Dockerfile
adds the azure-swift-overlay.conflist in the dropgz build file so Azure CNI Overlay clusters can use the dropgz to install the cni.
Signed-off-by: Tyler Lloyd <tylloyd@microsoft.com>
Adds the [azure-swift-overlay](https://github.com/Azure/azure-container-networking/blob/95155ca9b4079cfe9ce4e93c04de419e28a3ad3c/cni/azure-linux-swift-overlay.conflist) conflist to dropgz's build process so that it can be loaded onto a host without the conflist.
**Notes**:
=> feat: include swift-overlay.conflist in the dropgz build

.pipelines/pipeline.yaml, .pipelines/submodules-pipeline.yaml
=> fix: submodule tag trigger

.pipelines/pipeline.yaml, .pipelines/submodules-pipeline.yaml
=> exclude v* in submodule tag trigger

.pipelines/pipeline.yaml
- include all tags to trigger a build for pipeline
- exclude submodule paths from triggers of main pr pipeline
**Notes**:
=> trigger for all tags in main pipeline

Makefile
=> fix: prefixed tag parsing

README.md, docs/README.md, docs/cilium.md, docs/overlay-for-aks.md
Adds docs for Azure CNI Powered by Cilium and Azure CNI Overlay mode.
**Notes**:
=> docs: add cilium and overlay docs

.pipelines/singletenancy/aks-swift/e2e-step-template.yaml, .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml, hack/swift/Makefile
- cleanup + parameterization of hackfile variables
- extracted a region var and used in pipelines so that test clusters can easily be moved to other regions due to quota or outages
**Notes**:
=> Parameterize and tidy up the hackfile, use region variable in pipelines

cns/healthserver/server.go
hide this:
```
...
____    __
/ __/___/ /  ___
/ _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.7.2
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
O\
⇨ http server started on [::]:10092
...
```
from the CNS logs
**Notes**:
=> fix: hide echo banner in log

cni/internal.go, cni/ipam/ipam.go, cni/netconfig.go, cni/network/invoker_azure.go, cni/network/invoker_azure_test.go, cni/network/multitenancy.go, cni/network/multitenancy_test.go, cni/network/network.go, cni/network/network_test.go, cns/client/client_test.go, cns/cniconflist/generator.go, cns/cniconflist/generator_linux.go, cns/cniconflist/generator_linux_test.go, cns/cniconflist/generator_windows.go, cns/cniconflist/testdata/fixtures/azure-linux-swift-overlay.conflist, cns/configuration/configuration.go, cns/restserver/api_test.go, cns/restserver/internalapi.go, cns/restserver/ipam_test.go, cns/restserver/restserver.go, cns/service/main.go, fs/atmoic_test.go, fs/atomic.go, fs/testdata/.gitignore, fs/testdata/data.txt, tools/acncli/installer/conflist.go
This PR will allow CNS to write the CNI conflist (right now for Azure CNI Overlay only), so it can keep the Node in the NotReady state until the network is ready.
**Notes**:
=> feat: cns writes cni conflist

hack/swift/Makefile
$REGION needs to be declared above its usage in $CLUSTER to work correctly when $CLUSTER is not set at invocation
**Notes**:
=> fix variable ordering in hackfile

dropgz/build/cni.Dockerfile
=> add v1 conflist to dropgz

npm/pkg/controlplane/controllers/v2/podController.go
Do not reque Pods with bad IPs, and reduce wording from "error" to "warn".
```
2022/07/28 19:39:21 [79064] [podController processNextWorkItem] Error: failed to syncPod netpol-779-y/a. Requeuing with err: failed to sync pod due to Operation [AddPod] failed with error code [999], full cmd [], full error [syncAddedPod] Error: ADD POD  [netpol-779-y/a/aksawin22000002/map[pod:a]/2001:0db8:85a3:0000:0000:8a2e:0370:7334] failed as the PodIP is not valid ipv4 address
```
```
2022/07/28 19:39:21 [79064] [podController processNextWorkItem] Error: failed to syncPod netpol-779-y/a. Requeuing with err: failed to sync pod due to Operation [AddPod] failed with error code [999], full cmd [], full error [syncAddedPod] Error: ADD POD  [netpol-779-y/a/aksawin22000002/map[pod:a]/] failed as the PodIP is not …
```
=> log: [NPM] warn instead of error on invalid Pod IPs

tools/acncli/api/constants.go, tools/acncli/cmd/cni/install.go, tools/acncli/cmd/install.go, tools/acncli/installer/conflist.go, tools/acncli/installer/install.go
Adding in the capabilty of setting the network name in the azure cni conflist, for the acn-cli image
=> Network name as an optional variable

Makefile
Makefile target to print the image name and tag of each image
=> Image name and tag print in makefile

.pipelines/pipeline.yaml
=> Revert linux e2e removal

.pipelines/singletenancy/aks-engine/e2e-step-template.yaml
Unblock the ACN pipeline for flaky aks-e tests.
aks-e update can be referred in this PR
https://github.com/csfmomo/aks-engine/commit/6ea7fbb061151c12bf36d76a9913af8b4c148fe7
**Notes**:
=> Updated aks-engine to unblock the pipeline.

.pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml, .pipelines/singletenancy/overlay/overlay-e2e-step-template.yaml, cilium/cilium_helm_values.yaml
v1.12.1.1 no longer exists in the helm repos, updating to latest 1.12.x
**Notes**:
=> update cilium version to fix pipelines

dropgz/build/cni.Dockerfile
- Updates the bundled AzCNI in DropGZ to latest v1.4.39
- Parameterizes the dependency versions to make it clearer what versions are used
**Notes**:
closes #1713
=> parameterize dependency versions in dropgz and update azcni

test/integration/setup_test.go
Current test setup is missing these binaries for the Swift scenario
**Notes**:
=> Copy azure-vnet-telemetry and azure-vnet-ipam in test setup

cni/network/plugin/main.go, cni/plugin.go, ipam/manager.go, network/manager.go, telemetry/telemetrybuffer.go
Revert:
We found race condition issues with the new CNI and IPAM lock fix.
The related PRs will get reverted until the new design roll out.
=> Revert "fix: Adding a defer func to connecttoTelemetryservice() to prevent CNI fro…"

Makefile
=> fix tag for building container images

keyvault/shim.go, keyvault/shim_test.go
=> update azsecrets dependency

npm/pkg/dataplane/dataplane-test-cases_windows_test.go, npm/pkg/dataplane/dataplane_windows_test.go
Skip UTs relevant to #1856. These UTs can fail sometimes
**Notes**:
=> test: [WIN-NPM] skip unnecessary UTs

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/crdgen.yaml, .github/workflows/cyclonus-netpol-extended-nightly-test.yaml, .github/workflows/cyclonus-netpol-test.yaml, .github/workflows/golangci.yaml, azure-ipam/go.mod, build/tools/go.mod, cns/linux.Dockerfile, cns/windows.Dockerfile, dropgz/build/cniTest.Dockerfile, dropgz/build/linux.Dockerfile, dropgz/go.mod, go.mod, hack/toolbox/Dockerfile.windows, hack/toolbox/server/Dockerfile.heavy, hack/toolbox/server/Dockerfile.lite, npm/linux.Dockerfile, npm/windows.Dockerfile, tools/acncli/Dockerfile, zapai/go.mod
=> update to go1.20

zapai/go.mod, zapai/go.sum
Dependabot is doing its best but isn't keeping up. This updates all the deps for this submodule.
**Notes**:
=> consolidated dependency update for zapai

.github/workflows/golangci.yaml
A couple PRs continually timeout on golint windows.
**Notes**:
=> ci: increase golint timeout from 10 to 15m

Makefile
Fixing bug in CNS build introduced in #1844.
**Notes**:
=> ci: [CNS] fix cns-manifest-build parameter

dropgz/build/linux.Dockerfile
Update the CNI release version (1.5.0) to be used in the dropgz image
**Notes**:
=> Update CNI version for the dropgz image

cns/ipampool/monitor.go
=> fix nnccli log message

.pipelines/containers/manifest-template.yaml, .pipelines/pipeline.yaml, test/apimodels/cniWindows1903.json
=> ci: windows profile container image

npm/pkg/dataplane/dataplane.go
=> fix: [NPM] check if policy exists in case of nil pointer

.pipelines/cni/cilium/cilium-cni-load-test.yaml, .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml, .pipelines/singletenancy/overlay/overlay-e2e-step-template.yaml, hack/scripts/validate_state.sh, hack/swift/Makefile, hack/swift/kube-proxy.json
- creates new hackfile targets to spin up byocni clusters without kube-proxy for cilium pipeline tests
- includes small fix for load test after node restart, bug was found while testing this pr in load test pipeline.
**Notes**:
=> ci: disable kube-proxy for test clusters

tools/cleanup-npm-iptables.sh
=> tool: [NPM] script to clean up iptable chains

test/scale/config/prometheus
Adding the prometheus config for ACN docs
**Notes**:
=> test: Adding prometheus config for acn docs

cilium/cilium_helm_values.yaml, test/integration/manifests/cilium/cilium-agent/daemonset.yaml, test/integration/manifests/cilium/cilium-operator/deployment.yaml
Moving to cilium v1.12.10 in aks-rp, aligning ACN to match.
Load Test run: https://msazure.visualstudio.com/One/_build/results?buildId=74245517&view=results
**Notes**:
=> ci: bump cilium to v1.12.10

.github/PULL_REQUEST_TEMPLATE.md
updating the pull request readme to add labels for each PR
**Notes**:
=> docs: updating the pull request readme to add labels for each PR

.pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
Adds retry for cilium connectivity test in the cilium nightly pipeline and the cilium overlay e2e stage in the PR pipeline.
**Notes**:
Cilium Nightly Pipeline - Working
=> ci:[CNI] Add Retry to connectivity test

test/scale/test-scale.sh
=> fix: [CI] mismatch in the variable name to deploy the services in scale test

.pipelines/pipeline.yaml
Pulls in https://github.com/Azure/azure-container-networking/pull/2095 so future versions on that release branch will auto-trigger the CI
**Notes**:
=> chore: add release branches to pr pipeline trigger (#2095)

.pipelines/cni/pipeline.yaml
=> CI: add variable for node count

.pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
[Test](https://github.com/kubernetes/kubernetes/blob/1620473a9a01dd6bbef3398c0acb2e581d0a13c3/test/e2e/network/dns.go#L561) fails on windows clusters and is brought in with k8s version update. Does not provide any additional functional coverage to existing DNS [tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns.go). 
**Notes**:
=> ci: Update dns tests for k8s conformance

.pipelines/submodules-pipeline.yaml
adding cni package as a trigger
**Notes**:
=> ci: adding cni package as a trigger

cns/restserver/ipusage.go
This is a nit change in the logging.
**Notes**:
=> Updated log line for IP Usage metrics.

.pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml, .pipelines/npm/npm-cni-integration-test.yaml
Adds NPM|CNI test coverage to load-test pipeline.
**Notes**:
=> ci: [CNI] [NPM] Add NPM|CNI integration test to load-test pipeline.

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
Updating CNI version in dropgz to CNI v1.5.9 that has a fix for preventing the CNS to panic when no NCs are found on an NNC.
**Notes**:
=> fix: updating CNI to v1.5.9 for dropgz

log/logger.go, log/logger_test.go
This PR addresses a deadlock path in file rotation: when reading file stats to get file size, an error is handled with a recursive call to `logger.Debugf`, which deadlocks since a mutex cannot be acquired recursively.
**Notes**:
Cleaned up a few more things in the `rotate` method. The changes should be equivalent in behavior, with todos added to investigate if the original rotation logic is correct.
=> fix: deadlock when os.Stat errors within rotate method

.github/CODEOWNERS
=> chore: Adding CNI codeowners

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/pipeline.yaml
=> fix: correct make cmd for creating cilium cluster

.pipelines/submodules-pipeline.yaml
=> ci: add packages for submodule trigger

crd/multitenantpodnetworkconfig/api/v1alpha1/multitenantpodnetworkconfig.go, crd/multitenantpodnetworkconfig/manifests/acn.azure.com_multitenantpodnetworkconfigs.yaml
Add PN field to MTPNC spec as discussed in Matt's PR
**Notes**:
=> [Multitenancy]: Add PodNetwork field to MTPNC spec

docs/feature/async-delete/cni.md, docs/feature/async-delete/cns.md, docs/feature/async-delete/readme.md
Design proposal to fix the synchronous Pod delete/ReleaseIP deadlock
**Notes**:
=> docs: proposal for async pod delete handling

cns/configuration/configuration.go, cns/kubecontroller/nodenetworkconfig/reconciler.go, cns/kubecontroller/podwatcher/podwatcher.go, cns/service/main.go
Adds config and Reconciler for watching Pods. 
**Notes**:
=> feat: stub CNS Pod watcher

network/transparent_endpointclient_linux.go
=> hotfix for adding duplicated routes

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/load-test-templates/pod-deployment-template.yaml, .pipelines/cni/load-test-templates/restart-node-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
Fixes improper argument for `^TestScaleDeployment$`. Replaced and improved the functionality for reporting in load-test templates to be dynamic with inputs.  
**Notes**:
scaleup: Now needs a value between 1-240
=> fix: Change argument in load-test template

dropgz/build/cni.Dockerfile
Updating the dropgz v0.0.4 to take in CNI hot fix release v1.4.39.1
**Notes**:
=> chore: update azure-cni version in dropgz

cns/cniconflist/generator.go, cns/cniconflist/generator_linux.go, cns/cniconflist/generator_linux_test.go, cns/cniconflist/generator_windows.go, cns/cniconflist/testdata/fixtures/azure-linux-swift.conflist, cns/service/main.go
=> feat: CNS writes SWIFT conflist

hack/manifests/cni-installer-v1.yaml, hack/manifests/cni-installer.yaml, test/integration/manifests/cilium/cns-write-ovly.yaml, test/integration/manifests/cns/daemonset.yaml
Container registry cleanup removed old images greater than 30d on acnpublic. This resulted in files becoming outdated and inoperable. Going forward we should be using production repositories `mcr.microsoft.com/containernetworking/*` for when we want stable images for long term use. 
**Notes**:
=> ci: update CNS|dropgz version

crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go, crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
Updated MTPNC scope from Cluster to Namespaced as MTPNC has a 1:1 mapping with podname and needs to be in same namespace as the pod
**Notes**:
=> Update MTPNC scope

fs/atomic.go, fs/atomic_test.go
Backporting https://github.com/Azure/azure-container-networking/pull/2115 into `release/v1.4.44` branch
**Notes**:
=> fix: don't delete an existing conflist (#2115)

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
Updating to CNI v1.5.11 so we can build a new version of dropgz
**Notes**:
=> fix: updating CNI to v1.5.11 for dropgz

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/load-test-templates/create-cluster-template.yaml, .pipelines/cni/load-test-templates/pod-deployment-template.yaml, .pipelines/cni/load-test-templates/restart-cns-template.yaml, .pipelines/cni/load-test-templates/restart-node-template.yaml, .pipelines/cni/load-test-templates/validate-state-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/linux-cniv2-template.yaml, .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml, .pipelines/npm/npm-cni-integration-test.yaml, test/integration/manifests/noop-deployment-linux.yaml, test/integration/manifests/noop-deployment-windows.yaml, test/validate/linux_validate.go
Add CNIv2 (swift and overlay) to Load Test pipeline. 
Refactor existing load-test templates to contain less stages for further CI. 
Removed make revision in order avoid "merge to master" conflicts. 
NPM|CNI integration updated for windows and linux instead of using exclusively one branch.
Changed the order of testing as NPM was reporting false negatives after scale test. 
**Notes**:
Work from #2109, #2136, #2181 pulled from this PR in order for quicker reviews. Please look at comments from those PR's to amplify this one.
=> ci: Add CNIv2 Linux to Load Test pipeline

.pipelines/pipeline.yaml, .pipelines/singletenancy/aks-swift/e2e-step-template.yaml, .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Coverage for PR pipeline was missing latest CNI binaries due to use of dropgz vs dropgz-test.
**Notes**:
=> ci: Enable dropgz-test in PR pipeline

cns/ipampool/monitor.go, cns/ipampool/monitor_test.go, cns/kubecontroller/nodenetworkconfig/scopedclient.go
Moves from Update to Patch for NNC Spec updates from CNS. 
Update is prone to conflicts, and requires a pull/edit/push flow to resolve these. Patching applies the partial object update regardless of the current remote state of the object.
**Notes**:
=> migrate to patch for NNC spec updates

cni/network/invoker_cns.go
The original changes to CNI to allow for async pod deletes ( #2183 ) only checks for failure to release IPs after the ReleaseIPs call. This PR adds an additional check for the case when the older API, ReleaseIPAddress, fails as well.
**Notes**:
=> CNI async delete after ReleaseIPAddress

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/load-test-templates/restart-node-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/cniv1-template.yaml, hack/aks/Makefile, test/validate/linux_validate.go
Adds Linux CNIv1 to load test pipeline to test additional scenarios.
Refactors windows and linux CNIv1 into a single template to ensure that the testing coverage matches where applicable.
**Notes**:
=> ci: Add CNIv1 Linux to Load Test Pipeline

dropgz/build/windows.Dockerfile
=> Adding overlay v4/dualstack conflists to Windows Dropgz

cns/service/main.go
=> fixing config.channelmode to execute go routine for Mellanox

.github/workflows/cyclonus-netpol-test.yaml
=> test: [NPM] skip cyclonus for test dir

CONTRIBUTING.md, docs/contributing/git.md, docs/contributing/github.md, docs/contributing/go.md
=> Create initial contrbuting guides

cns/NetworkContainerContract.go
update cns network container contract for swift 2
**Notes**:
=> feat: update cns network container contract for swift 2

.pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml, hack/aks/Makefile, hack/aks/README.md, test/integration/datapath/datapath_windows_test.go, test/integration/load/load_test.go, test/internal/kubernetes/utils.go, test/internal/kubernetes/utils_create.go, test/validate/linux_validate.go, test/validate/utils.go, test/validate/validate.go, test/validate/windows_validate.go
This PR is to add ipv4 overlay windows test cases in ACN pipeline
**Notes**:
=> v4overlay windows test cases

cns/swagger.yaml
=> Add OpenAPI doucmentation to CNS

.pipelines/cni/load-test-templates/restart-hns-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/cniv1-template.yaml, test/integration/manifests/load/privileged-daemonset-windows.yaml
Adds HNS coverage to windows cniv1 in the load test pipeline. 
**Notes**:
=> ci: Add HNS restart to Windows CNIv1 in Load Test Pipeline 

Makefile, cni/network/common.go, cni/network/stateless/main.go, common/plugin.go, telemetry/telemetrybuffer.go
feat: Adding the cni changes for the stateless CNI
**Notes**:
=> 🌈 feat: adding flags for stateless cni

cni/network/plugin/main.go, cni/plugin.go, cni/telemetry/service/telemetrymain.go, cnms/service/networkmonitor.go, cns/service/main.go, telemetry/aiwrapper.go, telemetry/aiwrapper_test.go, telemetry/telemetry.go, telemetry/telemetry_test.go, telemetry/telemetrybuffer.go, telemetry/telemetrybuffer_test.go
This PR is to migrate zap logger for telemetry package
**Notes**:
=> [CNI] zap logger telemetry package

cni/network/network.go, cnm/network/network.go, network/endpoint.go, network/manager.go, network/manager_mock.go
Applying the required stateless CNI mode changes in network package.
**Notes**:
=> 🌈 feat: StatelessCNI: Applying stateless CNI mode changes in network package.

crd/multitenancy/api/v1alpha1/podnetworkinstance.go, crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworkinstances.yaml
Update pni scope to namespaced
**Notes**:
=> Fix: Update pni scope to namespaced

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/load-test-templates/restart-node-template.yaml, .pipelines/cni/load-test-templates/validate-state-template.yaml, .pipelines/cni/singletenancy/cniv1-template.yaml, .pipelines/cni/singletenancy/linux-cniv2-template.yaml
Improves CNI Release Test pipeline by:
- Removing flaky interactions from restart node template
- Parameterize dropgz image tag for specific version work
**Notes**:
=> ci: Update CNI Release Test pipeline

common/utils.go
Endpoints for API calls to DNC when CNS is running in Managed mode are incorrect. DNC expects networks string as part of the URL.
Fixes Issue #25350573 on ADO
**Notes**:
=> Fix endpoints for CNS pull model API calls to DNC

.pipelines/pipeline.yaml
=> fix: improper field change

dropgz/build/linux.Dockerfile
use azure-ipam/v0.0.5 in dropgz to include dualstack changes
**Notes**:
=> update dropgz with azure-ipam/v0.0.5

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/pipeline.yaml
Increases coverage of cilium OS/Processor configurations on overlay clusters.
**Notes**:
=> ci: add Cilium OS/Proc coverage to CNI Load Test pipeline

cns/restserver/ipam.go
Draft code for stateless CNI migration from legacy CNI statefile.
The Migration procedure is placed with the EndpointAPIHandler and as a result when staeless CNI is making the first call to CNS for GetEndpoint or UpdatedEndpoint then the migration from legacy CNI starts. After the migration is done the legacy CNI statefile will be deleted so the subsequent call will not check this again.
**Notes**:
=> Stateless CNI migration code.

azure-ipam/ipam.go
revert async delete changes for azure-ipam for preparation of dualstack release. changes will be added back later on
**Notes**:
=> revert: async delete changes for azure-ipam

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Add k8s conformance and increase timeout of cilium connectivity tests
**Notes**:
=> ci: Add k8s conformance to cilium E2E | Increase test timeouts cilium connectivity test

dropgz/build/linux.Dockerfile
dropgz with azure-ipam/v0.0.6 to support dualstack cilium
**Notes**:
=> update dropgz with azure-ipam/v0.0.6

cni/linux.Dockerfile, dropgz/build/cniTest_linux.Dockerfile
Add multitenancy transparent vlan conflist to dropgz image so that transparent vlan mode can be used with dropgz.
**Notes**:
=> test: add multitenancy transparent vlan conflist to dropgz

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/cniv1-template.yaml, .pipelines/cni/singletenancy/linux-cniv2-template.yaml, .pipelines/singletenancy/aks/e2e-step-template.yaml
#2283 Only parameterized dropgz within each respective template. Defining dropgz within the Setup stage to ensure all templates use the same image tag.  
**Notes**:
=> ci: Parameterize dropgz input for all Release pipeline scenarios

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Unblocks the PR pipeline as Cilium CLI update v0.15.11 -> v0.15.12 brought in new tests for features we may or may not support. 
**Notes**:
https://github.com/cilium/cilium-cli/releases/tag/v0.15.12 
https://github.com/cilium/cilium-cli/compare/v0.15.11...v0.15.12
=> fix: Cilium CLI version

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
=> bring new v1.4 CNI bins to dropgz

hack/aks/Makefile, hack/aks/README.md
new targets to create cilium dualstack and byocni dualstack with no kube proxy
**Notes**:
=> add cilium dualstack hackfile targets

azure-ipam/go.mod, azure-ipam/go.sum, go.mod, go.sum
Updating goproxy as dependabot has a backlog 
**Notes**:
=> chore: Update goproxy v0.0.0-20231031074852-3ec07828be7a

azure-ipam/go.mod, azure-ipam/go.sum, go.mod, go.sum
Update to gorilla/handlers and dependencies as dependabot has a backlog. 
**Notes**:
=> chore: Update handlers v1.5.2

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
Making new DropGZ version for Windows and Linux with CNI 1.5.14 to be used on K8s 1.28.0
- [] includes documentation
- [] adds unit tests
**Notes**:
=> feat: Making new DropGZ version for Windows and Linux with CNI 1.5.14

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
release dropgz for swift v2
**Notes**:
=> chore: release dropgz for swift v2

test/integration/manifests/cilium/cilium-config-hubble.yaml
Cilium config fix for cilium nightly pipeline
**Notes**:
=> fix: cilium config for hubble in cilium nightly pipeline

.pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
Fixes #2372 deletion of cilium nightly conditional logic. 
**Notes**:
=> fix: replace nightly params

hack/manifests/cni-installer-v1.yaml, hack/manifests/cni-installer.yaml
azure-cni:v1.5.14 was not published; update the hack/manifests to point to 1.5.15 
**Notes**:
=> fix: update azure-cni image version to published image

.github/workflows/codeql.yaml
=> chore: update CodeQL

.pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
The issue is fixed in cilium:  https://github.com/cilium/cilium/issues/29213
**Notes**:
=> ci: fix for cilium connectivity merged upstream

cns/service/main.go, cns/service/main_test.go, common/utils.go
=> Change expected code to 200, since DNC returns 200

.github/workflows/codeql.yaml, .github/workflows/crdgen.yaml, .github/workflows/golangci.yaml, .pipelines/pipeline.yaml, .pipelines/test-file.txt
Modifies the existing ACN PR pipeline for merge queue.
**Notes**:
=> ci: Modify ACN PR pipeline for merge queue use

.github/workflows/codeql.yaml
CodeQL currently does not work seamlessly with merge queue runs. 
**Notes**:
https://github.com/github/codeql-action/issues/1537 - Ongoing issue tracking effort
=> ci: revert codeQL checks to apart of merge queue runs

.pipelines/pipeline.yaml
We no longer use the submodule pipeline. As such, these submodules can trigger the PR pipeline and subsequentially, the merge queue successfully. 
**Notes**:
=> revert: submodule path exclusion

hack/manifests/busybox-ds.yaml, hack/manifests/busybox.yaml, hack/manifests/cni-installer.yaml, hack/manifests/scaler.yaml, npm/deploy/kustomize/overlays/controller/deployment.yaml, npm/deploy/kustomize/overlays/daemon/deployment.yaml, npm/deploy/manifests/controller/azure-npm.yaml, npm/deploy/manifests/daemon/azure-npm.yaml, test/integration/manifests/datapath/linux-deployment-ipv6.yaml, test/integration/manifests/datapath/linux-deployment.yaml, test/integration/manifests/goldpinger/daemonset-ipv6.yaml, test/integration/manifests/goldpinger/daemonset.yaml, test/integration/manifests/goldpinger/deployment.yaml, test/kubemark/aks-e/hollow-node.yaml
AZP has started auto-injecting a registry scan that has flagged some of our container refs
**Notes**:
=> chore: migrate from disallowed registries

.pipelines/pipeline.yaml
ACN Pipeline was showing memory pressure taints on Swift E2E from running goldpinger. Causing all follow on tests and re-runs to fail until memory was successfully recovered in the cluster.
**Notes**:
=> ci: Increase ACN pipeline Swift E2E vmSize

.pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml, .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml, .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml, .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml, .pipelines/templates/log-template.yaml
Overlay (v4 and Dualstack) step templates were unable to be called for individual OS E2E. 
Using `os.parameter` if blocks for `windows | linux` will solve problems it had with re-running, timeout control, incorrect failure logs based around the OS, and result in improved AZP analytics for failed jobs/steps.
**Notes**:
=> ci: Cleanup Dual OS ACN PR pipeline step templates

cns/fsnotify/fsnotify.go, cns/service/main.go, go.mod, go.sum
=> backport: fix: add contexts to clean up fsnotify goroutines

.github/dependabot.yaml
Merge queue has enabled higher velocity within the repo. This enables us to keep up to date with dependencies and security updates more effectively.
**Notes**:
=> ci: increase dependabot PR limit to 10

test/integration/manifests/ip-masq-agent/config-custom.yaml, test/integration/manifests/ip-masq-agent/config-reconcile.yaml
Adding commonly used pod-cidrs to ip-masq-agent templates. Fixes unwanted masquerading for cilium connectivity tests.
**Notes**:
=> ci: update pod-cidrs in ip-masq-agent

test/integration/manifests/load/privileged-daemonset.yaml, test/validate/linux_validate.go
Changed image for our daemonset to be more lightweight. 
Change in filesystem no longer required an additional shell for systemd-networkd restart
**Notes**:
=> ci: nsenter daemonset

.pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
Missed PR #2534 in #2483. 
Capturing all E2E with this PR.
**Notes**:
=> ci: Replace make test-integration [2/2]

cnms/Dockerfile
=> fix: modify cnms dockerfile with new image

.pipelines/templates/log-template.yaml
If privileged pod was the cause of the failure in a test scenario it could potentially get missed and the error logs overwritten. 
**Notes**:
=> ci: Capture privileged pod failure

.pipelines/cni/load-test-templates/create-cluster-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/cniv1-template.yaml, .pipelines/cni/singletenancy/cniv2-template.yaml
Adds in coverage for Windows CNIv2 singletenancy scenarios.  
**Notes**:
=> ci: Add Windows2019 to CNI Release Test pipeline

.pipelines/npm/npm-cni-integration-test.yaml, npm/examples/windows/azure-npm.yaml
Daemonset could not find executables. This is a result of the containderd update to 1.7+ that comes with AKS k8s version 1.28.
**Notes**:
=> ci: update NPM Windows daemonset for k8s version 1.28

go.mod, go.sum
=> deps: update controller-runtime

cns/linux.Dockerfile
`mcr.microsoft.com/cbl-mariner/base/core:1.0` no longer had valid certs and has been depreciated for an extended time. Retrieving certs instead from `mcr.microsoft.com/cbl-mariner/base/core:2.0`. 
**Notes**:
=> ci: update Linux CNS dockerfile

.github/workflows/codeql.yaml
Update to codeql is causing timeout issues due to increased coverage. https://codeql.github.com/docs/codeql-overview/codeql-changelog/codeql-cli-2.16.4/#golang-1
**Notes**:
=> ci: Increase Codeql timeout

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
Updates the CNI so that we can cut a new release of dropgz
**Notes**:
=> chore: Updating CNI in dropgz to 1.5.24

cns/linux.Dockerfile
=> fix: Install packages from mariner 2.0 instead of 1.0

.pipelines/mdnc/azure-cns-cni-1.4.39.1.yaml, .pipelines/mdnc/azure-cns-cni-1.4.43.1.yaml
Old CNI versions don't allow upgrading Ubuntu nodes to latest versions due to kernel issues. We are bumping up the min CNI version to allow node upgrades to latest LTS Ubuntu version.
**Notes**:
=> [MDNC] New CNI spec to target version 1.4.39.1

.pipelines/pipeline.yaml
Backports #2705 effort
**Notes**:
=> ci: [backport] Remove AKS Engine storage account usage

telemetry/telemetrybuffer.go
Backport telemetry leaking sockets fix related to #2703
**Notes**:
=> backport: fix: close connection on any return from azure-vnet-telemetry (#2711)

.pipelines/cni/pipeline.yaml
Matches cluster creation with deletion to avoid Resource group and cluster leaks
**Notes**:
=> ci: match cilium ds cluster create/delete

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
Update dropgz dockerfile for cni 1.5.28
**Notes**:
=> chore: update cni in dropgz to 1.5.28

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
Bumps the dropgz used in 1.4.x cni releases to consume version 1.4.54
**Notes**:
=> chore: update cni in v0.0.x dropgz to 1.4.54

.pipelines/cni/cilium/nightly-release-test.yml, .pipelines/containers/container-template.yaml, .pipelines/containers/manifest-template.yaml
Going from docker registry service connection to ARM service connection requires the use of AZ CLI task.
Added variable to change image repository.
**Notes**:
Impacts 
- NPM Conformance Tests
- ACN PR 
- Cilium Nightly
- NPM Scale Test
=> ci: Change ACR Service Connection

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml, azure-ipam/go.mod, azure-ipam/ipam.go, hack/scripts/async-delete-test.sh
tests async delete in cilium scenarios for ACN PR and release test pipelines
+includes async delete changes for azure-ipam
**Notes**:
=> ci: test async delete in cilium stages

.pipelines/multitenancy/swiftv2-e2e-job-template.yaml, .pipelines/multitenancy/swiftv2-e2e-step-template.yaml, .pipelines/templates/create-cluster-swiftv2.yaml, test/integration/swiftv2/swiftv2_test.go
The underlying testing cluster for swiftv2 is not stable and need add condition to unblock the pipeline merge.
**Notes**:
=> Add unblock condition for the swiftv2 tests.

cns/healthserver/server.go
=> fix: order of healthz and readyz arguments

.pipelines/pipeline.yaml, Makefile, cns/Dockerfile
CNS and CNI windows 2025 binaries can be built locally
**Notes**:
=> build windows 2025 binaries

cns/NetworkContainerContract.go
Modified the value of DelegatedVMNIC to resolve compatibility issue
**Notes**:
=> fix: Modified the value of DelegatedVMNIC to resolve compatibility issue

cns/NetworkContainerContract.go
Modified the value of DelegatedVMNIC to resolve compatibility issue
**Notes**:
=> fix: Revert the naming change for DelegatedVMNIC on master

processlock/processlock.go
update file lock directory permissions for 1.5.x release train
#2818 
**Notes**:
=> backport: fix: update azure-vnet directory permissions (#2819)

crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go, crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
Update the multitenancy CRD schemas to include subnet address space in MTPNC status.
**Notes**:
=> feat: add subnet address space to mtpnc status

.pipelines/multitenancy/swiftv2-e2e-step-template.yaml, .pipelines/pipeline.yaml, hack/aks/Makefile, test/integration/manifests/swiftv2/podnetwork.yaml
PR pipeline fixes and stability.
**Notes**:
=> Fix ACN PR Pipeline failures related to swiftv2

.pipelines/pipeline.yaml
Enable merge queue for `release/v1.5`
**Notes**:
=> ci: Change `release/v1.5` merge queue trigger

dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile
Update dropgz dockerfile for cni 1.5.30
**Notes**:
=> chore: update cni in dropgz to 1.5.30

.pipelines/multitenancy/swiftv2-e2e-step-template.yaml, .pipelines/pipeline.yaml, hack/aks/Makefile, test/integration/manifests/swiftv2/podnetwork.yaml
=> backport acn pipeline stability fix

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/pipeline.yaml
Test Cilium dual stack with AzureLinux, rdma, and ARM64 and change daemonset for dual stack tests
**Notes**:
=> ci: add AzureLinux, rdma and ARM64 release test scenarios for cilium dual stack

crd/multitenancy/api/v1alpha1/nodeinfo.go, crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
Removed annotation for .status.status field which is not needed
- [x relevant PR labels added
**Notes**:
=> fix nodeInfo schema

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml, .pipelines/cni/load-test-templates/restart-node-template.yaml, .pipelines/cni/lsg/lsg-cni-intergration-template.yaml, .pipelines/cni/pipeline.yaml, .pipelines/cni/singletenancy/cniv1-template.yaml, .pipelines/cni/singletenancy/cniv2-template.yaml
Backport VM usage to release/v1.5 
**Notes**:
=> [backport] ci: Adjust VM usage for CNI Release Test Pipeline (#2837)

.pipelines/cni/cilium/nightly-release-test.yml
Leverages ACR cache and image mirror to unblock nightly pipeline
**Notes**:
=> ci: Unblock nightly pipeline

.github/workflows/cyclonus-netpol-extended-nightly-test.yaml, .github/workflows/cyclonus-netpol-test.yaml
An update to `actions/upload-artifact` broke the naming convention of artifacts.
Doc - https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
**Notes**:
This does not need to be backported to `release/v1.4` as v3 is not depreciated yet.
=> [fix] ci: update cyclonus workflow

.github/workflows/cyclonus-netpol-test.yaml
Did not track `release/*` branches.
**Notes**:
=> ci: update Cyclonus workflow triggers

.pipelines/npm/npm-conformance-tests-latest-release.yaml, .pipelines/npm/npm-conformance-tests.yaml, .pipelines/npm/npm-scale-test.yaml
- Cut runtime of Windows Conformance from ~3 hours to ~45 minutes
- Disable Windows Cyclonus (consistently timing out after 6 hours)
- Disable Windows Scale Test (consistently failing to establish initial connectivity in time)
**Notes**:
=> ci: [NPM] speed up Windows conformance and disable Windows Cyclonus/Scale

cns/configuration/configuration.go
Adding EnableK8sDevicePlugin field in CNS config for future use.
Updated config in AKS-RP side https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp/pullrequest/10476188
**Notes**:
=> chore: add enable k8s device plugin to cns config

.pipelines/npm/npm-conformance-tests.yaml
NPM Conformance test is being ran more regularly and will use up quota unless clusters are deleted after automated runs. 
NPM Conformance was using the latest testing suite, which is not paired with the k8s version of the cluster, potentially bringing in unwanted changes to our subset of tests. This change also allows the test suite to be dynamic and paired to whatever cluster k8s version is in use. 
**Notes**:
=> ci: [NPM] NPM Conformance Test improvements

.github/workflows/golangci.yaml
Testing if targetting different release branch fixes linter issues.
**Notes**:
=> ci: make lint target release/v1.5 branch

.pipelines/OneBranch.NonOfficial.CrossPlat.yaml, .pipelines/OneBranch.Official.CrossPlat.yaml
Adding the initial files used for OneBranch builds.
This is a part of our security initiative to build more secure resources.
**Notes**:
=> Add Initial Compliant Pipeline Files

ipam/azure.go
Adds logs so we can tell if NMAgent response is empty/does not contain interfaces when using azure vnet ipam
**Notes**:
=> fix: add log for ipam data received

.pipelines/pipeline.yaml, Makefile, cni/Dockerfile, cns/Dockerfile
Create window 2025 images for CNI and CNS using the insider tags provided by windows, until ltsc2025 tags are officially release by windows servercore.
**Notes**:
=> feat: Create win 2025 images for CNI and CNS using windows servercore insider tags.

.pipelines/singletenancy/aks/e2e-step-template.yaml
Enable state validation. The infra/tests/params should already be in place.
**Notes**:
=> ci: enable state validation in linux cni v1

go.mod, go.sum
bump github.com/docker/docker (#2912)
=> backport: deps: bump github.com/docker/docker (#2912)

npm/pkg/dataplane/dataplane.go, npm/pkg/dataplane/dataplane_test.go, npm/pkg/dataplane/ipsets/ipsetmanager.go, npm/pkg/dataplane/ipsets/testutils_linux.go, npm/pkg/dataplane/ipsets/testutils_windows.go, npm/pkg/dataplane/policies/policy.go
Backport #2978 
Fixes #2977 in release/v1.5 branch
=> [backport] fix: [NPM] [Linux] race when deleting/readding NetPol

npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
Backport #2998
Fixes #2997 in release/v1.5 branch
=> [backport] fix: [NPM] [Linux] handle more than 15 leaked ipsets

.pipelines/cni/cilium/nightly-release-test.yml
Add in missing service connection for Cilium Nightly Pipeline on Cluster Deletion job
**Notes**:
=> fix: Add missing service connection

.pipelines/cni/cilium/cilium-scale-test.yaml
Adds stage to create a cluster in Cilium scale test pipeline and allows to specify resource group name separately from cluster name.
**Notes**:
=> ci: add create cluster stage to cilium scale test pipeline

.pipelines/cni/cilium/cilium-scale-test.yaml
adjust job timeout to avoid pipeline failure before scaling completes
**Notes**:
=> ci: add timeoutInMinutes during scale

.pipelines/cni/lsg/pipeline.yaml
Missed cluster deletion for CNI-LSG pipeline from #2986 
**Notes**:
=> [ci] fix: CNI-LSG pipeline cluster deletion

go.mod
=> Update go toolchain to cover cve CVE-2024-34156

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/crdgen.yaml, .github/workflows/cyclonus-netpol-extended-nightly-test.yaml, .github/workflows/cyclonus-netpol-test.yaml, .github/workflows/golangci.yaml, azure-ipam/go.mod, azure-ipam/linux.Dockerfile, azure-ipam/windows.Dockerfile, build/tools/go.mod, cni/build/windows.Dockerfile, cni/linux.Dockerfile, cni/windows.Dockerfile, cns/linux.Dockerfile, cns/windows.Dockerfile, dropgz/build/cniTest_linux.Dockerfile, dropgz/build/cniTest_windows.Dockerfile, dropgz/build/linux.Dockerfile, dropgz/build/windows.Dockerfile, dropgz/go.mod, go.mod, hack/toolbox/Dockerfile.windows, hack/toolbox/server/Dockerfile.heavy, hack/toolbox/server/Dockerfile.lite, npm/linux.Dockerfile, npm/windows.Dockerfile, tools/acncli/Dockerfile, zapai/go.mod
Upgrade to go v1.22.7 for CVE fixes
**Notes**:
=> upgrade to go v1.22.7

cns/ipampool/v2/monitor.go
Purely event-driven IPAM does not retry if the reconcile is unsuccesful until there is a new Event pushed to trigger it. This could result in delays in pool scaling if the cluster is relatively static and there are transient errors in updating the NNC.
This adds a max re-reconcile delay so that the pool will be recalculated _at least_ once per max delay. The calculation is no-op if the pool is already at the target state, but will trigger the appropriate NNC update if it is not.
**Notes**:
=> fix: add max reconcile delay interval to IPAM monitor

npm/examples/azure-npm-lite.yaml, npm/examples/windows/azure-npm-lite-win.yaml
Fixes a syntax error in npm lite yaml file
**Notes**:
=> [NPM Lite] Fix for NPM Lite Yaml File

go.mod
v1.16.15 was created by accident, due to a typo in v1.6.15. We are adding a retraction in this PR
Retracts v1.16.15
**Notes**:
=> fix: add retraction of v1.16.15

Makefile
=> [backport] ci: hardcode docker container build image

.pipelines/templates/cilium-cli.yaml
Previous regex logic did not match with the additional `-######` that is a part of the new cilium images. 
**Notes**:
=> ci: update regex for new cilium images

Makefile
Backporting required ci changes.
**Notes**:
=> [backport] ci: hardcode docker container build image into release/v1.4

.pipelines/templates/cilium-cli.steps.yaml, .pipelines/templates/cilium-cli.yaml
Forward-porting a change from release/v1.5 that addresses the new image usage from mcr.
**Notes**:
=> [forwardport] ci: update regex for new cilium images (#3115)

.pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml, .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml, .pipelines/templates/cilium-cli.yaml
Templatizes Cilium CLI install to ensure that nothing slips. 
Updates regex with OR operator to check for old and new cilium images.
**Notes**:
=> [backport] ci: Cilium CLI template changes 

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Adds in missing changes from #3089 to CNI Release Test Pipeline
**Notes**:
=> ci: add coverage from #3089 to hubble testing in CNI Release Test Pipeline

.pipelines/cni/lsg/lsg-cni-intergration-template.yaml, .pipelines/cni/singletenancy/cniv1-template.yaml, .pipelines/cni/singletenancy/cniv2-template.yaml
Updates pipeline scripts that clean up test resources to account for updated namespace usage
**Notes**:
=> [fix] ci: update recover resource job

.github/dependabot.yaml
Adds release branches to dependabot config for gomod updates.
**Notes**:
=> chore: add release branches to dependabot gomod updates

.github/dependabot.yaml
Hard to easily discern and sort which dependencies are being updated for each release train. Adding existing `release/*` and pkg labels to respective dependabot PR(s).
**Notes**:
=> ci: update dependabot labels

cns/service/main.go, platform/os_linux.go, platform/os_windows.go, platform/os_windows_test.go
backport of #2993
remove powershell from windows registry txs
**Notes**:
=> fix: remove PowerShell from Windows registry interactions (#2993)

go.mod
We retracted v1.16.15 (which was created due to a typo), but for the retraction to take effect, we need an even newer version. The newer version in this case will be 1.16.16. Since we aren't ready for 1.16.16 yet, the version should retract itself. This PR has the changes to that effect. Once this is merged, we should release 1.16.16.
**Notes**:
=> chore: add a retraction of 1.16.16

go.mod
We just discovered that there was a typo when creating 1.5.22, resulting in the creation of 1.15.22. We are retracting this version, and since we will publish the retraction in version 1.16.17, retracting that one too.
**Notes**:
=> chore: retract 1.16.17 and 1.15.22

.golangci.yml, cns/service/main.go, platform/os_windows.go
Prevents CNS hanging forover for HNS restart
**Notes**:
=> backport: fix: prevent CNS hanging on HNS restart (#3343)

cns/logger/constants.go, cns/metric/heartbeat.go
Add dual stack fix's presence for AZR in CNS heartbeat metric
**Notes**:
=> Add dual stack fix's presence for AZR in CNS heartbeat metric

.golangci.yml
Golint failing with invalid config
Modifies config to conform to https://golangci-lint.run/usage/linters/#govet
**Notes**:
=> ci: fix check-shadowing not allowed

npm/azure-npm.yaml, npm/cmd/start.go, npm/cmd/start_daemon.go, npm/cmd/start_server.go, npm/config/config.go, npm/metrics/ai-utils.go, npm/pkg/controlplane/controllers/v2/namespaceController.go, npm/pkg/controlplane/controllers/v2/networkPolicyController.go, npm/pkg/controlplane/controllers/v2/podController.go, npm/pkg/dataplane/dataplane.go, npm/pkg/dataplane/dataplane_linux_test.go, npm/pkg/dataplane/dataplane_test.go, npm/pkg/dataplane/dataplane_windows_test.go, npm/pkg/dataplane/ipsets/ipsetmanager.go, npm/pkg/dataplane/ipsets/ipsetmanager_linux.go, npm/pkg/dataplane/types.go, npm/util/const.go, npm/util/ioutil/restore.go
Backporting https://github.com/Azure/azure-container-networking/pull/3468 to reduce noisy NPM logs.
**Notes**:
=> [backport] [NPM] Reduce/Refactor Noisy NPM Logs

go.mod
https://github.com/golang/go/issues/57631 requires the specification of a patch version to download the correct toolchain. This also prevents dependabot from adding in the toolchain directive. https://github.com/Azure/azure-container-networking/pull/3467
**Notes**:
=> ci: remove toolchain usage 

go.mod
https://github.com/golang/go/issues/57631 requires the specification of a patch version to download the correct toolchain. This also prevents dependabot from adding in the toolchain directive. https://github.com/Azure/azure-container-networking/pull/3484/files
**Notes**:
=> deps: go 1.23.0

test/integration/manifests/cilium/v1.13/cilium-config/cilium-config.yaml
Add enable lrp to internal cilium config for cilium version 1.13
**Notes**:
=> ci: enable lrp in cilium 1.13 config

hack/aks/Makefile
Latest aks preview has a bug-- mitigation is to set the aks preview version to the above until a fix is released; then we can revert this change.
Clusters create now: 
https://msazure.visualstudio.com/One/_build/results?buildId=122530390&view=results
https://msazure.visualstudio.com/One/_build/results?buildId=122531525&view=results
See above
**Notes**:
=> ci: set aks preview to 14.0.0b3

hack/aks/Makefile
`release/v1.5` k8s version pair is going into LTS.
**Notes**:
=> ci: required changes for LTS support | v1.5

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Fix v1.5 release test ci for cilium hubble install
**Notes**:
=> ci: fix cilium hubble deployment v1.5

.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
make azure-ipam and cns images customizable for release test
**Notes**:
=> ci: create test image vars for release test

.pipelines/pipeline.yaml
=> ci: enable merge queue for release/v1.6

.pipelines/build/generate-manifest.steps.yaml, .pipelines/build/image.steps.yaml, .pipelines/build/images.jobs.yaml
Resolving issues related to ADO pipeline build for release/v1.6 branch.
No ADO issues associated to this.
**Notes**:
=> ci: Fixing build pipeline for 1.6 release

cns/windows.Dockerfile
=> chore: dependency update for v1.5

.pipelines/npm/npm-conformance-tests.yaml, npm/azure-npm.yaml, npm/deploy/kustomize/overlays/controller/deployment.yaml, npm/deploy/kustomize/overlays/daemon/deployment.yaml, npm/deploy/manifests/controller/azure-npm.yaml, npm/deploy/manifests/daemon/azure-npm.yaml, npm/deploy/npm/azure-npm.yaml, npm/examples/azure-npm-lite.yaml, npm/examples/windows/azure-npm-capz.yaml, npm/examples/windows/azure-npm-lite-win.yaml, npm/examples/windows/azure-npm.yaml
Backports the following NPM commits made to master branch:
- https://github.com/Azure/azure-container-networking/pull/3888
- https://github.com/Azure/azure-container-networking/pull/3887
**Notes**:
=> [NPM] [Backport] Remove NPM Windows 2022 Tests from the NPM Conformance Tests + Clean Up NPM release/v1.4
